### ISSUE TITLE
Onboarding & help strategy

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#133]
The help button currently does nothing when clicked.

What should the expected behaviour be? 

Currently the Help menu in the Menubar gives the users 2 menu options (tutorials & provide feedback).

**Comment by surajpindoria** [comment]
We have the docs on phonegap.com now, is this still relevant?

**Comment by jahoni** [comment]
I'd say "no", but i also don't have a clear sense of how complete the docs are.

**Comment by surajpindoria** [comment]
The docs have:

- Installation
- FAQ/Troubleshoot
- Creating a project
- Opening a project
- Active vs inactive projects
- Previewing app using developer app
- Removing a project
- Updating the app
- Editing settings
- Server logs

I am going to go ahead and close this out.
