### ISSUE TITLE
Add "start-up" modal

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-app-desktop#135]
Add the hints modal on app start-up:

![desktop-app_0000_hints-modal](https://cloud.githubusercontent.com/assets/178345/3332132/7006e88a-f7e3-11e3-9baa-090ae4bc83d6.png)

**Comment by surajpindoria** [comment]
Is there still a plan to add this modal to the app?

**Comment by jahoni** [comment]
I'd say no.

**Comment by surajpindoria** [comment]
Cool beans, closing this out.
