### ISSUE TITLE
Project list order: Alphabetize

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-app-desktop#157]
Projects in the list should be sorted by alphabetical order. This should enhance find-ability in the event of long lists.

In the future, we may want to consider making the list user sortable.

**Comment by hollyschinsky** [comment]
Updated code to sort projects when initially loaded and to determine where to insert the new DOM element when a new one is added [here](https://github.com/phonegap/phonegap-app-desktop/commit/2fb161d80248b745473ece096ee1afb66bff680d). Had to move the `removeMissingProjects` call to after where the `addProjectWidget` is called  to avoid timing issues.

**Comment by hollyschinsky** [comment]
Fixed remaining issues, closing.

**Comment by hollyschinsky** [comment]
Still some remaining inconsistencies, reopening.

**Comment by hermwong** [comment]
Moving to backlog, we will shelf this fix until for the current version of PG Desktop.

**Comment by surajpindoria** [comment]
Did you manage to work out the problems you were seeing here @hollyschinsky?

**Comment by hermwong** [comment]
This issue still exists.
