### ISSUE TITLE
Can't connect to the app

### ISSUE THREAD

**Issue by cfjedimaster** [phonegap/phonegap-app-desktop#162]
No matter what port I use, I get an error connecting to my running app. It is a TIMED OUT error, but it occurs very quickly. Basically I hit connect and boom - error.

I made another PG project, ran serve on it, and was able to connect.

**Comment by tronghv77** [comment]
see #396

**Comment by Reispar** [comment]
@tronghv77 , I disabled firewall still cant connect.
