### ISSUE TITLE
Support Plugins

### ISSUE THREAD

**Issue by cfjedimaster** [phonegap/phonegap-app-desktop#170]
The app should tell me what plugins I have installed and provide a quick way to install/remove them. Like my Brackets extension (https://github.com/cfjedimaster/Cordova-Extension).

**Comment by murliatdure** [comment]
:+1:

**Comment by surajpindoria** [comment]
Have we had any further discussions on this @hermwong? I think this would require some design work though.

**Comment by hermwong** [comment]
We've thrown around high level ideas about supporting 3rd party plugins, but have not started any concrete planning or design regarding how we would implement this feature.
