### ISSUE TITLE
Selected folder doesn't contain a config.xml file error when it does

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-app-desktop#175]
Sometimes when I open an app I get the error :

'Selected folder doesn't contain a config.xml file' 

But the folder does actually have one. Trying to open a subsequent project that normally works also gives this error. The first time I got it, it was a basic template created with the Ionic CLI. Maybe that's not supported? Subsequent tries on regular phonegap or cordova created apps give same error after the first one but if I close the app and open again then those same phonegap or cordova apps that i received this error on before no longer give me the error.

The same Ionic project works if i drag it in towards the bottom of the app, but not in the top where the Add to existing project option shows up or when I do the File | Open Project option.

**Comment by frtkync** [comment]
I have just installed the Desktop App, try to create a project. Gives the same error but with a difference. My project folder has just .cordova, hooks, platforms and plugins directories but all of them empty. It seems the app couldn't download and place all the files it needs. Could you help please ? Thanks.

**Comment by hermwong** [comment]
@frtkync try resetting PhoneGap Desktop's template cache by following these [instructions](https://github.com/phonegap/phonegap-app-desktop/issues/648#issuecomment-233003701).

**Comment by Skin0x** [comment]
@frtkync Did you found a solution ? :worried:

**Comment by hermwong** [comment]
We've pinpointed the issue and are working on a fix. See [here](https://github.com/phonegap/phonegap-app-desktop/issues/584#issuecomment-233056416) for details.

**Comment by hermwong** [comment]
We've made a fix to the template, however you'll need to reset your template cache by deleting the `.cordova` folder.

On Mac:

`/Users/<username>/.cordova`

On Windows:

`C:\Users\<username>\.cordova`

**Comment by frtkync** [comment]
@hermwong and @Skin0x yes it seems it is well done. Thanks for your helps fellas. It is great right now. To be honest, i've tried to do it older versions of phonegap but it is easier with desktop. Thanks again ! :)
