### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by davejohnson** [phonegap/phonegap-app-desktop#188]

**Comment by hermwong** [comment]
[Spectron](https://github.com/electron/spectron) allows testing of Electron apps through the use of ChromeDriver and Webdriverio.

The examples on the Spectron readme.md use mocha JS test framework; the readme.md also states that Spectron will support any testing framework.

**Comment by hermwong** [comment]
[Headless JS testing for Electron on any CI server](http://webuild.envato.com/blog/running-headless-javascript-testing-with-electron-on-any-ci-server/), may also apply to #379.
