### ISSUE TITLE
PhoneGap Developer Desktop App distribution channels

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#200]
We need to finalize the distribution of the packaged app.
1. phonegap.com
2. Mac App store
3. Windows store

**Comment by hermwong** [comment]
Only Windows RT SDK published apps can be distributed on the Windows Store.

With the move to Electron we should be able to distribute to the [Mac App Store](http://blog.atom.io/2015/11/05/electron-updates-mac-app-store-and-windows-auto-updater.html).

**Comment by surajpindoria** [comment]
Are we still trying to distribute the app through app stores? Or are we ok with how we are doing it now?
