### ISSUE TITLE
Take a look at implementing the tray functionality

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#217]
Implement system tray icon & menu for the PG-Desktop.

We should define what type of functionality needs to be accessed from the system tray.

**Comment by surajpindoria** [comment]
Not really sure what this is based on the description above. Is this something we are still interested in? If not let's close it out.

**Comment by hermwong** [comment]
Probably leave this in the backlog - it might be something that we want to implement with the upcoming rewrite.

**Comment by hermwong** [comment]
This is a duplicate of #383
