### ISSUE TITLE
no such file or directory error when running the automated build on BuildBox

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#225]
![screen shot 2014-11-25 at 4 33 19 pm](https://cloud.githubusercontent.com/assets/107754/5194355/e2f3316e-74c0-11e4-8ed7-6d0529e6e27e.png)

**Comment by hermwong** [comment]
Encountered this issue again on Jan. 21, 2015 @ approx. 3pm. PG-Desktop Build #51.

**Comment by surajpindoria** [comment]
We are no longer using the buildbox for the app, going to close this out.
