### ISSUE TITLE
evaluate offline experience 

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#244]
We need to take a look at the offline experience of the app, currently the app has some quirks when the user tries to run the app without a connection.

**Comment by surajpindoria** [comment]
Just tried this, as expected the update check fails and displays an error overlay. But if you 'Ok' the dialog the app still runs and serves projects over localhost. Let's change the update checker so it doesn't throw an error if there's no connection and I think we should be good.

![no connection](https://cloud.githubusercontent.com/assets/6467569/25546033/11d70898-2c16-11e7-8b5f-efc4d0f5b6f0.png)

**Comment by hermwong** [comment]
Another use case to consider would be if a user was attempting to run PG Desktop for the first time without an Internet connection.

We need to consider how this impacts the initial download of templates - probably throw an error on project creation.

**Comment by surajpindoria** [comment]
Ahh yes, I didn't think of all the use cases. Just tried creating a project and it attempts to download and locks the user behind the spinner. Forces a restart of the app, definitely need to research this more.
