### ISSUE TITLE
Firewall warnings

### ISSUE THREAD

**Issue by purplecabbage** [phonegap/phonegap-app-desktop#247]
Docs should specify that you may need to allow network access in your firewall.

![capture](https://cloud.githubusercontent.com/assets/46134/5402542/3f3df208-813a-11e4-90af-42ffb033622c.PNG)

**Comment by hermwong** [comment]
Should be fixed with this commit: https://github.com/phonegap/phonegap-app-desktop/commit/442852f8756a32e6628744764dfe6616823e5865

Related to: https://github.com/phonegap/phonegap-app-desktop/issues/63

**Comment by hermwong** [comment]
The firewall warnings don't appear if the user opens `PhoneGap.exe` from Windows Explorer but when the user opens `PhoneGap.exe` from the Windows Start Menu the firewall warnings will still display.

**Comment by surajpindoria** [comment]
I am not seeing this on the docs, we should add it to the [windows installation section](http://docs.phonegap.com/references/desktop-app/install/win/).

**Comment by sashabrava** [comment]
The server doesn't work across network if the Firewall exception isn't added manually. Windows 10 doesn't doesn't show the Security Alert dialog.
