### ISSUE TITLE
IP Address does not change when network changes

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-desktop#256]
**Reported by:**

https://github.com/phonegap/phonegap-app-developer/issues/255

**Recreate Issue:**

Turn on the PhoneGap Desktop app's server. It will display a green banner on the bottom with the system's IP address.

Now select a different network. For example, close your laptop and reconnect somewhere else.

After changing networks, the system will have a different IP address. However, the PhoneGap Desktop will continue to report the old address.

**Overview:**

This isn't a high priority issue, but we should think about ways to detect the network change and update the address.

**Comment by surajpindoria** [comment]
Still an issue, adding to potential redesign ideas.
