### ISSUE TITLE
server offline

### ISSUE THREAD

**Issue by batman11111** [phonegap/phonegap-app-desktop#257]
I installed the phonegap app desktop. As soon as I open it it says "server is offline at the bottom.  I have windows 8, I've tried running it as administrator, I've tried running it under windows 7 compatibility mode, I've allowed phonegap.exe through the firewall, and I've tried unblocking the dll files in powershell 3.0.  Any suggestions on how to get this to work?

**Comment by hermwong** [comment]
@thefristloser,

The location of the project templates on Windows (tested on Windows 8) is `C:\Users\<username>\.cordova`.

**Comment by thefristloser** [comment]
@hermwong  Thank  you. I saw the location on my Windows 7,but it was empty. Then reinstalled the latest version of the Windows 7,it worked.
