### ISSUE TITLE
windows 8 ,open app?

### ISSUE THREAD

**Issue by techker** [phonegap/phonegap-app-desktop#258]
Hey guys i tried it all for compatibility and run as admin but i only got it open once..but 98% of the time the application will not open?

is there a different way to open it?

**Comment by infiniteguitar** [comment]
Hi, are you going to release a Windows 7 32bit system, I can not open the new version which means the app won't work on my phone

**Comment by oldbk** [comment]
![2016-11-26_203242](https://cloud.githubusercontent.com/assets/6886009/20642105/961281cc-b417-11e6-9600-ea0ceb716591.png)
hi! phonegap don`t want to start on my win 8.1, there just unlimited circle round inside app from start

**Comment by kdoonboli** [comment]
Had the same issue. Uninstalled the app.
Before installing it again, make sure you are NOT connected to a VPN or intranet network. Have a direct internet connection. Then run the install file as administrator. It works for me now. Originally I installed it on VPN.
Now when I'm connected to VPN it still works.
