### ISSUE TITLE
Bundle PG project templates in PG Desktop App

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#262]
The first time the PG Desktop is launched it requires an Internet connection to download the PG project templates otherwise the PG Desktop will end up creating projects with 4 empty folder (.cordova,hooks,platforms,plugins).

**Comment by vigneshmunisamy** [comment]
I have same kind of problem ..if you any solution ..Let me know..

**Comment by hermwong** [comment]
Should be fixed: https://github.com/phonegap/connect-phonegap/issues/108
