### ISSUE TITLE
Simple app not positioning 'label' text correctly

### ISSUE THREAD

**Issue by lwoods** [phonegap/phonegap-app-desktop#264]
Added the following trivial code within 'app' div:
<fieldset >
<label for="name">Name:</label><input id="name" type="text" name="name" value="Enter Name" />
<label for="addr" >Address:</label><input id="addr" type="text" name="addr" value="Enter Address" />
</fieldset>
This will display with 'Name' and 'Address' correctly on the left on my Samsung Note BUT on my Motorola table "Address" is centered above the 'addr' textbox.
NOW if you remove the <fieldset> tags, just the opposite occurs.  All looks good on the Motorola tablet but "Address" is centered above the 'addr' textbox on my Samsung Note.

**Comment by lwoods** [comment]
Oops!  I didn't tag the inserted code correctly.  Here it is:
```
<fieldset >
<label for="name">Name:</label><input id="name" type="text" name="name" value="Enter Name" />
<label for="addr" >Address:</label><input id="addr" type="text" name="addr" value="Enter Address" />
</fieldset>
```

**Comment by lwoods** [comment]
Just for completeness, here is my original problem, cleaned up:

I added the following trivial code within 'app' div:
```
<fieldset >
<label for="name">Name:</label>
<input id="name" type="text" name="name" value="Enter Name" />
<label for="addr" >Address:</label>
<input id="addr" type="text" name="addr" value="Enter Address" />
</fieldset>
```
The above code will display with 'Name' and 'Address' correctly on the left of each of my textboxes on my Samsung Note BUT on my Motorola table "Address" is centered above the 'addr' textbox.
NOW if you remove the ```<fieldset>```
tags, just the opposite occurs. All looks good on the Motorola tablet but "Address" is centered above the 'addr' textbox on my Samsung Note.

**Comment by hermwong** [comment]
Hi @lwoods,

The issue that you're encountering sounds like HTML rendering issue, you might be able to find a solution or get more help in the [PhoneGap Google Group](https://groups.google.com/forum/#!forum/phonegap).
