### ISSUE TITLE
Accelerometer not working

### ISSUE THREAD

**Issue by markjsb** [phonegap/phonegap-app-desktop#265]
I've been trying some of the native phone features and I cannot seem to get the accelerometer to work at all. 

Putting a console.log('success'); into the onSuccess function never shows up on the server log so the event is clearly not firing. All the code I'm using is cut and paste straight from docs so no errors.

**Comment by hermwong** [comment]
Hi @markjsb,

You might be able to find a solution or get more help for your issue in the [PhoneGap Google Group](https://groups.google.com/forum/#!forum/phonegap).

**Comment by markjsb** [comment]
Thanks Herm, it's definitely something to do with either the desktop App or on device App as code I'm using has been published in a working App, so it's probably worth investigating.

**Comment by hermwong** [comment]
Thanks @markjsb, I'll add this issue to the backlog so that it can get prioritized.

**Comment by surajpindoria** [comment]
Just tested this using both browser platform and iOS and am seeing the output in server logs. Closing this, please reopen if you are still encountering the issue.
