### ISSUE TITLE
programmatically update the version of PhoneGap used in the index.html file

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#270]
Currently the PhoneGap version must be manually updated in the index.html file.

Determine if there is a way to programmatically update the PhoneGap version in the index.html file when a new version of PhoneGap is released.

**Comment by surajpindoria** [comment]
Not sure what the issue is here, Herm some more info please.

**Comment by hermwong** [comment]
Don't think this issue is applicable anymore - in older versions of the Desktop app we used to have the version of the phonegap dependency hardcoded in index.html.

**Comment by surajpindoria** [comment]
Ok, closing this.
