### ISSUE TITLE
Unable to connect from Phonegap mobile app to systems' hotspot

### ISSUE THREAD

**Issue by giridhar69** [phonegap/phonegap-app-desktop#271]
Hi, I am not using a wifi router to connect my laptop and mobile. Instead, I am using a virtual router in my laptop to connect my phone. I have a broadband connection via LAN to my laptop, so i am sharing the same network to develop apps. But I'm unable to connect using phonegap mobile app because it says timed out. Please help.

**Comment by hermwong** [comment]
Are you using a firewall or any anti-virus software on your laptop or LAN? The port number being used could be blocked by a firewall or anti-virus software; you could try changing the port number used in the settings of the PhoneGap Desktop App which would prevent the PhoneGap Developer App from connecting to the PhoneGap Desktop App when both are connected to the same network.

See also: https://github.com/phonegap/phonegap-app-desktop/issues/162
