### ISSUE TITLE
Adding Plugins and Platforms

### ISSUE THREAD

**Issue by JesseScott** [phonegap/phonegap-app-desktop#272]
Sorry if this is a dumb question, but I am confused about how to add plugins and platforms with the desktop app. Is there supposed to be a gui option for this, or are we expected to cd to the project location and do it by the command line? 

Just curious as I might use this in a class that I am teaching, but want to know if I can (currently or in the future) avoid the CLI ...

**Comment by hermwong** [comment]
Hi @JesseScott!

Thanks for the feedback!

Both of the features that you've asked about are currently in our backlog and still need to be prioritized on the PhoneGap Desktop's project roadmap.

1. [Support Plugins](https://github.com/phonegap/phonegap-app-desktop/issues/170).
1. [Add, Remove, List Platforms](https://github.com/phonegap/phonegap-app-desktop/issues/171).

**Comment by JesseScott** [comment]
Ah Ok, sorry, I did a cursory search of the issues before posting, but missed them. Good to know! Pretty stoked on this!
