### ISSUE TITLE
 Where is the "cordova.js"??

### ISSUE THREAD

**Issue by thefristloser** [phonegap/phonegap-app-desktop#274]
This's page:"https://github.com/phonegap/phonegap-start/blob/master/www/index.html"
On line 40: <script type="text/javascript" src="cordova.js"></script>
I didn't find the file "cordova.js".
1. Can you tell me how the file is loaded when the PhoneGap Developer App requests it?
2. How does the PhoneGap Desktop App differentiate between the android phone and the Apple iPhone?
Thanks.

**Comment by tanjentman** [comment]
I am having the same problem.  There seems to be no device api's loaded when creating a new project.  I am new to PhoneGap so it may be something I'm doing wrong.  Please feel free to offer any suggestions/guidance.  It would be greatly appreciated.  Thanks.

**Comment by hermwong** [comment]
The `cordova.js` file won't be found in the project that you've created using the PhoneGap Desktop App, it gets included when you connect to the project with the PhoneGap Developer App.

The `connect-phonegap` module used by the PhoneGap Desktop App contains the logic that determines the platform version of `cordova.js` that will be served to the PhoneGap Developer App.

For example, if you are using the PhoneGap Developer App on an Android device, then you will automatically get the Android version of `cordova.js` when previewing your project.

**Comment by tanjentman** [comment]
Hi hermwong, even when i use the PhoneGap Developer App on my Iphone, it doesn't see to find any of the device apis?  I get an error whenever I try to access any of them.  I can't tell what error it is because the app doesn't display any error messages.  It just hits that line of code and freezes.  I am using the the device api to get the platform, version, uuid, etc.  It locks up on the first call (var MODEL = device.model).  Any suggestions? Thanks.

**Comment by hermwong** [comment]
Hi @tanjentman,

I can't seem to reproduce your issue. I've attached a screenshot of my results and the code snippet used to generate the result.

![img_6772](https://cloud.githubusercontent.com/assets/107754/5843979/5ef76c6e-a165-11e4-9fbb-4fea7a0feeff.PNG)

```
        <script type="text/javascript">
            app.initialize(); 
            
            
            
            // Wait for device API libraries to load
            //
            document.addEventListener("deviceready", onDeviceReady, false);

            // device APIs are available
            //
            function onDeviceReady() {
                var element = document.getElementById('deviceProperties');
                element.innerHTML = 'Device Model: '    + device.model    + '<br />' +
                                    'Device Cordova: '  + device.cordova  + '<br />' +
                                    'Device Platform: ' + device.platform + '<br />' +
                                    'Device UUID: '     + device.uuid     + '<br />' +
                                    'Device Version: '  + device.version  + '<br />';
            }
            
        </script>   
```

**Comment by tanjentman** [comment]
Hi hermwong, I was missing the index.js and app.initialze...that was a dumb one on my part. Thanks for helping me through it.
