### ISSUE TITLE
cannot locate confiq.xml file after create new project

### ISSUE THREAD

**Issue by booyen** [phonegap/phonegap-app-desktop#275]
guys..im trying to use phonegap desktop and im new to phonegap evenviroment. after create a project..its indicate that "cannot find the config.xml in the selected folder"..try install node and all sort of related things..still nothing..also the newly created folder is empty.....

**Comment by hermwong** [comment]
Are you using the PhoneGap Desktop App on Windows or Mac?

**Comment by booyen** [comment]
sry...im using windows 7...64bit..

**Comment by hermwong** [comment]
Perhaps you are running into one of [these issues](https://github.com/phonegap/phonegap-app-desktop/issues/257).

**Comment by booyen** [comment]
well seems like the problem is solved..i download a demo from git.then paste it into .cardova/www folder..thanks..btw..i still dont now why these things happens..
