### ISSUE TITLE
How to deploy app to device using the desktop app

### ISSUE THREAD

**Issue by Ankur** [phonegap/phonegap-app-desktop#277]
Say someone wants to deploy their app that is previewing just fine on their android device with the Phonegap android app and the companion desktop app, how would they go about deploying it to a .apk file?

**Comment by mwbrooks** [comment]
Hi @Ankur,

You would need to do the following:

1. Setup your system for Android Development
1. On your Android device, enable third-party apps under "Security"
1. Connect your Android device to your system via USB
1. Run `phonegap run android`
  - This will add the Android platform to your project
  - Build the Android project
  - Install the Android app to your device

**Comment by hermwong** [comment]
Hi @Ankur,

The PhoneGap Desktop App currently does not support building & deploying apps to devices. We currently have the [build feature](https://github.com/phonegap/phonegap-app-desktop/issues/20) in our roadmap and will be prioritizing it for a future release.

To build your app you will need to use the PhoneGap CLI or PhoneGap Build service.

**Comment by Ankur** [comment]
Ah, so the CLI commands are not integrated into the Desktop app.  Got it to build using CLI though!  Thanks.
