### ISSUE TITLE
navigator.contacts.pickContact is undefined

### ISSUE THREAD

**Issue by creativeagent** [phonegap/phonegap-app-desktop#278]
hi, 
first of all congratulation for phonegap desktop. it's great!

i have a problem with the plugin contacts. 

when i upload my app to build.phonegap.com the app works fine included the function navigator.contacts.pickContact. if i try to run the app in phonegap desktop, then nothing is happen, when the function navigator.contacts.pickContact is called. 

if i check, then navigator.contacts is defined, but navigator.contacts.pickContact is undefined. 

can any one help?

br
stephan kobel

**Comment by hermwong** [comment]
Hi @creativeagent,

Can you please provide me with the steps you've taken to run your app on the PhoneGap Desktop App?

**Comment by creativeagent** [comment]
Hi herm, 

 

thanks for your answer! 

 

how you mean the steps? Source code ? installation ? or what ? 

 

best regards

stephan

 

Von: Herm Wong [mailto:notifications@github.com] 
Gesendet: Mittwoch, 21. Januar 2015 21:09
An: phonegap/phonegap-app-desktop
Cc: creativeagent
Betreff: Re: [phonegap-app-desktop] navigator.contacts.pickContact is undefined (#278)

 

Hi @creativeagent <https://github.com/creativeagent> ,

Can you please provide me with the steps you've taken to run your app on the PhoneGap Desktop App?

**Comment by hermwong** [comment]
I'm trying to determine what you mean when you are running your app on the PhoneGap Desktop. Do you mean that you are using the PhoneGap Desktop to create a server and previewing your app in the PhoneGap Developer App on your mobile device?

**Comment by creativeagent** [comment]
Yes, we use the PhoneGap Desktop to create a server, connect with WiFi to it and then we previewing our app on a iphone with the PhoneGAP Developer App. 

 

Von: Herm Wong [mailto:notifications@github.com] 
Gesendet: Mittwoch, 21. Januar 2015 22:57
An: phonegap/phonegap-app-desktop
Cc: creativeagent
Betreff: Re: [phonegap-app-desktop] navigator.contacts.pickContact is undefined (#278)

 

I'm trying to determine what you mean when you are running your app on the PhoneGap Desktop. Do you mean that you are using the PhoneGap Desktop to create a server and previewing your app in the PhoneGap Developer App on your mobile device?

**Comment by hermwong** [comment]
Would you be able to provide the following details:

1. Are you running the PhoneGap Desktop on Windows or Mac?
1. What device are you using to run the PhoneGap Developer App?

The PhoneGap Developer App does support previewing of [official plugins (APIs)](http://phonegap.com/about/feature/).

We've logged your [issue](https://github.com/phonegap/phonegap-app-developer/issues/268) in the PhoneGap Developer App's issue tracker.

**Comment by hermwong** [comment]
Looks like this issue is a bug in the PhoneGap Developer App. 

For more details: https://github.com/phonegap/phonegap-app-developer/issues/268

**Comment by timkim** [comment]
The fix is in the latest `connect-phonegap` @ `0.14.7` or `phonegap-cli` @ `4.2.0-0.24.1`

**Comment by creativeagent** [comment]
thx

**Comment by hermwong** [comment]
This fix will be included in the PhoneGap Desktop 0.1.2 release.
