### ISSUE TITLE
iPhone 6 scaling issue

### ISSUE THREAD

**Issue by Jarvey** [phonegap/phonegap-app-desktop#279]
Hi, I'm new in the phonegap world.
I'm currently trying  the desktop app in combination with the iOS app on my iPhone 6.
What I notice is that my app is being scaled of some sort on my iPhone 6.
The text and shape are not 100% sharp (retina)
Also the iPhone 6 screen size css media queries are different from the real screen size.

For example the iPhone 6 media queries screen size is 375 × 667. If I test my app in the webbrowser I have to use the  375 × 667 media queries styles for my iPhone 6. If I want to test my app in the phone gap app I have to use ... × 567. 

Is this a bug or am I doing something wrong ?

**Comment by hermwong** [comment]
Hi @Jarvey,

Could you provide your meta-viewport tag & values?

This [thread](http://community.phonegap.com/nitobi/topics/app-auto-scaling-on-iphone-6-and-6-screens) may also have a solution to your issue.

**Comment by Jarvey** [comment]
Hi hermwong,

Thanks for your help!

meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height, target-densitydpi=device-px" 

I also tried some things mentioned in the thread, but with no succes. Also in the thread they talk about scaling issues with the splash screens. I don't have splash screens currently in my app.

**Comment by dougestey** [comment]
I had this issue in Cordova a few weeks ago. As mentioned in the thread linked above, you need to specify the splash screens in order for the iPhone 6 and 6+ to not scale your app up and look terrible. It's the only way. Good luck.

**Comment by Jarvey** [comment]
Hi @dougestey,

Thank you for your help.
Can you be more specific about what and where you specify the splash screens.
Even with the help of the thread I can't get it to work, maybe I'm doing something wrong.

Thanks!!

**Comment by hermwong** [comment]
@Jarvey, the [PhoneGap docs regarding icons and splash screen configuration](http://docs.phonegap.com/en/4.0.0/config_ref_images.md.html) has some examples of how to set up splash screens in your project's `config.xml` file.

**Comment by dougestey** [comment]
@hermwong unfortunately the config.xml doesn't always set the needed options in Xcode for launch images.

@Jarvey you will need to set up asset catalogs for your launch images. See this section in Xcode.

![screenshot 2015-01-26 11 20 42](https://cloud.githubusercontent.com/assets/680366/5903049/6f2355a8-a54d-11e4-8731-c3dc6170f577.png)

**Comment by rihdus** [comment]
I have seen this issue often. here are some screenshots of 'http://google.com' site rendered on a phonegap 3.5.0 webview in iPhone 5 and iPhone 6 simulator.

You would expect more screen space available in an iPhone 6 device, but the iPhone 6 screenshot looks just like a scaled up version of the iPhone 5 screenshot.

For example, assuming the search bar is a simple div element with some fixed margin, it should appear wider in an iPhone 6 than in iPhone 5.

iPhone 5 screenshot:
![iphone 5-screenshot](https://cloud.githubusercontent.com/assets/4523345/7466770/5e4ab524-f31c-11e4-947d-29b3f9243b45.png)


iPhone 6 screenshot:
![iphone 6-screenshot](https://cloud.githubusercontent.com/assets/4523345/7466771/64a61a3a-f31c-11e4-833d-a94e9aaaa5d3.png)

**Comment by surajpindoria** [comment]
This is an old issue and I haven't heard of other scaling issues recently, going to close this. If it is still a problem please feel free to reopen.
