### ISSUE TITLE
PhoneGap project not created properly 

### ISSUE THREAD

**Issue by vigneshmunisamy** [phonegap/phonegap-app-desktop#282]
Hi.

I Downloaded and run the Ponegap desktop app..
only 4 folder created ,.cordova,hooks,platforms,plugins

other then that ,i don't any files inside the folder..same software i installed in a different system..in that it's working fine..

i don't know why ...and am using Windows 7 ...

**Comment by hermwong** [comment]
Related to: https://github.com/phonegap/phonegap-app-desktop/issues/262

**Comment by hermwong** [comment]
It sounds like the PhoneGap project templates did not get installed correctly, can you please read & try the solution suggested [here](https://github.com/phonegap/phonegap-app-desktop/issues/257#issuecomment-68320380).
