### ISSUE TITLE
Code signing to remove unknown publisher in Windows installer

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#283]
When running the Windows installer, Windows will display warning messages telling users that the PG-Desktop is from an unknown publisher. To remove the warnings, we need sign the code with Adobe's profile.

The Inno API for code signing can be found [here](http://www.jrsoftware.org/ishelp/index.php?topic=scriptcreating).

![screen shot 2015-01-27 at 2 05 30 pm](https://cloud.githubusercontent.com/assets/107754/5928188/f29beae0-a62d-11e4-95af-3730a9604688.png)

![screen shot 2015-01-27 at 2 05 42 pm](https://cloud.githubusercontent.com/assets/107754/5928191/f9d90978-a62d-11e4-8046-213e0d635473.png)

**Comment by hermwong** [comment]
Related to: https://github.com/phonegap/phonegap-app-desktop/issues/63

**Comment by hermwong** [comment]
R & D required for:

1. self signing for local / dev purposes (document the process)
1. requirements needed for code signing for production releases (document this as well)
  1. do we need a signing authority?
  1. is a server required?
1 automate Windows code signing in our build process (Grunt / Inno script etc.)

**Comment by purplecabbage** [comment]
A server is not required, a certificate from a signing authority is.
Local/dev releases are typically unsigned.

**Comment by hollyschinsky** [comment]
We can get around this with a self-signed developer certificate. I will paste a link here with the documented approach once finalized. We'll still need to obtain an official certificate to sign it but we can give the users more of a warm fuzzy by code signing it with a developer cert in the meantime. The result is shown below:

![image](https://cloud.githubusercontent.com/assets/359935/16497607/e6ac61f6-3ec5-11e6-9352-2945041c4ecd.png)

**Comment by hollyschinsky** [comment]
All the instructions on how to create a self-signing certificate on Windows 10 and Windows 8.1 have been documented [here](https://docs.google.com/document/d/1e5hbWLSDe71jfEtzUiVqKbv5LO8KUBlD37oitckn3z0/edit#) and should be used to sign the next release.

**Comment by hermwong** [comment]
Following the instructions outlined in the docs worked for me on Windows 10.

**Comment by purplecabbage** [comment]
Yes, that is how you sign it.  But if you give that installer to anyone else, they will see an unknown publisher. Self signing only works for sharing amongst people you already trust as you all need to install the same certificate.

If Holly sent you the install.exe she has built, you will see the issue, since you have both just generated your own certs.

**Comment by hermwong** [comment]
We have a task in the roadmap for looking into getting a certificate from a signing authority.

https://github.com/phonegap/phonegap-roadmap/issues/155#issuecomment-232148493
