### ISSUE TITLE
Recent IP address list / Favourite IP address list and Bonjour discovery

### ISSUE THREAD

**Issue by drenwick** [phonegap/phonegap-app-desktop#284]
Hi there - this is a brief enhancement request to add a pop-up menu of recent IP Addresses and another for Favourites. This helps get the app connected to your Desktop app when moving between locations and networks. 
Also - to aide connection. Please consider adding Bonjour discovery. On the Mac you can create a simple Bonjour service with the dns-sd command line. 

Thanks

**Comment by hermwong** [comment]
Thanks for the feedback! I'm adding this into our backlog.

**Comment by surajpindoria** [comment]
We are working on a recent IP list and new connection methods in the developer app redesign. Going to close this issue.
