### ISSUE TITLE
connect-phonegap 0.14.7 doesn't seem to return an IP address

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#287]
PhoneGap Desktop using `connect-phonegap` 0.14.3:

![screen shot 2015-01-30 at 3 51 29 pm](https://cloud.githubusercontent.com/assets/107754/5985598/0b957ab2-a899-11e4-9da6-511ff99a2e9c.png)

PhoneGap Desktop using `connect-phonegap` 0.14.7:

![screen shot 2015-01-30 at 3 56 14 pm](https://cloud.githubusercontent.com/assets/107754/5985599/1a8dc2ae-a899-11e4-845a-dc224060855d.png)

The [`serverOnlineState` function](https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/server-status.js#L28) receives a `data` object returned from the [`complete` event](https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/server-status.js#L24-L33) of the `connect-phonegap.listen` API which is [parsed](https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/server-status.js#L67-L72) to display the IP address within the PhoneGap Desktop App.

With the update to `connect-phonegap` 0.14.7, the `data` object is returning the string `unknown` as the `data.address` property.

![screen shot 2015-01-30 at 4 09 13 pm](https://cloud.githubusercontent.com/assets/107754/5985687/6033d78e-a89a-11e4-9036-46b9e427f42c.png)

**Comment by timkim** [comment]
Ya, I found something similar with the last few releases as well. Here's the issue I logged: https://github.com/phonegap/connect-phonegap/issues/107

I think it has to do with some of the commits introduced in `0.14.6` with some of the changes to the `util/ip.js`.

**Comment by mwbrooks** [comment]
Published as `connect-phonegap@0.14.8`

I wasn't able to recreate the issue, but I've added additional steps to look up the IP address. Let me know how it goes.

**Comment by StevenHu** [comment]
How do I turn off all these notifications?

**Comment by mwbrooks** [comment]
@StevenHu can choose to unwatch or ignore the repository's notifications:
![screen shot 2015-02-02 at 5 46 57 pm](https://cloud.githubusercontent.com/assets/21328/6012979/90120fc8-ab03-11e4-82ac-15700859cfce.png)

**Comment by StevenHu** [comment]
Thank you. I had Ignoring set and was still receiving notifications.
