### ISSUE TITLE
Windows Installer: Update default install path

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-desktop#293]
Currently, the default install path is `C:\Program Files (x86)\My Program\PhoneGap Desktop\`

![screen shot 2015-02-05 at 2 16 15 pm](https://cloud.githubusercontent.com/assets/21328/6070524/fc6c2bdc-ad41-11e4-80c7-f79a06f72114.png)

We should update the path to be either:
- `C:\Program Files (x86)\PhoneGap\PhoneGap Desktop\`
- `C:\Program Files (x86)\Adobe\PhoneGap\PhoneGap Desktop\`

**Comment by hermwong** [comment]
The path can be configured by updating: https://github.com/phonegap/phonegap-app-desktop/blob/master/res/installers/win/pg-desktop.iss#L11

**Comment by hermwong** [comment]
![win-default-install-dir](https://cloud.githubusercontent.com/assets/107754/6114425/e7b144fc-b052-11e4-847d-fffcdeffd694.png)

**Comment by mwbrooks** [comment]
Nice!
