### ISSUE TITLE
Windows Installer: Add to Start Menu

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-desktop#294]
Currently, after installing the PhoneGap Desktop app, there is no shortcut created to launch it. The expected result of installing a program is that it will appear in the Start Menu.

**Comment by hermwong** [comment]
Looks like this [Inno API](http://www.jrsoftware.org/ishelp/index.php?topic=iconssection) should add the PG-Desktop to the Start Menu.

**Comment by hermwong** [comment]
![win-start-menu](https://cloud.githubusercontent.com/assets/107754/6114396/a807b1e2-b052-11e4-9f26-8bb8de3a562e.png)

**Comment by mwbrooks** [comment]
Nice!
