### ISSUE TITLE
The EULA displayed in the Mac installer has a weird bolding issue.

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#295]
![screen shot 2015-02-05 at 3 30 18 pm](https://cloud.githubusercontent.com/assets/107754/6071555/03a3b76c-ad4c-11e4-9199-fc2e47021414.png)

**Comment by purplecabbage** [comment]
repro steps:
After you have built the dmg, you can recreate the error with 
`python res/installers/osx/support/dmg-license.py PhoneGapDesktop.dmg res/installers/osx/license.txt`

**Comment by purplecabbage** [comment]
note: repro steps above should now point to an rtf file instead of txt
