### ISSUE TITLE
Google Analytics Support

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-desktop#298]
Is there any reason why we can't add Google Analytics to the node-webkit app? Does it handle offline state okay? What about tracking unique sessions?

It would be extremely informative to have GA support. At the very least, we can identify geography and OS.

**Comment by hermwong** [comment]
Would need some time to look into it.

OS will be tracked with analytics in the 0.1.2 release.

**Comment by hermwong** [comment]
Look into adding a debug flag so that the debug/development sessions are not tracked.

**Comment by hermwong** [comment]
Even though we have the GA js library embedded in the app, it doesn't seem to be tracking sessions in GA. We need to investigate and determine why this is happening.

**Comment by mwbrooks** [comment]
Looks like this article provides a solution for Node Webkit and Electron:
http://stackoverflow.com/questions/27144245/how-to-use-google-analytics-in-node-webkit-desktop-apps

**Comment by Daaru00** [comment]
Try to use this: [nwjs-analytics](https://github.com/Daaru00/nwjs-analytics)

I wrote it a few days ago, is really simple but for me it works
