### ISSUE TITLE
Hot-swapping index.html, index.js and CSS files causes PG-Desktop to freeze

### ISSUE THREAD

**Issue by aleshh** [phonegap/phonegap-app-desktop#300]
With the app running, I renamed and then replaced index.html and the css and js directories. Phonegap throws up this screen and crashes (can't be quit from the menu):

![screen shot 2015-02-09 at 8 39 57 am](https://cloud.githubusercontent.com/assets/4977780/6107388/7fb474ec-b038-11e4-8eec-41a64eb8e308.png)

**Comment by hermwong** [comment]
Can you list out the step by step instructions on how you got the error?

Would you also be able to provide the full error message? I've found that Node-webkit won't let you copy & paste the error from the window when it crashes; the work around that I've used is to select all of the text and then drag it into your text editor.

**Comment by aleshh** [comment]
Hi!

I did something totally kunckleheaded: while the server was running, I
hot-swapped index.html, index.js, and the CSS files in the directory. I
tried selecting the next but couldn’t do anything: select, drag, quit, or
even resize the application window. Had to force-quit the app.

All in all not unreasonable behavior for a beta app, but seemed worth
reporting.

**Comment by hermwong** [comment]
Thanks for providing more info! We definitely appreciate all feedback and issues that our users report.

**Comment by surajpindoria** [comment]
Just tried this and it no longer crashes the app. Closing this issue.
