### ISSUE TITLE
Icon should have transparent background in the Windows Start Menu

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#301]
The PG-Desktop Icon should have a transparent background instead of the blue background when it is installed on the Windows Start Menu.

![win-start-menu](https://cloud.githubusercontent.com/assets/107754/6115709/752b6f70-b05c-11e4-9b93-7782e4c6099e.png)

**Comment by surajpindoria** [comment]
Not seeing this anymore. Closing.
