### ISSUE TITLE
Space in Path makes Phonegap.exe unusable

### ISSUE THREAD

**Issue by Netzvamp** [phonegap/phonegap-app-desktop#302]
On Windows the Phonegap.exe doesn't start if there is an Space in the path to the Executable. I had to change the foldername from "Phonegap Desktop" to ""PhonegapDesktop", to get it working. With the space in the path i only see an white window with an ASCI-Art "Node Webkit" in the middle.

**Comment by surajpindoria** [comment]
Just tested this and it now works with spaces in the path. Closing.
