### ISSUE TITLE
App just shows node-webkit

### ISSUE THREAD

**Issue by iamdriz** [phonegap/phonegap-app-desktop#303]
When I launch the app on Windows 7 all I see the is the node-webkit default screen if no app files are provided...

![image](https://cloud.githubusercontent.com/assets/801252/6166443/38382f9c-b2a8-11e4-8a5e-f2bd2c0537d2.png)

**Comment by hermwong** [comment]
duplicate: https://github.com/phonegap/phonegap-app-desktop/issues/302

**Comment by iamdriz** [comment]
This isn't actually the same reason as I'm running the app from here: `C:\PhoneGap\PhoneGap.exe` so I don't have spaces or weird characters in the path.

**Comment by dotnet54** [comment]
agree I'm getting the same screen, I don't have a space in the name as well

**Comment by hermwong** [comment]
@dotnet54 are you running on Windows 7 or 8?

**Comment by dotnet54** [comment]
windows 8.1 pro

**Comment by mlall** [comment]
Hi, 

I have the same problem but am on Windows 7. I don't have any spaces in the exe path as i installed it @"C:\PhoneGapDesktop"
Is this issue resolved ? or any work around ?

**Comment by imkumarsaurabh** [comment]
I am also getting the same blank screen.

Is this issue reolved??

![node](https://cloud.githubusercontent.com/assets/4995415/7388905/d0dd65b8-ee86-11e4-8838-61e8f379aee4.png)

**Comment by KingJP** [comment]
I also have Win7 with the same Problem.
I tried to install it in C:\PhoneGap. The error was still there.
In next step I found, that Port 80 and Port 443 are blocked.
So I stopped my Web Server and now the Desktop App is working.

**Comment by tixsys** [comment]
Same problem, win7 x64

**Comment by DevProLog** [comment]
I have the same problem on Windows 7.

**Comment by PedroHFranco** [comment]
I have same problem windows 8.1
![capturar](https://cloud.githubusercontent.com/assets/10779853/8873377/5fd5d28a-31dc-11e5-9f57-902a9b585b4f.JPG)

**Comment by touchonesolutions** [comment]
Hi all, I too have been having these issues running Win 7 x64.  However the one thing I have noticed is that in my VM of Windows XP it runs fine.

**Comment by vinaykannambadi** [comment]
bug still exists in Phone gap desktop app, i closed the app and restart the app it worked for me. Try closing and restarting.

**Comment by hermwong** [comment]
Please see: https://github.com/phonegap/phonegap-app-desktop/issues/362#issuecomment-140543191

Will be closing & locking this issue. If this issue still occurs please continue the discussion in the comments for [#362].

**Comment by hermwong** [comment]
[PhoneGap Desktop 0.1.11](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.1.11) should fix this issue. Please leave any feedback in #362.
