### ISSUE TITLE
config.xml sometimes not being read / refreshed when changed

### ISSUE THREAD

**Issue by bcray76** [phonegap/phonegap-app-desktop#304]
Whenever I make a project, and change, say, the version number in the widget tag to 0.0.1, I can see that reflected in the desktop app project list.  But, if I change the content src to anything else instead of index.html, it doesn't reflect that change when running the app on my phone with the phonegap app.  It always loads index.html no matter what is in the config.xml.  I've tried stopping and restarting the server before runnign the phone app and still get the same results. Any thoughts on this?

**Comment by andygup** [comment]
Ditto. I'm seeing the same issue. I even tried moving config.xml to www/ directory.

**Comment by hermwong** [comment]
Does it reflect the changes in your config.xml if you quit & restart the PhoneGap Developer App on your mobile device?

**Comment by bcray76** [comment]
It does not, unfortunately.

**Comment by hermwong** [comment]
It looks like the PhoneGap Developer App doesn't actually read the `config.xml` so the value in  `<content src="mypage.html"/>` is ignored and the PhoneGap Developer App just assumes that the `index.html` is the  default page in your app.

The PhoneGap Desktop App uses the Connect-PhoneGap module to serve your app to the PhoneGap Developer App. It looks like the Connect-PhoneGap module also uses the same assumption as the PhoneGap Developer App and serves `index.html` as the default page in the app without reading the `<content src="mypage.html"/>` value from `config.xml`.

A possible (unverified) workaround would be appending `mypage.html` to the url in the PhoneGap Developer App. For example, `http://192.168.1.1:3000/mypage.html`.

**Comment by hermwong** [comment]
I've logged this issue as a feature request in the PhoneGap Developer App's issue tracker.

**Comment by hermwong** [comment]
The suggested workaround mentioned above has now been tested and verified.
