### ISSUE TITLE
PhoneGap Desktop App 0.1.1 for Windows XP

### ISSUE THREAD

**Issue by spences** [phonegap/phonegap-app-desktop#308]
Unable to create a project. when create project button is clicked. I get this error --- an unhandled win32 exception occurred in PhoneGap.exe[3988]

I running Windows XP professional (desktop operating system). Question - does the phonegap software work on windows xp?

**Comment by hermwong** [comment]
We've only tested on Windows 7 & Windows 8.

**Comment by hermwong** [comment]
As on PhoneGap Desktop 0.2.0, we're only developing & testing for Windows 8.1 and Windows 10.
