### ISSUE TITLE
Icons are somehow missing in Windows v0.1.1

### ISSUE THREAD

**Issue by faldeland** [phonegap/phonegap-app-desktop#309]
![2015-02-16_141634](https://cloud.githubusercontent.com/assets/6295230/6217869/71e88d2c-b5e6-11e4-975e-2dc9ec41c8ae.png)

**Comment by faldeland** [comment]
Here is a screen capture of the unzipped folder contents.
![2015-02-16_141839](https://cloud.githubusercontent.com/assets/6295230/6217900/bde2acd0-b5e6-11e4-9ebb-fad873643e6f.png)

**Comment by hermwong** [comment]
Definitely a strange issue, the images should be built into the `.exe` file.

Which version of Windows are you using?

**Comment by faldeland** [comment]
Windows 7 (64 bit)


*Leland D. Falde*
leland@faldeland.com
c: 517.414.1618

**Comment by excogitation** [comment]
still no icons in 0.1.3 in win7 64bit

**Comment by hermwong** [comment]
I tested on Windows 8.1 64bit and wasn't able to replicate this issue.

**Comment by kkretsch** [comment]
Same here with version 0.1.8 64bit running under win 7 64bit.

**Comment by amin2009** [comment]
Installed PhoneGap Desktop 0.1.11 ... still not solved.

**Comment by amin2009** [comment]
Like to mention that

http://brackets.io/

**Comment by excogitation** [comment]
For me it was this issue: https://github.com/adobe/brackets/issues/7208
and uninstalling Inkscape solved the icon problem with Phonegap
(and brackets.io / atom.io). wtf!

**Comment by faldeland** [comment]
I also use Inkscape. Thanks for posting.

**Comment by surajpindoria** [comment]
A lot has changed since version 0.1.X, going to close this issue. If you are still seeing this please reopen.
