### ISSUE TITLE
Cannot copy from server log on mac

### ISSUE THREAD

**Issue by cwsterling** [phonegap/phonegap-app-desktop#310]
Doing some debugging where I'm making remote calls to a server and are given a service ticket. I can't copy the service ticket in the server log to be able to debug. I've tried both command + c and control + c to copy.

Tried to search, didn't find anything

**Comment by hermwong** [comment]
Copy and Select All have been added to the PhoneGap Desktop App. Keyboard shortcuts for both features have been added as well.
