### ISSUE TITLE
update workflow

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#311]
When the PG-Desktop detects that an update is available it should be prompt the user if they want to update now or update later.

**Comment by hermwong** [comment]
Related: https://github.com/phonegap/phonegap-app-desktop/issues/307

**Comment by hermwong** [comment]
![screen shot 2015-02-23 at 1 54 10 pm](https://cloud.githubusercontent.com/assets/107754/6338409/83d9ad68-bb63-11e4-8685-577b7768092f.png)

**Comment by mwbrooks** [comment]
Nice!

**Comment by hermwong** [comment]
![win-update-prompt](https://cloud.githubusercontent.com/assets/107754/6338643/2d8332a2-bb65-11e4-832f-885d79ca596b.png)

**Comment by hermwong** [comment]
The `Update` button will open the GitHub Releases page for the PG-Desktop and also hide the update prompt.

The `Cancel` button will hide the update prompt.

I think this should be the current update workflow for release 0.1.2.

We will need to modify the `Update` button to initiate the full auto-update workflow in a future release when we are able to resolve: https://github.com/phonegap/phonegap-app-desktop/issues/291
