### ISSUE TITLE
server time out error

### ISSUE THREAD

**Issue by Ken666** [phonegap/phonegap-app-desktop#313]
When connected to internet PhoneGap desktop accesses 192.168.1.102:3000 as server and I get time out errors on trying to access from device.  With out internet connection  desktop shows server as unknown:3000 although I do have xampp running.

**Comment by sarpramukh** [comment]
i have same problem when i try to connect phonegap desktop server to phonegap desktop app , it gone to timed out.

**Comment by shaun314** [comment]
Having the same issue, just installed the Windows PC Desktop Version and then installed on my Galaxy S4 - I enter the ip address and get time out errors repeatedly.

**Comment by Ken666** [comment]
So, what do we do now? I am going to try the old way of installing PhoneGp and see if i have the same issue.  I will update  when I can.

**Comment by Ken666** [comment]
I went back to the command line install and it's relatively easy to work with so I'll use that until I herar the desktop version is out of beta.
Thanks

**Comment by sarpramukh** [comment]
Thanks Ken666 for giving me some ideas...

**Comment by hermwong** [comment]
Do you have firewall or anti-virus running on your computer?

Firewall and anti-virus may require you to open up the port that the PhoneGap Desktop is using, causing time out issues.

**Comment by Ken666** [comment]
Great help - that did the job.  I had a firewall and anti-virus going.  When I closed them out the url on the desktop worked fine.  thanks much
