### ISSUE TITLE
App disappears w/o crashing and no errors

### ISSUE THREAD

**Issue by andygup** [phonegap/phonegap-app-desktop#315]
If I leave the app idling and open on my Android sometimes it just disappears and I'm left with a blank screen. The app framework itself doesn't crash, it looks like the view simply goes blank. No errors show up in the PhoneGap Server Log. 

This is not consistently reproducible at this time. But, if someone else experiences this hopefully we'll know it's not platform or phone specific. 

To reload the app I have to hit the Android navigation back button and then reconnect.

Nexus 5
Android 5.0.1
Mac OSX 10.9.5

**Comment by hermwong** [comment]
Hi @andygup, thanks for reporting this issue. Could you answer a few questions so that I have a better idea of what is happening?

Which app is disappearing? Your mobile app that you're previewing on your Android device using the PhoneGap Developer App or is it the PhoneGap Desktop App?

**Comment by andygup** [comment]
>> Which app is disappearing?
Any custom app. I thought it might have to do with any filesystem change, such as a 'save', in the project directory. For example, when I save any file in the directory and the app in the PhoneGap Developer App reloads. But, in the instances I'm referring to the app simply doesn't come back and I hadn't knowingly made any changes in the project directory.

>>Your mobile app that you're previewing on your Android device using the PhoneGap Developer App or is it the PhoneGap Desktop App?

The app is disappearing from the PhoneGap Developer App installed on my Android phone. I didn't know the Mac version of the PhoneGap Desktop App had a preview window?

**Comment by hermwong** [comment]
Thanks for the clarification.

The PhoneGap Desktop App doesn't have a preview window, the question was poorly worded. I was trying to find out if it was the PhoneGap Desktop App that was disappearing on you or if it was your own app.

**Comment by xclipper** [comment]
I have the same issue. My mobile app that i developped with Phonegap hangs some device. iOs iPad, Nexus 5.

**Comment by craigfairhurst** [comment]
Apparently your bundle id in iTunes Connect has to be the same as in your config.xml file but doesn't seem to work for me. [Craig](http://www.youds.com)

**Comment by surajpindoria** [comment]
This is an old issue related to the developer app. A lot has changed in both the desktop and developer apps, going to close this off. If you are still able to reproduce, please reopen this.
