### ISSUE TITLE
Provide direction about the server url

### ISSUE THREAD

**Issue by cfjedimaster** [phonegap/phonegap-app-desktop#316]
So, being a dummy, I started up the server and copied the url to my browser. That displayed the app but caused Chrome to crash. I know (now ;) that the use case is to use the Developer App, but it would be nice if the Desktop App made this more clear. (Or the docs anyway.)

**Comment by hermwong** [comment]
Issue has been fixed through on the [PhoneGap Docs](http://docs.phonegap.com/getting-started/4-run-your-app/desktop/) site.
