### ISSUE TITLE
Play Button doesn't start the right project when no projects are being served

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-app-desktop#320]
If I have a list of projects that are all inactive (not being served), and click the Play button on a project in the list, most times the wrong project gets started rather the one with the play button I clicked. If I subsequently hit play on the one I really want **without stopping the first one**, it will play. 

Any time all are inactive though by hitting stop, it's uncertain which will actually play when hitting play on one in the list.

**Comment by mannly01** [comment]
This is still happening in 0.1.8.
