### ISSUE TITLE
PhoneGap Desktop unable to load project templates

### ISSUE THREAD

**Issue by mramsay356** [phonegap/phonegap-app-desktop#322]
Hi, 

I am trying to develop a cross-platform mobile app for my company using the phonegap desktop application as the IDE.

Every time I create a new project, I get told that "the selected folder does not contain a config.xml file". I have tried saving the project to both our network and my local machine, as well as running the application as an administrator but the same error seems to occur. I am also constantly told that the server is offline.

I have reinstalled the application using the 1.1.2 build but nothing has changed.
I am using Windows 7 64-bit and have all antivirus turned off while endeavoring to solve the issue.

What should I do to get the application running?

**Comment by hermwong** [comment]
Would you be able to attach a screen shot of your app's folder structure with all of the `www` folder expanded?

Example provided below:
![screen shot 2015-03-12 at 10 38 45 am](https://cloud.githubusercontent.com/assets/107754/6624055/1c896510-c8a4-11e4-90da-0652ed9086fe.png)

**Comment by mramsay356** [comment]
I have attached a screen shot but the issue seems to be after I create new project... the folders are empty and nothing is there. There is no network or security measure preventing the app from doing anything but the folders it creates are empty.
![phonegap-bug](https://cloud.githubusercontent.com/assets/11441359/6625480/ab94d4de-c8c6-11e4-9e6b-54ec331d61c3.png)

**Comment by hermwong** [comment]
I think you're running into the same issue as this one: https://github.com/phonegap/phonegap-app-desktop/issues/257

**Comment by hermwong** [comment]
Are you're `.cordova`, `hooks`, `platforms` and `plugins` folders empty?

If they are it sounds like the PhoneGap Desktop had an issue initializing the project templates that are used to create projects.

Try these steps to reset the project templates:

1. make sure your firewall or antivirus will allow the port that PhoneGap Desktop uses to access the Internet
1. quit PhoneGap Desktop
1. delete the following folders: `.cordova`, `hooks`, `platforms` and `plugins`
1. restart PhoneGap Desktop

**Comment by mramsay356** [comment]
The server port :3000 is open and nothing is inhibiting it from accessing the internet but new projects are still created with empty folders. Is there somewhere I can download a working demo to see if I can host it from the application.

**Comment by hermwong** [comment]
Thanks for the info, we're currently looking into the module that does the template loading for the PhoneGap Desktop App.

It seems that there might be an issue related in the template loading code.

**Comment by hermwong** [comment]
Logged in the `connect-phonegap` issue tracker: https://github.com/phonegap/connect-phonegap/issues/108
