### ISSUE TITLE
Phonegap desktop app crashes on project creation

### ISSUE THREAD

**Issue by ghost** [phonegap/phonegap-app-desktop#323]
Hi, 
I have installed the app and try to launch it in my windows 7 32 bit OS. The app opens up fine but I am not able to create a new project. When I click the + button, it takes me through choosing path and naming the app but when I click create, the app stops responding and crashes.

**Comment by hermwong** [comment]
Are you getting an error message or is the PG-Desktop App completely crashing without any error message being displayed?

**Comment by surajpindoria** [comment]
Closing due to lack of response, please reopen if this is still an issue.
