### ISSUE TITLE
Phonegapp Desktop App crashes

### ISSUE THREAD

**Issue by kaiserkiwi** [phonegap/phonegap-app-desktop#324]
Last week I installed the Desktop App to run a Phonegap-Server on my Network. It worked fine. But now, if I try to start the application, it crashes after it tries to connect to the Server. :-1:

**Comment by hermwong** [comment]
Are you getting an error message or is the PG-Desktop App completely crashing without any error message being displayed?

**Comment by hermwong** [comment]
Are you using the Windows or Mac version of the PG-Desktop App?

**Comment by hermwong** [comment]
Closing due to lack of info from the user.
