### ISSUE TITLE
Phonegap "Server is Offline"/ config.xml missing

### ISSUE THREAD

**Issue by nighty9** [phonegap/phonegap-app-desktop#325]
Hello,

I'm on a Macbook pro OSX 10.9.5

I've been browsing the forums but can't find a working solution.

I installed the Desktop app from the website, using njs doesn't work in China it seems like, nothing is downloading using command lines.

When i try to create a new project i get the Config.xml file missing; from what i could read it's because the app doesn't download the templates from phonegap's server.

My connection is working, i tried without VPN, with Astrill in OpenWeb, OpenVPN and also in Stealth VPN; nothing is working.

Thank you for your help,

Nicolas

**Comment by hermwong** [comment]
Related to: https://github.com/phonegap/phonegap-app-desktop/issues/322

See: https://github.com/phonegap/phonegap-app-desktop/issues/322#issuecomment-83718756
