### ISSUE TITLE
Source Code Lost in Translation

### ISSUE THREAD

**Issue by chimon2000** [phonegap/phonegap-app-desktop#327]
I am using PhoneGap on w/ an optimized index file (contains all of my JavaScript, CSS, etc.)

When I use the desktop app to debug, there is a line

`var iframeContents = '<html><body>' + script + '</body></html>';`

That gets translated to 

`var iframeContents = '<html><body>' + script + '<script type="text/javascript">`

Which causes epic failure (error, along w/ source code being displayed). I have verified that this is not an issue when I run my emulator, both for windows 8 and android.

The specific offending library I am using is firebase v.2.2.3 and I would imagine that you can recreate this issue w/o even optimizing the file, but here's my steps to reproduce:
1. `bower install firebase` and include its reference in your index.html
2. `npm install -g vulcanize`
3. `vulcanize --inline index.html`
4. Put your vulcanized index file in your phonegap project and Run it in desktop
5. Hit the page from your browser and you'll see the source code.

**Comment by chimon2000** [comment]
I believe this issue exists if I serve my app CLI style as well using 

`phonegap serve`

**Comment by surajpindoria** [comment]
Is this still an issue @chimon2000? If not I am going to close this out.
