### ISSUE TITLE
icons and splashscreen not integrated in build

### ISSUE THREAD

**Issue by BMo-design** [phonegap/phonegap-app-desktop#328]
Hi,
I used your great desctop app and created a new hello world example.
Next I ziped it, upload it to build.phonegap.com and build an ios app (with phonegap version 3.6.3).

Works well, I got a working app.
But the build routine didn't integrated your icons and splashscreens in www/res/...

I tried to find the error but...
Not succeeded. 

Do you have an idea?

**Comment by BMo-design** [comment]
I work on mac

**Comment by hermwong** [comment]
Which version of iOS are you targeting when you build your app on build.phonegap.com?

**Comment by surajpindoria** [comment]
Build has fixed many issues related to icons, going to close. If you are still seeing this please reopen this issue.
