### ISSUE TITLE
Fullscreen and Orientation not working

### ISSUE THREAD

**Issue by iamdriz** [phonegap/phonegap-app-desktop#329]
In my config.xml I have:

```
<preference name="orientation" value="landscape"/>
<preference name="fullscreen" value="true"/>
```

But when testing the app with the latest version of PhoneGap Desktop, it doesn't hide the status bar or show the app in landscape mode on my iPhone 6 with iOS 8...

Is this supported in PhoneGap Desktop yet?

**Comment by iamdriz** [comment]
Any updates on this?

**Comment by hermwong** [comment]
Orientation isn't working on the PhoneGap Developer App and has been logged as an issue: https://github.com/phonegap/phonegap-app-developer/issues/266

I'll need verify if fullscreen is supported in the PhoneGap Developer App.

**Comment by Justin-Case** [comment]
PhoneGap Developer Beta 1.9 serving locally from a PC and an iPad running v1.5.4 PhoneGap Developer app from the App Store.  The iPad won't change orientation to Landscape and the iOS title bar is still visible.  Building on the PhoneGap cloud and then provisioning it *will* orient as expected but the iOS title bar is still displaying.  The config.xml, I believe, is correctly asking for the two preferences:

    <preference name="orientation" value="default" />
    <preference name="fullscreen" value="true" />

**Comment by surajpindoria** [comment]
The issue with landscape mode in the developer app has been fixed. The developer app also does not read config.xml preferences, only the contents of your www directory. That is why you are not seeing your app in fullscreen.

Going to close this.
