### ISSUE TITLE
Desktop app gets private IP address

### ISSUE THREAD

**Issue by lehik** [phonegap/phonegap-app-desktop#330]
I have 2 network connections on my Win 8.1 desktop:
1) Ethernet (which gets an IP address from DHCP)
2) vEthernet (added by MS Visual Studio for WP app emulator. The connection is called Internal Ethernet Port Windows Phone Emulator Internal Switch and it has a private IP address 169.254.80.80)

The problem is that if the vEthernet is enabled, Phonegap Desktop also gets the private address 169.254.80.80:3000 and there's no way to connect to the server. If I disable the vEthernet adapter, everything works as expected.

Is there any way to force the Phonegap Desktop to use certain connection? Or at least it would be good to inform the user if the IP is in private range.

**Comment by hermwong** [comment]
PhoneGap Desktop currently doesn't have the ability to configure a certain connection; it only uses the computer's default connection.

In theory, it might be possibly to do it with some type of networking / routing / firewall software; but I haven't tried it.

**Comment by hermwong** [comment]
Related to this issue: https://github.com/phonegap/connect-phonegap/issues/77

**Comment by theogray** [comment]
I have the same adapters as @lehik but have found no problem connecting as although Phonegap Developer says it's running on just the `169.254...` address, in reality it has bound to port `3000` on all available IPs, including the IPv4 addresses of all adapters and `127.0.0.1`.

**Comment by hermwong** [comment]
Moving the discussion over to #356.

**Comment by hermwong** [comment]
Possible solution: https://github.com/phonegap/phonegap-app-desktop/issues/356#issuecomment-145995007
