### ISSUE TITLE
Sever Offline - > Selected folder doesn't contain config.xml file ???

### ISSUE THREAD

**Issue by afsheen1** [phonegap/phonegap-app-desktop#331]
Hi, 

I download phonegap desktop version 0.1.3 and install it in windows 7 everything correct and unlocked the files inside phonegap folder and run the .exe as admin... after adding new project it keep says.

Selected folder doesn't contain config.xml file,

after creating project I check the folder created by phonegap it's all EMPTY... nothing inside.

I search here but find no helpfully content to help me out...the firwall allowed  too

![1](https://cloud.githubusercontent.com/assets/11718827/6895572/f189cfce-d6f6-11e4-809a-686bbeeec55e.jpg)
![2](https://cloud.githubusercontent.com/assets/11718827/6895575/fb27c09a-d6f6-11e4-9029-7cf3bf2142d4.jpg)
![3](https://cloud.githubusercontent.com/assets/11718827/6895576/fe7750c6-d6f6-11e4-9796-8b16a86f84ec.jpg)
![4](https://cloud.githubusercontent.com/assets/11718827/6895580/0729352c-d6f7-11e4-96be-d74c665eadae.jpg)

**Comment by afsheen1** [comment]
hi,

any update  on this issue ?

**Comment by afsheen1** [comment]
Hi,

I solved the problem myself.... maybe it will be helpful for someone else also.

when you first create a project the phonegap desktop app add a folder in ,
C:\Users\yoursername\   and the folder will be   .cordova  delete this folder and run the phonegap  .exe again add your new project now it will work.... remember you should allowed phonegap in antivirus firewall as well.

this way phonegap desktop app worked for me.

thanks

**Comment by hermwong** [comment]
The selected folder doesn't contain config.xml issue is being worked on.

https://github.com/phonegap/phonegap-app-desktop/issues/322
https://github.com/phonegap/connect-phonegap/issues/108

**Comment by dalisoft** [comment]
@afsheen1: Thanks for comment, but your way is not helped for me

**Comment by PedroHFranco** [comment]
Thank, but that wasn't helpful for me too.

**Comment by hermwong** [comment]
@PedroHFranco, which OS are you using?

Have you tried this [solution](https://github.com/phonegap/phonegap-app-desktop/issues/257#issuecomment-68320380).

**Comment by jammes47** [comment]
Did not work for me. 
![23846182_2076576455908415_1553318471_n](https://user-images.githubusercontent.com/31456231/33139666-edd25f0c-cfe8-11e7-8324-457e08c9682d.png)

**Comment by hermwong** [comment]
@jammes47 did you install the Desktop app using the `.exe` installer or manually from the `.zip` files?

**Comment by omar-bakhsh** [comment]
ADD THIS PATH
C:\Users\"UserName"\.cordova
