### ISSUE TITLE
PhoneGap Desktop App server offline

### ISSUE THREAD

**Issue by Malcolmn4i** [phonegap/phonegap-app-desktop#332]
The server offline issue doesn't go away. Ive left it for an hour, restarted the mac reinstalled PhoneGap. I do have internet access.

**Comment by afsheen1** [comment]
@Malcolmn4i  check out here, was same issue....

https://github.com/phonegap/phonegap-app-desktop/issues/331

**Comment by hermwong** [comment]
If you have anti-virus or firewall software they might be blocking the port that the PhoneGap Desktop App is trying to use when it creates the server.

Suggested solutions:
 1. disable your anti-virus or firewall
 1. configure your anti-virus or firewall to allow the port that PhoneGap Desktop App uses for the server

**Comment by dalisoft** [comment]
Hi all!
First-time running PhoneGap Desktop App says "Server is offline". And have some fixes for PC.

1) Please hotspot Wi-Fi from your PC (Virtual Wi-Fi Router)
2) Connect iOS, Android or WP8 Wi-Fi to PC Hotspot.
3) Run PhoneGap Desktop App.
4) Create one project with any name.
5) Please check, server is started, is started, skip to 6-step.
6) Add existing project.
7) Click ">" to your project.
8) Please check, your project is active (left green border on your project line)
9) Run your mobile PhoneGap App.
10) Write IP-adress from PhoneGap Desktop app server adress.
11) Click "Connect".
