### ISSUE TITLE
Media (audio) not working on Android 

### ISSUE THREAD

**Issue by iamandrea** [phonegap/phonegap-app-desktop#335]
I've had someone else test my code and it works fine for them without the Phonegap Deskop App, but when I test the app, it won't work on my end. All my config files have Media enabled - 
<gap:plugin name="org.apache.cordova.media"/>

Here's more detail on my issue - 
http://stackoverflow.com/questions/29456521/phonegap-3-5-audio-not-playing-on-android-even-with-correct-file-type-and-path

**Comment by hermwong** [comment]
Hi @iamandrea,

Currently the only way to preview your app with plugins is to use the PhoneGap CLI to serve your app to the PhoneGap Developer app. The PhoneGap Developer app only supports previewing of the official PhoneGap Plugins.

The PhoneGap Desktop App currently doesn't have support for plugins; the feature is in our roadmap and has been logged in our backlog (https://github.com/phonegap/phonegap-app-desktop/issues/170).
