### ISSUE TITLE
desktop app says "listen EADDRINUSE" then crashes

### ISSUE THREAD

**Issue by jamiemac262** [phonegap/phonegap-app-desktop#336]
I'm not sure what's happening here, when i create a new app the PG Desktop app created the app, gives me a message saying "listen EADDRINUSE" and then the window goes black and crashes.

i don't get any error messages, the first time this happened i got a message about a breakpoint being reached but haven't seen that message since

i had thought this was a bug in the latest release but have just downgraded and have the same issues

**Comment by hermwong** [comment]
Would you be able to provide the following information:

1. Which version of Windows or Mac are you running?
1. Do you have anti-virus or firewall software on your computer?

**Comment by jamiemac262** [comment]
It's windows XP, i do have anti-virus and firewall(s), i am using phonegap at work, i'm not sure what firewalls and anti-virus are on my computer thoughand i won't be back in until Wednesday

**Comment by jamiemac262** [comment]
It's windows XP, i do have anti-virus and firewall(s), i am using phonegap at work, i'm not sure what firewalls and anti-virus are on my computer thoughand i won't be back in until Wednesday

**Comment by hermwong** [comment]
It's possible that the anti-virus or firewall software may be blocking the port that the PhoneGap Desktop App is using for its server; this could lead to the  "listen EADDRINUSE" error.

The other possibility is that your work network might be blocking the port.

I haven't done too much testing on Windows XP, most of my Windows-based testing has been done on Windows 8.1.

**Comment by hermwong** [comment]
Closing due to lack of feedback / info from the user.
