### ISSUE TITLE
Windows bug: App crashes on build

### ISSUE THREAD

**Issue by bgstcola** [phonegap/phonegap-app-desktop#345]
Phonegap App crashes when I build my project. I guess it has something to do with how Windows handles monitoring files that gets deleted and recreated. There are no issues when I build the project on a Mac. 

I get this error:

Uncaught node.js Error
Error: watch EPERM
    at exports._errnoException (util.js:742:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1045:26)

**Comment by hermwong** [comment]
Would you be able to provide the following information:
1. Version of Windows
1. Steps to reproduce

**Comment by bgstcola** [comment]
1. Windows 7 64bit.
2. Delete files ind the www folder while phonegap app is open.

**Comment by hermwong** [comment]
Are you deleting the files using Windows Explorer instead of using the remove project feature in the PhoneGap Desktop App?

**Comment by bgstcola** [comment]
The files get deleted when I run scripts to build the files for the project.

**Comment by hermwong** [comment]
Sounds similar to issue [#300](https://github.com/phonegap/phonegap-app-desktop/issues/300) which seem to cause the PhoneGap Desktop App to crash when project files are deleted or removed without using the remove project feature in PhoneGap Desktop App.

**Comment by bgstcola** [comment]
Yes I believe it's the same issue.

**Comment by hermwong** [comment]
Locking thread since this is a duplicate of #300, keep all discussion of this issue in the #300 comment thread.
