### ISSUE TITLE
Getting project exists notification when creating a new project

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#346]
When creating consecutive new projects in the PhoneGap-Desktop the user will see an error notification stating that "the project already exists and a duplicate has not been added".

1. create a new project (e.g. `test01`) in a directory (e.g. `_test`)
1. after `test01` has been created, immediately create another new project (e.g. `test02) in the same directory (`_test`)
1. the user will see the error notification

**Comment by hermwong** [comment]
It looks like the `create` method is being triggered multiple times when consecutive projects are being created, this causes the error notification to popup.

In the attached screenshot, I'm creating `test09` after creating `test08`. The log shows that `create` (`created project`) is triggered twice when `test09` is created.

![screen shot 2015-05-06 at 2 48 01 pm](https://cloud.githubusercontent.com/assets/107754/7504432/edb0266c-f3fe-11e4-86ea-e7f6fa40d43c.png)

**Comment by hermwong** [comment]
probably related to: https://github.com/phonegap/phonegap-app-desktop/issues/598

**Comment by hollyschinsky** [comment]
I've tested and verified this is no longer an issue.
