### ISSUE TITLE
Desktop app crashes w/ gray screen; No error msg

### ISSUE THREAD

**Issue by andrewjcole** [phonegap/phonegap-app-desktop#347]
I'm kind of new to this program, so feel free to close this issue if this has already been mentioned.

The desktop app ran absolutely fine the first time. I created a project. Then, I restarted the desktop app. Now, whenever I use it, the window turn gray. The app will close and Windows will do the "error report popup".

I am using my old Windows XP laptop while my computer is in for repairs, so it could be a Windows XP problem running the app, but it's hard to be sure. I am not sure how to check which version I'm running

**Comment by hermwong** [comment]
Would you be provide a screenshot?

**Comment by andrewjcole** [comment]
Hello! I cannot get one right now. It looks like a regular Windows window but all the contents are solid gray. After a minute or so, it tells me it stopped working.

**Comment by IOTPractitioner** [comment]
I have a same problem with windows xp.

**Comment by hermwong** [comment]
Win XP is not one of our officially supported platforms. Some early versions of the PhoneGap Desktop were targeted for Windows 7. However the current version (v0.2.0) are developed for and tested on Windows 8.1 and Windows 10.

**Comment by andrewjcole** [comment]
I hope they're still compatible with 7 too (which I'd assume they are since 7 and 8 are similar). Windows 7 is still the most widely used OS sooo....
