### ISSUE TITLE
Desktop App and External plugins

### ISSUE THREAD

**Issue by panayot-zhi** [phonegap/phonegap-app-desktop#351]
Seems that when I serve the application on a local server through the phonegap desktop application it does not load the plugins that I've add through the cli. Deploying the application however, or building with the Phonegap build, recognizes and uses the plugins installed, so I though this is an app issue.

I'm using v 0.1.4 and been testing with a facebookConnect plugin.

**Comment by hermwong** [comment]
Currently we only support the core PhoneGap plugins when you are previewing your application.

**Comment by KamalSalah** [comment]
Then What should i do if i can not install phonegap plugins in phonegap desktop?
If i use phonegap cli will it work do i need to unistall phonegap desktop ?

What component do i need to install phonegap cli? 
Is there any information about this:?

I using mac and i is new of everything with cli.
What do i need to have installed in cli?

Phonegap CLI i understand
NPN?
Other component that are needed to run phonegap error free?

Plese give me some information..

**Comment by hermwong** [comment]
@KamalSalah If you require 3rd party plugins, you will need to use the PhoneGap CLI.

**Comment by surajpindoria** [comment]
@KamalSalah 

Along with the PhoneGap CLI if you are trying to preview your application using the PhoneGap Developer App you will need to create a custom build that includes the 3rd party plugins you would like to use. Below are the docs on how to create this new build.

https://github.com/phonegap/phonegap-app-developer#adding-custom-plugins

**Comment by KamalSalah** [comment]
Hi, Now i Am confused,


Phone-app-desktop
Phone Developer App
PhoneGap CLI
Phonegap plugins
Cordova plugins


I new at all this what is this phone developer app?


Lets begin from the beginning.


I have just installed Phonegap Desktop the problem i have i would like to add an plugin to my project that is missing (Like Background services for audio example)


So what do I need to do?
Please tell me step by step. and a little explanation please so i get it.








Best regards

Kamal Salah

**Comment by hermwong** [comment]
@KamalSalah The information that you're looking for can be found on the [PhoneGap Getting Started guide](http://docs.phonegap.com/getting-started/).

**Comment by KamalSalah** [comment]
Ehen are phonegap desktop new version comming.?

**Comment by KamalSalah** [comment]
Hi, can phone gap run background services with phonegap desktop?








Best regards

Kamal Salah

**Comment by surajpindoria** [comment]
Sorry for the late response @KamalSalah. To answer your first question, we are just finishing up the next release and should hopefully have it out soon.

As to your second, I am not sure I understand what you are asking. Could you please explain what you mean by "background services"?

**Comment by KamalSalah** [comment]
I have an app in time to execute or play an audio filé but do i need to The
applikation to be aktive?  Backgroud service a service in memory that check
The time.when to execute. Like The alarm. In The Phone.

**Comment by surajpindoria** [comment]
There are plugins that can help you to achieve this. After a quick google search I managed to find one that will allow this, I don't know how good this plugin is but they are available.

https://github.com/katzer/cordova-plugin-background-mode

**Comment by KamalSalah** [comment]
OK i using phone gap-desktop and i not good at install any plugin. i waiting for the new phone gap desktop is there any function in that the install the external plugins in  the new version ??


Because i have not manage to arrive install other plugins in the desktop version. is there any step by step how to do that in phone gap desktop app. osx.




Best regards

Kamal Salah

**Comment by surajpindoria** [comment]
So the new version of the desktop app will not allow you to install third-party plugins. The only way to do this would be to use the CLI. The command to add a plugin is: `phonegap plugin add <plugin>`.

I have linked below to the documentation for cordova, which phonegap uses under the hood. All the commands listed on these docs can be used with phonegap, just replace `cordova` with `phonegap` and it will work.

https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html#saving-plugins

**Comment by KamalSalah** [comment]
Do i have to do more than use this cli command do i need to edit other files?
I have installed phone gap cli is this nessarry to? can i run the application from the phone gap cli then? or are i stuck with the cli commands.?


I mean that if i install the plugin can i use phone gap desktop then? because i used to that application..






Best regards

Kamal Salah

**Comment by surajpindoria** [comment]
You will have to continue using the CLI, the desktop app only supports the core phonegap plugins. In order to build for a specific platform, Android, iOS, or Windows, you will need to make sure you have all of the necessary build tools installed on your machine.

http://cordova.apache.org/docs/en/latest/guide/cli/index.html#install-pre-requisites-for-building

**Comment by KamalSalah** [comment]
Will Phonegap Desktop be able to use external plugins from cordova in future? So we can leave the CLI Aside? Because not everybody can use the CLI i dont like the terminal … 






Best regards

Kamal Salah

**Comment by hermwong** [comment]
It's on our roadmap but we don't have an ETA for the feature.

**Comment by KamalSalah** [comment]
What will come in the new relise ? any news?








Best regards

Kamal Salah

**Comment by hermwong** [comment]
The next release will be [PhoneGap Desktop 0.4.5](https://github.com/phonegap/phonegap-app-desktop/milestone/52).

**Comment by KamalSalah** [comment]
I did what you said. (OSX)


phonegap help create

  $ phonegap create path/to/my-app

  $ cd my-app/

  $ phonegap run ios

  $ phonegap analytics on






1. I installed CLI PHonegap
2. Installed NPM
3. Installed Android studio


Navigated to the phongap project i created in Phonegap Desktop (Makes a copy)


Phonegap plugin add cordova-plugin-background-mode


Runned this code as you said then it installed without a problem


Then I phonegap run Android


TO start right?




I get this error:





Dependent plugin "cordova-plugin-device" already installed on browser.







Saved plugin info for "cordova-plugin-background-mode" to config.xml







Kamals-iMac:Bontider_sverige_CLI kamalsalah$ phonegap run android

[phonegap] executing 'cordova platform add --save android ' ...

[phonegap] completed 'cordova platform add --save android --no-telemetry'

[phonegap] executing 'cordova run android ' ...

ANDROID_HOME=/Users/kamalsalah/Library/Android/sdk




JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home




Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.

Looked here: /Users/kamalsalah/Library/Android/sdk/tools/templates/gradle/wrapper




I have the news version of phongap CLI (6.5.2)


There is no wrapper or template directory on my mac (can not find it)


templates/gradle/wrapper



What do I do Wrong?






Best regards

Kamal Salah

**Comment by KamalSalah** [comment]
I got pass this know. but know my question is:


Can i use Phonegap developer from App Store to test if i use Phonegap CLI? And the plugins i added? Does this emulator works?
Or do i have to do anything else to test the application?




Best regards

Kamal Salah

**Comment by surajpindoria** [comment]
No you can not be able to use the developer app as that only includes the core plugins. You will need to create a build using `phonegap build android` and then install the resulting apk to your device.

**Comment by hermwong** [comment]
Here is the list of the default [core plugins](http://docs.phonegap.com/references/plugin-apis/) that are supported by the PhoneGap Developer App.

If you would still like to use the PhoneGap Developer App to preview your App with 3rd party plugins, you will need to build a custom version of the PhoneGap Developer App. Instructions on how to build a custom version of the PhoneGap Developer App can be found [here](http://docs.phonegap.com/references/developer-app/custom-build/ios/).

**Comment by KamalSalah** [comment]
Hi,


Why do i get this?


[phonegap] [console.log] Persistent fs quota granted

[phonegap] 200 /img/splash.png

[phonegap] 200 /all_events.xml

[phonegap] [console.log] StatusBar is not supported

[phonegap] [console.log] Error: exec proxy not found for :: VolumeControl :: getVolume

[phonegap] [console.log] Error: exec proxy not found for :: VolumeControl :: toggleMute

[phonegap] [console.log] Error: exec proxy not found for :: VolumeControl :: isMuted

[phonegap] [console.log] Error: exec proxy not found for :: VolumeControl :: setVolume

[phonegap] [console.log] Device Ready…




I have installed the plugin as you said before.


 phonegap plugin add <plugin>
.



Then i started the Phonegap serve


But getting this error.? Im xml it have added the volume control


Is i missing anything?






Best regards

Kamal Salah

**Comment by surajpindoria** [comment]
Are you testing this on a device or in the browser?

**Comment by KamalSalah** [comment]
Both… but most phone gap developer




Best regards

Kamal Salah

**Comment by KamalSalah** [comment]
I also getting this:




[phonegap] [console.warn] Content Security Policy has been modified to be: <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' gap: ws: https://ssl.gstatic.com;style-src 'self' 'unsafe-inline' data: blob:;media-src *;img-src * 'self' data: content:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">

[phonegap] [console.warn] Content Security Policy has been modified to be: <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' gap: ws: https://ssl.gstatic.com;style-src 'self' 'unsafe-inline' data: blob:;media-src *;img-src * 'self' data: content:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">

[phonegap] [console.warn] Content Security Policy has been modified to be: <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' gap: ws: https://ssl.gstatic.com;style-src 'self' 'unsafe-inline' data: blob:;media-src *;img-src * 'self' data: content:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">

[phonegap] [console.warn] Content Security Policy has been modified to be: <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' gap: ws: https://ssl.gstatic.com;style-src 'self' 'unsafe-inline' data: blob:;media-src *;img-src * 'self' data: content:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">

[phonegap] [console.warn] Content Security Policy has been modified to be: <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' gap: ws: https://ssl.gstatic.com;style-src 'self' 'unsafe-inline' data: blob:;media-src *;img-src * 'self' data: content:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">

[phonegap] [console.warn] Content Security Policy has been modified to be: <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' gap: ws: https://ssl.gstatic.com;style-src 'self' 'unsafe-inline' data: blob:;media-src *;img-src * 'self' data: content:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">

[phonegap] [console.warn] Content Security Policy has been modified to be: <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' gap: ws: https://ssl.gstatic.com;style-src 'self' 'unsafe-inline' data: blob:;media-src *;img-src * 'self' data: content:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">

[phonegap] [console.warn] Content Security Policy has been added: <meta http-equiv="Content-Security-Policy" content="default-src * gap: ws: https://ssl.gstatic.com;img-src * 'self' data: content:;style-src 'self' 'unsafe-inline' data: blob:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">

[phonegap] [console.warn] Content Security Policy has been modified to be: <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' gap: ws: https://ssl.gstatic.com;style-src 'self' 'unsafe-inline' data: blob:;media-src *;img-src * 'self' data: content:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">








Best regards

Kamal Salah

**Comment by surajpindoria** [comment]
You are most likely seeing those previous errors on the browser, and that is because whatever plugin you are trying to use does not have an implementation for the browser platform.

And regarding those warning messages, that is normal. In order for the desktop app and CLI to serve your app to the developer app, we need to modify your content security policy so that it allows certain types of connections in order to work. We are not actually changing any files but on the backend we update it so things will work.

**Comment by KamalSalah** [comment]
Thanks.


There are one more question i trying to find a plugin that controls the volume on the android and iOS phones.


Is this possible?


Can you recommend any?




Best regards

Kamal Salah

**Comment by surajpindoria** [comment]
Looks like Ionic has a plugin that can control volume. Not sure if it does exactly what you want but their plugins are all verified and typically very well maintained.

**Comment by KamalSalah** [comment]
Can i use Inoic plugin ? for phone gap?




Best regards

Kamal Salah

**Comment by KamalSalah** [comment]
I want to mute the phone on a specific time volume to set to 0.


mute on / off


this is what i looking for.




Best regards

Kamal Salah

**Comment by surajpindoria** [comment]
Yes, you can use Ionic plugins with PhoneGap.

**Comment by KamalSalah** [comment]
okej that is nice.
same install method as phongap plugin add..right?




Best regards

Kamal Salah

**Comment by surajpindoria** [comment]
Yes, it is the same. If you open that link it gives you installation instructions as well as how to use the plugin.

**Comment by KamalSalah** [comment]
About media for phoegap. i can no play the mp3 file it seems it does not find it.
i have it in my www root on my phone gap project.


src: A URI containing the audio content. (DOMString)


mediaSuccess: (Optional) The callback that executes after a Media
 object has completed the current play, record, or stop action. (Function)


mediaError: (Optional) The callback that executes if an error occurs. (Function)


mediaStatus: (Optional) The callback that executes to indicate status changes. (Function)



NOTE: cdvfile
 path is supported as src
 parameter:

var my_media = new Media('cdvfile://localhost/temporary/recording.mp3', ...);






i write this to get it but no luck


var my_media = new Media('recording.mp3')





does it not take it form my root?






Best regards

Kamal Salah

**Comment by surajpindoria** [comment]
Sorry @KamalSalah,

I am not too familiar with the media plugin and how the file paths work with a bundled app. You should try asking on the PhoneGap forums, the community will definitely be able to help you there.

https://forums.adobe.com/community/phonegap

**Comment by KamalSalah** [comment]
Hi, I have a question can i use Angular 4 with phone gap?








Best regards

Kamal Salah

**Comment by KamalSalah** [comment]
I mean phone gap Desktop..




Best regards

Kamal Salah

**Comment by KamalSalah** [comment]
When is the background service coming to phone gap Desktop?


I would like to close the app and then still use it for alarms and other triggers application..








Best regards

Kamal Salah

**Comment by surajpindoria** [comment]
Hi @KamalSalah,

Angular does with PhoneGap projects but depending on how you have your setup it may not work with the Desktop app. Anything that requires some post processing in order to build your project (Babel, webpack...) will not work.

There is no plan to add a background service feature that you have described.

**Comment by KamalSalah** [comment]
So background service works if i use angular 4? 


Or is there any future plans to implement background service to phonegap desktop?


We are still in beta what is the plan for this year? anything new or ? Still the same?








Best regards

Kamal Salah

**Comment by surajpindoria** [comment]
There are no future plans to implement background services.
