### ISSUE TITLE
OSX error: “PhoneGap” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by michalien** [phonegap/phonegap-app-desktop#355]
Downloaded the OSX desktop app today.  Starting the app I get the following error message:

“PhoneGap” can’t be opened because it is from an unidentified developer.

I know I can change my security settings to allow the app to run.  Just wondering if that's the only way?

**Comment by shazron** [comment]
Right-click on the .app, then select "Open" in the context menu. When the dialog shows, select the "Open" button.

**Comment by michalien** [comment]
My system shows only an OK button.  Pressing OK closes the app and I guess I'm not really happy to bypass the security settings.  I'm wondering why the team behind the app would be unidentified?

**Comment by shazron** [comment]
I don't think you followed my instructions to the letter.
See https://support.apple.com/kb/PH14369?locale=en_US

**Comment by michalien** [comment]
Yes, I see you're right.  Thanks for your suggestion and gentle prompting.  I was flicking between tasks and skimmed over the essential .app part of your reply.

**Comment by renjithvk** [comment]
You can't open **undefined developer** application directly form **Launchpad**. Go to **Finder** and open the application from **Applications**.

**Comment by mxcl** [comment]
WTF? My first experience with PhoneGap is one where I suspect it is malware. Get your app signed FFS.

**Comment by shazron** [comment]
I'm sorry Max, I'm surprised that you, as an open source maintainer (thanks for Homebrew, btw) is hurling abuse at other open source maintainers. I'll forward your request to the devs.

**Comment by john3parker** [comment]
Ditto to Max's comment. I can't open PhoneGap on my work laptop due to policy and your application not being signed. @shazron the message you passed on over a year ago didn't stick - try again please.
