### ISSUE TITLE
Download Error in iOS companion app with 0.1.6 of Desktop App

### ISSUE THREAD

**Issue by aptonline** [phonegap/phonegap-app-desktop#358]
I'm getting a download error in the iOS companion app when using 0.1.6 of the PhoneGap desktop app for OSX.  It recommends checking network settings or upgrading the version of PhoneGap CLI.  In the PhoneGap desktop window it states version 1.0.0 under the app title.

Any suggestions?

**Comment by hermwong** [comment]
it looks like the `connect-phonegap` dependency in the `PhoneGap Desktop App` needs to be updated to `v0.16.0`.

**Comment by hermwong** [comment]
![slack_for_ios_upload](https://cloud.githubusercontent.com/assets/107754/7715972/3b705744-fe42-11e4-9f3c-6d38a8145225.png)

**Comment by DennisVanRijswijk** [comment]
Updated to 0.1.7(windows) but download problem on device (Android & iOS) not solved.

**Comment by hermwong** [comment]
Please refer to this comment if you're still running into this issue after updating to PhoneGap Desktop 0.1.7: https://github.com/phonegap/phonegap-app-desktop/issues/360#issuecomment-103969087
