### ISSUE TITLE
InAppBrowser - Android back button

### ISSUE THREAD

**Issue by kennergrings** [phonegap/phonegap-app-desktop#363]
Hi,

I have already a mobile version of a WebSite, when user enter www.mysite.com.br on a mobile device he is redirected to m.mysite.com.br.
Now I'm using PhoneGap Developer App to have a mobile app to publish to Google Play.

To open the mobile version I'm using InAppBrowser and have in my JavaScript the following code: window.open('http://m.mysite.com.br', '_self', 'location=no'). 

When I test the app with PhoneGap Developer on my Android connecting with the server IP, the app loads correctly the webpage and I can navigate on the site. When I press the Android Back button (on the phone) the web page goes back to the previous page correctly on the user navigation history.
But, when I upload my code to PhoneGap Build and download the APK on my Android the back button doesn't works and the InnAppBrowser is closed, going back to the index.html page.

Is it a bug? Can somebody help-me how to solve it?

Best regards,
Kenner Grings

**Comment by hermwong** [comment]
Hi @kennergrings,

You'll probably be able to find some help or the answer to your issue in the [PhoneGap Google Group](https://groups.google.com/forum/#!forum/phonegap).
