### ISSUE TITLE
Iphone 6/6+ scaling issue

### ISSUE THREAD

**Issue by P4V4** [phonegap/phonegap-app-desktop#364]
I am totally new to the phonegap world and so far I love it! 
I encountered this issue and I am not able to solve it, been at it for hours. This is my last place where I could maybe find a solution.
So I am trying to make a HTML canvas which covers the whole screen but the whole application is downsized? I am not sure if this is an error I made somewhere in the config or in the HTML or in the js. I uploaded all files here: http://jsfiddle.net/pezyf0sd/1/ and here: http://jsfiddle.net/pnhvdk4y/

I would really appreciate if someone could help me, I am feeling totally lost...
Edit: I also defined that the app is portrait only (in the conf) but that is not working, what did I do wrong here?

**Comment by hermwong** [comment]
take a look at this issue: https://github.com/phonegap/phonegap-app-desktop/issues/279
