### ISSUE TITLE
Broken app icon on adding, and index.html path is also broken on phonegap mobile app :(

### ISSUE THREAD

**Issue by ipsjolly** [phonegap/phonegap-app-desktop#376]
When I add existing phonegap ionic project  to PDA( Phonegap Desktop App ) v 1.1.7. It is showing broken app icon. And when I see this app on android phonegap app it is showing below error:

Desktop ScreenShot
![pda](https://cloud.githubusercontent.com/assets/12899397/8276878/64b51336-18d9-11e5-8f3a-ba7881c24661.png)

Mobile Screen Shot
![screenshot_2015-06-22-12-14-18](https://cloud.githubusercontent.com/assets/12899397/8276846/eec121f6-18d8-11e5-898b-8b6a1ed1b1d1.png)

**Comment by hermwong** [comment]
Would you be able to provide the following details?

- Which version of Windows are you using on your computer?
- Do you have  firewall or anti-virius software enabled?
- Is your computer and mobile device connected to the same network?
- Are you on a corporate network?

**Comment by hermwong** [comment]
Use #427 for discussion of this missing icon images.
