### ISSUE TITLE
phonegap app desktop is not working with sqlite io.litehelpers.cordova.sqlite Android

### ISSUE THREAD

**Issue by rudraprasadsahu** [phonegap/phonegap-app-desktop#377]
It gives error "Cannot call method 'openDatabase' of undefined

**Comment by hermwong** [comment]
The PhoneGap Desktop & Developer Apps only support the core PhoneGap plugins. Here is the list of [supported plugins](http://docs.phonegap.com/plugin-apis/).

**Comment by hermwong** [comment]
Reference [comment](https://github.com/phonegap/phonegap-app-desktop/issues/343#issuecomment-115809222).
