### ISSUE TITLE
How to set debuggable flag for Android

### ISSUE THREAD

**Issue by marcovtwout** [phonegap/phonegap-app-desktop#378]
When doing the traditional local build, we can enable Chrome Remote Debugging my setting the Debuggable flag in AndroidManifest.xml (according to: https://github.com/phonegap/phonegap/wiki/Debugging-in-PhoneGap#chrome-remote-debugging)

Is there a way to accomplish the same using Phonegap App Desktop?

**Comment by roeycohen** [comment]
+1

**Comment by surajpindoria** [comment]
Unfortunately this is not a limitation of the desktop app, but of the mobile app. Since it is a release version of the app you are not able to debug it, if you wanted to accomplish this you would need to create a custom build of the mobile app with the android debuggable flag.

Going to close this.
