### ISSUE TITLE
Add Travis CI Support

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-desktop#379]
Travis CI can handle the testing aspect of our CI setup.

The Travis CI setup should support PhoneGapCI@adobe.com, Slack, and ci.phonegap.com.

See any PhoneGap project for a `travis.yml` reference file.

**Comment by hermwong** [comment]
Added initial support.

Need to see why Travis CI isn't triggering notifications in the PhoneGap-CI Slack channel.

**Comment by hermwong** [comment]
["How to code-sign OSX Electron Apps in Travis CI"](https://medium.com/juan-cruz-viotti/how-to-code-sign-os-x-electron-apps-in-travis-ci-6b6a0756c04a#.lz5nuuauy) article.

["Code signing Electron applications in Continuous Integration"](http://vilar.cc/2015/codesign-electron-continuous-integration/) uses CircleCI.
