### ISSUE TITLE
Switch NodeWebkit for Electron

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-desktop#381]
Can we switch the current NodeWebkit packager for Electron, without losing the auto-update functionality? If so, let's do it!

**Comment by hermwong** [comment]
Electron template has been set up. Time to start migrating the existing code base into the Electron project and determine which areas of the code that need to be replaced or updated to work in Electron.

**Comment by hermwong** [comment]
Code base has been switched over to Electron. Regression testing of features are being tracked in [issue 418](https://github.com/phonegap/phonegap-app-desktop/issues/418).
