### ISSUE TITLE
Electron Auto-Update Support for OSX

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-desktop#382]
Let's ensure that the auto-update feature continues to work within Electron.

**Comment by hermwong** [comment]
Old school manual update method has been implemented for now. See #458.

**Comment by hermwong** [comment]
[Electron docs for auto-updater](http://electron.atom.io/docs/v0.34.0/api/auto-updater/)

**Comment by hermwong** [comment]
[Mac App Store & Windows auto-updater](http://blog.atom.io/2015/11/05/electron-updates-mac-app-store-and-windows-auto-updater.html)

**Comment by chrisgriffith** [comment]
Am I correct that for OS X releases it is now an either or choice: Have Mac App Store approval OR have access to the auto-updater module?

**Comment by hermwong** [comment]
@chrisgriffith I'm not too sure yet. I just found the blog post and put the link in this issue so that I didn't lose it. I haven't had a chance to read up on it yet.

**Comment by hermwong** [comment]
@chrisgriffith not sure if you've done anymore research into the auto-updater. It looks like latest version of the Electron Auto-updater will allow you to use it in the Mac App Store since it requires the apps to be signed by an Apple Developer Certificate.

**Comment by chrisgriffith** [comment]
Thanks. I did. I am still trying to understand the whole ecosystem and configuration. If you are going to be at PG Day, maybe I can steal some time to look things over

**Comment by hermwong** [comment]
Mac OSX codesigning example: http://www.pracucci.com/atom-electron-signing-mac-app.html

**Comment by hermwong** [comment]
Squirrel.Mac server side reqs: https://github.com/Squirrel/Squirrel.Mac#server-support

**Comment by hermwong** [comment]
TODO: will need to modify `feedUrl` when we get the production URL (https://github.com/phonegap/phonegap-app-desktop/blob/937ac46e38e7ff0790ac9d1d2113ac42b9b19f3d/www/js/auto-updater.js#L22)

**Comment by hermwong** [comment]
We will require visual notification to let the user know when an update has been found and that the app will automatically download, quit, install & restart.

**Comment by hermwong** [comment]
<img width="465" alt="screen shot 2016-01-19 at 1 04 00 pm" src="https://cloud.githubusercontent.com/assets/107754/12431985/6ceb7b38-bead-11e5-8721-8602a2fabd86.png">

Used the same styling as the nwjs auto-update prompt.

**Comment by hermwong** [comment]
Settled on using `A newer version of PhoneGap Desktop was found. PhoneGap Desktop will automatically download the update & restart.` as the update message.

**Comment by hermwong** [comment]
Windows requires us to use a unique AppId in the installer for the auto-updater. Will be using `com.adobe.phonegap.desktop` as the AppId.

**Comment by hermwong** [comment]
Revising the scope to only include auto-updater for OSX. Created a new task to track Windows Auto-updater #542
