### ISSUE TITLE
Investigate Multiple App Usage

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-desktop#384]
Based on our usage information, are developers taking advantage of multiple apps? If so, are they regularly switching between active apps or simply allowing unused apps to "pile up"?

**Comment by hermwong** [comment]
Current stats seem to indicate that 67% of our total sessions only contain 1 project.

**Comment by surajpindoria** [comment]
Is this still relevant or can we close this?

**Comment by hermwong** [comment]
We're collecting analytics on this with the `projectsLoaded` event. We haven't really used the data we've collected yet.

Perhaps it's something we should consider before we get the use cases & workflows created for the Desktop re-write?

**Comment by surajpindoria** [comment]
What was the intention behind this? Were we planning on adding a limit to the projects loaded or something?

**Comment by hermwong** [comment]
To determine if the Desktop app should function and behave as it currently does - allowing user to load multiple projects in the project list or to modify the Desktop app so that it could only load 1 app at a time.

**Comment by surajpindoria** [comment]
Gotcha. In terms of performance I haven't really seen any issues with a lot of projects loaded. That would be my main point to decide whether we add a project limit or not.
