### ISSUE TITLE
Not able to load existing phonegap apps in v0.1.7

### ISSUE THREAD

**Issue by mynk28** [phonegap/phonegap-app-desktop#387]
I've created one app (in Windows 8.1) using phonegap desktop but not able to add as existing project. Not sure if its added but not displaying any projects.

It only showing me new added project in phonegap desktop apps listing. If I modify that project, close the phonegap desktop and relaunch the phonegap desktop, again the project listing is becomes blank.

**Comment by hermwong** [comment]
We haven't been able to reproduce this issue, would you be able to provide more details regarding your system config?
