### ISSUE TITLE
SECURITY WARNING: Please treat the URL above as you would your password and do not share it with anyone.

### ISSUE THREAD

**Issue by mynk28** [phonegap/phonegap-app-desktop#388]
I've used http://coenraets.org/blog/2014/04/facebook-phonegap-cordova-without-plugin/ this article to add external authentication with facebook. But I’m facing a problem after successful login and showing the screen containing following message.

SECURITY WARNING: Please treat the URL above as you would your password and do not share it with anyone.

No unable to go back to my app from it.

I show many of them having the same issue, can anyone let me know how to resolve it?

Thanks!

**Comment by hermwong** [comment]
You might be able to get more help with your issue on the [PhoneGap Google Group](https://groups.google.com/forum/#!forum/phonegap).
