### ISSUE TITLE
console.log codes are buggy

### ISSUE THREAD

**Issue by emnkoksal** [phonegap/phonegap-app-desktop#389]
console.log print codes do not work correctly when the app runs inside phonegap app on android.
Simple texts (eg, console.log('debug 1');) works; however complex objects (eg. console.log($scope)) cause problem; js stops running after that code, and phonegap desktop app does not print any error log about that. So, it is hard to understand.

However, when the app is built and installed as native android app (instead of running in phonegap app), this problem does not exist.

**Comment by hermwong** [comment]
Will it work if you assign your complex object to a temp variable?

```
var tempObj = $scope;
console.log(tempObj);
```

**Comment by surajpindoria** [comment]
Going to close this due to inactivity. Please reopen if you are still seeing this.
