### ISSUE TITLE
(Phonegap Desktop 0.1.2) Unable to download archive from the server

### ISSUE THREAD

**Issue by EdRuane** [phonegap/phonegap-app-desktop#394]
OS: Windows 7 64-bit
Software version: Phonegap Desktop 0.1.2

I installed the latest stable version of the desktop app and tried to load my project. The server seems to be running well enough, but I cannot connect to it via the mobile app or even by browsing directly to it. I get a 404 error when trying to access /__api__/appzip

My firewall is configured to allow all traffic for Phonegap. What steps can I take to get this working?

![image](https://cloud.githubusercontent.com/assets/11572748/8625002/e25bf460-2709-11e5-9a52-5a256607ebce.png)

![2015-07-10 17 48 35](https://cloud.githubusercontent.com/assets/11572748/8625079/723fb5e4-270a-11e5-9dc5-cc613272cdc6.png)

![image](https://cloud.githubusercontent.com/assets/11572748/8625110/a4553d42-270a-11e5-8932-8a3168c24933.png)

**Comment by EdRuane** [comment]
In looking through some of the other issues out there, I see that there's a more recent version out there (0.1.8). I installed that, and now when I try to run the desktop app I get this:

![image](https://cloud.githubusercontent.com/assets/11572748/8625468/ffd0996c-270c-11e5-87be-b2e758b9c6a6.png)

**Comment by deepakgahlot98** [comment]
same issue here as well

**Comment by hermwong** [comment]
related to: It is just a rumor at this point
