### ISSUE TITLE
Phonegap Desktop for Linux

### ISSUE THREAD

**Issue by batalvi** [phonegap/phonegap-app-desktop#397]
Is there a version of Phonegap Desktop for Ubuntu 14.01. Thanks.

**Comment by hermwong** [comment]
Duplicate of: https://github.com/phonegap/phonegap-app-desktop/issues/249

**Comment by jrortiz8585** [comment]
the version for linux ubuntu 14.x

**Comment by pontume1** [comment]
+1 Ubuntu
