### ISSUE TITLE
Crash when I create new project on Mac

### ISSUE THREAD

**Issue by zoiodev** [phonegap/phonegap-app-desktop#407]

**Comment by damiansmith86** [comment]
I am also having issues with the app closing itself once you click on the Create project button.

I am using Yosemite 10.10.4 (14E46)

**Comment by 5HT2A** [comment]
Same here. Have you figured this out maybe?

**Comment by zoiodev** [comment]
Not yet.

_

[cid:B591E12D-2A1E-4777-9478-2707C1A3CCBF@mcci.qg]

-


[cid:E9009CB1-8346-4C13-A7FC-0A3103A4E87E@mcci.qg]

Em 02/09/2015, à(s) 11:13 AM, 5HT2A <notifications@github.com<mailto:notifications@github.com>> escreveu:


Same here. Have you figured this out maybe?

**Comment by hebert-nr** [comment]
I'm having the same issue in Windows. I can get it to load an existing Phonegap app (done through the webpage) but it won't open that one and when I attempt to create the new one, the app closes without error notice upon clicking "Create".

**Comment by hebert-nr** [comment]
It looks like leaving the "ID" textbox in the PhoneGap Desktop app empty/blank allows for creation of the project without shutting down unexpectedly.

**Comment by surajpindoria** [comment]
This is an old issue, we have had many improvements since this was filed. Going to close.
