### ISSUE TITLE
unable create new project

### ISSUE THREAD

**Issue by quyennvse02884** [phonegap/phonegap-app-desktop#411]
Hi all,
When i click "Create project". Phonegap show alert connect ECONNREFUSED 192.30.252.129:443. Unable connect to server. I cannot create new project phonegap. Please help me. Thanks so much.
![8-4-2015 10-34-02 am](https://cloud.githubusercontent.com/assets/8041493/9052685/996e7c7a-3a94-11e5-8cd0-59ccec884726.png)

**Comment by hermwong** [comment]
Try using a different port number. The port `443` is usually a system reserved port for SSL.

**Comment by hermwong** [comment]
PhoneGap Desktop docs for [changing settings](http://docs.phonegap.com/references/desktop-app/edit-settings/).

**Comment by julmot** [comment]
In my case the default port was 3000. It didn't helped to change it.

**Comment by hermwong** [comment]
@julmot If you're on a corporate network or behind a firewall, the default port might be blocked. You'll need to get the port opened by configuring the corporate network or firewall.

**Comment by julmot** [comment]
Can you please describe on detail what needs to be done? I need to tell this my network administrators.

**Comment by hermwong** [comment]
You can either ask them to open up port 3000 (or another port of their choice).

**Comment by RupenAnjaria** [comment]
I am facing the same issue. 
In the image it shows IP as 192.30.252.128:443. It does not have port as 3000 in the message.

**Comment by hermwong** [comment]
You won't be able to use port 443 since it's reserved for SSL. Try a different port.

**Comment by RupenAnjaria** [comment]
I know this. However, in setting we have given different port. I got this port by using dos command "netstat -an" to get list of free port. say for example it is 48120. 

Even after specifying this in setting, phoneGap is referring to 443.

**Comment by RupenAnjaria** [comment]
Please refer this issue https://github.com/phonegap/phonegap-app-desktop/issues/582

**Comment by RupenAnjaria** [comment]
Please refer details provided in
https://github.com/phonegap/phonegap-app-desktop/issues/582

**Comment by derzunov** [comment]
In settings port 3000
In error message - 443
WTF?

**Comment by hermwong** [comment]
@derzunov, could you provide the following information:

PhoneGap Desktop version / PhoneGap CLI version
PhoneGap Mobile App version
Mobile devices & Mobile OS version
Computer OS version
network type (home/corporate)
computer / network security (firewall / anti-virus / disk encryption)
are you using VMs on your computer?
do you have multiple network adapters (or virtual network adapters)
are you using VPN?
