### ISSUE TITLE
Symbolic link to www dir

### ISSUE THREAD

**Issue by olimortimer** [phonegap/phonegap-app-desktop#424]
The Phonegap Desktop App (or at least the mobile app part) seems to have issues when the `www` dir is symlinked to another directory.

This is something I do for all my Phonegap projects, to keep things cleaner and easily accessible to designers etc.  It also allows me to use common files throughout all projects.

However, with the desktop and mobile developer app, as soon as I symlink the `www` dir to another directory, the mobile app cannot download the files.

`Alert
Unable to download archive from the server.

Unable to properly unzip the archive`

If I access the `appzip` URL in my browser (http://192.168.1.154:3000/__api__/appzip), I'm served a zip file, but it's only 22 bytes in size, and cannot be opened.

If I access the app URL in my browser (http://192.168.1.154:3000/), I'm correctly served the app.

**Comment by hermwong** [comment]
Probably related to: https://github.com/phonegap/connect-phonegap/pull/116

**Comment by surajpindoria** [comment]
This has been added already, going to close.
