### ISSUE TITLE
PhoneGap Desktop broken icon for selected app

### ISSUE THREAD

**Issue by Justin-Case** [phonegap/phonegap-app-desktop#427]
PhoneGap Desktop v0.1.9 for Windows:

Seemed to be failing (cosmetically) while serving up the app successfully, showing a broken image reference for the app's logo.png file as referenced in config.xml.

app\config.xml simply references without a path:  <icon src="icon.png" />
app\icon.png

I had to download and review the src for the PhoneGap Desktop application to see that it's trying to display the app's icon in...

phonegap-app-desktop-0.1.9/www/js/project-create-open-handlers.js: updateConfigOnProjectCreation()
    var iconPath = projDir + buildPathBasedOnOS("/www/");
    var projectIcon = global.jQuery.xml.find("icon").attr("src");
    iconPath += projectIcon;

I thought that PhoneGap had the icon.png in the app directory itself rather than the www subfolder.  Anyway, I just copied the icon.png to the app/www folder and now the PhoneGap Desktop app will display the app's icon as expected.  Maybe project-create-open-handlers.js needs to be updated to use the icon.png that's stored in the application directory rather than somewhere else.

**Comment by hermwong** [comment]
probably related to: https://github.com/phonegap/phonegap-app-desktop/issues/376

**Comment by hermwong** [comment]
Did this happen when you opened an existing PhoneGap project?

**Comment by hermwong** [comment]
If you're using a project created by Ionic CLI, I believe the place the icon.png file into `www/img/` directory.

The Cordova & PhoneGap CLI place the icon.png file into the `www` directory; which is why the PhoneGap Desktop looks for the icon at `www/icon.png`.

**Comment by Justin-Case** [comment]
> You should be able to provide an override by adding <icon src='img/icon.png' /> in your project's config.xml file.



If you do this, you’ll break the online build or so experience suggests.


And if this is the way all this works across platforms then why not make it the default in config.xml and in the PhoneGap init routine?





From: Herm Wong
Sent: ‎Tuesday‎, ‎September‎ ‎22‎, ‎2015 ‎4‎:‎27‎ ‎PM
To: phonegap/phonegap-app-desktop
Cc: Justin Case





Closed #427.

**Comment by hermwong** [comment]
The default behavior of searching for the icon in the `www` directory is based off of the the default behavior from the PhoneGap CLI. If you're using some other tool to generate your project then you can either place your icon in the `www` folder or provide an override in the config.xml.

**Comment by serandel** [comment]
I can see using www/icon.png as the default value, but I think it's really broken to append a "www/" path to the override specified in config.xml.
