### ISSUE TITLE
The Phonegap App And The Desktop App Will Not Connect.

### ISSUE THREAD

**Issue by bayez321** [phonegap/phonegap-app-desktop#432]
Any suggestions or help?? Thanks!

**Comment by hermwong** [comment]
Do you have any more details? What error message are you receiving? What is your network / computer set up?

**Comment by hermwong** [comment]
Might be related to: https://github.com/phonegap/phonegap-app-desktop/issues/396

**Comment by edenprojectde** [comment]
0.1.9 Desktop and latest Mobile App are compatible
The Version on the site(http://phonegap.com/blog/2015/03/02/phonegap-app-desktop-0-1-2/) doesn't seem to work with the Mobile App

Try this: https://github.com/phonegap/phonegap-app-desktop/releases
