### ISSUE TITLE
Also Problem with PhoneGap App and Desktop App Connecting

### ISSUE THREAD

**Issue by shill13** [phonegap/phonegap-app-desktop#433]
I get a 'DOWNLOAD ERROR' message, and then an alert comes up which states: 'Unable to download archive from the server.  Unable to properly connect to the server'

It worked fine previously.  I am no aware of anything that changed in the server configuration.

Thank you in advance for your help.

**Comment by hermwong** [comment]
Duplicate: https://github.com/phonegap/phonegap-app-desktop/issues/396
