### ISSUE TITLE
Node.js page openes when we try to open installed PhoneGap desktop application

### ISSUE THREAD

**Issue by neerajtr2000** [phonegap/phonegap-app-desktop#439]
In installed Node.js and PhoneGap desktop application on Windows-7 32 bit. every thing was installed fine but when I try to open Phone Gap, it opens nw.js page

**Comment by hermwong** [comment]
Duplicate: https://github.com/phonegap/phonegap-app-desktop/issues/362

**Comment by hermwong** [comment]
[PhoneGap Desktop 0.1.11](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.1.11) should fix this issue. Please leave any feedback in #362.
