### ISSUE TITLE
Windows Desktop Installation 'Out of memory.' error?

### ISSUE THREAD

**Issue by troliver** [phonegap/phonegap-app-desktop#451]
As per the title, I am getting this error message when trying to install the desktop application, I'm running Windows 7, 16GB ram (lots free), and ~100Gb free HDD, any ideas?!

**Comment by hermwong** [comment]
Is this happening when you run the `PhoneGapSetup.exe` installer?

**Comment by hermwong** [comment]
Closing due to lack of feedback / info from the user.
