### ISSUE TITLE
On OS X 10.11 El Capitan new/updated .dmg versions may NOT work

### ISSUE THREAD

**Issue by PatrikLori** [phonegap/phonegap-app-desktop#452]
We have tested to first install & run ..
PhoneGapDesktop.dmg 0.1.4 => it is working on OS X 10.11            ;-)
PhoneGapDesktop.dmg 0.1.3 => it is also working on OS X 10.11    ;-)
PhoneGapDesktop.dmg 0.1.2 => it is also working on OS X 10.11    ;-)

ATTENTION if you first installing ..
PhoneGapDesktop.dmg 0.1.11 => it is NOT working on OS X 10.11
PhoneGapDesktop.dmg 0.1.10 => it is NOT working on OS X 10.11
PhoneGapDesktop.dmg 0.1.9  => it is NOT working on OS X 10.11
PhoneGapDesktop.dmg 0.1.8  => it is NOT working on OS X 10.11
PhoneGapDesktop.dmg 0.1.7  => it is NOT working on OS X 10.11
PhoneGapDesktop.dmg 0.1.6  => it is NOT working on OS X 10.11
PhoneGapDesktop.dmg 0.1.5  => it is NOT working on OS X 10.11

Please fix the issues!

Quick-Fix:
If we FIRST install PhoneGapDesktop.dmg 0.1.4 AND then PhoneGapDesktop.dmg 0.1.11 it works also on OS X 10.11.

Many Thanks!

**Comment by hermwong** [comment]
That seems very strange that you'd need to install 0.1.4 before any of the newer versions for it to work.

**Comment by hermwong** [comment]
Does it work for you if you try to install 0.1.11 using the `PhoneGap-Desktop-Beta-0.1.11-mac.zip` package?

**Comment by PatrikLori** [comment]
No, the *-01.11-mac.zip package is also NOT working.

.. only the described workaround (first install version 0.1.4) finally solved the problem.

Kind regards
Patrik Lori

Mr. P. Lori
Panoramastr. 6
5625 Kallern
Switzerland

Mobile: 	+41 79 326 75 97
Email:	Patrik@Lori.name

**Comment by hermwong** [comment]
Thanks for the detailed testinog @PatrikLori.

**Comment by barayuda** [comment]
Hi @hermwong I have same issue for 0.1.11 on OSX el capitan
<img width="432" alt="screen shot 2015-10-19 at 10 18 15" src="https://cloud.githubusercontent.com/assets/520463/10568438/17059370-764b-11e5-820b-855dd2ba9213.png">

Thanks for quickFix @PatrikLori

**Comment by barayuda** [comment]
Hi @hermwong I have same issue for 0.1.11 on OSX el capitan
<img width="432" alt="screen shot 2015-10-19 at 10 18 15" src="https://cloud.githubusercontent.com/assets/520463/10568438/17059370-764b-11e5-820b-855dd2ba9213.png">

Thanks for quickFix @PatrikLori

**Comment by etricbiasoni** [comment]
Same issue on El Capitan....
version 0.1.4 say

![12186181_10154179918431509_312965732_o](https://cloud.githubusercontent.com/assets/12458983/10820897/dea28148-7e4f-11e5-8341-d8ffa2a45020.jpg)

version 0.1.5 and later say

![](https://cloud.githubusercontent.com/assets/520463/10568438/17059370-764b-11e5-820b-855dd2ba9213.png)

Any news? thanks

**Comment by hermwong** [comment]
I was able to get the manual install using `PhoneGap-Desktop-Beta-0.1.11-mac.zip` to work in OSX El Capitan.

I did have to enable the Allow apps downloaded from anywhere setting in the OSX's Security and Privacy settings before OSX allowed PhoneGap Desktop to run.
![screen shot 2015-10-29 at 10 12 58 am](https://cloud.githubusercontent.com/assets/107754/10826191/c0be7bde-7e25-11e5-9044-daea08412823.png)

**Comment by hermwong** [comment]
Can you guys try [PhoneGap Desktop Beta 0.2.0](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.2.0)?

**Comment by amakh** [comment]
All versions are working when  "Allow apps downloaded from anywhere" is enabled but isn't launching when app is in Application folder.

Juste tried to put 0.2.0 in my Document folder and it's working (not in Application folder).

**Comment by hermwong** [comment]
@amakh Could you let us know if you used the DMG or the ZIP file to install PhoneGap Desktop on your computer?

**Comment by hermwong** [comment]
@amakh It could be related to El Capitan's new SIP security feature. Some other people have reported that rebooting your computer can fix the issue [more details](http://help.infinitekind.com/discussions/problems/19360-os-x-el-capitan-cannot-use-moneydanceapp-if-moved-to-applications-folder).

**Comment by shazron** [comment]
If its SIP, it's definitely an Electron problem that they have to handle. Probably no access to a folder: https://github.com/mafintosh/electron-prebuilt/issues/48

**Comment by hermwong** [comment]
After some more research it does look like the issue could be SIP related. I've found references of other apps having a similar issue on El Capitan.

[Steam](https://steamcommunity.com/discussions/forum/2/496880503081587427/)
[MoneyApp](http://help.infinitekind.com/discussions/problems/19360-os-x-el-capitan-cannot-use-moneydanceapp-if-moved-to-applications-folder)
[AirTame](http://forum.airtame.com/t/fix-mac-software-v1-5-cant-open-on-el-capitan/2624)

**Comment by amakh** [comment]
@hermwong Tested with 0.2.0:
- The zip version works in the application folder but we have to authorize it from "Security and Privacy".
- Dmg version works fine now, working in app folder and no security settings to do!

**Comment by surajpindoria** [comment]
Seems there was a resolution here, going to close this off.
