### ISSUE TITLE
Downloading... for unlimited time

### ISSUE THREAD

**Issue by moderactif** [phonegap/phonegap-app-desktop#459]
Hello,

I have downloaded the destop software (latest)  and the iOS app "Phonegap Developer".
I created the project on mobile and connected the device to the same network

So I added the Server address in the mobile app but it just says "Downloading..." for unlimited time.

why?

**Comment by hermwong** [comment]
Duplicate of #396.

Closing & locking this issue. Please keep all discussion in #396.
