### ISSUE TITLE
3rd party plugins not installed

### ISSUE THREAD

**Issue by gitlovenotwar** [phonegap/phonegap-app-desktop#460]
Hi, great work on this developer app but it seems 3rd party plugins will be not installed. There is some solution to add the plugin as mentioned here https://github.com/phonegap/phonegap-app-developer/issues/247 but the problem is I am in windows environment having ios devices so it's not possible. Please add the feature to add 3rd party plugins please. Thanks

**Comment by hermwong** [comment]
@gitlovenotwar the only way to support 3rd party plugins would be for you to clone the `phonegap-app-developer` repo and create you own custom build of the `phonegap mobile app` with the 3rd party plugin that you require.

See this [comment](https://github.com/phonegap/phonegap-app-developer/issues/247#issuecomment-67241309) for further instructions on how to build your own version of the `phonegap-app-developer`.

**Comment by gitlovenotwar** [comment]
@hermwong Thanks for the reply. As I mentioned above, <pre>I am in windows environment having ios devices so it's not possible.</pre> to build platform ios.
