### ISSUE TITLE
Cant Create project - ENOTFOUND

### ISSUE THREAD

**Issue by shoeflic** [phonegap/phonegap-app-desktop#462]
Can't create a project  get Alert
getaddrinfo ENOTFOUND github.com github.com:443

I see from another post that 443 is a port setting that should be changed - where do I do that, if this is the cause of the problem.

thx

**Comment by hermwong** [comment]
@shoeflic, PhoneGap Desktop docs for [changing settings](http://docs.phonegap.com/references/desktop-app/edit-settings/).

**Comment by hermwong** [comment]
Possibly related to: #411

**Comment by shoeflic** [comment]
[cid:image001.png@01D1116D.D5169730]
This is a screen shot of my settings – I do not get an IP address in the server port
I this a firewall issue on my end or something else.

Thanks
Sandra

**Comment by hermwong** [comment]
@shoeflic your screen shot didn't get uploaded.

Could you provide the following info?

1. PhoneGap Desktop version / PhoneGap CLI version
1. PhoneGap Mobile App version
1. Mobile devices & Mobile OS version
1. Computer OS version
1. network type (home/corporate)
1. computer / network security (firewall / anti-virus / disk encryption)
1. are you using VMs on your computer?
1. do you have multiple network adapters (or virtual network adapters)
1. number of files in your mobile app
1. size of your mobile app

**Comment by surajpindoria** [comment]
Going to close due to inactivity. Please reopen if you are still seeing this issue.
