### ISSUE TITLE
AMAZINGLY Complicated

### ISSUE THREAD

**Issue by Genysoft** [phonegap/phonegap-app-desktop#475]
Hi I am 58 years old software engeneer... I have not touch much the conception of softwares since my retirement only 3 years ago... I use to have Mobione from Genuitec to build my android app... Genuitec does not support the software anymore and since i do not remember everything about it i wanted to get the tutorial... no way, they remoed it from their website SO i read every where that people now use phone gap ... THERE is nothing easy about it, i downloaded 125 megabytes of stuff to just compile one line of html the redirects to my web sites WHERE ARE the good old years when things were simple...

Is there anyone out there with enough understanding to drive me to a simple html to apk software ?????

I do not want to learn for months just to do that

Thanks

**Comment by hermwong** [comment]
Did you try checking out the walkthrough from the [PhoneGap Documentation](http://docs.phonegap.com/getting-started/1-install-phonegap/desktop/)?

**Comment by purplecabbage** [comment]
npm install -g manifoldjs
    manifoldjs mywebsiteurl
    manifoldjs run android
More info at http://manifoldjs.com/
