### ISSUE TITLE
Installing PhoneGap CLI Mac 10.10.5

### ISSUE THREAD

**Issue by brorbw** [phonegap/phonegap-app-desktop#476]
When i install the cli via "sudo npm install -g phonegap" i get permission denied. I don't think it is related to node.js but rather phonegap. 

Here is a dump from the installation.

>npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.2.2","npm":"2.14.7"})

>\> ws@0.4.31 install /usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/socket.io/node_modules/engine.io/node_modules/ws
\> (node-gyp rebuild 2> builderror.log) || (exit 0)

>shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

>\> ws@0.4.31 install /usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
\> (node-gyp rebuild 2> builderror.log) || (exit 0)

>shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
/usr/local/bin/phonegap -> /usr/local/lib/node_modules/phonegap/bin/phonegap.js
phonegap@5.3.6 /usr/local/lib/node_modules/phonegap
├── pluralize@0.0.4
├── colors@0.6.0-1
├── semver@1.1.0
├── minimist@0.1.0
├── qrcode-terminal@0.9.4
├── shelljs@0.1.4
├── prompt@0.2.11 (revalidator@0.1.8, pkginfo@0.3.1, read@1.0.7, winston@0.6.2, utile@0.2.1)
├── phonegap-build@0.9.2 (colors@0.6.2, qrcode-terminal@0.8.0, optimist@0.3.7, shelljs@0.0.9, phonegap-build-api@0.3.3)
├── connect-phonegap@0.18.0 (home-dir@0.1.2, connect-inject@0.3.2, ip@0.3.1, adm-zip@0.4.7, request-progress@0.3.1, http-proxy@1.8.1, walkdir@0.0.8, shelljs@0.2.6, useragent@2.0.8, request@2.33.0, node-static@0.7.0, gaze@0.4.3, tar@0.1.19, localtunnel@1.3.0, socket.io@1.0.4, connect@2.12.0, archiver@0.14.3)
└── cordova@5.3.3 (underscore@1.7.0, q@1.0.1, nopt@3.0.1, cordova-lib@5.3.3)

**Comment by hermwong** [comment]
@brorbw it looks like you might be having a permissions issue. 

This thread might be able to help you: https://github.com/yeoman/yo/issues/253

**Comment by brorbw** [comment]
Yes thank you. https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md
This fixed the problem. I can now do npm install and sudo npm install without any problem. But it was a hassel since i have multiple .profiles.
