### ISSUE TITLE
Eclipse unable to find the Android project generated by PhoneGap Desktop App

### ISSUE THREAD

**Issue by sumangvs** [phonegap/phonegap-app-desktop#477]
Eclipse unable to find the Android project generated by PhoneGap Desktop App
Is there something which I am missing.
These are the files and folders generated by the PhoneGap Desktop App
![capture](https://cloud.githubusercontent.com/assets/11856427/10985352/943c7de6-8446-11e5-8700-69eb5ba3ad53.PNG)

**Comment by hermwong** [comment]
hi @sumangvs,

The project created by the PhoneGap Desktop only contains the contents of the web portion of a PhoneGap project; it won't create an Android/iOS/Windows Phone specific project.

The feature to build platform specific projects has been logged in our backlog (#20).

**Comment by hermwong** [comment]
You can also use PhoneGap Build or the PhoneGap CLI to build your Android app. More information can be found on the [PhoneGap Docs](http://docs.phonegap.com/getting-started/5-going-further/).
