### ISSUE TITLE
The application PhoneGap.app can't be opened

### ISSUE THREAD

**Issue by DfKimera** [phonegap/phonegap-app-desktop#479]
Since version 0.1.6, starting the application yields a generic error:

![screenshot 2015-11-09 19 59 10](https://cloud.githubusercontent.com/assets/581765/11048182/7d4e3938-871d-11e5-972c-c798cb9ee3e8.png)

By checking the Console, the following error is generated:

`09/11/2015 20:08:46.712 com.apple.xpc.launchd[1]: (com.intel.nw.8672[88453]) Could not find and/or execute program specified by service: 2: No such file or directory: /Applications/PhoneGap.app/Contents/MacOS/node-webkit`

Tested both ZIP and DMG links, and tried starting the app from the Downloads folder and from the Applications folder, all to same avail. I've tested all versions down to 0.1.2, and 0.1.5 is last version that works.

**Comment by hermwong** [comment]
I went back and looked at the change logs for the 0.1.6 release and it looks like the app actually migrated from older `node-webkit` project to it's re-branded `nwjs` project.

Which explains the why the `node-webkit` folder can't be found.

Would you be able to provide more info regarding your computer's setup?

**Comment by DfKimera** [comment]
I'm running OS X 10.11.1 El Capitan on a MBP Early 2011. I have Node/NPM installed globally but never installed the `node-webkit` package, neither locally or globally, so I assume we can discard a path conflict.

I will try the desktop app at my home machine, where I'm still running Yosemite, and see if I get the same error.

**Comment by hermwong** [comment]
Let me know the result of trying to run `PhoneGap.app` on your home machine.

The `nwjs` packages should be included as part of `PhoneGap.app` so the user shouldn't have to pre-install `node-webkit` or `nwjs`.

**Comment by francescom** [comment]
It is a bug in the app. Show the app package contents
Navigate to the MacOS folder, inside the app: PhoneGap.app/Contents/MacOS
Make a symbolic link to nwjs named node-webkit

![schermata 2015-11-23 alle 12 37 29](https://cloud.githubusercontent.com/assets/736161/11335711/fa736d9a-91de-11e5-98c6-d0cab314514c.png)
After this the app opens.

Seriously, how can nobody in the team notice this? They have bundled the app with nwjs but continue to reference it as node-webkit..

**Comment by hermwong** [comment]
I tested using both the `PhoneGapDesktop.dmg` and also using the `PhoneGap-Desktop-Beta-0.1.11-mac.zip` methods from the [PhoneGap Desktop 0.1.11 release page](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.1.11) and don't have the `node-webkit` short cut in my `Contents/MacOS` folder.

Would you be willing to delete your local copy of PhoneGap Desktop and try installing from the release page and letting me know if you're still getting the `node-webkit` short cut in your `Contents/MacOS` folder.

**Comment by francescom** [comment]
Of course you don't have the node-webkit short cut... I created it to make the app launch.

The problem is that there is NO node-webkit while the app is still looking for it. Read the message: ```No such file or directory: /Applications/PhoneGap.app/Contents/MacOS/node-webkit```

- App was fresh from download (Version 0.1.11)
- Couldn't launch (with error dialog above and console message above)
- I created shortcut (technically a symbolic link)
- Now app launches

**UPDATE**

Creating the symbolic link makes the app launch, but then it can't connect with the mobile part. Anyway I downloaded the **beta version** and after a short auto-upgrade of the app itself, now all works.

Strange: the beta auto-upgraded itself, while the stable version did not aut-oupgrade (and didn't work)

**Comment by hermwong** [comment]
It's strange that there were still references to node-webkit. We moved away from node-webkit to nwjs in the [0.1.6 release](https://github.com/phonegap/phonegap-app-desktop/issues/286).

We actually don't have a stable release, if you check out [releases page](https://github.com/phonegap/phonegap-app-desktop/releases) every release of the PhoneGap Desktop has been classified as a beta version.

With the latest auto update are you now running on 0.1.12 or 0.2.0?

**Comment by francescom** [comment]
Now  v0.2.0 (working)

**Comment by hermwong** [comment]
@DfKimera try v0.2.0. We have re-written the PhoneGap Desktop using Electron (Atom Shell).

**Comment by davidsilvasmith** [comment]
What is the link to download so I can proceed?

I had a working phonegap and now from installing the latest [Mac OS X Installer](https://github.com/phonegap/phonegap-app-desktop/releases/download/0.2.0/PhoneGapDesktop.dmg) the install is broken.

Like @francescom said the install is broken with the error message:

    11/25/15 10:04:22.671 AM com.apple.xpc.launchd[1]:(com.apple.xpc.launchd.oneshot.0x10000015.nwjs[2248]) Could not find and/or execute program specified by service: 2: No such file or directory: /Applications/PhoneGap.app/Contents/MacOS/nwjs

**Comment by francescom** [comment]
Yep, the question is not closed until all the old non working versions are removed from download!

Go here and take the beta 020 (PhoneGap-Desktop-Beta-0.2.0-mac.zip): 

https://github.com/phonegap/phonegap-app-desktop/releases

That works (after auto upgrade)

**Comment by markhilton** [comment]
PhoneGap (v0.3.0) getting an error that application cannot be opened. However when I try to open the app from dmg directly it works fine.

**Comment by hermwong** [comment]
@markhilton can you post the error message that you're getting?

**Comment by markhilton** [comment]
@hermwong I am getting: 'The Application "PhoneGap.app" can't be opened' - just like the first comment here. However when I switch accounts on my OS X and try to run it I am getting: "PhoneGap" is damaged and can't be opened. You should move it to the Trash.
I have downloaded and re-installed several times. 
![error](https://cloud.githubusercontent.com/assets/1205145/14709297/edfcd5d0-079d-11e6-9b6e-88281db4ae6c.png)

**Comment by hermwong** [comment]
@markhilton try this one: https://github.com/phonegap/phonegap-app-desktop/releases/download/0.3.0/PhoneGap-0.3.0-loading-fix-2-mac.zip

**Comment by markhilton** [comment]
@hermwong  ![error](https://cloud.githubusercontent.com/assets/1205145/14742105/7f2aa620-0868-11e6-916e-8c49ab78a4eb.png)

**Comment by adamwjohnson5** [comment]
I'm also getting "“PhoneGap” is damaged and can’t be opened. You should move it to the Trash." when trying to install 0.3.1

**Comment by hermwong** [comment]
@markhilton @adamwjohnson5 the error is an OSX security issue. See here for solution: http://www.tech-recipes.com/rx/45404/mac-downloaded-app-is-damaged-and-cant-be-opened-error-solved/

**Comment by markhilton** [comment]
I was able to launch PhoneGap-0.3.0-loading-fix-2-mac.zip after allowing OS X to open applications "from anywhere". However I encounter new errors upon app auto update.
<img width="446" alt="screen1" src="https://cloud.githubusercontent.com/assets/1205145/14762871/72500832-0953-11e6-904b-f32cc494d848.png">
<img width="445" alt="screen2" src="https://cloud.githubusercontent.com/assets/1205145/14762872/725f66f6-0953-11e6-908c-4e416596aadf.png">

**Comment by hermwong** [comment]
@markhilton here is the direct link to manually download & install [PhoneGap Desktop 0.3.1](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.3.1).

**Comment by hermwong** [comment]
@markhilton 

Could you also provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?

**Comment by ndubbaka** [comment]
I get the same error on Beta 0.3.3
PhoneGap-Desktop-Beta-0.3.3-mac.zip https://github.com/phonegap/phonegap-app-desktop/releases/download/0.3.3/PhoneGap-Desktop-Beta-0.3.3-mac.zip
![image](https://cloud.githubusercontent.com/assets/545961/15909028/81e8c384-2d92-11e6-8c8d-4e44e8e65a4e.png)
![image](https://cloud.githubusercontent.com/assets/545961/15909066/a80f0b36-2d92-11e6-90cb-54eacb6918ce.png)

**Comment by hermwong** [comment]
@ndubbaka There are 2 different fixes for the PhoneGap is damaged and can't be opened error.

1. under your system preferences -> security & privacy -> allow apps from anywhere

<img width="467" alt="screen shot 2016-06-08 at 1 25 05 pm" src="https://cloud.githubusercontent.com/assets/107754/15909733/87c59df6-2d7c-11e6-83aa-ba5d61a78c47.png">

2. Right click the app icon and select open from the right click menu.

**Comment by SnakeO** [comment]
Same Bug on 0.3.3 beta

osx 10.11.4: https://wow-ss.s3.amazonaws.com/Zkw6X5l.png
Security settings: https://wow-ss.s3.amazonaws.com/wACfG0v.png
When I double click the app or right click and open: https://wow-ss.s3.amazonaws.com/e62WoU1.png
Console: https://wow-ss.s3.amazonaws.com/muVzb3b.png

**Comment by hermwong** [comment]
@SnakeO In the console screen shot it shows a reference to `nw-builder` and `nwjs` which we haven't used in PhoneGap Desktop since 0.1.X. I'm not sure why you're getting the references to `nwjs` since have been using Electron since 0.2.X and above versions of PhoneGap Desktop.

A few people have reported similar issues in the past, but I've never been able to replicate the issue.

**Comment by faluxbkk** [comment]
On MacOS Sierra, I get it to open and work 100% properly only by right clicking the App, 'Show Package Contents', navigate to '/Applications/PhoneGap.app/Contents/MacOS' and double-click 'PhoneGap'.
