### ISSUE TITLE
phonegap

### ISSUE THREAD

**Issue by mahissswetu** [phonegap/phonegap-app-desktop#484]
when i publish my file in phonegap developer in device then an problem occure my file size is 52 mb it suddenly close app and how can i build apk plz give me full tutorial or upload video in youtube bcz i am your subscriber watcher i will receive that

**Comment by hermwong** [comment]
For instructions on how to build and package the apk of your PhoneGap app see the [documentation on the PhoneGap Docs](http://docs.phonegap.com/getting-started/5-going-further/).
