### ISSUE TITLE
Upgrade to Connect-PhoneGap 0.18.1

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-desktop#494]
This update should be backwards compatible with the existing module.
- For those with multiple IP Addresses, the additional addresses will be listed in the _Server Logs_.
- We will need to come up with a design that can visually show the multiple IP Addresses as well.

**Comment by hermwong** [comment]
![desktop-app_0021_apps-runningmutipleip_1024](https://cloud.githubusercontent.com/assets/107754/11488232/e14ac87c-9779-11e5-9439-cac84f75076b.png)

- When 1 IP address is available, use the current display
- When multiple IP Addresses are available, use the above mockup
- Add event tracking to know how many people are seeing multiple IP addresses and how many
(the analytics can help inform us on whether Joni needs to change the design for people seeing 9 IP addresses)

**Comment by mwbrooks** [comment]
For `connect-phonegap` the serve's completion event returns the following object:

**For one IP address:**

```javascript
{
    address: '192.168.0.1',
    addresses: ['192.168.0.1'],
    port: '3000',
    server: server
}
```

**For multiple IP addresses:**

```javascript
{
    address: '192.168.0.1',
    addresses: ['192.168.0.1', '10.0.1.4'],
    port: '3000',
    server: server
}
```

The first IP address is always the best guess.

**Comment by hermwong** [comment]
The interface needs to scrollable when 5+ IP addresses are found.

The analytics for tracking number of IP addresses found still need to be added.

**Comment by hermwong** [comment]
<img width="302" alt="screen shot 2015-12-15 at 3 48 50 pm" src="https://cloud.githubusercontent.com/assets/107754/11827782/c3b716fa-a343-11e5-80df-dca37e979340.png">

Server Log displaying multiple IP addresses using Mac OSX with a Win 10 VM running.

**Comment by hermwong** [comment]
<img width="421" alt="screen shot 2015-12-15 at 3 53 48 pm" src="https://cloud.githubusercontent.com/assets/107754/11827834/10352f80-a344-11e5-9fdc-fe9f4a752663.png">
