### ISSUE TITLE
PhoneGap Desktop Mac 0.2.0 - Can't open app

### ISSUE THREAD

**Issue by shazron** [phonegap/phonegap-app-desktop#496]
@hermwong The app can't launch, see screenshot below.
I'm running El Capitan 10.11 with the latest system updates, etc.

![screen shot 2015-11-30 at 1 38 58 am](https://cloud.githubusercontent.com/assets/36107/11468326/6abbc20e-9703-11e5-8012-1d129e343e69.png)

**Comment by hermwong** [comment]
Did you install using the DMG installer or the ZIP file?

We've had another user report that he wasn't able to run PhoneGap Desktop from the Applications folder but was able to run it from another folder. [More details](https://github.com/phonegap/phonegap-app-desktop/issues/452#issuecomment-160156288f).

**Comment by shazron** [comment]
.DMG, then drag install to the Applications folder. I then ran it from the Applications folder using, right-click -> Open (just in case the Gatekeeper thing prevented me).

**Comment by shazron** [comment]
Could be this, but I'm not sure why the exec bit wasn't set: http://superuser.com/questions/898124/the-application-someapp-app-can-t-be-opened

**Comment by mwbrooks** [comment]
I'm having the same issue.

Here's what I've discovered:

- DMG installer produces the _can't be opened_ error
- ZIP dragged into the `/Applications` folder produces the _can't be opened_ error
- ZIP run from `/Downloads` works (same zip that was dragged into `/Applications`
  - Remember to update the security settings to run any app from anywhere (resets on OS updates)

**Comment by mwbrooks** [comment]
Oddly, after rebooting my Macbook, I can now open the app successfully.

**Comment by shazron** [comment]
I think OS X when you try launch it, it's running as a superuser for some reason? who knows.

When I do `su /Applications/PhoneGap.app/Contents/MacOS/Electron` it fails but when I run ` /Applications/PhoneGap.app/Contents/MacOS/Electron` (current user) it passes.

**Comment by heporap** [comment]
I can opend the App as follows.

Open package of /Applications/PhoneGap.app
Do right click /Applications/PhoneGap.app/Contents/MacOS/Electron
Select "Open with" of the  context menu, and "terminal 2.3" of the choices

**Comment by sergiks** [comment]
Can it be a conflict with another Electron (atom/electron) I have locally installed?

**Comment by surajpindoria** [comment]
This may have been an issue with this release, haven't seen this since. Going to close this issue.
