### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by cvesnetadmin** [phonegap/phonegap-app-desktop#500]
We are attempting to try this software, but we keep getting unable to obtain first certificate when we create a project.  I believe its due to our content filter, but I do not see anything getting blocked in the firewall logs. Thoughts?

**Comment by hermwong** [comment]
Would you be able to provide more details on your system config?

* OS & Version
* firewall (y/n)
* AV software (y/n)
* which version of PhoneGap Mobile App (iOS/Android or Windows Phone)

Would you also be able to provide a screen shot?

**Comment by cvesnetadmin** [comment]
This error appears after you open the Program on the Computer, then try to create a new Project.

Windows 7 Professional x64
Windows Firewall No
AV Software No
We don’t even make it to which type of app you are designing, but it would be for iOS.

**Comment by cvesnetadmin** [comment]
![phonegap error](https://cloud.githubusercontent.com/assets/16157394/11666167/148312ea-9db9-11e5-8ff9-4ea155f5a5a0.png)

**Comment by hermwong** [comment]
A quick google search seems to indicate that the issue is related to [Windows network configuration](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=windows+7+unable+to+verify+certificate).
