### ISSUE TITLE
PG Desktop autoreload does not work on Desktop Web Browser

### ISSUE THREAD

**Issue by iSynth** [phonegap/phonegap-app-desktop#502]
Hello!

Why do you close this issue ? https://github.com/phonegap/phonegap-app-desktop/issues/501
It has not due to auto-update on mobile devices. I mean auto-update in the desktop browser. It seems that support for desktop browsers absent. PG Desktop developers should pay attention to how such of auto-apdate in browsers is implemented in Ionic fremawork (http://ionicframework.com). We all know that the development and debugging JavaScript applications in desktop browsers do much more convenient. Therefore, the feature to auto-update in browsers should definitely be supported in PG Desktop.

**Comment by hermwong** [comment]
This feature has been implemented in the PhoneGap Desktop Browser Support. It should be released soon.
