### ISSUE TITLE
PG Desktop hangs with serving openui5 framefork project.

### ISSUE THREAD

**Issue by iSynth** [phonegap/phonegap-app-desktop#503]
PG Desktop hangs when I add project containing openui5 framework (http://openui5.org).
In the Activity Monitor PG Desktop process takes 100% CPU.

OS X EL Capitan 10.11.1.

**Comment by surajpindoria** [comment]
A lot of changes have happened to both the desktop app and openui5. I am going to close this, please reopen if it is still an issue.
