### ISSUE TITLE
Incorrect IP Address Displayed

### ISSUE THREAD

**Issue by Nickm2** [phonegap/phonegap-app-desktop#508]
The IP address displayed by the application when the server was running was incorrect for me. It used the IP address of the virtual network adapter that is added to Windows when you install VMWare to your computer. I believe this should be a quick and easy fix, but it should be looked into in case some less tech-savvy people try using the app and can't figure out what IP address they should actually type into the mobile app.

**Comment by hermwong** [comment]
this will be fixed with the changes made in #494.
