### ISSUE TITLE
window.cordova.plugins is undefined 

### ISSUE THREAD

**Issue by alialaa** [phonegap/phonegap-app-desktop#509]
Hello, Is it normal that window.cordova.plugins is undefined when testing with desktop app? I am using ionic and when trying to alert plugins I get undefined

```
$ionicPlatform.ready(function() {
    alert(JSON.stringify(window.cordova)); //defined
    alert(JSON.stringify(window.cordova.plugins)); //undefined
})
```

also StatusBar styling is not working, is that related?

```
if (window.StatusBar) {
  // org.apache.cordova.statusbar required
  // StatusBar.styleDefault();
  StatusBar.style(1) //not showing on mobile
  StatusBar.backgroundColorByHexString("#FAB"); //not showing on mobile
}
```

**Comment by surajpindoria** [comment]
Just tested with Ionic and this works. Closing issue.

**Comment by alialaa** [comment]
@surajpindoria Thanks for the fast reply, you really saved my life bro.
