### ISSUE TITLE
Phonegap Desktop Create project error : getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by maddy20pg** [phonegap/phonegap-app-desktop#511]
I am new to phonegap and trying to create my first project using phonegap desktop app.
While creating project I am getting error:
getaddrinfo EAI_AGAIN github.com:443
 and somtimes i got
getaddrinfo ENOTFOUND

I am using Phonegapover an organization proxy settings. If proxy is the problem please let me know where I can provide proxy server and port settings  to create the project.
Attaching the screenshot for the error.
![error_phonegap](https://cloud.githubusercontent.com/assets/16332211/11863097/0155af7a-a4b7-11e5-848c-00f48b98b829.PNG)

**Comment by maddy20pg** [comment]
heyy buddy.. any suggestions on how to solve this issue plz... bcoz i have to upload my www folder evrytime on build.phonegap.com to see the changes..
plz let me know if anything can be done on this part

**Comment by hermwong** [comment]
Try some of the suggestions here: #411.

**Comment by maddy20pg** [comment]
Do i have to include my company proxy settings also?..firewall uses 8080 port to open network access. I tried to change 3000 to 8080 but same result. 
can you please tell me whats the main reason behind this error?
in the post you mentioned.. its not clear

**Comment by hermwong** [comment]
When PhoneGap Desktop creates a project it tries to start up a local webserver to host the PhoneGap project that you've just created. You can use the PhoneGap Mobile App to preview the PhoneGap project that is being served by PhoneGap Desktop's local webserver.

The issue that you seem to be encountering is that the ports that you've tried are either 

1. closed off or blocked by a corporate network security policy or a firewall.
1. used by another process / protocol.

For example port 443 doesn't work since it is used by the SSL protocol.

**Comment by maddy20pg** [comment]
Ok ... but durnig normal web server hosting.. when I try to host a webapp using Eclipse, I can easily start a server on ports like 8080/8081/8085 and can run the app on that hosted server. It means these ports are not blocked by the corporate firewall. Then why phonegap is unable to host its server on those ports when there is nothing running on them

**Comment by midza04** [comment]
Im facing a similar problem ..mind to share the solution if your problem was solved?

**Comment by hermwong** [comment]
After a bit more research I've found `getaddrinfo EAI_AGAIN` error seems to be caused by a [DNS resolution error](https://github.com/npm/npm/issues/7348#issuecomment-75363630).

We also encountered the same issue with the [PhoneGap-CLI project](https://github.com/phonegap/phonegap-cli/issues/533).

**Comment by RupenAnjaria** [comment]
I am facing the same issue.

Is there any real solution to this problem? The arguments by maddy20pg does not seems to be answered by any reference.

**Comment by Shodipo-Ayomide00** [comment]
It didn't work because phonegap works with Internet it needs a server to start up and running to know more please call +2348130776799

**Comment by lenisheita** [comment]
after the error you need to navigate to the folder where you created the project(local path), the project will be there. copy the server address in the web browser to display the html page. mine worked

**Comment by surajpindoria** [comment]
Going to close because of inactivity. Please reopen if this is still an issue.
