### ISSUE TITLE
Don't see the play button and pause button and the server address

### ISSUE THREAD

**Issue by koushik72** [phonegap/phonegap-app-desktop#513]
![image](https://cloud.githubusercontent.com/assets/12221775/11914256/80eebc04-a6a1-11e5-849c-8124d83df1b3.png)
Why don't I see the play button, pause button and the server address?
I am clicking on them but nothing happening.
Please help.
Thanks.

**Comment by hermwong** [comment]
hi @koushik72 , the ">" is the play button.

**Comment by hermwong** [comment]
Looks like you found a workaround for this issue in #276.
