### ISSUE TITLE
getaddrinfo EAI_AGAIN error on phonegap desktop application.

### ISSUE THREAD

**Issue by Defaultacc9** [phonegap/phonegap-app-desktop#516]
I am trying to use Phonegap Desktop app on company network but its giving "getaddrinfo EAI_AGAIN" error. What could be the reason for this error and is there any solution for it??

Thanks in advance

**Comment by hermwong** [comment]
Looks like this is a duplicate of #511.

**Comment by hermwong** [comment]
Closing & locking the issue. Let's keep all discussion regarding this issue in the comments of #511.
