### ISSUE TITLE
Updated to latest build, now get "Listen EADDRINUSE" when trying to change projects

### ISSUE THREAD

**Issue by scannermobs** [phonegap/phonegap-app-desktop#518]
I have only recently begun working with PhoneGap (but massively enjoying it so far), however I have run into a small issue with the latest version of the desktop app for El Capitan. I am not running any firewall or AV.

The app starts and runs the uppermost project in the list (with the green bar), but if I need to restart the project or change to a different project it will not work correctly – instead I get the "listen EADDRINUSE" message and no green bar. It would seem the existing/old instance of the project is still running, even if I clicked the Stop button first.

If I roll back to the November build of the app it works fine, but currently the app is essentially only usable with a single project (as the app automatically starts the first project in the list, and won't run another project).

Any help would be great.

**Comment by philrob** [comment]
Hi,
I have EXACTLY same issue and have also reverted back to v0.2.0 which works fine.

**Comment by Farufon** [comment]
Same issue here, after upgrading.

**Comment by hermwong** [comment]
A current work around for changing projects would be to just click the Start button of the project that you want to Start (bypass stopping your original project and then clicking start on your next project).

We're currently looking into the issue regarding the Stop/Start workflow.
