### ISSUE TITLE
PhoneGap searches for deleted projects at startup

### ISSUE THREAD

**Issue by Farufon** [phonegap/phonegap-app-desktop#519]
While using Desktop v 0.2.1, and AFTER deleting previous app using the "-" function, then shutting down:  Upon restarting PhoneGap, a popup prompt returns "config.xml not found in: /path/path.../www/config.xml or /path/path.../www/config.xml"  where (/path/path/) is a previous path to the deleted app projects. 

PhoneGap is obviously saving this history somewhere.

**Comment by hermwong** [comment]
You can try to delete the `localStorage` used by PhoneGap Desktop at the following location: `~/Library/Application Support/PhoneGap/Local Storage` this will remove all the projects that are locally stored by PhoneGap Desktop.

**Comment by Farufon** [comment]
Thank you.  That solved it!
