### ISSUE TITLE
PhoneGap Desktop -- listen EADDRINUSE :::3000 

### ISSUE THREAD

**Issue by Gennttii** [phonegap/phonegap-app-desktop#532]
![untitled](https://cloud.githubusercontent.com/assets/3110966/12539703/0984e5f2-c2f9-11e5-9720-190e8840b6b0.png)

Hello, I am having this problem in my PhoneGap Desktop in Windows . I just started, installed and created a project as in the tutorial but when I want to connect it shows that message: 

listen EADDRINUSE :::3000 

I have searched in google how to fix this but nothing is working. 
Please help me to fix. 
Thanks

**Comment by Gennttii** [comment]
I tried to use PhoneGap Desktop in Windows which you can see in the photo below( In PhoneGap I can see 2 options Desktop App and CLI so I am using Desktop App) 
This is my first app. 
Target that I am trying are Iphone 4 CMDA with ios version 7.1.2 And Motorola Moto G with android version 4.4.4 

The problem itself was PhoneGap Desktop which was not connecting with those two phones but I think its fixed now because I wrote some codes of CLI version . 
It is still showing listen EADDRINUSE :::3000 but I am connected in Iphone and Moto g.

Maybe they can try to fix it because its beta version and I guess it has that bug type.. 

Regards

**Comment by hermwong** [comment]
We have a potential fix for this issue with #518 which will be included in the PhoneGap Desktop 0.2.2 release.

**Comment by hermwong** [comment]
Are you using the PhoneGap CLI and PhoneGap Desktop at the same time?

If you start the `phonegap serve` command in the CLI and then start the PhoneGap Desktop there will be conflict on port 3000. The default port for the CLI and PhoneGap Desktop serve functionality is port 3000.

**Comment by Gennttii** [comment]
No I am not using CLI version, only Desktop version..

**Comment by hermwong** [comment]
Does this error occur even when you change the port numbers.

**Comment by Gennttii** [comment]
Yes, because if you can see in photo I tried port 8080, and I wrote here port 3000. It is happening with any port number

**Comment by klokoleva** [comment]
try to run in web browser http://localhost:3000/

**Comment by marK-Chow** [comment]
I have the same problem, when i try to run it in the web browser it works but it still show the "link eaddrinuse". I've checked in the cmd i don't think it's the port in use problem...

**Comment by Gennttii** [comment]
@klokoleva 
As I mentioned before, it runs in localhost, in iphone and android, but it still shows listen EADDRINUSE.

IDK why

**Comment by hermwong** [comment]
See #537 for commits related to the fix for this issue.

The fix will be released with 0.2.2.

**Comment by joelnewcomer** [comment]
In case this helps someone, I had Gulp running and it was causing this.
