### ISSUE TITLE
PhoneGap Desktop -- listen EADDRINUSE :::3000

### ISSUE THREAD

**Issue by jessemonroy650** [phonegap/phonegap-app-desktop#533]
Jesse,
volunteer from Nitobi forum. I have another report of the same issue.

http://community.phonegap.com/nitobi/topics/listen-eaddrinuse-3000
OP reports as such:

> I tried to use PhoneGap Desktop in Windows which you can see in the photo below( In PhoneGap I can see 2 options Desktop App and CLI so I am using Desktop App)
> This is my first app.
> Target that I am trying are Iphone 4 CMDA with ios version 7.1.2 And Motorola Moto G with android version 4.4.4

> The problem itself was PhoneGap Desktop which was not connecting with those two phones but I think its fixed now because I wrote some codes of CLI version .
> It is still showing listen EADDRINUSE :::3000 but I am connected in Iphone and Moto g.

Reports browser as:
> Chrome Version 47.0.2526.111 m

**Comment by hermwong** [comment]
Thanks Jesse.

I think the same user submitted the issue here: #532

**Comment by jessemonroy650** [comment]
Yep, appears to be the same. Sorry for the duplicate.

**Comment by hermwong** [comment]
No worries @jessemonroy650, we appreciate all the help & feedback we get from the community.

I'll close this issue since it's a duplicate.
