### ISSUE TITLE
Possible solution for download error in mobile app 

### ISSUE THREAD

**Issue by georgetour** [phonegap/phonegap-app-desktop#535]
Hello ,
Congratulations for phonegap.I had a download error in mobile app and tried to understand what was wrong.I noticed that sometimes either in desktop application or in mobile application the IP was changed automatically after restarts.So I recommend if users restart the applications  check again and again the IP in both.

**Comment by hermwong** [comment]
Another common issue is that users may have a firewall / AV software or be on a corporate network with security policy that are preventing the PhoneGap Desktop app to serve the zip file over to the PhoneGap Mobile app.

**Comment by surajpindoria** [comment]
Closing this.
