### ISSUE TITLE
EADDRINUSE when pressing run multiple times from non-running state

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-desktop#537]
Reproduce:

- Build and run the latest 0.2.2 branch
- Stop all apps from running
- Press run multiple times quickly
- The EADDRINUSE error is displayed

Resolution (guess):

- Disable the run button while the server is starting up

**Comment by DougJoseph** [comment]
I am brand new to PhoneGap, but I think I may be having this or a very similar issue.

I just downloaded and installed the desktop app for OS X. I also just installed the developer app on my iPhone.

I created a new project, and then attempted to connect to it.

The phone app will not ever connect, even though I tried all of the IP addresses shown.

Also, when I click the green right arrow, I get this:

EADDRINUSE :::3000

I have no idea what should happen, but I think this is not it.

**Comment by hermwong** [comment]
The following use case needs to be looked at:

1. delete a project
1. open an existing project

results in the following:
![screen_shot_2016-02-10_at_1 49 08_pm](https://cloud.githubusercontent.com/assets/107754/12967485/c476f902-d01b-11e5-84c5-4e77494c24f6.png)
