### ISSUE TITLE
Server is offline but project displayed as online

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-desktop#540]
**Reproduce:**

- Open PhoneGap Desktop (I have 1 project running)
- Delete the existing project while the server is running
- Open the existing project (same project that you removed above)
_The project opens, the server status is offline, but the project status is online (green button)._

![screen shot 2016-02-10 at 1 49 08 pm](https://cloud.githubusercontent.com/assets/21328/12963116/b35add96-cffd-11e5-8577-b8b2f9b8c22d.png)

**Comment by hermwong** [comment]
Also need to test the use case where a user has 2 (or more) projects.

1. remove 1 project
1. open an existing project

expected result:

1. the server should be online
1. the opened project should be marked as active
