### ISSUE TITLE
404 /__api__/appzip

### ISSUE THREAD

**Issue by ikivilev** [phonegap/phonegap-app-desktop#544]
Didn't find a solution that would work for me, so reporting the issue here

This is what I see in PhoneGap desktop

![image](https://cloud.githubusercontent.com/assets/10121584/13010654/edbaf202-d1b3-11e5-9c4c-dd62f5a2f21f.png)

iPhone app keeps telling DOWNLOADING and then TAP TO CANCEL

I can download the appzip using the browser from my computer at http://192.168.1.39:3000
zip is downloaded and opened correctly.

Windows 8.1 x32
PhoneGap desktop 0.2.1
iPhone 4S with iOS 6.1.3 (Steve Jobs Lives!)
Not sure about iPhone app version, but downloaded it from the App Store yesterday.

I don't really know where to continue the fix, please advise something to set it up!

**Comment by hermwong** [comment]
This issue happens when the PhoneGap Developer App is unable to receive the `zip` file from the PhoneGap Desktop's server.

Common causes of this issue can be related to network configuration / security configuration of you computer or network.

Do you have firewall, VPN or AV software installed?
Are you on a corporate network?

**Comment by ikivilev** [comment]
This is my home network via Wi-Fi. I tried it with firewall disabled, no VPN or AV software installed.
Looks like it was due to iOS 6.1.3 as you mentioned in [https://github.com/phonegap/phonegap-app-desktop/issues/523](url)

Still looking for a way of running it on 6.1.3 :(

Thanks for helping!

**Comment by hermwong** [comment]
It likely won't work on iOS 6.

There was a change to the method used to serve & receive between the PhoneGap Desktop / CLI to the PhoneGap Developer App.

So older versions of the PhoneGap Developer app (in your case, the iOS 6 version) will not be compatible with the current versions of the PhoneGap Desktop or PhoneGap CLI.

**Comment by hermwong** [comment]
See https://github.com/phonegap/phonegap-app-desktop/issues/360#issuecomment-108583229 for more details.
