### ISSUE TITLE
Changing the port does not update within the app

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/phonegap-app-desktop#546]
If you manually change the port, it does not update the server address in the apps green bar even though it is being correctly served from the new port.

**Comment by hermwong** [comment]
Were you running any VMs or have multiple IP addresses found on your computer when you ran into this issue?

**Comment by surajpindoria** [comment]
It only happens when multiple IP addresses were found.

**Comment by hermwong** [comment]
Looks like the IP list was actually appending the updates, the user could actually scroll down to see the updates.

The expected behaviour would be for the IP list to replace the old content with the update content instead of appending the updated content to the old content.
