### ISSUE TITLE
Error connecting with 0.2.2

### ISSUE THREAD

**Issue by lavarith** [phonegap/phonegap-app-desktop#553]
After downloading the newest version, none of my apps will connect. I receive an Error! connecting and then the server app blacks out.

**Comment by hermwong** [comment]
Could you provide more info regarding your computer & network setup? Any of the following information might help us determine the cause of your issue:

1. PhoneGap Desktop version / PhoneGap CLI version
1. PhoneGap Mobile App version
1. Mobile devices & Mobile OS version
1. Computer OS version
1. network type (home/corporate)
1. computer / network security (firewall / anti-virus / disk encryption)
1. are you using VMs on your computer?
1. do you have multiple network adapters (or virtual network adapters)
1. number of files in your mobile app
1. size of your mobile app

**Comment by lavarith** [comment]
PDV = 0.2.2 / PCLI = 6.0.0
Mobile version 1.5.13
Samsung Galaxy s6 edge - Android 5.1.1
Computer OS Windows 10 64 bit
Home Network
Windows Firewall and AVG
No VMs currently in use for this purpose (although virtual box is installed).
Wifi adapter and Hamachi
79 Files
2.48 MB

Let me know if I can answer any other questions

**Comment by hermwong** [comment]
Just a few of questions:

1. did you un-install the previous version of PhoneGap Desktop before installing the latest version?
1. do you disable your firewall & AV when using PhoneGap Desktop and the PhoneGap mobile app?
1. would you be able to provide screen shot of what you're seeing on PhoneGap Desktop and the PhoneGap mobile app when this error occurs?

**Comment by lavarith** [comment]
1. I just did, the error still exists.
2. I disabled the firewall and AV. Still error.

The error on the app says "Download Error" and it gives an alert say that it couldn't connect to the server.

Here is the desktop result:
![image](https://cloud.githubusercontent.com/assets/3874034/13237703/f291edfe-d99b-11e5-893c-2cff6e3c9dc5.png)

**Comment by LaurenceHA** [comment]
Had the exact same problem as lavarith, rolling back to 0.2.1 solved it...

**Comment by RubenDorrego** [comment]
Same here! We had to go back to previous version. We have windows 10 64bits.

**Comment by wawanopoulos** [comment]
It's my first installation of this app and i get the same error on the Android app : "Unable to download archive from the server. Unable to properly connect to the server". 

![screenshot_2016-02-23-14-43-27](https://cloud.githubusercontent.com/assets/7994096/13253360/f6ffbef2-da3b-11e5-8690-b5ba952289e4.png)

On Desktop side

**Comment by carokanns** [comment]
I had exactly the same as lavarith.
0.2.1 works now
windows 64 bits

**Comment by hermwong** [comment]
It looks like this issue is only happening on Windows; I'll start investigating the issue on Windows until I receive reports of it happening on OSX.

**Comment by MacEduBe** [comment]
Sorry to say hermwong, but I have the same problem. When connecting my iPhone to the server, server got blank...

OSX El Capitain 10.11.3

**Comment by hermwong** [comment]
@MacEduBe thanks for the info, we now know that the issue occurs on both platforms instead of just Windows.

Are you receiving any type of error on the PhoneGap mobile app?

**Comment by ManelPereira** [comment]
Exact same error, windows 7 64 bits

**Comment by carm2318** [comment]
same error windows 10 64 bits

**Comment by ivanlaharnar** [comment]
Like @LaurenceHA said, back to previous version solve the problem. I'm new on developing on phonegap and this was my first instalation. I've studied half a day to come to this conclusion.

**Comment by MacEduBe** [comment]
@Herm Wong I got this message on the PhoneGap mobile app

**Comment by hermwong** [comment]
hi @MacEduBe, was there supposed to be a screen shot with your last response?

**Comment by hermwong** [comment]
I haven't had any luck reproducing this issue on OSX 10.11.2 El Capitan, Win 10 x64 VM and Win 8.1 x64 VM.

We're still trying to gather information to see how we can reproduce this issue consistently.

**Comment by hermwong** [comment]
Just a quick update on this issue. We've found the root cause of the problem and will be releasing the fix soon.

Thanks to everyone that reported the issue and provided information!

**Comment by hermwong** [comment]
From our investigation it looks like Electron 0.36.0 which is used in PhoneGap Desktop 0.2.2 is causing some type of conflict resulting in this issue. We've found that Electron 0.35.0 works fine even when used with the PhoneGap Desktop 0.2.2 code base; we're currently looking into what could be causing this issue to occur when using Electron 0.36.0.

For the time being we suggest our users to use [PhoneGap Desktop 0.2.1](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.2.1)

**Comment by hermwong** [comment]
We've released a fix to this issue. You'll need to manually update to [PhoneGap Desktop 0.2.3](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.2.3).

**Comment by ivanlaharnar** [comment]
It works now :-)
