### ISSUE TITLE
Use correct font in the Desktop App UI

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-app-desktop#567]
Currently, the app (on Mac, OSX 10.11.3) is displaying a serif typeface for text fields and buttons:

![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/13442434/06de922e-dfb1-11e5-97c8-f20b698a7ca4.png)

These elements should use the same san serif typeface (Adobe Clean) as the rest of the interface. From the mock-up:

![desktop-app_0008_add-create](https://cloud.githubusercontent.com/assets/178345/13442517/71cae754-dfb1-11e5-9c3c-746761afd5c0.png)

**Comment by hermwong** [comment]
Duplicate #560
