### ISSUE TITLE
Phonegap Destop app using an old template

### ISSUE THREAD

**Issue by jcesarmobile** [phonegap/phonegap-app-desktop#571]
When using the phonegap desktop app I get an app created from an old template.
It doesn't happen if I use the phonegap or cordova CLIs.

Tracking down the issue I've discovered that the problem is on the connect-phonegap component. 
I've opened an issue on connect-phonegap repository (https://github.com/phonegap/connect-phonegap/issues/148) but as this only happens on Phonegap Desktop and not the CLIs I thought I should report it here too.

**Comment by chrisgriffith** [comment]
I am working on updating that template (https://github.com/chrisgriffith/phonegap-template-hello-world). I am tracking down a few outstanding resource questions, then will make a pull request.

**Comment by jcesarmobile** [comment]
My problem isn't that the phonegap-template-hello-world is out of date (that is a problem too). 

My problem is that the phonegap Desktop app creates the project with an old version of that template. I assume it was downloaded the first time I used the Desktop app and it has not been updated ever again.
It has this line `<preference name="phonegap-version" value="3.5.0" />`, on the current version has that line, but it's commented.

**Comment by hermwong** [comment]
@jcesarmobile That's a valid point. On first run the PG-Desktop will download templates, but it actually never checks to see if templates need to be updated.

The Desktop needs a new feature that will check the template version and download new templates if they are available.

**Comment by hermwong** [comment]
With template support added to the Desktop App (v0.4.0) we need to be able to to flush out existing / older versions of the templates that users may have cached on their computers and use the "pinned" versions of the templates found in `[template-list.js](https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/template-list.js)`.

**Comment by surajpindoria** [comment]
I have looked into this and it looks like the old create logic in `connect-phonegap` was causing it use older templates as long as it was already cached. Now that we are using the CLI and have the template versions pinned we are always pulling the specified version. We should probably update the pinned versions but I will file a separate issue for that.

Closing this issue.
