### ISSUE TITLE
Investigate the resizing the PG-Desktop App

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#572]
How much work is involved?

**Comment by hermwong** [comment]
Window width:

https://github.com/phonegap/phonegap-app-desktop/blob/0.2.4/www/index.js#L26
https://github.com/phonegap/phonegap-app-desktop/blob/0.2.4/www/index.js#L28

CSS changes to control width:

1. overlays for:
  1. create new / open existing
  1. create new project
    1. form fields for:
      1. path
      1. project name
      1. project id
  1. settings
  1. server log
    1. textArea
  1. help

1. project widget
  1. project path
  1. project name field

1. server status bar
  1. multi-ip list

1. error notification

**Comment by jahoni** [comment]
I was able to fit everything into the window we've currently got rocking (at least for the time being) @hermwong (see #569 for mock-ups)
