### ISSUE TITLE
Switching projects does not properly serve the new app

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/phonegap-app-desktop#574]
Prerequisites:
- Have 2 or more projects in desktop app already

Reproduction Steps:
1. Launch the desktop application
2. Open developer app to port specified in desktop app
3. Make changes to project, view changes on phone
4. In desktop app, click play button on another project to serve it
5. Either wait for changes on phone, or exit to menu and re-download
6. New project will be displayed
7. Making changes to new project will not trigger reload, but changing old one will error out and reload original project

**Comment by surajpindoria** [comment]
![Uploading Desktop Error.jpg…](Debug Logs)

**Comment by hermwong** [comment]
While testing this I've found that when you follow with 2 or more projects:

1. start Desktop App
1. launch Developer App & use IP address of the default project (project A) being served
1. make changes to project A, view changes on phone
1. click play button on a different project (project B)
1. reload the Developer App (3 finger press)
1. project B is now being served in the Developer App

Using the browser branch - rebased with the master

**Comment by hermwong** [comment]
Tried the workflow listed in @surajpindoria's comment and got the following result:

1. Launch the desktop application
1. Llaunch Developer App & use IP address of the default project (project A) being served
1. make changes to project A, view changes on phone
1. click play button on a different project (project B)
1. reload the Developer App (3 finger press)
1. project B is now being served in the Developer App
1. make change to project B
1. **Expected Result:** Developer App should display changes to project B, **Actual Result:** nothing happens
1. make a change to project A's code
1. Developer App reloads and displays the changes to project A

This was also using the browser branch - rebased with the master

**Comment by hermwong** [comment]
Does this also happen when serving & switching projects when using the CLI?

**Comment by surajpindoria** [comment]
I am able to recreate this within the CLI. After some further investigation this issue seems to be a problem with how we are serving the app. Spoke with @mwbrooks about some potential solutions

**Comment by surajpindoria** [comment]
After further investigation, I have a more insight into why we are having difficulties with project switching. The issue is primarily due to how the http server works within node. When we attempt to close the server, all this does is stop any new connections from being made, but all existing connections will remain open and continue to run. Only after all connections have been closed will the server actually terminate. Once terminated, pressing the play button on a new project will correctly serve that app.

With this behavior, even the latest changes to `connect-phonegap` that add a project ID will not work properly as the server will not close immediately. Within the CLI we are fine since we are explicitly killing the server from the terminal. But programmatically we are a little stuck with the current implementation.
@mwbrooks

**Comment by hermwong** [comment]
Does this mean that `connect-phonegap` needs a refactor to kill the server each time the user switches (or starts serving a different project) in the Desktop?

**Comment by surajpindoria** [comment]
Yes. According to what I read online it wouldn't be a huge change. We would just need to keep track of each device that connects to the server. Then when we attempt to close the server, manually go through and kill each connection.

**Comment by surajpindoria** [comment]
Added in the fix for tracking server connections and closing them when we shutdown the server. This now works properly on devices, but still fails in the browser. I have tracked down the issue for the browser to [cordova-lib](https://github.com/apache/cordova-lib/blob/master/cordova-lib/src/cordova/util.js#L101).

When returning the cordova / phonegap project directory, cordova takes favor to use `process.env.PWD` over `process.cwd()`. So for the desktop app this will be whatever the first project served is and does not change when we switch to a new project. If I remove that code from `cordova-lib`, the browser project switches as expected. Not sure how to handle this.

**Comment by surajpindoria** [comment]
Managed to fix above issue with the last commit. Project switching now works as intended on all platforms!

**Comment by hermwong** [comment]
Tested this feature on:

### Pre-conditions

1. not on corporate network
1. no AV
1. firewall disabled

### PhoneGap Desktop to Mobile Device switching projects

1. OSX (El Capitan) and iPhone (Dev App 1.6.0)
  1. works as expected, the Dev App reloads to the home screen when the project is switched
1. Win 10 64 bit and iPhone (Dev App 1.6.0)
  1. works as expected, the Dev App reloads to the home screen when the project is switched

### PhoneGap Desktop to default Browser switching projects

1. OSX (El Capitan) and Google Chrome
  1. loads the 1st project, but throws an error when attempting to reload the 2nd project
1. Win 10 64 bit and MS Edge
  1. loads the 1st project, but throws an error when attempting to reload the 2nd project

PhoneGap Desktop's console displays this error:

<img width="1077" alt="screen shot 2016-04-06 at 3 31 32 pm" src="https://cloud.githubusercontent.com/assets/107754/14335224/77d27e40-fc0e-11e5-84fe-812ba4455c0b.png">

Result in the Browser:

<img width="646" alt="screen shot 2016-04-06 at 3 45 41 pm" src="https://cloud.githubusercontent.com/assets/107754/14335260/be898f40-fc0e-11e5-986e-4aa0817b0edf.png">

**Comment by surajpindoria** [comment]
The above issue is resolved in the desktop-browser branches of both `phonegap-cli` and `connect-phonegap`. Both are ready and we will need to merge / release for the desktop app

**Comment by hermwong** [comment]
@surajpindoria thanks. I'll modify my local build to use those branches and perform a final test run.

**Comment by hermwong** [comment]
Still running into issues using the `desktop-browser` branch in for `phonegap-cli` and `connect-phonegap`.

**Comment by hermwong** [comment]
There was a bit of miscommunication on the branches to be used.

`connect-phonegap` needed to use the `desktop-browser` branch rebased with `master` while the `phonegap-cli` could use the `desktop-browser` branch.

Initial tests with project switching worked. We will now perform a final regression test to before signing off on this feature.
