### ISSUE TITLE
Desktop App performance when bundling in CLI

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#575]

**Comment by hermwong** [comment]
I've run some initial tests on the launching of the Desktop App with CLI bundled.

Using the "eye" test:

1. on OSX there doesn't to be any impact when starting the Desktop App
1. on Win 10 x64 VM (w/ 6GB RAM) there appears to be a slight (~5 seconds) lag before the Desktop App completely renders. The Desktop will initially load with a blank interface and then lag before populating with projects.

**Comment by hermwong** [comment]
@mwbrooks would it be worthwhile to add in some benchmarking so that we can gather metrics to compare the "no CLI" vs "CLI?

**Comment by mwbrooks** [comment]
@hermwong If you want, you could add a `bootTime` type metric to Keen.io that will report the time it took to load the app. I'm not sure if this is easy for you. The upside of a metric like this is that we can identify slow load times in production.

**Comment by mwbrooks** [comment]
Here is my 4GB Windows 10 VM opening the production build:
![](http://cl.ly/0f12423R1V39/Screen%20Recording%202016-03-15%20at%2011.51%20AM.gif)

**Comment by surajpindoria** [comment]
@mwbrooks Try it with some projects in the app. That's where I noticed the lag

**Comment by hermwong** [comment]
I had 2-3 projects loaded in the app when I noticed the lag (approx 5 seconds).

**Comment by mwbrooks** [comment]
The Desktop app fails to create a new project - pressing _Create_ does not respond and there is no info displayed in Web Inspector.

**Comment by hermwong** [comment]
I suspect the fail to create new project is related to the changes made for the fix to #562.

**Comment by hermwong** [comment]
Perhaps we should add some type of loading animation or boot up screen?

**Comment by jahoni** [comment]
Definitely adding a loading animation makes sense. Not sure what our options are, technically, though. Can we display a modal/overlay?

**Comment by hermwong** [comment]
We could probably use an overlay that displays a generic loading animation which removes itself once the app has retrieved all of it's data and rendered.

The overlay would cover the whole interface and prevent the users from interacting with any of the buttons, drag & drop etc until the overlay has been removed.

I would prefer a generic loading animation is used, so that we have the potential to re-use in the app (if necessary).

**Comment by hermwong** [comment]
<img width="646" alt="screen shot 2016-04-06 at 3 45 41 pm" src="https://cloud.githubusercontent.com/assets/107754/14335945/39737f18-fc14-11e5-9089-826fa7bf4b8f.png">

**Comment by hermwong** [comment]
![screen recording 2016-04-06 at 04 24 pm](https://cloud.githubusercontent.com/assets/107754/14335955/4380caec-fc14-11e5-9c76-02925638c68f.gif)

**Comment by hermwong** [comment]
Loading animation to be used: https://raw.githubusercontent.com/SamHerbert/SVG-Loaders/master/svg-loaders/oval.svg

Loader should be:

1. centered (vertically & horizontally)
1. use phonegap blue `#27a1c5`

**Comment by hermwong** [comment]
Preview of the loading overlay.

![screen recording 2016-04-07 at 01 28 pm](https://cloud.githubusercontent.com/assets/107754/14365841/a59526f0-fcc4-11e5-94c0-c6e852a59aa6.gif)

**Comment by hermwong** [comment]
On Windows:

The animation doesn't seem to run very well on my Windows 10 VM.
![screen recording 2016-04-07 at 03 26 pm](https://cloud.githubusercontent.com/assets/107754/14368859/47110e58-fcd5-11e5-8041-c0eec539ac30.gif)

On OSX:

![screen recording 2016-04-07 at 03 28 pm](https://cloud.githubusercontent.com/assets/107754/14368888/8815939c-fcd5-11e5-8f35-624709f42281.gif)

**Comment by jahoni** [comment]
do you need a new animation, then?

**Comment by hermwong** [comment]
Ran a quick test on the animations from that repo. None of the SVG animations work on my Windows 10 VM.

Tried a video capture for about 5 seconds:

![screen recording 2016-04-08 at 12 57 pm](https://cloud.githubusercontent.com/assets/107754/14395938/97ed36da-fd89-11e5-9d68-fca153d3094c.gif)

**Comment by hermwong** [comment]
Changed to a CSS based loader.

Results on Windows:

![screen recording 2016-04-08 at 03 39 pm](https://cloud.githubusercontent.com/assets/107754/14399382/08c889c4-fda1-11e5-976e-5da647d5f2e7.gif)

Result on OSX:

![screen recording 2016-04-08 at 03 45 pm](https://cloud.githubusercontent.com/assets/107754/14399386/133adbaa-fda1-11e5-8fee-bf5edfc64dd7.gif)

**Comment by hermwong** [comment]
Updated the visuals on the loader.

![screen recording 2016-04-09 at 11 38 am](https://cloud.githubusercontent.com/assets/107754/14405638/fe89c93a-fe47-11e5-9f36-7702bfca2af5.gif)

**Comment by jahoni** [comment]
nice one, @hermwong
