### ISSUE TITLE
PhoneGap: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by davdinesh** [phonegap/phonegap-app-desktop#578]
Hi, 

I installed PhoneGap desktop app on my Win 7 64 bit machine. When I try to create a new phone gap app, got self signed certificate in certificate chain error and unable to create a new project. Could you please help to resolve this issue?

Thanks

**Comment by hermwong** [comment]
Would you be able to provide some details regarding your computer & network setup.

1. Do you have a firewall or AV software on your computer?
1. Are you on a VPN?
1. Are you using a VM?
1. Are you on a corporate network?
1. Do you have disk encryption software?

**Comment by hermwong** [comment]
The issue could be related to either #500 or #526.

**Comment by davdinesh** [comment]
1.Do you have a firewall or AV software on your computer? McAfee enabled
2.Are you on a VPN? No
3.Are you using a VM? No
4.Are you on a corporate network? Yes
5.Do you have disk encryption software? No

**Comment by hermwong** [comment]
Would you be able to provide the exact error message you're receiving?

**Comment by citruz** [comment]
I have the same problem when trying to create a new project. The message is just "self signed certificate".
My setup is similar to @davdinesh with McAffee enabled and inside a corporate network. Additionally, I have disk encryption (Bitlocker) enabled as well.
![phonegap](https://cloud.githubusercontent.com/assets/3756270/13873258/7ec1e614-ecf0-11e5-8881-61122d2928a3.png)

**Comment by citruz** [comment]
My company requires to use a web proxy to access the internet. Could this be the problem?

**Comment by davdinesh** [comment]
I installed PhoneGap desktop app on my personal laptop and tried from my home network. I am able to create project successfully. Issue is with proxy settings. Any idea how to set up proxy?

**Comment by hermwong** [comment]
@citruz & @davdinesh the certificate error is related to the proxy server on your networks. Unfortunately, I'm not able to help you configure the proxy settings since I don't know anything about your network configuration & security policies. It would be best to contact your IT dept and see if they can help you with the issue.

**Comment by citruz** [comment]
Yes you're right, but my system is already configured correctly to use the proxy. Other applications are working fine. 
There is a system setting and the environment variables `HTTP_PROXY` and `HTTPS_PROXY`. These are used by most applications. Others (like git or npm) have their own configuration. For me it looks like the PhoneGap application does not respect the system-wide setting but does not offer to specify a proxy either.

**Comment by surajpindoria** [comment]
Going to close this off due to inactivity.
