### ISSUE TITLE
Console Control and Console Clearing

### ISSUE THREAD

**Issue by Khaleel** [phonegap/phonegap-app-desktop#579]
Hi Guys

I am using Mac OSX and currently enjoying the Phonegap App for desktop. I use it with AMPPS, Nginx, Mamp and also Ripple from time to time so a good environment for developing.

Is it possible to add a clear console function or allow us some CLI functions or commands in the desktop console window as it saves everything single history and compilation action and the window gets massive to scroll - no scroll is shown in the screenshot but this is what I mean - the list gets huge..

![sample](https://cloud.githubusercontent.com/assets/355336/13922076/2b025bf2-ef94-11e5-8817-8354a160ce54.jpg)

**Comment by hermwong** [comment]
We can probably add a `Clear` button which clears out the contents of the server log window.

**Comment by jacobking** [comment]
It's very necessary！do you have a plan which version will add this Clear button?@hermwong

**Comment by hermwong** [comment]
This enhancement will most likely be released in the [template support release](https://github.com/phonegap/phonegap-app-desktop/milestones/0.2.5%20Template%20Support).

**Comment by jacobking** [comment]
nice!looking forward! :-D @hermwong

**Comment by hermwong** [comment]
A merge error has removed the `clear` button handler. Will be fixing the merge error in 0.3.3.
