### ISSUE TITLE
Linux ?

### ISSUE THREAD

**Issue by code2be** [phonegap/phonegap-app-desktop#58]
Hello,

Many PhoneGap Developers uses Linux. But, I don't see any Linux-oriented talk here.

So, Somebody working on that ? I can handle it.

Thanks.

**Comment by fgh151** [comment]
Here instruction how to build on linux https://openitstudio.ru/blog/18.html
I buil it on Ubuntu and Debian

**Comment by surajmandalcell** [comment]
@fgh151 your link is working anymore. please provide a fresh link!
