### ISSUE TITLE
Download is taking forever/error appears in PhoneGap Developer App for Android

### ISSUE THREAD

**Issue by Cookiedouable** [phonegap/phonegap-app-desktop#580]
I'm currently residing in Shanghai for a few months, and I am really not sure if it is because of China's great (fire)wall that I simply cannot do the initial setting up for the mobile app. I have read through the forums and disabled my laptop's firewall and antivirus, have even tried doing the download while on VPN and without VPN. If the mobile app could show a download progress bar that would be so helpful, so that I will know if it is even downloading or not. I have been trying for a few days, and initially kept getting the error until i disabled the firewalls, and now my only problem is it's been downloading for a few hours and I have no idea if it is installing or not.

**Comment by hermwong** [comment]
Are you on a corporate network?

From our experience, if you're on a corporate network or a network that uses a proxy server it could cause issues with the download to the PhoneGap mobile app.

**Comment by Cookiedouable** [comment]
I've tried the downloading both at home as well as at work, didn't work out for me. The download still took infinitely forever with no hint whatsoever that it was going to be completed or not.

**Comment by hermwong** [comment]
Could you provide the following info:

1. which version of Android?
1. which version of PhoneGap Developer App?
1. which version of PhoneGap Desktop?
1. which version is your computer's OS?

**Comment by Cookiedouable** [comment]
1. Android 5.1.1
2.  1.5.13
3.  0.2.3 (Beta)
4. Windows 10.0.10586 Build 10586

**Comment by hermwong** [comment]
Thanks...could you provide the following info. We're trying to gather as much data as we can about your set up so that we can recommend a solution.

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. computer / network security (firewall / anti-virus / disk encryption)
7. are you using VMs on your computer?
8. do you have multiple network adapters (or virtual network adapters)

**Comment by hermwong** [comment]
Here's our [FAQ](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/) for troubleshooting connection issues for the Mobile App.

**Comment by Cookiedouable** [comment]
1. Phonegap Desktop 0.2.3 (Beta)
2. 1.5.13 for Android
3. Samsung S6, Android 5.1.1
4. Windows 10.0.10586 Build 10586
5. Home
6. Disabled firewall, disabled antivirus, no disk encryption
7. No VMs at all.
8. No multiple/virtual network adapters, have tried on WiFi, WiFi + LAN, LAN alone.
9. I've tried the download both with and without the VPN.

**Comment by Cookiedouable** [comment]
By the way this is the initial setting up of the PhoneGap Developer app, I'm just trying to get through the setting up and installation phase

**Comment by surajpindoria** [comment]
@Cookiedouable were you ever able to get this set up?
