### ISSUE TITLE
Phonegap build error - failed to notify build listener

### ISSUE THREAD

**Issue by maddy20pg** [phonegap/phonegap-app-desktop#583]
Below is a part of command line statements I received after executing
phonegap build android 
command.
Build gets successful but then failed with exception - failed to notify build listener (Please look below)
I am able to see the output apk file in the build folder of my project but this apk is giving error when I try to install it on an android emulator/device.
Kindly help.

UP-TO-DATE
:validateDebugSigning

:packageDebug

:zipalignDebug

:assembleDebug

:cdvBuildDebug

BUILD SUCCESSFUL

Total time: 1 mins 46.4 secs

FAILURE: Build failed with an exception.

* What went wrong:

**Failed to notify build listener.**

* Try:

Run with
--stacktrace
 option to get the stack trace. Run with --info
 or --debug
 option to get more log output.

C:\Users\680626\PhonegapProjects\TestBuild\platforms\android\cordova\node_module
s\q\q.js:126
                    throw e;
                    ^
Error code 1 for command: cmd with args: /s /c "C:\Users\680626\PhonegapProjects
\TestBuild\platforms\android\gradlew cdvBuildDebug -b C:\Users\680626\PhonegapPr
ojects\TestBuild\platforms\android\build.gradle -Dorg.gradle.daemon=true"

ERROR building one of the platforms: Error: cmd: Command failed with exit code 1

You may not have the required environment or OS to build this project

Error: cmd: Command failed with exit code 1

**Comment by hermwong** [comment]
Could you try running `phonegap build android --verbose` and provide the output?

**Comment by maddy20pg** [comment]
error resolved.. it was error in find_java batch file of android sdk.
it was looking for java_64.exe but my system is 32 bit.

Thanks

**Comment by hermwong** [comment]
Great. Closing the issue as it seems to be resolved.
