### ISSUE TITLE
Selected folder does not contain config.xml

### ISSUE THREAD

**Issue by LiveListMobile** [phonegap/phonegap-app-desktop#584]
As of today, 03/30/2016 I tried to install phonegap desktop via the installer on my windows 7 64 bit machine and got the above error when I tried to create a new project.  I also downloaded the zip file and manually install but got the same error.  I could not find the config.xml file anywhere in the downloaded, extracted zip file nor the files installed by the exe.  I can't find any solutions online.  Any ideas?  This is my personal machine so no network issues.  I also opened the firewall to the appropriate port but that shouldnt have anything to do with the missing file.  I searched both

**Comment by hermwong** [comment]
Maybe try this: #409 and also #322.

**Comment by jhhood** [comment]
I'm running into the same issue. I'm on Windows 10 x64 however. First time touching phonegap ever; downloaded it from the adobe site, installed it just fine. Went to run it and things were looking good. The moment I created a project, I got this error about the config.xml file not being found and started doing research. After following every post I could find (mainly by you @hermwong ) I was unable to fix my issue. I'm hoping this is an easy fix. I did notice that if I try to add the empty project it made, i get the same issue as the guy from #585

**Comment by hourad** [comment]
I'm also running into the same issue. I followed #409 but no changes. Both firewall and antivirus are deactived. I also saw that when I removed the empty folders and I opened the phonegap desktop app to open the project, the folders that I deleted (.cordova, hooks, platforms, plugins) are not created again. I'm running PhoneGap Desktop App on Windows 8.1 x64.

**Comment by jhhood** [comment]
When I downloaded a version of PhoneGap that was not the new Desktop app i could find a config.xml on my machine. Its almost like a bunch of files are just missing from the installer. I wish there was better output during the project creation.

**Comment by flyingwombat** [comment]
Just downloaded the OSX version of PhoneGap (v0.2.3) and have the same issue when creating projects.  "Selected folder doesn't contain a config.xml".

**Comment by jhhood** [comment]
Yup I just tried doing it here at work on a completely different computer and network and same issue. It will create the file structure with no contents in them other than the www folder.

This is exactly what gets deployed during a project creation for me:

C:\Users\hoodj\Desktop\test\.cordova
C:\Users\hoodj\Desktop\test\hooks
C:\Users\hoodj\Desktop\test\platforms
C:\Users\hoodj\Desktop\test\plugins
C:\Users\hoodj\Desktop\test\www
C:\Users\hoodj\Desktop\test\www\css
C:\Users\hoodj\Desktop\test\www\img
C:\Users\hoodj\Desktop\test\www\js
C:\Users\hoodj\Desktop\test\www\spec
C:\Users\hoodj\Desktop\test\www\index.html
C:\Users\hoodj\Desktop\test\www\spec.html
C:\Users\hoodj\Desktop\test\www\css\index.css
C:\Users\hoodj\Desktop\test\www\img\logo.png
C:\Users\hoodj\Desktop\test\www\js\index.js
C:\Users\hoodj\Desktop\test\www\spec\lib
C:\Users\hoodj\Desktop\test\www\spec\helper.js
C:\Users\hoodj\Desktop\test\www\spec\index.js
C:\Users\hoodj\Desktop\test\www\spec\lib\jasmine-1.2.0
C:\Users\hoodj\Desktop\test\www\spec\lib\jasmine-1.2.0\jasmine.css
C:\Users\hoodj\Desktop\test\www\spec\lib\jasmine-1.2.0\jasmine.js
C:\Users\hoodj\Desktop\test\www\spec\lib\jasmine-1.2.0\jasmine-html.js
C:\Users\hoodj\Desktop\test\www\spec\lib\jasmine-1.2.0\MIT.LICENSE

**Comment by LiveListMobile** [comment]
@hermwong I just followed your suggestions.  The same error message persists.  The 4 folders .cordova, hooks, platforms,and plugins are empty.  The www folder is not.  There most be some sort of problem, as suggested with how PG Desktop is creating the folders.  I did notice that the installer reads "win32"  perhaps the problem lies in that.  Is there a 64 bit version somewhere?

**Comment by rodknous** [comment]
I am having the same problem listed above. Went through all the steps listed- followed multiple fixes... no luck.

The .cordova, hooks, platforms, and plugins folders are all empty.

Please advise.

I also tried earlier versions of the software to no avail.

**Comment by jhhood** [comment]
I've tried downloading previous installers (tried 0.2.3, 0.2.2, 0.2.0, initial commit) and all do the same thing. I cannot just download the desktop app, run it, and just make a project. I have tried downloading the iss file for 0.2.3 and compiling it with Inno Setup and I get I/O error 53. I have also tried downloading the source for 0.2.3 and tried running the update-server test and got the following message: "Can not find Squirrel"... nothing seems to work with the PhoneGap Desktop app at all.

**Comment by hermwong** [comment]
@LiveListMobile Win 64 bit has backwards compatibility for 32 bit apps. We don't have a 64 bit release since we went to 0.2.X.

**Comment by hermwong** [comment]
@jhhood usually the `folder does not contain config.xml` issue is a result of the templates being corrupt.

Could you provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. computer / network security (firewall / anti-virus / disk encryption)
7. are you using VMs on your computer?
8. do you have multiple network adapters (or virtual network adapters)
9. are you using VPN?

**Comment by jhhood** [comment]
@hermwong 

PhoneGap Desktop version / PhoneGap CLI version : **PhoneGap DeskTop Version 0.2.3**
PhoneGap Mobile App version **version 1.5.13**
Mobile devices & Mobile OS version **Verizon LG V10 using Android 6.0**
Computer OS version **Windows 10 Home x64**
network type (home/corporate) **Home**
computer / network security (firewall / anti-virus / disk encryption) **win-defender / none / none**
are you using VMs on your computer? ** none**
do you have multiple network adapters (or virtual network adapters) **wireless / LAN currently using wireless**
are you using VPN? **nope**

**Comment by LiveListMobile** [comment]
@hermwong 
Here are the answers relative to my set up.

PhoneGap Desktop version / PhoneGap CLI version - **PhoneGap Desktop v. 0.2.3**
PhoneGap Mobile App version - **1.15.13**
Mobile devices & Mobile OS version - **Sprint Samsung Note 4 android 6.1 (I think)**
Computer OS version - **windows 7 x64**
network type (home/corporate) - **home**
computer / network security (firewall / anti-virus / disk encryption) - **Toshiba Laptop - Windows Firewall - Avira**
are you using VMs on your computer? - **no**
do you have multiple network adapters (or virtual network adapters) - **no**
are you using VPN? - no

**Comment by hermwong** [comment]
Can you guys try the following:

1. delete the template folders as described in #409 
1. turn off your firewall
1. launch the PhoneGap Desktop
1. try to create a project

**Comment by jhhood** [comment]
@hermwong 

If I delete everything in the folder, all thats left is the www folder. If I try to create a project again, i get an error saying a project already exists with that name. If i try importing the project, two things happens. 1) "Server is running on multiple IP addresses:" 2) "Cannot find config.xml" I've tried what #409 recommended several times with no success.

**Comment by hermwong** [comment]
What is the path that you're deleting the folders from? Are you deleting them the project folder (the folder where you tried to create your project) or the PhoneGap Desktop install folder?

If you're deleting the folders from the project folder then the solution in #409 won't work. The solution in #409 is to delete the templates from PhoneGap Desktop's install folder.

You need to delete the template folders in PhoneGap Desktop's install folder. The path to PhoneGap Desktop's default install folder should be: `C:\Users\<username>\.cordova`. If you can't find the 4 folder (.cordova, hooks, platforms and plugins), you can just delete the `.cordova` folder and it should clear out the template cache.

Next [reset the `Local Storage`](https://github.com/phonegap/phonegap-app-desktop/issues/519#issuecomment-168791674) used by PhoneGap Desktop and then retrying the steps above.

**Comment by LiveListMobile** [comment]
Still same result: Selected folder does not contain config.xml

Also, I did a search for C:\Users\<Windows User Name>\AppData\Roaming\PhoneGap\Local Storage but that directory doesn't exist on anywhere on my machine

**Comment by lsteel** [comment]
Not to "me too" or anything, but on OS X El Capitan I have the same "Cannot find config.xml" error. I've followed the #409 instructions and no luck. Shut down the app, deleted the .cordova folder from the user root directory, made sure firewall is off, restarted the app, same issue. :/

**Comment by seanwallis** [comment]
I've just downloaded the recommended public download (v0.2.3) on OSX Yosemite 10.10.5 and hit the exact same problem. Does PhoneGap create a log file that we could send you?

(As a developer myself I don't want to bug you when this is obviously an urgent fix, but I'd like to know when it is resolved.)

If there is a known workaround e.g. using the CLI then let us know.

**Comment by jhhood** [comment]
Funny you mention the CLI because I was able to go through that archaic method of doing things and was finally able to make a proper project. Luckily after you get your server running there isn't much more to do in the console window but still. Kind of a bummer that I can't just click a few things in a GUI and be done.

**Comment by LiveListMobile** [comment]
Yeah, its too bad that this isn't working out.  I was really excited about the live previewing/updating functionality, saving the build/install routine which is a bit time consuming.  But, c'est la vie I suppose.  Hopefully they will get this issue resolved at some point.  Its seems like these guys do really good work and I certainly appreciate the effort they have put into this project.

**Comment by hermwong** [comment]
It looks like some recent changes to the [template](https://github.com/phonegap/phonegap-app-desktop/issues/586#issuecomment-204422918) is causing the required `config.xml` file to not be generated.

The current work around is to [download](https://github.com/phonegap/phonegap-template-hello-world) `config.xml` and place it into your project directory.

We're currently looking into getting the template fixed. We would like to thank you for your patience and reporting this issue to us.

**Comment by chrisgriffith** [comment]
We moved it from within the www folder to match the other templates structures.

**Comment by hermwong** [comment]
@chrisgriffith it seems like there is an issue with the `config.xml` being copied over when a project is being created.

This is my template cache with the latest `hello world` template changes:

<img width="298" alt="screen shot 2016-04-01 at 11 47 11 am" src="https://cloud.githubusercontent.com/assets/107754/14217294/08b85c92-f802-11e5-943e-e49579cfe437.png">

This is my project folder `test02` when trying to create a new project using the above template cache.

<img width="220" alt="screen shot 2016-04-01 at 11 48 38 am" src="https://cloud.githubusercontent.com/assets/107754/14217322/25643b9a-f802-11e5-93d4-3632707e8843.png">

It's possible that the `create` function used in the `connect-phonegap` dependency isn't looking for the `config.xml` in it's new location in the template update; so we are getting a project created without a `config.xml` file.

**Comment by chrisgriffith** [comment]
Yeah. I am looking at the create code now.

**Comment by LiveListMobile** [comment]
I downloaded the config file and placed it into my project directory. That did, finally, cure the error however as you can see, there are still problems.  For instance, my app name was appSample5 and it is reading Hello World.  The logo is missing, including the default one in the img folder of the project directory.  Also, the 4 folders are still empty.

**Comment by hermwong** [comment]
@LiveListMobile yeah. the new `config.xml` from the updated template isn't referencing the correct location of the icon. So PhoneGap Desktop is having an issue finding the icon.

I'm currently working with @devgeeks to find a quick resolution to the issue with the template changes.

**Comment by hermwong** [comment]
Hi All,

Thanks again for your patience and providing the information that we required to troubleshoot this issue.

@devgeeks was able to quickly resolve the issue with the information provided.

To get the fix to work on your computer's you'll need to reset your Local Storage and also reset PhoneGap Desktop's template cache.

To reset the Local Storage you'll need to delete the Local Storage folder used by PhoneGap Desktop at the following locations:

On Mac:

~/Library/Application Support/PhoneGap/Local Storage

On Windows:

C:\Users\<Windows User Name>\AppData\Roaming\PhoneGap\Local Storage

Next you'll need to reset PhoneGap Desktop's template cache by deleting the `.cordova` folder which can be found at the following locations:

On Mac:

/Users/<username>/.cordova

On Windows:

C:\Users\<username>\.cordova

**Comment by LiveListMobile** [comment]
@hermwong @devgeeks 
Guys, just wanted to follow up and let you know that your last set of instructions worked.  I was able to successfully create the Hello World sample apps without the error.  It is displaying the correct Hello World logo and my updates are showing up on my device running the Developer App.
Many thanks to you all for your efforts in getting this issue resolved.

**Comment by Delevop** [comment]
Hi - I'm still having trouble with this. Just downloaded 0.3.3 for Windows. I've tired all the above and plenty other suggestions on other threads. PG-Desktop seems to be making a .cordova folder in C:\users\<username>\ with a www folder. The 4 folders created in my target project folder are all empty.

Does PhoneGap still work?

**Comment by hermwong** [comment]
@Delevop try resetting PhoneGap Desktop's template cache by following these [instructions](https://github.com/phonegap/phonegap-app-desktop/issues/648#issuecomment-233003701).

**Comment by Delevop** [comment]
Thanks for the reply. I tried that several times in many different orders. No luck whatsoever..

On 15 Jul 2016 17:48, Herm Wong <notifications@github.com> wrote:@Delevop try resetting PhoneGap Desktop's template cache by following these instructions.

**Comment by hermwong** [comment]
@Delevop I've pinpointed the issue, there seems to be have been a recent change to the template and it seems to have a compatibility issue with the `connect-phonegap create` API which is used by PhoneGap Desktop to create projects.

We're currently working on a fix.

**Comment by Delevop** [comment]
Thanks a lot for looking into it - do let us know when the fix is ready. Looking forward to using PhoneGap for the first time..

**Comment by hermwong** [comment]
We've made a fix to the template, however you'll need to reset your template cache by deleting the `.cordova` folder.

On Mac:

`/Users/<username>/.cordova`

On Windows:

`C:\Users\<username>\.cordova`

**Comment by Farzin-S-Amini** [comment]
thank you so much. I can create a project now!!
