### ISSUE TITLE
Server is running on multiple IP addresses

### ISSUE THREAD

**Issue by DeemStarr** [phonegap/phonegap-app-desktop#585]
I have looked through various threads and cannot get to the bottom of this issue, anyone know how to fix this? Thanks.

**Comment by hermwong** [comment]
Are you running Virtual Machine or VPN on your computer?

**Comment by DeemStarr** [comment]
Hey Herm,

I'm running it on my computer (laptop).

Thanks for the help,
Andrew

**Comment by DeemStarr** [comment]
Would I have to connect to a server?

**Comment by hermwong** [comment]
If the server is running on multiple IP addresses it usually means that your computer has 1 of the following:

1. multiple network adapters
1. Virtual Machine software (VM)
1. Virtual Private Network software (VPN)

Your best bet would be to try each of the IP addresses in the PhoneGap Mobile App and see if any of them will serve your project to the Mobile App.

If you are on a corporate network or have firewall software or anti-virus software (AV) they may prevent the pairing between the PhoneGap Desktop and PhoneGap Mobile App.

**Comment by DeemStarr** [comment]
I enabled the program through firewall, so it shouldn't be the issue. I
don't use VPN or VM, so I may just run it on a server when my friend gets
me access to his. I would have to enable the IP through my IPV4 protocol?
However, I did get apache cordova up and running on visual studio, so
that's a plus for now!

**Comment by hermwong** [comment]
The PhoneGap Desktop creates a local server on your computer. If you've created or imported a project into the PhoneGap Desktop you can use the PhoneGap Mobile App to preview your project.

Here is our [Getting Started with PhoneGap](http://docs.phonegap.com/getting-started/1-install-phonegap/desktop/) walk through that will explain how to get started using the PhoneGap Desktop and PhoneGap Mobile App.
