### ISSUE TITLE
Create Default PhoneGap Project

### ISSUE THREAD

**Issue by snowinmay** [phonegap/phonegap-app-desktop#586]
The PhoneGap desktop tools include a default Hello World project for beginners to start with.
Where is the  default Hello World project?
I couldn't find it

**Comment by jhhood** [comment]
@snowinmay its under the installation directory; where ever you put that. Look in there under ./resources/default_app. It doesnt contain a config.xml though so when i tried loading it into the PhoneGap desktop as a project it just complained and didnt do anything, but you can just open the index.html and it will pop up. It isnt a Hello World app though.

**Comment by hermwong** [comment]
@snowinmay, were you able to successfully create a project?

If you follow these steps in our [documentation](http://docs.phonegap.com/getting-started/3-create-your-app/desktop/), it will show you how to create a project using the PhoneGap Desktop App.

To preview the `Hello World` project you will need to [install](http://docs.phonegap.com/getting-started/2-install-mobile-app/) the PhoneGap Developer App on your mobile device.

**Comment by Blissmann** [comment]
On OS X 10.11.4 - Following the Getting Started documentation, Step 3 substep 2: click the green Create project button. This results in "Selected folder doesn't contain a config.xml file". At this point, we are unable to get to Step 4 following the documentation. Where can I find a config.xml file for this Getting Started Hello World walkthrough? BTW, it appears as if all the other files have been created in the folder, just not the config.xml file.

**Comment by chrisgriffith** [comment]
Could it be related to the clean up on the template (https://github.com/phonegap/phonegap-template-hello-world) itself causing the issue?

**Comment by Blissmann** [comment]
Thanks Chris, this is most likely related to that issue. I grabbed the config.xml from here: https://github.com/phonegap/phonegap-template-hello-world
and put it into my app folder. I have it working now. Thank you! It just appears as if the desktop app doesn't generate the config.xml.

**Comment by hermwong** [comment]
Hi Everyone,

We've found a fix to this issue. Please see this [comment](https://github.com/phonegap/phonegap-app-desktop/issues/584#issuecomment-204590124) for instructions on how to resolve the issue.
