### ISSUE TITLE
Blank screen when trying to create new project

### ISSUE THREAD

**Issue by jacob-j** [phonegap/phonegap-app-desktop#589]
Hello!

Im getting a blank screen when I try to create a new project. As seen below.
I've tried reinstalling, restarting and everything in between.

Im using OS X 10.11.4 and Phonegap 0.2.3.

<img width="466" alt="screen shot 2016-04-08 at 18 33 09" src="https://cloud.githubusercontent.com/assets/5649576/14390663/7e8ac868-fdb8-11e5-9b62-63e4e82fc897.png">

**Comment by hermwong** [comment]
Hi @jacob-j, could you provide us with some information regarding your computer's configuration?

PhoneGap Desktop version / PhoneGap CLI version
PhoneGap Mobile App version
Mobile devices & Mobile OS version
Computer OS version
network type (home/corporate)
computer / network security (firewall / anti-virus / disk encryption)
are you using VMs on your computer?
do you have multiple network adapters (or virtual network adapters)
are you using VPN?

**Comment by jacob-j** [comment]
PhoneGap Desktop version / PhoneGap CLI version: `0.2.3`
PhoneGap Mobile App version `1.6.1`
Mobile devices & Mobile OS version `iPhone 6, iOS 9.3.1`
Computer `OS version 10.11.4 (15E65)`
network type (home/corporate) `Home`
computer / network security (firewall / anti-virus / disk encryption) `OS X built in Firewall. FileVault (Disk encryption) turned on.`
are you using VMs on your computer?` No`
do you have multiple network adapters (or virtual network adapters) `No`
are you using VPN? `No`

**Comment by hermwong** [comment]
Could you try it with FileVault disabled? I've never developed & tested with FileVault enabled so it may be causing the issue.

**Comment by jacob-j** [comment]
I still gives me blank screen.

**Comment by hermwong** [comment]
I wonder if the initial attempts at running PhoneGap Desktop with FileVault enabled would have caused some issues with the install files, localStorage or templates used by the PhoneGap Desktop.

Could you try the following:

With FileVault on:

1. delete the PhoneGap Desktop localStorage found here: `~/Library/Application Support/PhoneGap/Local Storage`
1. delete the PhoneGap Desktop template cache found here: `/Users/<username>/.cordova`
1. uninstall PhoneGap Desktop

Turn off FileVault:

1. download & install the latest PhoneGap Desktop 0.2.3
1. try to create a project

**Comment by jacob-j** [comment]
This solved it! 
Is there a "known issues" section of phonegap you should add this there. 
Thanks for your help.

**Comment by Gamaroff** [comment]
1. delete the PhoneGap Desktop localStorage found here: ~/Library/Application Support/PhoneGap/Local Storage

Works. Thanks.
