### ISSUE TITLE
Missing cordova.js when using browser

### ISSUE THREAD

**Issue by DrRoach** [phonegap/phonegap-app-desktop#591]
When you create a new app using the desktop app, you can't visit the given IP for the server in a browser without getting a 'missing cordova.js' error. 

Should you be able to visit the IP given in the phonegap app and have a local dev environment in your browser?

**Comment by hermwong** [comment]
Browser support isn't supported in 0.2.3 of the Desktop App. The browser support feature will be released in the upcoming 0.2.4 release of the Desktop App.

**Comment by DrRoach** [comment]
Ah okay that would make sense, sorry about that.
