### ISSUE TITLE
After removing projects, creating a new one will add previously removed projects back

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/phonegap-app-desktop#595]
1. Remove some projects from the list
2. Create a new project

**Actual Result**: New project as well as previously removed projects are added to the list

**Expected Result**: Only the new project should be added to the list

This does NOT occur when opening an existing project

**Comment by hermwong** [comment]
Wasn't able to reproduce this issue. I suspect it was related to #598 and fixed with the changes made for #598.
