### ISSUE TITLE
Connect-PhoneGap & PhoneGap-CLI releases 

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#596]
The Desktop will require updated versions of `connect-phonegap` and `phonegap-cli` to be released before it can be updated to with the Browser Platform support feature.

**Comment by surajpindoria** [comment]
Released latest PG-CLI and connect-phonegap with browser support for desktop added
@hermwong

**Comment by hermwong** [comment]
Desktop needs to be updated to user `phonegap-cli 6.0.5` and `connect-phonegap 0.20.6`.
