### ISSUE TITLE
getting error "read ECONNRESET" while creating project

### ISSUE THREAD

**Issue by mk48** [phonegap/phonegap-app-desktop#597]
I just newly installed the PhoneGap desktop and tried to create a project, getting and error like "read ECONNRESET".
I have attached the screenshot here.
![projectcreationerr](https://cloud.githubusercontent.com/assets/3082469/14602429/8107e52e-0585-11e6-85d1-af9824856145.png)

**Comment by hermwong** [comment]
@mk48, if you could provide the following information it would help me troubleshoot your issue:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?

**Comment by mk48** [comment]
1. PhoneGap Desktop version / PhoneGap CLI version
The reported problem was in 0.2.3
but today morning I got alert that newer version is available, 
so installed the latest version 0.3.0 
the latest version shows busy indicator, not even able to click the '+' for new project.
I will attach the screen later.

2. PhoneGap Mobile App version
I haven't installed the Mobile App version yet, first tried to create the project.

3. Mobile devices & Mobile OS version
first wanted to create project in desktop version, then I will go to mobile device side. 
not able to create a project, so haven't tried the next steps.

4. Computer OS version
Windows 7 Enterprise - SP1
64 bit

5. network type (home/corporate)
corporate

6. is your network using a proxy?
yes, we are using web based proxy.

7. computer / network security (firewall / anti-virus / disk encryption)
Firewall is ON.
Microsoft Forefront endpoint protection
NO disk encryption.

8. are you using VMs on your computer?
NO, I tried in my physical desktop system.

9. do you have multiple network adapters (or virtual network adapters)
NO

10. are you using VPN?
NO, direction connection.

**Comment by mk48** [comment]
the latest version 0.3.0 is in busy mode

![busy screen 0 3 0](https://cloud.githubusercontent.com/assets/3082469/14627275/65265aee-0610-11e6-8052-ac35feccdb8d.png)

**Comment by mk48** [comment]
I hope clicking the new project button will create some folders and files.
Is there any way to manually download those initial template files from net. so that I can use 'open existing project' option and continue.

**Comment by hermwong** [comment]
Hi @mk48, 

We're currently looking into the stuck loading screen for PhoneGap Desktop 0.3.0.

In regards to your previous issue with the `read ECONNRESET` error:

1. Corporate network - may have security policy that prevent PhoneGap Desktop from downloading required dependencies
1. Proxy network connection - in our experience proxy network connections always prevent PhoneGap Desktop from downloading required dependencies
1. Firewall - may be block some of the ports that PhoneGap Desktop requires

**Comment by mk48** [comment]
Thanks @hermwong 
Is there any way to manually download those initial template files?

**Comment by mk48** [comment]
hi @hermwong, version 0.2.3 is working fine in home net work.
the latest version 0.3.0 having different problem.
so I am closing this issue.
