### ISSUE TITLE
Duplicate error on create project 

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-app-desktop#598]
Using the 0.3.0 **pre-release**

If I create a new project in a folder where I just created a previous one but with a different name, I get a duplicate error, shown in screenshot:

![screen shot 2016-04-18 at 12 14 06 pm](https://cloud.githubusercontent.com/assets/359935/14611530/b832a252-0560-11e6-9c3e-92ea15be2412.png)

Despite the error, the project does actually get added. In this case desktop3 was the project that gave me the error though I was able to reproduce several times.

**Comment by hermwong** [comment]
It's looking like the `complete` event listener isn't removed after the first project is created, so when the second project is created the event listener fires twice.

https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/project-create-open-handlers.js#L147
