### ISSUE TITLE
Config.xml error on project create

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-app-desktop#600]
Using pre-release **0.3.0**

After I create a new project (leaving the default package) in a folder where I've created a previous project using this version of the Desktop app, I receive this error: 

![image](https://cloud.githubusercontent.com/assets/359935/14616245/834033fe-0577-11e6-81d8-a3f9e36d374d.png)

It's usually followed by the duplicate error I reported in issue #598 as well. 

**Note:** In this same session I've also deleted all the projects in the list prior and created new ones (with completely different names) in case that has any effect on the workflow. I also left the default package name for each project created.

**Comment by hermwong** [comment]
@hollyschinsky, I'm having troubles reproducing this issue.

Would you be able to list out the steps to reproduce in a numbered list format?

**Comment by hermwong** [comment]
I wonder if the changes made for the #598 fix, resolved this issue as well.
