### ISSUE TITLE
Different project being served then desktop app highlights green

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-app-desktop#601]
**Using pre-release 0.3.0**

I ran into a case where after project creates/deletes and the issues reported in issue #598, #600 the desktop app showed a certain project as running but the browser loaded a different one (see config.xml app name versus what desktop app shows below):

![image](https://cloud.githubusercontent.com/assets/359935/14616755/b98f2b2a-0579-11e6-9331-3ecdffaf89be.png)

I was able to reproduce this a couple times by deleting them all and creating new ones (also saw issue #595 and all my deleted projects were back). It adds the new project after the config/duplicate errors and highlights it like it's the currently served project but it's not when you check the config.xml loaded in the browser. If you manually start another one it will load the right one in the browser.

**Comment by hermwong** [comment]
I wonder if this is related to #593

**Comment by hermwong** [comment]
Can't seem to reproduce after the changes made for #598.
