### ISSUE TITLE
Plugins not loaded in browser

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-app-desktop#603]
When loading the IP address being served from the Desktop app in the browser using the latest browser support, the plugins defined in the root config.xml are not loaded and the `browser.json` does not show them as defined so they will all throw errors when trying to use them currently. 

![image](https://cloud.githubusercontent.com/assets/359935/14623037/86da1bb8-059c-11e6-9191-ef990e246523.png)

And this output is from the same project being served above from Desktop app:
![image](https://cloud.githubusercontent.com/assets/359935/14623065/c56148d4-059c-11e6-9a38-d03574e7ba69.png)

**Comment by devgeeks** [comment]
This could be related to the template config.xml not specifying a version for plugins.

The template published to npm does, but `master` (used by the desktop app) had to roll this back temporarily.

If this is the cause (pretty sure), then we'll need to update the `config.xml` in the template again with a version number for each plugin...

**Comment by hollyschinsky** [comment]
Yes I thought that was it too but even using one created by the CLI first (where the spec version is in the template used) where the Desktop app serves it and adds browser platform shows the same issue. Looking in the `platforms/browser` folder in the project directly shows some of the plugins actually are added but it's not all of them and the config and JSON files for the browser platform are out of whack with their definitions. :/ 

To recreate:

- Use CLI to create project - `$ phonegap create myApp`
- Open it in PhoneGap Desktop and `serve` it there

- Open URL in Browser - no plugins 

![image](https://cloud.githubusercontent.com/assets/359935/14623975/68786258-05a4-11e6-8a26-d76e53e01333.png)

Served From CLI - you'll see the plugins folder load like screenshot below (though doesn't always load *all* of them unless they're specifically added and removed with the CLI `plugin add` command or if the `$ phonegap platform remove browser` followed by `$ phonegap platform add browser`. May still be related to `config.xml` plugin definitions, just need to test with using` >` vs `~` etc too. 

![image](https://cloud.githubusercontent.com/assets/359935/14623988/7c73327e-05a4-11e6-9c78-d409bf63e9c8.png)

**Comment by surajpindoria** [comment]
Also noticing that `cordova_plugins.js` and `<project-root>/platforms/browser/platform_www/plugins/` are not getting updated properly. Even running `phonegap prepare browser` does not do the trick. But using plugin commands, `phonegap plugin (add / rm) ...` will re-populate files / dirs correctly.

Still investigating further, my guess is there are steps in the plugin commands that are not run during prepare.

**Comment by surajpindoria** [comment]
So the issue is with the way we are adding the browser platform in the desktop app. We were running into issues when invoking the platform create scripts from within the app so I implemented a workaround for the time being. But by doing this, I am not properly creating `<project-root>/plugins/browser.json`. When running prepare, cordova is looking for that file to get the installed plugins and since it does not exist we are getting this problem.

Solution is to find a way to properly add the browser platform and remove this workaround. Currently working on this now.

**Comment by onclickstudio** [comment]
whilst this bug is being fixed, is there any workaround or manual hack to make browser platform test usefull? I am not using CLI, just html/css/js development with build compilation but I discovered phonegap desktop and I would like to make it work with plugins...

**Comment by surajpindoria** [comment]
Hi @onclickstudio,

Currently the only workaround I have found involves using the CLI. If you already installed the browser platform using the desktop app then you will need to reinstall from the CLI. You can do this with the following commands:
```
$ phonegap platform rm browser
$ phonegap platform add browser
```

**Comment by surajpindoria** [comment]
I have finished the workaround for this in `connect-phonegap` desktop-plugins branch.

@hollyschinsky Can you retest this to double check please! Just remove browser platform from your project and rebuild desktop app with:
`"connect-phonegap": "https://github.com/phonegap/connect-phonegap.git#desktop-plugins",`
in package.json.

**Comment by onclickstudio** [comment]
thanks @surajpindoria, it worked for me!
