### ISSUE TITLE
See if the OSX Auto-Updater can be initiated by user input

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#605]
Currently the OSX auto-updater will notify the user that an update is available and then perform the auto-update.

We would like to see if we can modify this behavior so that it follows these steps:

1. notify user update is available
1. user can choose to update or cancel
1. if user chooses to update, the auto-updater will update the app

**Comment by hermwong** [comment]
We may need to migrate from `squirrel.mac` (Electron's default auto-updater) to `[electron-updater](https://www.npmjs.com/package/electron-updater#example-mainjs)` to add the desired workflow to the auto-update workflow.

**Comment by hermwong** [comment]
The `electron-updater` writes an error log at this location `~/Library/Application Support/PhoneGap/logs/updater.log`

**Comment by hermwong** [comment]
Docs on configuring binary updates:

1. https://github.com/EvolveLabs/electron-updater/issues/21
2. https://github.com/EvolveLabs/electron-updater/issues/20

**Comment by hermwong** [comment]
Looks like `electron-updater` uses `.tgz` for [binary distribution on `OSX`](https://github.com/EvolveLabs/electron-ref/blob/master/package.json#L38).

**Comment by hermwong** [comment]
[Compress to `.tgz` from OSX terminal](http://osxdaily.com/2012/04/05/create-tar-gzip/).

**Comment by hermwong** [comment]
Another option suggested by @mwbrooks:

"Modify our existing code to do the manual update checking and piggy back on Electron's auto-updater."

Pros:

- re-use existing update infrastructure
- minimize risk since we aren't introducing a new dependency (and its dependencies)

**Comment by hermwong** [comment]
<img width="461" alt="screen shot 2016-06-14 at 3 15 28 pm" src="https://cloud.githubusercontent.com/assets/107754/16061634/df2ffd0a-3242-11e6-9397-df0d87b43a28.png">

**Comment by hermwong** [comment]
Auto-updater now works with the `Update Now` workflow.

We probably need to add is some type of indicator to the user that the update is happening.

Currently when the user clicks on the `Update Now` button, the `Update Available` dialog disappears and the Desktop App just appears to be in normal state while the update is downloading in the background.

**Comment by mwbrooks** [comment]
@hermwong awesome! Yea, I agree that we need to show that the download is in progress. It feels pointless to allow the user to navigate around the app, since it will suddenly close and restart when the download is complete. @jahoni should be looped in to help. She may even have a design setup already.

**Comment by jahoni** [comment]
as we chatted about (briefly) @hermwong - it'd be great if we could show the notification in a modal. once the user chooses "Update Now", a determinate progress indicator should appear. After a very quick look I couldn't find any open source determinate progress indicators out there...maybe you'll have more luck?

let me know if you need a mock-up.

**Comment by hermwong** [comment]
Will take another look at Electron's auto-update APIs to see if we can get the download progress information.

**Comment by hermwong** [comment]
It doesn't look like the Electron Auto Updater API exposes the download progress.

**Comment by jahoni** [comment]
Well, that settles it then - we'll need to go with an indeterminate progress indicator. The circular one used on app load is cool.

**Comment by hermwong** [comment]
Should the screen look like the initial loading screen with the exception of the copy "Update is in progress..."

**Comment by jahoni** [comment]
I think that'll work....

**Comment by hermwong** [comment]
See here for reminder of the existing loading screen: https://github.com/phonegap/phonegap-app-desktop/issues/575#issuecomment-207828410

Should the copy be placed above or below the loader animation.

**Comment by jahoni** [comment]
Text above the loader, same colour blue

**Comment by hermwong** [comment]
![screen recording 2016-06-20 at 11 35 am](https://cloud.githubusercontent.com/assets/107754/16209855/d4985838-36ed-11e6-9860-5860f42094ee.gif)
