### ISSUE TITLE
Constantly Crashing

### ISSUE THREAD

**Issue by AugmentBLU** [phonegap/phonegap-app-desktop#610]
Hello,

I'm having a lot of issues with the desktop app, it starts up fine but after a short time the app goes black and the menu options do not work, neither does the local server. I have to force shutdown and restart the app to view a project locally in my browser.

I'm using Windows 10 - however it's been fine until the last update. 0.3.1

Any ideas what could be causing this freezing and crash?

The image below shows what happens, for some reason it's showing a white background when it's actually black on my screen.

![image](https://cloud.githubusercontent.com/assets/442602/14770005/16625988-0a5e-11e6-9f7c-f1cb8b749764.png)

Thanks,
Ross

**Comment by hermwong** [comment]
@AugmentBLU 

Could you provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?

Is there anything in particular that you were doing within the app before it crashed on you? (Trying to pinpoint the steps to reproduce the issue would help me troubleshoot).

**Comment by AugmentBLU** [comment]
Sure, sorry I should of provided a bit more information first time.

1. PhoneGap Desktop v 0.3.1 / CLI 6.1.0
2. Mobile App v 1.6.2
3. Testing on my Samsung S6 using Android 6.0.1
4. PC OS Windows 10 64 bit with all latest updates/drivers
5. Network 4G mobile broadband
6. No
7. Intel i7-6700K CPU @ 4ghz/ 16GB RAM/ Nvidia GTX 980 TI/ all drives are SSD, main drive is M.2 SSD
Firewall on router / Avast Anti Virus/ no disk encryption
8. No
9. No
10. No

I'm using the desktop app as you normally would, open up the local IP (http://192.168.43.245:3000/) of in Chrome to get an idea of how the app is progressing and at random times, the site will no longer be available and the PhoneGap desktop app is black and unresponsive. 

I edit my app in NetBeans 8.0.1, sometimes when I refresh the browser the crash happens, sometimes it happens with no interaction. I'll either see the page couldn't be reached as the server has crashed or in the browser I see something similar to phonegap Error: EPERM: operation not permitted.

If there's any more information that I can provide, let me know as I'm quite new to PhoneGap. Thanks.

**Comment by hermwong** [comment]
I did a search for the `EPERM` error and found this NPM [issue](https://github.com/Medium/phantomjs/issues/19) which suggests that:

1. AV software could be causing an issue
1. The App should be run as an Administrator

**Comment by AugmentBLU** [comment]
I did disable the AV and it still happened, however I didn't try running the app as an Administrator. I'll do that now and see how it goes, I'll report back either way in case others are having the same issue.

Thanks,
Ross

**Comment by M4sterShake** [comment]
I don't have an antivirus installed and have tried running as administrator but am getting the exact same issue with a very similar setup to AugmentBLU.

My answers to the question posted by hermwong:
PhoneGap Desktop v 0.3.5
Mobile App v 1.7.2
Testing on my Samsung S6 using Android 6.0.1
PC OS Windows 10 64 bit with all latest updates/drivers
Network 4G mobile broadband
No
Intel i7-6700HQ CPU @ 2.6ghz/ 16GB RAM/ Nvidia GTX 960M / Samsung PM951 SSD / Firewall on router / No Anti Virus / no disk encryption
No
No
No

**Comment by pedramvdl31** [comment]
Okay i had the same issue and it drove me crazy for days.
My issue was that i used my website html, within the codes i had **google analytics** script. turned out this script is keep communicating with server therefor somehow triggers the phonegap autoreload.

**Comment by surajpindoria** [comment]
We have made many improvements to the desktop app, particularly on Windows. I have not seen this issue in awhile and believe that it has been resolved in the latest version.

Going to close this off.

**Comment by Kreozot** [comment]
Still crashing. Windows 10, PhoneGap 0.4.5

**Comment by nenadcvele** [comment]
Crashing, windows 10, phonegap v 0.4.5. I use scss in my projects, and sometimes I see scss task running in phpstorm when I switch from Chrome to PhpStorm even if I dont make any changes in scss. I think it crashes when I make a lot of scss changes.

**Comment by nenadcvele** [comment]
I stopped using scss file watcher, writing plain css and no crashes so far, so I guess scss is the culprit somehow.

**Comment by Valkhan** [comment]
I use Visual Studio Code integrated with my git repo, it's also causing a lot o crashes that I believe is duo to file watcher of Phonegap App and VSCode, really anoying.

**Comment by actieve** [comment]
I just started having this happen as well, this is the only thing that shows in console then it is blank and h ave to force a restart:

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at Object.handle (C:\Program Files (x86)\Adobe\PhoneGap\PhoneGap Desktop\resources\app.asar.unpacked\node_modules\connect-phonegap\lib\middleware\cordova\cordova_plugins.js:18:33)
    at next (C:\Program Files (x86)\Adobe\PhoneGap\PhoneGap Desktop\resources\app.asar.unpacked\node_modules\connect\lib\proto.js:174:15)
    at Object.handle (C:\Program Files (x86)\Adobe\PhoneGap\PhoneGap Desktop\resources\app.asar.unpacked\node_modules\connect-phonegap\lib\middleware\cordova\cordova.js:33:13)
    at next (C:\Program Files (x86)\Adobe\PhoneGap\PhoneGap Desktop\resources\app.asar.unpacked\node_modules\connect\lib\proto.js:174:15)
    at SendStream.error (C:\Program Files (x86)\Adobe\PhoneGap\PhoneGap Desktop\resources\app.asar.unpacked\node_modules\serve-static\index.js:120:7)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:188:7)
    at SendStream.error (C:\Program Files (x86)\Adobe\PhoneGap\PhoneGap Desktop\resources\app.asar.unpacked\node_modules\send\index.js:245:17)

**Comment by honkmother** [comment]
Hahahaha, is this seriously closed?
