### ISSUE TITLE
When will there be support for external plugins ( April 2016 )

### ISSUE THREAD

**Issue by Annuther** [phonegap/phonegap-app-desktop#611]
Is there a plan to include support for external plugins installed via the CLI into PG Desktop. Just stumbled upon a thread from 2015 and sub was advised there is no support. Now, its 2016 and i have the latest version of PG Desktop v 0.3.1 wondering if this is any closer to becoming a reality??

If not is there anyway to use view these plugins in a testing environment instead of a device from PG desktop??

Cheers ...

**Comment by chrisgriffith** [comment]
The issue is any plugin that is used by the app, must be prebuilt into the app itself. Hence, why only the core plugins are supported. You could create a custom build of the mobile app with the plugin set you need and distribute that among the team as one option, or just build the app bypassing the Mobile App all together

**Comment by surajpindoria** [comment]
Here is a list of steps to follow in order to add custom plugins to the developer app:
https://github.com/phonegap/phonegap-app-developer#adding-custom-plugins

**Comment by Annuther** [comment]
**@chrisgriffith, surajpindoria,**
Thanks for that heads up guys - im relatively new to PG/cordova but im going to try the custom build it looks exactly what i want - i know ill get stuck somewhere so ill probably be back here at some point.

Just a quick query :  I have Cordova CLI already installed and Node - from the link provided (surajpindoria) is it correct that i dont need to have Cordova (with global switch) installed as i can create the custom build with Node/NPM and GIT alone is that correct??

**Comment by surajpindoria** [comment]
@Annuther 

You will need the PhoneGap CLI installed because the developer app will make commands to it when building. After that, just modify the `config.xml` with the new plugins that you would like to add and follow [these](https://github.com/phonegap/phonegap-app-developer#compile-and-run) steps to compile the new app.

**Comment by Annuther** [comment]
Ok i think i made a boo boo here ... i run the compile and run without adding the plugins that i required ... i see now but i get this error after the compile and run line ends:

> Executing "after_plugin_add"  hook for all plugins.

> ERROR running one or more of the platforms: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
> Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.
> You may not have the required environment or OS to run this project
> [phonegap] completed 'cordova --verbose run android'
> C:\customPGDesktop\phonegap-app-developer>

presuming that all i need to do to correct this before i try again is to add my plugins to config.xml and add  'ANDROID_HOME' to my environment path ( not sure about the, Failed to find 'android' command in your 'PATH' ).

How do i get the custm build onto my Android phone or do i have to run it locally??

**Comment by surajpindoria** [comment]
Follow the instructions [here](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#setting-environment-variables) to properly set up your environment variables. Once you have this set up it be able to find the `android` command.

When you have successfully built your custom app it will output a line at the end with the path to the apk:
```
Built the following apk(s):
	/Users/spindori/Documents/PhoneGap/phonegap-app-developer/platforms/android/build/outputs/apk/android.apk
```
To install to your device make sure it is connected and run `adb install <path-to-apk>`.

**Comment by Annuther** [comment]
@surajpindoria
Yes, figured it out this morning  - the error messages say it all ... my version of the SDK was messed up and parts none existent - reinstalled now ive got the .apk ... sweet

Cheers for your help much appreciated
