### ISSUE TITLE
Closing log window will show IP address list when server is off

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/phonegap-app-desktop#613]
Preconditions: Have multiple IP addresses when serving app

1. Turn off the server
2. Open the log window
3. Close log window

![phonegap](https://cloud.githubusercontent.com/assets/6467569/14969122/77aa0160-1075-11e6-827c-59fbbb1b6347.png)

**Comment by hermwong** [comment]
Was this tested on the 0.3.2 branch?

**Comment by surajpindoria** [comment]
Yes
