### ISSUE TITLE
Phonegap blackScreen on windows 10

### ISSUE THREAD

**Issue by Tibaka** [phonegap/phonegap-app-desktop#616]
Hi,

When i start phonegap on windows 10 i have a black windows instead of the normal view with the projets...

I don't know how to run the app.
Can i have some help ?

**Comment by hermwong** [comment]
hi @Tibaka,

To help me troubleshoot the issue, could you provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?

**Comment by Tibaka** [comment]
HI,

1. It's an issue with Phonegap DesktopVersion
2. No at all
3. Mobile: Nexus 5 under Android 6.0
4. Windows 10
5. Corporation (Ottawa's University)
6. I don't know
7. My computer is a laptop (ASUS) with a personal firework and Antivir (it's my anti-virus)
8. Yes i do
9. No
10. No

That's all i think ^^

**Comment by hermwong** [comment]
Were you able to run previous versions of the PhoneGap Desktop without issues before?

**Comment by Tibaka** [comment]
I'll  try previous versions, sry didn't have the time to do it before. And no it's my first time with this app i usualy use the commande line.

**Comment by hermwong** [comment]
We still haven't been able to duplicate this on our test clients, but we're still gathering data and trying to find a way to consistently reproduce this issue so that we can work on a fix.

**Comment by xenned12** [comment]
Any results here yet? I am getting similar issue with Phonegap Desktop on Windows 10 but mine is working good until certain number of app refreshes.

Shows this error first:
Error: EPERM: operation not permitted, stat 'DirectoryToMyApp\platforms\browser\www\index.html' at Error (native)

Then window turns black.
![2016-07-24_1902](https://cloud.githubusercontent.com/assets/18576206/17083371/6d7ed236-51d1-11e6-9d12-f7697f6d7bce.png)

**Comment by hermwong** [comment]
@xenned12, do you have NPM installed on your computer?

From the looks of it, the `EPERM` error requires an NPM cache clearing.

See here for details: https://github.com/npm/npm/issues/10826

**Comment by xenned12** [comment]
Yes, I do have. I already tried npm cache clearing but it still happens. I'll try the new update and hope that it wouldn't happen. I'll give you an update. Thanks.

**Comment by surajpindoria** [comment]
We have made a lot of improvements to the desktop app, particularly on Windows. Have not seen this issue in awhile and believe it to be resolved in the latest version. 

Going to close this off.

**Comment by zeketpa** [comment]
Just installed PhoneGap Desktop App today on my Acer Win 10 Laptop and when I try to create the default helloworld project it comes up with an error window stating: "You have been opted out of telemetry.  To change this run: cordova telemetry on.  Creating a new Cordova project.  Error: EPREM operation not permitted, mkdir 'C:\Users\ezeki\Desktop\PhoneGap\My test project".  When I manually created this dir it spilled out a much larger series of errors displayed in a new error window.

**Comment by surajpindoria** [comment]
Hrmm, this is very interesting! Thanks for reporting this @zeketpa, I will take a look at this. Can you just tell me what version of the desktop app you are using?

**Comment by zeketpa** [comment]
@surajpindoria 
The ver is 0.4.4

**Comment by scrublullz** [comment]
@zeketpa You still there man?
