### ISSUE TITLE
proxy URI problem in ajax POST

### ISSUE THREAD

**Issue by edward9145** [phonegap/phonegap-app-desktop#618]
v0.3.2 desktop version

when I do post request by XMLHttpRequest, 
example:
```
$$.ajax({
      url: "http://my.domain/api/request_uri"
      type: "POST",
      contentType: "application/x-www-form-urlencoded",
      data: {},
      success: function(res, status, xhr){
        console.log(res);
      }
    });
```
server will received the wrong URI like this: `api/request_uri/api/request_uri`

It works fine before v0.3.2 and ajax GET.

**Comment by edward9145** [comment]
another suggestion: add auto update config

**Comment by surajpindoria** [comment]
Hi @edward9145,

I am aware of this issue and have submitted a fix to the proper dependency.

**Comment by hermwong** [comment]
This will be fixed when Desktop includes `connect-phonegap` 0.21.4 or greater.

**Comment by surajpindoria** [comment]
Fixed in https://github.com/phonegap/connect-phonegap/commit/c43fe0962a77cb15c244ba047d28d54525c25362
