### ISSUE TITLE
Default app error

### ISSUE THREAD

**Issue by fcpauldiaz** [phonegap/phonegap-app-desktop#623]
Why the default app of phonegap shows errors?

![captura de pantalla 2016-05-15 19 26 46](https://cloud.githubusercontent.com/assets/4523284/15278246/1e44eb0e-1ad3-11e6-88d6-75fcbd4e9dc1.png)

**Comment by devgeeks** [comment]
The Uncaught TypeError one is a known issue. I should be submitting a fix for that later today.

Not sure about the other one... We'll get back to you on that.

**Comment by fcpauldiaz** [comment]
Is there also a known issue about the ajax requests ? @devgeeks I'm having trouble with ajax requests that I didn't had before.

**Comment by devgeeks** [comment]
Yes. That should also be getting a fix in the next day or so.

**Comment by devgeeks** [comment]
Re-opening this till we actually get the fix out.

**Comment by hermwong** [comment]
What are the steps to reproduce this issue?

**Comment by fcpauldiaz** [comment]
Just create a new app with the 0.32 desktop version

**Comment by hermwong** [comment]
Preview in the browser?

**Comment by fcpauldiaz** [comment]
yes

**Comment by hermwong** [comment]
@fcpauldiaz thanks. I've updated to include the fixes and currently in the process of performing regression tests.

If all goes well, we will release PhoneGap Desktop Beta v0.3.3.

**Comment by surajpindoria** [comment]
Fixed with https://github.com/phonegap/connect-phonegap/commit/e53fe7a39bd5c7a186502e37cf1a5e7ce881d0c7
