### ISSUE TITLE
Desktop needs to find project icon from new template config.xml format

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#626]

**Comment by hermwong** [comment]
Need to discuss with @devgeeks to determine the best approach for fixing this issue.

**Comment by hermwong** [comment]
New template format in the `hello-world` template and `Star Track` template have removed the `<icon>` tag which the PhoneGap Desktop uses to display the project icon.

As a temporary workaround, we've added the `<icon>` tag back into the config.xml of the templates.

We need to discuss ideas and determine a proper solution to this issue.

**Comment by mwbrooks** [comment]
I think it would be nice to write a small node module that can parse the `config.xml` and return the best icon path.

Something like (replace the names and syntax are what you would choose):

```javascript
var icon = require('cordova-config-icon');
icon.getPath(configXMLPath, function(e, info) {
  // info.largest.path
  // info.smallest.path
});
```

**Comment by devgeeks** [comment]
As above, but also have it fail gracefully to a default icon if it can't find one.

**Comment by hermwong** [comment]
As an FYI:

[This is where the PG-Desktop looks for `<icon>` in `config.xml`](https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/project-create-open-handlers.js#L196).

[This is where the icon retrieved from `<icon>` is used in the Desktop App](https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/project-widget.js#L28).

**Comment by hermwong** [comment]
Perhaps we should bundle the "default" icon and fail back to it, if the Desktop App can't find an icon in the template's `config.xml`.

**Comment by surajpindoria** [comment]
https://github.com/apache/cordova-lib/blob/master/cordova-common/src/ConfigParser/ConfigParser.js#L170

**Comment by purplecabbage** [comment]
Is this about the desktop app being able to use the icon in it's own UI?

**Comment by hermwong** [comment]
@purplecabbage Yeah. The new `config.xml` format has icons defined for each platform while the Desktop App expects to find an icon defined in the root.

**Comment by chrisgriffith** [comment]
But which icon to show? the iOS, Android, or Windows?

**Comment by purplecabbage** [comment]
The best fit for the UI I would assume.

**Comment by hermwong** [comment]
Fixed through:

https://github.com/phonegap/phonegap-app-desktop/pull/655

https://github.com/phonegap/phonegap-app-desktop/pull/689

**Comment by hermwong** [comment]
Fixed through:

https://github.com/phonegap/phonegap-app-desktop/pull/655

https://github.com/phonegap/phonegap-app-desktop/pull/689

**Comment by hermwong** [comment]
Fixed through:

https://github.com/phonegap/phonegap-app-desktop/pull/655

https://github.com/phonegap/phonegap-app-desktop/pull/689
