### ISSUE TITLE
The application "PhoneGap" can't be opened on Mac OS X

### ISSUE THREAD

**Issue by michaelhodgins** [phonegap/phonegap-app-desktop#634]
Hi

I've just downloaded the latest version of the PhoneGap desktop app. After overwriting my previous version, it no longer runs. Instead I get a native Mac dialog which says "The application "PhoneGap" can't be opened."

The Console program logs the following errors:

25/05/2016 09:17:03.189 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x1000000b.nwjs[4139]) Could not find and/or execute program specified by service: 2: No such file or directory: /Applications/PhoneGap.app/Contents/MacOS/nwjs
25/05/2016 09:17:03.189 Finder[416]: spawn_via_launchd() failed, errno=111 label=[0x0-0xc90c9].com.nw-builder.phonegap path=/Applications/PhoneGap.app/Contents/MacOS/nwjs flags=1 : LaunchApplicationClient.cp #963 LaunchApplicationWithSpawnViaLaunchD() q=com.apple.root.default-qos
25/05/2016 09:17:03.189 Finder[416]: spawn_via_launchd() failed, errno=111 label=[0x0-0xc90c9].com.nw-builder.phonegap path=/Applications/PhoneGap.app/Contents/MacOS/nwjs flags=1

I've looking inside the directory /Applications/PhoneGap.app/Contents/MacOS and nwjs does not exist. In fact, the only file in there is Electron.

**Comment by Nemtes** [comment]
+1

**Comment by hermwong** [comment]
It's weird that the app is looking for NWJS. The PhoneGap Desktop has been using Electron since 0.2.0 (released in late Nov. 2015).

Can you delete your current install of the PhoneGap Desktop and re-install the newest version ([PhoneGap Desktop v0.3.3](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.3.3)] and see if that resolves the issue for you?

**Comment by Nemtes** [comment]
I cleaned my installation and the zip version works for me. DMG package doesn't work.

**Comment by hermwong** [comment]
@Nemtes What is the error from the DMG?

**Comment by michaelhodgins** [comment]
@hermwong The DMG doesn't produce any errors for me as such, it's just that the software it installs doesn't work.

**Comment by hermwong** [comment]
@michaelhodgins did the Desktop App work when you did a manual install from the zip files?

**Comment by michaelhodgins** [comment]
@hermwong The .zip version does work.

**Comment by hermwong** [comment]
@Nemtes & @michaelhodgins thanks for confirming that the `.zip` install works.

I'll need to investigate the issue with the DMG installer.

**Comment by hermwong** [comment]
Just want to confirm that you both used the PhoneGap Desktop 0.3.3 DMG installer to produce this issue.

**Comment by michaelhodgins** [comment]
I downloaded the latest version from the website on May 25th. I don't recall the version number, but if 0.3.3 was the latest, then that would be the one. The application in the DMG claims to be 0.35.6, though I don't know how Mac OSX determines that.

**Comment by hermwong** [comment]
@michaelhodgins 0.35.6 is the version of Electron that we're using in PhoneGap Desktop 0.3.3. I'm not sure why the app would use the Electron version instead of the PhoneGap Desktop version which is defined in the [`package.json`](https://github.com/phonegap/phonegap-app-desktop/blob/master/package.json#L4).

**Comment by zavg** [comment]
+1

**Comment by surajpindoria** [comment]
I don't think this is still relevant as we are currently on version 0.4.4. Going to close this off.
