### ISSUE TITLE
XCode and Phonegap Resource Paths & Names Do Not Match

### ISSUE THREAD

**Issue by diloreto** [phonegap/phonegap-app-desktop#638]
PG Team,

I believe the paths and names of icons/splash screens that are generated from a new PhoneGap project do not match what XCode is looking for. A few things of note:
1. After I compile `phonegap build ios`, I have to manually copy & paste the images from the /www/res/icons/ directory into the platform/ icon folder for XCode to acknowledge them and add them to the project (so that they show up when pushing to devices).
2. When I run PhoneGap server, it is looking for the wrong path for these resources:

<img width="1003" alt="pg_server_directory_path_errors" src="https://cloud.githubusercontent.com/assets/1340168/16275217/160846cc-3877-11e6-8800-5c5b8fbc7302.png">

But when you create a new project `phonegap create my-app`, you will notice the directory structure is different:

<img width="447" alt="screen shot 2016-06-22 at 12 45 02 pm" src="https://cloud.githubusercontent.com/assets/1340168/16275385/c665533e-3877-11e6-9bbf-13b5c36beafe.png">

Can you please align the source directories to what the PhoneGap **serve** application expects, as well as the compiled directories with what XCode expects? If it wasn't obvious, I use a code-compile-compile-run setup.

**Comment by hermwong** [comment]
This looks like a PhoneGap CLI related suggestion. I'd suggest that you log it in the [PhoneGap CLI issue tracker](https://github.com/phonegap/phonegap-cli/issues).

**Comment by surajpindoria** [comment]
Closing this, not related to the desktop app.
