### ISSUE TITLE
PhoneGapDesktop.dmg damaged!

### ISSUE THREAD

**Issue by MCDan1670** [phonegap/phonegap-app-desktop#647]
The latest PhoneGapDesktop.dmg is damaged. Where can I get a working dmg with the PhoneGap Desktop app?

**Comment by hermwong** [comment]
You can follow this to fix the issue: http://www.tech-recipes.com/rx/45404/mac-downloaded-app-is-damaged-and-cant-be-opened-error-solved/

or this:

https://www.tekrevue.com/tip/disable-gatekeeper-el-capitan/

**Comment by devgeeks** [comment]
There is also work in progress on making sure this isn't needed... but until then, if you aren't comfortable with removing the Gatekeeper restriction entirely, you can right-click the PhoneGap app and choose the "open" item from the menu. This circumvents Gatekeeper for that specific app without disabling it and allowing other apps through.

**Comment by MCDan1670** [comment]
Ok, I just found out that version 0.3.3 does not support OS X 10.9 as mentioned on http://phonegap.com. Maybe you should change the requirements for OS X or fix version 0.3.3. ;)
