### ISSUE TITLE
Server is running/offline tab missing

### ISSUE THREAD

**Issue by bojankarkalasev** [phonegap/phonegap-app-desktop#649]
When I open PhoneGap Desktop and tried to create the a project I got the problem with config.xml missing and with the project folders empty. But then i noticed that the complete section where it should say Server is running or offline is missing. Also when i go to settings under Server Port: - i don't see my ip address.

I am running Windows 10 Pro x64. The PhoneGap Desktop version is v0.3.3 but I also tried downgrading with v0.3.2. I'm using Windows firewall with an exception for PG, Avast Free Antivirus which is disabled and I'm running PG as an administrator. Im using a home network and no proxy, no vpn. I have virtual machines with VMWare on my computer but im using the host for PhoneGap.

Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/20504011/16902541/20627be8-4c62-11e6-98eb-27e458fdff73.png)

**Comment by anuj1993** [comment]
is there a way to run phonegap 0.3.3 in windows 10(64-bit)?

**Comment by hermwong** [comment]
@anuj1993, Windows 10 (64-bit) is able to run 32-bit applications.

**Comment by hermwong** [comment]
@bojankarkalasev try clearing out PhoneGap Desktop's template cache:

You can reset your template cache by deleting the `.cordova` folder.

On Mac:

`/Users/<username>/.cordova`

On Windows:

`C:\Users\<username>\.cordova`

**Comment by bojankarkalasev** [comment]
I tried to reset the cache but nothing happens the Server is Running tab still doesn't appear.

I also tried installing PhoneGap Desktop on my freshly reinstalled laptop with Windows 7 Pro 64bit and i had the same problem. But now i fixed it with installing PhoneGap Desktop ver.0.2.3

**Comment by anuj1993** [comment]
i have install phonegap desktop app 0.3.3 on windows 10(64-bit), its install but its not show that its running or offline mode as mention in above question by @bojankarkalasev and i can't find any solution for this, should i need to install older version as bojankarkalasev mention in comment?

And this is bug for windows 10?

**Comment by surajpindoria** [comment]
We have made a lot of improvements to the desktop app, particularly on Windows. This is an issue with a pretty old version so it is not relevant anymore.

Going to close this.
