### ISSUE TITLE
Show a visual indicator when longer running tasks are occurring

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-app-desktop#651]
Show a visual indicator (maybe a spinner) and temporarily disable UI buttons or dialog interaction while longer running tasks are happening (for instance when fetching a template from npm and creating a new project).

**Comment by hermwong** [comment]
See if the loading code used in fix for #605 & #629 can be generalized to be used in any use case that requires a visual indicator when long running tasks are occurring.

**Comment by hermwong** [comment]
Let's identify which tasks need to display the loader.

- fetch template
-create project

what else?

**Comment by hermwong** [comment]
closed with #680
