### ISSUE TITLE
Better default icon handling

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-app-desktop#652]
We should never show a broken image link in the list for the project icon when one is not found, but instead have a default handling approach that looks more polished. 

One idea is to default to an icon with a grey (or something generic) background and a letter that matches the first letter of the app name chosen. Another is to use an X type of icon to show there's currently none specified. The 1st approach would be more visually appealing but would require a bit more work to implement.

**Comment by hermwong** [comment]
somewhat related to: #626

**Comment by purplecabbage** [comment]
Is this still relevant? Grey text and monogram are currently displayed.

**Comment by hermwong** [comment]
Probably not relevant anymore. The PR from #655 has resolved this issue.
