### ISSUE TITLE
0.3.4 is not refresh content in Developer Mobile App

### ISSUE THREAD

**Issue by zubus** [phonegap/phonegap-app-desktop#658]
Hello, I just upgraded to 0.3.4 phonegap. When making any changes to the source code of the project, this is not reflected in the app (Android).

Regards

**Comment by hermwong** [comment]
It looks like this is related to an issue with some changes in the latest `connect-phonegap` module which is used by both the PhoneGap Desktop and the PhoneGap Mobile App.

We're currently looking into the issue and hope to have a fix out soon.

**Comment by hermwong** [comment]
Temporary work a round would be to use your web browser to preview your project. You can do this by clicking on the URL on the server status bar on the bottom of the Desktop App or by typing the server's IP address & port into your web browser's address bar.

<img width="389" alt="screen shot 2016-07-27 at 10 49 27 am" src="https://cloud.githubusercontent.com/assets/107754/17185896/cf883126-53e7-11e6-8953-ce2d60472281.png">

**Comment by surajpindoria** [comment]
Tested this on Mac and Windows, also ran through [use cases](https://github.com/phonegap/phonegap-app-desktop/wiki/Use-Cases). Looks good!
