### ISSUE TITLE
Cannot dismiss "Update Available" message

### ISSUE THREAD

**Issue by andreagrossetti** [phonegap/phonegap-app-desktop#661]
Update available message is preventing me from working on my project since I can't dismiss it in any way. If I restart the app, it appears again.
Maybe it's still downloading the update, but I'm not aware of that since there's no loading bar. I've being waiting for 20 minutes

<img width="449" alt="schermata 2016-07-27 alle 12 07 19" src="https://cloud.githubusercontent.com/assets/6805823/17171937/14c48022-53f3-11e6-8b1a-53ae6dd28617.png">

**Comment by hermwong** [comment]
I would recommend that you manually perform the update: https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.3.4

**Comment by hermwong** [comment]
This has been fixed with #605. However you won't see the new auto-update workflow until you update from 0.3.4 to 0.3.5 (or newer).
