### ISSUE TITLE
v0.3.4 Server Log doesn't display 'console.log()' output.

### ISSUE THREAD

**Issue by hirofujimoto** [phonegap/phonegap-app-desktop#662]
After updating of the PhoneGap.app on my macOS, Server Log doesn't display 'console.log()' output. And I cannot to refresh or go home by 4 or 3finger tap on mobile device.

**Comment by surajpindoria** [comment]
Hi @hirofujimoto,

This issue was caused by an update to the `connect-phonegap` module we use to serve projects to the device. We already have a fix and will be releasing an update soon.

**Comment by surajpindoria** [comment]
Related to #658
