### ISSUE TITLE
Stop update automatically

### ISSUE THREAD

**Issue by edward9145** [phonegap/phonegap-app-desktop#663]
when started the phonegap desktop app, 
my app has been started, 
then the update message popped up automatically and there is no way to stop that...

It's hard to make sure the new version phonegap can be started properly, 
so I want to keep using the older version.

It could be better to add a confirm popup to select whether update or not.

**Comment by edward9145** [comment]
v0.3.4 It seems the proxy server for ajax not working

**Comment by surajpindoria** [comment]
Hey @edward9145,

We have added ability to confirm the update in the v0.3.4. Regarding your second issue, we had a bug related to the `connect-phonegap` module that has since been fixed. We will be releasing version v0.3.5 soon.

**Comment by hermwong** [comment]
Second issue is related to: #658

**Comment by hermwong** [comment]
For the auto-updater issue: #605 which has been released as part of 0.3.4. You won't see this workflow until you use 0.3.4 to update to 0.3.5 (or newer).
