### ISSUE TITLE
Phonegap Cannot Be Opened

### ISSUE THREAD

**Issue by jgacuca567** [phonegap/phonegap-app-desktop#665]
**Current Version:** 1.0.1
**Platform**: OS X El Capitan 10.11.6

After Updating to Phonegap from 0.3.5, I am unable to open the app, this is the error I am getting 

<img width="420" alt="screen shot 2016-07-29 at 3 56 49 pm" src="https://cloud.githubusercontent.com/assets/4000076/17261687/1c4ccf30-55a5-11e6-9fea-c4f4f21e2511.png">

**Comment by hermwong** [comment]
Can you try a reboot of your computer and then open PhoneGap Desktop?

**Comment by hermwong** [comment]
Sounds similar #496

**Comment by jgacuca567** [comment]
@hermwong it is now working, I think you should add a note that when it doesn't work to restart the computer.
