### ISSUE TITLE
PhoneGap cannot load Google.charts

### ISSUE THREAD

**Issue by hirofujimoto** [phonegap/phonegap-app-desktop#666]
On PhoneGap 0.3.3, I use the Google charts features on my PhoneGap project.

But after version 0.3.4, It failed to load chart library.

--- My code is: use '()' instead '<>'.

(script type="text/javascript" src="https://www.gstatic.com/charts/loader.js")(/script)
(script type="text/javascript" src="cordova.js")(/script)
(script type="text/javascript" src="js/index.js")(/script)
(script)
    console.log("----------------------- go to load! ---------------");
    google.charts.load('current', {packages: ['corechart']});
    google.charts.setOnLoadCallback(function(){
        console.log("---------------------we got it!!! ---------------");
    });
    app.initialize();
(/script)

ServerLog displays 'go to load!', but never display 'we got it!!!' and chart code do not work (naturally). I never changed CSP.

Any idea?

**Comment by hermwong** [comment]
I'd suggest that you post this on the [Adobe PhoneGap Forums](https://forums.adobe.com/community/phonegap).

**Comment by surajpindoria** [comment]
This was reported against an older version of the desktop app. If you are still noticing this in the latest version please feel free to reopen.
