### ISSUE TITLE
why phonegap start cost so much time?

### ISSUE THREAD

**Issue by Thstone37** [phonegap/phonegap-app-desktop#669]
when I click the exe,it cost me so much time to start phonegap?
![image](https://cloud.githubusercontent.com/assets/11756943/17430808/072e13dc-5b29-11e6-878f-9dc42fec0d07.png)
  I must wait so much time!!!!!
it make crazy!
how can i solve this problem?

**Comment by hermwong** [comment]
Could you provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?

**Comment by tanishak** [comment]
i am facing same problem, but after opening phonegap desktop for almost half an hour i am facing same problem. the desktop is not opening...

**Comment by hermwong** [comment]
Moving discussion over to #739.
