### ISSUE TITLE
Cannot create a project containing a space in the name

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-app-desktop#673]
Currently you cannot create a project containing a space while running with the template branch.

After investigation, the problem is due to some code in the PhoneGap CLI that is replacing all spaces with commas so the arguments cannot be properly parsed.

**Comment by hermwong** [comment]
confirmed that we're able to create a project with space in the name.

@hollyschinsky can you link the commit for this fix in a comment here?
