### ISSUE TITLE
Can't Open PhoneGap Desktop with OS X Sierra Latest Update

### ISSUE THREAD

**Issue by erhanyasar** [phonegap/phonegap-app-desktop#674]
I updated Sierra OS with latest release and idk why but it opens and just waits with all white window.

**Comment by hermwong** [comment]
We haven't tested on Sierra OS Beta yet. We'll most likely start taking a look at it after the 0.4.0 release of PhoneGap Desktop.

**Comment by erhanyasar** [comment]
Well I found out that changing any line of code after installing platforms & plugins it cause phonegap fails. Besides if any attempt of installing plugin after platform Android also make phonegap fails. It shouldn't be much hard to adding or changing project effect such a big error @hermwong

**Comment by erhanyasar** [comment]
closing this since #724 is updated and in progress
