### ISSUE TITLE
Desktop app won't launch - wrong path

### ISSUE THREAD

**Issue by monkeyinsurgency** [phonegap/phonegap-app-desktop#676]
Desktop app v1.0.1 (or 0.3.5) won't launch on OSX 10.11.6.  Console error is as such: 

`Finder[451]: spawn_via_launchd() failed, errno=111 label=[0x0-0x11f81f7].com.intel.nw path=/Applications/PhoneGap.app/Contents/MacOS/node-webkit flags=1`
 
node-webkit doesn't exist in that directory.

Any help would be much appreciated

**Comment by macdonst** [comment]
@monkeyinsurgency What version of PhoneGap.app are you using? The latest is v0.3.5 and to the best of my knowledge it doesn't even use node-webkit anymore. You may need to manually update yourself to the latest version at: https://github.com/phonegap/phonegap-app-desktop/releases/download/0.3.5/PhoneGapDesktop.dmg

**Comment by monkeyinsurgency** [comment]
I am using that very release.  I've done complete removals on my machine and fresh install from the .dmg, but still get that error.

**Comment by monkeyinsurgency** [comment]
I'm showing 1.0.1 through the GUI, but I downloaded from the same link you provided, both straight from the repo, and from the PhoneGap site, which points to the same thing.

![image](https://cloud.githubusercontent.com/assets/1014085/17651627/27017064-6263-11e6-8c10-434ae75c797c.png)

**Comment by macdonst** [comment]
@monkeyinsurgency same as me. If you go to the PhoneGap menu and click About you should see 0.3.5. Seems odd as it opens okay on my Mac. What version of OS is on your Mac?

**Comment by monkeyinsurgency** [comment]
10.11.6 (15G31)

I'd love to tell you what it says from the PhoneGap menu, but it won't load.

Are there preferences anywhere that would be providing this node path to the desktop app?

**Comment by macdonst** [comment]
@monkeyinsurgency LOL, of course. Forgive me.

I feel like there is some leftover preference on your machine that is trying to start the old node-webkit version. IIRC it is now updated to Electron but maybe @hermwong can chime in.

**Comment by monkeyinsurgency** [comment]
Cheers.  I'm up and running with the CLI, so I'm not blocked.  If anyone has any ideas, Herm or otherwise, I'm all ears 👂

**Comment by surajpindoria** [comment]
That version 1.0.1 is the Electron version used to build the app. Not sure why that is showing up instead of the actual app version

**Comment by hermwong** [comment]
The Desktop App has been using Electron since 0.2.0. We've had a few users report that they're getting the `node-webkit` or `nwjs` errors.

We're not sure why their system would still try load those dependencies since they are no longer used in the Desktop App. Unfortunately, we haven't been able to reproduce this issue on our own machines and test VMs, so we're not able to troubleshoot it.

Our only suggestions are to uninstall the Desktop and perform a manual install of the latest version ([via `.zip` package](https://github.com/phonegap/phonegap-app-desktop/releases)) or to use the PhoneGap-CLI.

**Comment by monkeyinsurgency** [comment]
I'm on the CLI, so I'm good.  I'll try the manual install, for curiosity's sake at least.

Thanks!
