### ISSUE TITLE
Display last directory selected

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#677]
Display last directory selected in Local Path field on the Project Details Overlay.

![](https://cloud.githubusercontent.com/assets/178345/17634029/549e2ca4-6085-11e6-8e6d-11aa130c52dc.png)

**Comment by hermwong** [comment]
@jahoni should the app only remember the last selected path on a success project create or should it just remember the last selected path even if the user clicks on the `cancel` or `back` buttons?

**Comment by jahoni** [comment]
good question, @hermwong. Took a look at how the GitHub desktop app deals with things, and I think it is a good approach.

To lay it out:

1. Remember the last selected path if create is successful, AND if the user hits the back button.
2. If the user cancels the process, do not remember the _last_ selected path (that is, revert to the previous/last successful create selection on next open).

The idea here, is that by selecting "back" the user is likely correcting which template they've selected, but would like want to keep their selected folder. Further, if the user cancels the whole process, they're abandoning their entire approach to that particular project set-up.

**Comment by hermwong** [comment]
Got the initial code in place to remember the path on successful project creation.

Continuing to work on the `back` and `cancel` use cases.
