### ISSUE TITLE
Re-evaluate Drag & Drop feature.

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#678]
Is it me, or does the drag and drop functionality not "work"? The intention was that users could drag a folder into the app, and a new project would be created from that folder....kinda like what happens in Ghostlab ([view a screencap](https://www.dropbox.com/s/nlegnt0rahzsy3t/ghostlab-dragndrop.m4v?dl=0)). Right now, users can drag a folder into the Desktop app, but nothing really happens (other than it seeming that the "+" button has been hit) ([view a screencap](https://www.dropbox.com/s/y37zeawsdmc4x2w/phonegapdesktop-dragndrop.m4v?dl=0)) My suggestion goes like this: if we can actually create a new project by dragging in a folder let's keep it, if we can only do what we're doing now - let's get rid of it.

**Comment by jahoni** [comment]
WHOA! nice. it works now. beauty - wasn't sure if we could get this working for this release. stoked.
