### ISSUE TITLE
Improve overlay transitions between Create Overlay & Template Overlay

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#679]
I'm not super happy with the transition between clicking the "Create new PhoneGap project..." link and the appearance of the template menu. There is a weird dissonance between the sliding back/out/left of the create menu, and the sliding down of the template menu. ([View a quick screencap of the transition I'm talking about here](https://www.dropbox.com/s/udz9w0g58k8b5wh/create-transition.m4v?dl=0)). If I manually scrub through the recording, I believe what is happening is that the template menu is sliding down "behind" the create menu, and the timing of the transitions isn't quite right. I *think* what I'd like to see is the template menu slide down, over top of the create menu, and that any transition out of the create menu be timed/obscured so that it isn't visible. This might require a bit of tweaking and/or a quick face to face to talk it out.

**Comment by hermwong** [comment]
Needs review by @jahoni.

**Comment by jahoni** [comment]
Looks GREAT! So much better - again, awesome work @hollyschinsky!!!!
