### ISSUE TITLE
Creating app progress indicator visibility

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#680]
The progress indicator isn't working well (because it isn't very visible) on the "creating app" screen. I'd like to suggest a couple of things: darken the colour of the modal overlay to about 80% transparent black, and change the colour of the indicator to white. Also - can we add helpful wording like "Loading PhoneGap Desktop..." and "Creating Project..." to the screens where the progress indicator appears?

**Comment by hermwong** [comment]
This feature has been implemented, just need UX sign off from @jahoni

**Comment by jahoni** [comment]
Looks perfect, nice work @hollyschinsky
