### ISSUE TITLE
Template Overlay - UI Improvements

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#681]
A few visual design related items:
- ~~There should be more space between the "|" (pipe separator) and the surrounding characters in the "STEP 1 of 2  I  SELECT A TEMPLATE" title.~~
- ~~The radio buttons should be aligned (left justified) to the other items..right now the list is indented about 20px.~~
- ~~The template descriptions should be aligned under the name, not under the radio button.~~
- The first item in the radio button list should be selected, which is the generally accepted pattern for this type of component. When I opened it, the second item (hello-world) was selected.
- I'd like to see friendly names (Hello World) used instead of computer generated names (hello-world) for the templates, as shown in the mock-up.
- I believe the order of the templates should be what is outlined in the mock-up.
- I also believe that the descriptions for the templates should match what is in the mock-up
- The "Server is offline" background is too large/tall on first open.
![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/17635266/41e34238-608b-11e6-8240-14898e89c321.png)

**Comment by hermwong** [comment]
For the order of the templates, we need to change how the template JSON in PhoneGap-CLI to include an index (order) property. Currently the Desktop just reads the `package.json` from PhoneGap-CLI and displays the them in FIFO order.

**Comment by hermwong** [comment]
A few other things to note:

1. Display user friendly names - should probably be a property in the template's json description
1. Template descriptions - needs to be updated in the PG-CLI's package.json in the template's json description

**Comment by hermwong** [comment]
The `hello-world` is selected as a default, in this case it just happens to be the second template loaded & then displayed. 

I've logged the necessary changes required in the PhoneGap-CLI's [issue tracker](https://github.com/phonegap/phonegap-cli/issues/641).

**Comment by jahoni** [comment]
Things look great to me, in the build from today. I'd say it is good to go, but won't close this issue off myself.
