### ISSUE TITLE
replace gaze with chokidar for file watching

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#683]
https://www.npmjs.com/package/chokidar

We used chokidar as the file watcher for #668.

**Comment by mwbrooks** [comment]
Nice! @surajpindoria I think we should do this in the PG CLI as well.

**Comment by hermwong** [comment]
Set ad dependency in [`src/config/package.json`](https://github.com/phonegap/phonegap-app-desktop/blob/master/src/config/package.json#L10).

Instantiated in [`www/js/requireStuff.js`](https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/requireStuff.js#L9).

Used in the [`setWatcher` method](https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/project-widget.js#L200).
