### ISSUE TITLE
[TASK] Remove binary files and host them elsewhere

### ISSUE THREAD

**Issue by shazron** [phonegap/phonegap-app-desktop#687]
This repo, on a fresh clone, is approx 2 GB in size. This is because of the binary files added to the repo. Removing the "installers" folder shrinks the repo size down to about 100MB, a 95% decrease.

Expected:
Reasonably sized repo size.

Actual:
Unreasonably sized repo size.

Having a smaller repo size will foster better collaboration, since users don't need to potentially wait half an hour or more (depending on connection) to clone the repo -- potentially frustrating or losing contributors in the process. 

Fix in two parts:
1. Remove binary files, and also remove from history (so repo size shrinks)
2. Put the binary files elsewhere, and refer to that new location in this repo (and update blog posts)

**Comment by shazron** [comment]
How to purge files from the repo, and history: https://help.github.com/articles/remove-sensitive-data/

**Comment by hermwong** [comment]
Ran the BFG tool and cleaned up the repo.

**Comment by hermwong** [comment]
Repo download has been reduced to ~ 106MB.

<img width="746" alt="screen shot 2016-10-27 at 2 42 25 pm" src="https://cloud.githubusercontent.com/assets/107754/19786606/a780d0e8-9c53-11e6-8fe7-df297093baeb.png">
