### ISSUE TITLE
live reload when updating new source file

### ISSUE THREAD

**Issue by edward9145** [phonegap/phonegap-app-desktop#694]
phonegap desktop v1.3.5
 Live reload works fine when I update the existed source files.

the problem is: 
A new HTML file is created, it can be accessed in the browser.
but when the new file is updated, live reload doesn't work.

I have to re-run the project.

**Comment by hermwong** [comment]
Could you provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?

**Comment by edward9145** [comment]
1. PhoneGap Desktop version / PhoneGap CLI version <br> PhoneGap Desktop (v1.3.5)

2. PhoneGap Mobile App <br> I didn't use phonegap mobile app, I used the latest chrome browser

3. Mobile devices & Mobile OS version

4. Computer OS version <br> OS X E Capitan 10.11.6

5. network type (home/corporate) <br> corporate

6. is your network using a proxy? <br> maybe, I'm not sure.

7. computer / network security (firewall / anti-virus / disk encryption) <br> mcafee is installed. none of the others.

8. are you using VMs on your computer? <br> No.

9. do you have multiple network adapters (or virtual network adapters) <br> No.

10. are you using VPN? <br> No.

**Comment by edward9145** [comment]
Here is a test case:
* run a phonegap project
```
www/
   index.html
```
* add a new HTML file `new.html`
```html
<h1>update me</h1>
```
```
www/
   index.html
   new.html
```
* access http://localhost:3000/new.html
* update `new.html`,
```html
<h1>updated</h1>
```

* http://localhost:3000/new.html does not automatically refresh

**Comment by surajpindoria** [comment]
I can confirm that this is an issue with the phonegap-cli. Adding a file does not trigger an autoreload, also subsequent file changes to the new file will not trigger autoreload. Have to stop/start the server to allow autoreload from the new file.
