### ISSUE TITLE
LiveReload Not working on iPhone Device

### ISSUE THREAD

**Issue by jgacuca567** [phonegap/phonegap-app-desktop#707]
@hermwong, have updated as requested 
Referencing issue #695, I am also experiencing the same issue. 
1. `DesktopVersion:` 0.3.5
2.  `PhonegapMobileVersion:` 1.7.2
3. `Device:`  iPhone 6+ , `iOS Version:` 9.3.5
4. `Platform:` OS X El Capitan 10.11.6
5. `NetworkType:` Home
6. `Proxy:` No
7. `Security:` None
8. `VM:` None
9. `MultipleAdapters:` None
10. `VPN:` None

Instant Livereload works in the browser

**Comment by hermwong** [comment]
Could you provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?

**Comment by jgacuca567** [comment]
@hermwong, status update?

**Comment by surajpindoria** [comment]
Hi @jgacuca567,

Did you ever manage to resolve this? If not, can you try this with the latest version of the desktop app and let me know if you are still facing this issue?

**Comment by jgacuca567** [comment]
@surajpindoria
@hermwong 

Its working now after updating to `0.4.4`. 
Thank You.

**Comment by hermwong** [comment]
Thanks for confirming.
