### ISSUE TITLE
White Window

### ISSUE THREAD

**Issue by duncanunderwood** [phonegap/phonegap-app-desktop#708]
After multiple re-installs. Phone gap desktop app boots up but then display a blank white window.

any ideas?

running OSX 10.11.6
Thanks

**Comment by hermwong** [comment]
Could you provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?

**Comment by duncanunderwood** [comment]
**1. MAC 0.3.5 Beta**
2. PhoneGap 1.7.2
3. iphone6plus 10.0.2
**4. 10.11.6**
5. home
6. no proxy
7. no
8. yes - parallels 
9. no
10. no

System Log
13/10/2016 3:28:29.903 AM SpotlightNetHelper[588]: tcp_connection_tls_session_error_callback_imp 54 __tcp_connection_tls_session_callback_write_block_invoke.434 error 22


![untitled](https://cloud.githubusercontent.com/assets/4410896/19318965/7696718a-90f6-11e6-9603-6ef4819d0846.jpg)

**Comment by hermwong** [comment]
Could you try reseting PhoneGap Desktop's localStorage & cache?

1. delete the PhoneGap Desktop localStorage found here: `~/Library/Application Support/PhoneGap/Local Storage`
1. delete the PhoneGap Desktop template cache found here: `/Users/<username>/.cordova`

**Comment by krisdes** [comment]
I'm having the same issue. Was trying to do the fix above, but there is no /PhoneGap in the /Application Support folder. Neither is there a .cordoba in user folder.

I've tried uninstalling Cordova and reinstalling. Clearing npm cache, and reboot. 

Phonegap boots and looks like it's initializing installs, then just goes to a white screen, exactly like pictured in OP's post.

**Comment by shaliko** [comment]
You can run PhoneGap app from console:

```
sudo npm install -g phonegap
```

From root folder of project:
```
phonegap serve
```

**Comment by surajpindoria** [comment]
Unfortunately we were not able to reproduce this on our end. Are you both still seeing this with the latest version of the app, 0.4.4.

@duncanunderwood @krisdes

**Comment by foker** [comment]
The same problem. deleting of cache didn't help. And I don't know what causes the problem

**Comment by foker** [comment]
Which way could I totally remove all about phonegap from my mac to clear the environment?

**Comment by foker** [comment]
Reinstalling phonegap and reloading mac  few times helped me... Maybe will help somebody else

**Comment by lkrubner** [comment]
phonegap info:

     package.json:    
    "phonegap-plugin-push": "^2.0.0",


    package-lock.json:    "phonegap-plugin-push": {
    package-lock.json:      "resolved": "https://registry.npmjs.org/phonegap-plugin-push/-/phonegap-plugin-push-2.1.2.tgz",

I'm struggling with this issue. First I run: 

    cordova emulate ios

The simulator starts up. I see the splash screen. Then the screen goes white. If I open the debug console log in the simulator, I see: 

    tcp_connection_tls_session_error_callback_imp 2 __tcp_connection_tls_session_callback_write_block_invoke.434 error 22

Several minutes later, this error also appears:

     MobileContainerManager gave us a path we weren't expecting; file a radar against them
	Expected: /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
	Actual: /Users/lkrubner/Library/Developer/CoreSimulator/Devices/7E725FBD-23F1-4759-BC45-FFC84DC93861/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
	Overriding MCM with the one true path
    Mar 22 14:09:42 Lawrences-MacBook-Pro routined[26374]: CoreLocation: Error occurred while 
    trying to retrieve motion state update: CMErrorDomain Code:104

My ionic info: 

    ionic info
    [WARN] Detected locally installed Ionic CLI, but it's too old--using global CLI.
    
    cli packages: (/usr/local/lib/node_modules)
    
        @ionic/cli-utils  : 1.19.2
        ionic (Ionic CLI) : 3.20.0
    
    global packages:
    
        cordova (Cordova CLI) : 7.1.0 
    
    local packages:
    
        @ionic/app-scripts : 2.1.4
        Cordova Platforms  : android broken ios 4.5.4
        Ionic Framework    : ionic-angular 3.6.0
    
    System:
    
        ios-deploy : 1.9.2 
        Node       : v6.5.0
        npm        : 3.10.3 
        OS         : OS X El Capitan
        Xcode      : Xcode 7.3.1 Build version 7D1014 
    
    Environment Variables:
    
        ANDROID_HOME : not set
    
    Misc:
    
        backend : pro
