### ISSUE TITLE
schedule downloading in phonegap/cordova

### ISSUE THREAD

**Issue by Lifesoftware** [phonegap/phonegap-app-desktop#709]
Please give me some code for shedual downlading a files using file transfer plugin in cordova .
Im trying so many tricks but not work.so please explain me.

**Comment by hermwong** [comment]
This issue tracker is for issues with the PhoneGap Desktop App.

If you would like to make a feature request for the Cordova File Transfer Plugin, I would suggest that you log the feature request in the [Apache Cordova File Transfer Plugin's issue tracker](https://issues.apache.org/jira/issues/?jql=project%20%3D%20CB%20AND%20status%20in%20%28Open%2C%20%22In%20Progress%22%2C%20Reopened%29%20AND%20resolution%20%3D%20Unresolved%20AND%20component%20%3D%20%22Plugin%20File%20Transfer%22%20ORDER%20BY%20priority%20DESC%2C%20summary%20ASC%2C%20updatedDate%20DESC).
