### ISSUE TITLE
cordova_plugins.js file missing returning 500 error

### ISSUE THREAD

**Issue by rmcroft** [phonegap/phonegap-app-desktop#711]
I'm trying to develop an app with the PhoneGap Desktop application (v0.3.5).  When I setup the default hello world project and look at the console I see a 500 error message trying to get it from the hello world project.  I think this error is preventing me from using the plugins and I can't find anything that says how to get rid of the error.

Request URL:http://xxx.xxx.xxx.xxx:3000/cordova_plugins.js
Request Method:GET
Status Code:500 Internal Server Error

**Comment by surajpindoria** [comment]
Are you testing this on the browser or on a phone?

**Comment by rmcroft** [comment]
I'm seeing the error in the browser.  I've been playing around with it on both the browser and the phone.  I haven't been able to get plugins to work in either case.

**Comment by rmcroft** [comment]
I also see it on the logs within the desktop app

**Comment by surajpindoria** [comment]
I think this may just be an issue when the browser platform was added to your project.

Do you have the PhoneGap CLI installed? If so, could you try removing the browser platform `phonegap platform rm browser`.

**Comment by rmcroft** [comment]
I don't have the CLI installed.  But this is happening the Hello World project ( + > Create new PhoneGap project... > enter data > run it) every time I create a new one.

**Comment by rmcroft** [comment]
That being said I did end up just moving the browser folder and forcing it to be recreated and  the cordova_plugins.js file got created.

**Comment by surajpindoria** [comment]
Awesome that you got it to work! We are going to be releasing a new version soon that has some changes to how the browser platform is added. Hopefully this will help to alleviate the issue in the future.

**Comment by chrisgriffith** [comment]
OK

**Comment by stefanedberg** [comment]
I'm having the same problem.

Steps to reproduce:

1. phonegap create project-name --id "com.project.name" --name "Project Name" --template blank

2. Import in PhoneGap app

3. View in browser

If I try to create the app through the PhoneGap app I just get "Project create failed with code 1".

macOS 10.12.3
phonegap-cli 6.4.3
PhoneGap app for mac v0.4.3

**Comment by mahanmarwat** [comment]
I'm having this same problem too.
Sometimes 404 and sometimes 500.

**Comment by jjalonso** [comment]
Same having it on 2020, just created a blank project using the mac tool.

**Comment by chrisgriffith** [comment]
The Desktop PhoneGap app is no longer maintained (and hasn't been for some time). It should not be used. In addition, the PhoneGap CLI is also no longer being maintained. Please shift over to using the Cordova CLI (which the PhoneGap CLI was based).
