### ISSUE TITLE
Version 0.4.0 stops at the loading screen

### ISSUE THREAD

**Issue by jakobjh** [phonegap/phonegap-app-desktop#716]
### PhoneGap Desktop version / PhoneGap CLI version
0.4.0

### Computer OS version
Win 10

### Expected Behaviour
Should start up showing the local server running

### Actual Behaviour
Gets stuck in loading screen. Just keeps on loading forever...

### Steps to Reproduce 
Start program :)
(no problems with 0.3.5)

#### Error messages
None

**Comment by jakobjh** [comment]
Found out i needed to run the downloadPG.js file manually from command prompt. Did not work by running the .bat file.

**Comment by surajpindoria** [comment]
Thanks for letting us know about the .bat file @jakobjh. I will look into this.
