### ISSUE TITLE
Latest update fails with Sierra OS

### ISSUE THREAD

**Issue by erhanyasar** [phonegap/phonegap-app-desktop#724]
Well as a starter, I have already issued kind of same situation till it's solved yet I got the same issue just after updating the PhoneGap on Sierra this time. It's issued with [#674](https://github.com/phonegap/phonegap-app-desktop/issues/674) and not closed. Wonder why do you need to test it with an on going OS.

Thanks,

## _System Configuration_
![screen shot 2016-11-02 at 14 36 33](https://cloud.githubusercontent.com/assets/11460444/19927226/70d8776e-a101-11e6-82d3-a7f673993282.png)
### PhoneGap Desktop version
PhoneGap v.0.4.1 -- I just updated and not able to add any other project anymore
### Mobile devices & Mobile OS version
Not even able to open it on desktop
### Computer OS version
shown in _System Configuration
### Network Type (home/corporate)
corporate
### Is your network using a proxy?
no
### Computer / Network security (firewall / anti-virus / disk encryption)
firewall only
### Are you using VMs on your computer?
no
### Do you have multiple network adapters (or virtual network adapters)?
I'm using corporate internet coming from multiple adapter but just I'm taking it from a single hub. Hence I tried it with a GSM and it was concluded the same way.
### Are you using VPN?
no
### Expected Behaviour
to create a new project
### Actual Behaviour
![screen shot 2016-11-02 at 14 27 57](https://cloud.githubusercontent.com/assets/11460444/19927518/a24a01a4-a102-11e6-87a4-60693f29259d.png)
### Steps to Reproduce 
I tried each new project choice (Blank, Hello World, Framework7, etc.) but failed the same way.
#### Error messages
Just as shown with Actual Behaviour "Project create failed with code 1"

**Comment by hermwong** [comment]
Does this error still occur for you if you try on your home network?

**Comment by erhanyasar** [comment]
I tried it with my gsm & office (both wi-fi & ethernet) hence not at home. I'll try it and let u know 2night @hermwong

**Comment by B00268219** [comment]
I have the same problem on win 7 laptop, even the previous version wasn't working for me, last that worked is 0.3.2 for me.
Did you find a solution to this?

**Comment by surajpindoria** [comment]
Hi @B00268219,

We do not support Windows 7 anymore. Currently we are only providing support for Windows 8.1 and Windows 10.

**Comment by zkrige** [comment]
same error for me on macOS Sierra

**Comment by erhanyasar** [comment]
@hermwong @surajpindoria @zkrige same with the home network, the problem is mainly with Sierra OS.

**Comment by hermwong** [comment]
Unfortunately, we haven't been able to reproduce this issue on our Sierra OS machines yet.

We will try to gather more info and see if we're able to determine what could be causing this issue.

Are you using the default OSX firewall or a 3rd party firewall?

**Comment by erhanyasar** [comment]
It's an OSX firewall hovewer I tried after I disabled the firewall again, yet the same @hermwong.

**Comment by shajisarasan** [comment]
Unfortunately, I too have the same problem. Mine is Windows 10. Getting error "Project create failed with code 1" Is there any solution for it?

**Comment by B00268219** [comment]
I solved this by removing PG, clearing all temps and restarting pc (Win7)
Install new PG,
 (go to bootom of this page (https://github.com/phonegap/phonegap-app-desktop)
see postInstall.bat location, run this as admin before running PG,
I was able to even install and run this from a USB stick, now works on many PC's :) Win7 and 10

**Comment by surajpindoria** [comment]
Awesome @B00268219,

Glad you were able to get this working.

**Comment by leegraham** [comment]
Same issue here: "Project create failed with code 1" Mac Sierra

**Comment by jpruett1** [comment]
Same issue here... Windows 10. And I attempted the uninstall and administrative run of the .bat script... No luck. Completely unable to use the application in its current state.

**Comment by shajisarasan** [comment]
Not solved yet... :( .... think it is common issue, but no solution ?

**Comment by erhanyasar** [comment]
I tried already whenever @B00268219 posts @surajpindoria hence does not work as @leegraham @jpruett1 @shajisarasan and many others. You may let us know if any additional way of removing the phonegap from applications folder.

**Comment by B00268219** [comment]
Not sure about Mac Sierra, but double check before unzipping/installing that all residual phonegap files are removed.
**After i ran uninstall, i deleted the remaining phonegap files found in C://....programs/adobe/phonegap**,

Make sure postInstall is ran *before* phonegap. 

Try installing on a usb stick (run postInstall first here aswell)

A few of us here all have it on USB now :)

**Comment by surajpindoria** [comment]
Hey @erhanyasar,

Do you have node/npm installed globally? And if not, can you try installing it and seeing if that solves your problem.

**Comment by erhanyasar** [comment]
I have node/npm latest and I even tried to reinstall cordova incase, not worked yet @surajpindoria.

**Comment by surajpindoria** [comment]
Ok, still investigating this. Some users on Windows were seeing that same error and it was due to an issue with the bundled `npm` module not being recognized. I thought maybe it could be the same thing for you.

**Comment by erhanyasar** [comment]
Situation Update:

I updated all outdated npm files either with "npm update" after your thoughts on npm and installed "uuid" globally which cordova require because of deprecated "node-uuid" yet still the same @surajpindoria.

**Comment by erhanyasar** [comment]
I formatted Mac completely and installed Sierra again. It's now working @surajpindoria

**Comment by surajpindoria** [comment]
Awesome! Glad you got it working @erhanyasar although that isn't the best solution for everyone haha. Will continue investigating on our end, it is tough without being able to reproduce the issue ourselves.

**Comment by erhanyasar** [comment]
Anyway many thanks even they weren't working :D . Take it easy and good luck with that @surajpindoria

**Comment by erhanyasar** [comment]
Hello again @surajpindoria (: I just didn't installed much to my older Mac (which I formatted) since I ordered new one but from a few of app I installed, I'm suspicious about Creative Cloud make it not working. It's not working again with the same errors I got after a few times I tried. I just installed a couple of npm packs and it was all ok till downloading that suit I guess. I'm not gonna delete it right now because some of my works but you may give it a try.

**Comment by erhanyasar** [comment]
Deleting creative cloud not working, I have just installed weinre debugger besides that. And just a couple of apps, IDE, browser, ftp/svn/server.

**Comment by erhanyasar** [comment]
Well, I'm happy with your newer update today morning released PhoneGap 2. FYI I tried to install it with upcoming pop up but it failed even if I tried 3 times. Then I deleted the desktop app and even uninstalled from the CLI. Hence after all, it creates the same mistakes "Project create failed with code 1" @surajpindoria :(

**Comment by erhanyasar** [comment]
Closing this issue since new update released #746[https://github.com/phonegap/phonegap-app-desktop/issues/746](url)

**Comment by surajpindoria** [comment]
Hi @erhanyasar,

I am actually going to reopen this issue and close the new one that you created. This issue has more responses with possible solutions and could be more helpful to others with this same issue.

**Comment by furmanali8nxb** [comment]
Facing same issue on macOS Sierra. "Project create failed with code 1". No error log :( even installed latest node.

**Comment by surajpindoria** [comment]
Hi @fani8nb,

We are aware of the issue and are currently investigated build 0.4.2. Most people were having success with version 0.4.1 if you want to give that a try.

**Comment by erhanyasar** [comment]
@surajpindoria FYI, I just tried my brand New Mac with Sierra OS either resulting the same.

**Comment by erhanyasar** [comment]
I tried to update with the pop-up of desktop app and it again failed to update itself. Hence, I deleted the old one and surprisingly the 0.4.3 is working with first a few trials @surajpindoria.

**Comment by surajpindoria** [comment]
Nice, glad to hear it is finally working for you @erhanyasar! I will look into the autoupdate flow.

**Comment by hermwong** [comment]
Was there any type of error message when the update failed through the auto-update?

**Comment by erhanyasar** [comment]
@hermwong no, it just shows reloading the update process hence nothing happens even if I wait for long minutes. It was the same when I tried to upgrade 0.4.2

**Comment by erhanyasar** [comment]
Hence there is still a bit minor problem. If you try to recreate a project in the exact same folder with the same name, it gives the above error again. Instead I delete the latest document on the path and then create new one O.o @hermwong @surajpindoria

**Comment by sseowhui** [comment]
Hi there, 

Having the same problem here.

I am using macOS Sierra v10.12.1, nodejs v7.4.0 and PhoneGap desktop (v0.4.3).
Besides that, I am working behind a proxy. Will that be an issue too? How can I configure the proxy in PhoneGap desktop?

Thanks.

**Comment by surajpindoria** [comment]
Hi @sseowhui,

Being behind the proxy may be what is causing you some problems. Can you try running the desktop app with the proxy disabled? We currently do not support a way to configure proxy use in the app itself.

**Comment by sseowhui** [comment]
Hi @surajpindoria,

I tried running without the proxy (the network will be disabled at the same time), but failed the same way. Any other alternative?

Thanks anyway.

**Comment by surajpindoria** [comment]
Hey @sseowhui,

If you are trying to create a new project you will need access to the network as the template project will need to be downloaded.

If you are just having problems getting your device to connect once you have started to serve a project. Take a look at this [doc](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/) page that contains some troubleshooting ideas. Specifically the last section titled `PhoneGap Developer App is unable to download from the server`

**Comment by ktecho** [comment]
I'm having this problem in Windows 10 with recently downloaded PG v0.4.3.

I'm not behind a proxy. I've uninstalled PG and all versions of nodejs installed. Then I reinstalled it, run (just in case) postInstall.bat as Admin and then started PhoneGap. It doesn't work.

**Comment by surajpindoria** [comment]
We have just released version 0.4.4 of the app and it should display a more helpful error message than just error code 1. If you could please try that out and let me know if it returns something else.

**Comment by erhanyasar** [comment]
Well, I think you already know and it may not be a first prioritized issue but whenever I try to open an existing project (either plugins or platforms installed) it fails since the first versions and still same like the screenshot below @surajpindoria.

<img width="452" alt="ekran resmi 2017-05-04 10 36 37" src="https://cloud.githubusercontent.com/assets/11460444/25694237/59a14cf2-30b6-11e7-8fde-73cedb86581b.png">

**Comment by erhanyasar** [comment]
I tried a couple of times and I couldn't make some of my projects work. Eventhough some of the projects work flawless, I got some works PhoneGap starts but not able to show in the browser that can't help me identify what's wrong.

<img width="675" alt="ekran resmi 2017-05-05 14 27 10" src="https://cloud.githubusercontent.com/assets/11460444/25743839/27e993ce-319f-11e7-995d-82f52415a8e4.png">
