### ISSUE TITLE
postInstall.bat should check PG-CLI version before installing

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#727]
When the user installs the PG Desktop for Windows, they are required to run `postInstall.bat` to install the PG-CLI dependency.

Currently `postInstall.bat` will always download and install the PG-CLI.

We should consider modifying the `postInstall.bat` script so that it checks to see if PG-CLI is already installed and also checks to see if a newer version of PG-CLI is available.

If PG-CLI is already installed and a newer version of PG-CLI is not available, we shouldn't force a re-install of the PG-CLI.

If PG-CLI is already installed and a newer version of PG-CLI is available, we should install the new version.

**Comment by surajpindoria** [comment]
> If PG-CLI is already installed and a newer version of PG-CLI is available, we should install the new version.

Not necessarily just a new version, but if the pinned version is newer than the current right?

**Comment by hermwong** [comment]
Yes, we don't necessarily need the latest version, just the newest pinned version.

**Comment by surajpindoria** [comment]
Just rethinking on this one, with the current implementation I am not sure we can do this. When we run `postInstall.bat`, it will install phonegap-cli to `<project-root>/resources/app.asar.unpacked/`. So when we update it will most likely overwrite the root folder and therefore the previously installed cli. We could look into moving the cli install location to the same folder we use for npm, `C:/ProgramData/Adobe/PhoneGap/`. Then we could implement this.
