### ISSUE TITLE
Add "Loading Browser Platform.." message/indicator on first server start

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-app-desktop#730]
On first run of a project within the desktop app, there is the possibility that the browser platform will need to load/be added, which could take upwards of 20 to 30 seconds on a fast connection.

As such, we need to display a message and indicator that the browser platform is being added. Users likely will not know what the browser platform is, but rather will understand it more as the ability/inability to view the project in a browser.

To confirm: Can we use a determinate progress indicator, showing the % installed?

**Comment by surajpindoria** [comment]
Double checked about the determinate indicator, unfortunately there is no way to get this info.

**Comment by jahoni** [comment]
no worries - thanks for confirming. we'll use an indeterminate indicator.
