### ISSUE TITLE
"Report Issue" option in PhoneGap Desktop doesn't work

### ISSUE THREAD

**Issue by JohnathanVegan** [phonegap/phonegap-app-desktop#733]
## _System Configuration_
Windows 8.1

### PhoneGap Desktop version
Latest, v0.4.1, brand new first time install.

### Expected Behaviour
A web page or dialog window would open so I can report an issue.

### Actual Behaviour
Nothing happens.

### Steps to Reproduce
Click on "Help" -> "Report Issue" from the menu.

**Comment by surajpindoria** [comment]
Hi @JohnathanVegan,

I can confirm that this is an issue on both Mac and Windows. Thanks for bringing this to our attention, we will make sure to get this included in the next release.
