### ISSUE TITLE
PhoneGap installer doesn't install NodeJS, causes error "project create failed with code 1"

### ISSUE THREAD

**Issue by JohnathanVegan** [phonegap/phonegap-app-desktop#734]
## _System Configuration_
Windows 8.1 (but I've seen reports of the same issue on Mac OS as well)

### PhoneGap Desktop version
Latest v0.4.1 brand new fresh install.

### Expected Behaviour
PhoneGap Desktop should be fully functional after using installer to install it.

### Actual Behaviour
When attempting to create your first project, the error "Project create failed with code 1" appears.

### Steps to Reproduce 
Install PhoneGap Desktop on a clean install of Windows 8.1 (a computer that has never had NodeJS installed before).

#### Error messages
Project create failed with code 1

**TEMPORARY FIX:** If you are experiencing this issue, install NodeJS from https://nodejs.org/en/download/ . This appears to fix the problem.

**Comment by surajpindoria** [comment]
Hi @JohnathanVegan,

Are you using the installer or zip archive to download the app? Both come with a node binary bundled into the app but if you used the zip there is an additional step to required for the app to work.

**Comment by JohnathanVegan** [comment]
I used the windows installer.

**Comment by kerrishotts** [comment]
I can report the same issue on my new Win10 tablet. The issue seems to lie in fetching the template, since when I run 

    node ..\node_modules\phonegap\bin\phonegap.js create d:\kerri\documents\phonegap\test com.example.test test

I get the following error message:

    Error: Uncaught, unspecified "error" event. (  Error from Cordova Fetch: Error: cmd: Command failed with exit code 1 Error output: 
    "C:\Program Files\Adobe\PhoneGap\PhoneGap Desktop\resources\app.asar.unpacked\bin\npm" is not recognized as an internal or external command, operable program or batch file.)

Now, there _is_ an `npm` file in the directory, but it's a *nix shell script, which is not going to any good on a Windows machine. If I create an `npm.bat` file in that location that looks like this:

    "%~dp0\node.exe" "%~dp0\..\node_modules\npm\bin\npm-cli.js" %*

everything works as it should. (Note: the above is a quick & dirty patch; I have no idea where or how that might break! I haven't done batch scripting in EONS.)

Hopefully that helps some.

**Comment by surajpindoria** [comment]
Thanks for the debugging @kerrishotts!

While I did test that npm command, I seem to have overlooked the case where nodejs/npm are not installed globally and that seems to be what is causing this issue. Will add this in for the next release.

**Comment by kerrishotts** [comment]
np; glad I could help! :-)

I usually have nodejs/npm installed globally as well, so normally I wouldn't run into this issue. But I had just picked up a cheap Win10 tablet so I could answer questions on that side of the house, and it has next to nothing installed on it -- certainly not nodejs/npm yet.

**Comment by AIMMOTH** [comment]
When is next release?

**Comment by surajpindoria** [comment]
We are still finishing off a couple of remaining issues, but are hoping to get it done within the next week and a half.

**Comment by AIMMOTH** [comment]
Is there a way to manually repair this?

**Comment by cireweb** [comment]
@kerrishotts, can you provide more detail for your solution? Did you add that line of code somewhere in the existing npm.bat or replace a pre-existing line? THANKS!

**Comment by kerrishotts** [comment]
@cireweb: There is no npm.bat file in C:\Program Files\Adobe\PhoneGap\PhoneGap Desktop\resources\app.asar.unpacked\bin\, which was the problem for me. I just created a new npm.bat with the line of code in my comment. You will need elevated privileges to save a file at that location, BTW.

**Comment by surajpindoria** [comment]
I have added an `npm.bat` file that points to the version of npm we install on Windows. I am closing this issue but will comment back once we release the next version. It is currently looking like we will be able to release early next week!

**Comment by ayez1389** [comment]
I just faced the same problem. I installed node.js and it worked for me.

**Comment by kgskgskgs** [comment]
@kerrishotts Thanks a lot! Very helpful!

**Comment by edison-hearst** [comment]
Seems like if you have a different version of node/npm installed on your computer, it will conflict.

I did this to fix the issue:
```
$ cd /Applications/PhoneGap.app/Contents/Resources/app/bin
$ sudo mv node was_node && sudo mv npm was_npm
$ sudo ln -s /usr/local/bin/node node && sudo ln -s /usr/local/bin/npm npm
$ cd ..
$ npm install
```

Ofcourse I did this to get the paths of node and npm from my mac:
```
$ which node
/usr/local/bin/node
$ which npm
/usr/local/bin/npm
```

I'm also using `n` to toggle between node versions, but I'm on the latests:
```
$ sudo n stable
```

**Comment by sharatdotinfo** [comment]
@edison-hearst This worked for me. Thanks!

**Comment by madhurivaidya** [comment]
@edison-hearst I tried the above mentioned but I am still getting the error **'Project create failed with code 1'**. When I type `npm install` it gives below message.
```
npm WARN PhoneGap@0.4.2 No description
npm WARN PhoneGap@0.4.2 No repository field.
npm WARN PhoneGap@0.4.2 No license field.
```

My version of node is v7.2.1 and npm is 3.10.9

Please suggest.

**Comment by chrisgriffith** [comment]
Those warnings can safely be ignored.

**Comment by ShahamFadakar** [comment]
@edison-hearst  Thanks

**Comment by sbeka** [comment]
@edison-hearst Thanks man!

**Comment by maplethorpej** [comment]
@edison-hearst I was pessimistic but that worked!! Thanks

**Comment by hubertfigas** [comment]
@edison-hearst Thanks!!!

**Comment by ricardomasao** [comment]
Same as @madhurivaidya ... Still getting error when create a new project
