### ISSUE TITLE
Update "Port in use" error message styling

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-app-desktop#735]
Currently, the error message shown is

1. Not human readable/friendly
2. Doesn't stand out a tonne

<img width="446" alt="screen shot 2016-11-17 at 11 45 40 am" src="https://cloud.githubusercontent.com/assets/178345/20449817/9126eb3a-ada0-11e6-90c4-5fe7573b6737.png">

Let's fix it, so that it is both more visible and more helpful.

**Comment by jahoni** [comment]
Alright alright.

So, here's a mock-up of a styling/wording for the error.

![desktop-app_0021_apps-server-error](https://cloud.githubusercontent.com/assets/178345/20450247/c7238de4-ada3-11e6-87ee-9719261f1792.png)

Where there is also a link to "Help". Suggestion is that link takes user to http://docs.phonegap.com/references/desktop-app/troubleshoot-faq/ where a new section will help 'em out with common server issues.

**Comment by filmaj** [comment]
What do you think about specifying what port is in use in the error case? In the original, unstyled, obtuse error, at least the "3000" gave me a hint as to wtf was going on.

Does it matter that this relates to the "Port" section of the desktop app preferences at all? Like, does it make sense to, say, link to the preferences in the error somehow? "Click here to change the port desktop app will use" or something. Long and wordy - probably bad.

Just thinking out loud 🤔

**Comment by jahoni** [comment]
Adding the port # to the error could be cool, if it is helpful. 

I'd say that the help documentation should cover where to change the port (settings). 
It should also cover the potential that a firewall is causing the issue.

**Comment by jahoni** [comment]
Updated mock-up, to include port number:

![desktop-app_0021_apps-server-error](https://cloud.githubusercontent.com/assets/178345/20450704/51275c48-ada7-11e6-9e1e-72e4fcc33b09.png)

**Comment by filmaj** [comment]
Makes sense, looks good!

**Comment by hermwong** [comment]
Handle EADDRINUSE (port in use) error.

<img width="458" alt="screen shot 2017-01-26 at 12 43 25 pm" src="https://cloud.githubusercontent.com/assets/107754/22349588/1e96f186-e3c5-11e6-93ed-45acc3497187.png">

Also handle the EACCES (permission denied) error

<img width="453" alt="screen shot 2017-01-26 at 12 42 50 pm" src="https://cloud.githubusercontent.com/assets/107754/22349614/3a6889e2-e3c5-11e6-8f09-ddb106a7f881.png">

The HELP hyperlink takes them to the [Desktop App FAQ](http://docs.phonegap.com/references/desktop-app/troubleshoot-faq/) on PhoneGap Docs.

@jahoni, do we need a hover color on the the HELP hyperlink when the user performs a mouseover on it?

**Comment by jahoni** [comment]
hey @hermwong -- looks good. no need for a hover state on the link, the underline should be enough.
