### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by 7egments** [phonegap/phonegap-app-desktop#738]
Today i downloaded the Phonegap Windows App from: http://phonegap.com/getstarted/ and Kaspersky detected an Virus inside: 

> UDS:DangerousObject.Multi.Generic

**PhoneGapSetup-win32.exe**

Who can i trust now?

King Regards, Ben

**Comment by surajpindoria** [comment]
Hi @7egments,

Someone else has reported the same issue already. I just haven't had a chance to look into this further. We are running some post install scripts and I am betting that's what is getting flagged by Kaspersky. I am hoping to have this resolved in time for the next release.

Closing this as it is a duplicate. https://github.com/phonegap/phonegap-app-desktop/issues/732
