### ISSUE TITLE
Template list scrollbar styling

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-app-desktop#742]
The template list scrollbar isn't noticeable enough and needs to be styled to stand out better.

**Comment by hermwong** [comment]
<img width="451" alt="screen shot 2017-01-09 at 1 42 24 pm" src="https://cloud.githubusercontent.com/assets/107754/21784692/8cf8e686-d671-11e6-9f84-2d08d889445a.png">

Scroll bar is much more visible.
