### ISSUE TITLE
Phonegap white display on project file save, auto update problem.

### ISSUE THREAD

**Issue by Devleaf-IT** [phonegap/phonegap-app-desktop#748]
## _System Configuration_
i5 6600, ASUS GTX 1060, 16gb RAM, 1tb SSHD, 128gb SSD, 1tb HDD
### PhoneGap Desktop version
0.4.2 (also persistant on any version > 0.3.5)
### PhoneGap Mobile App version
1.7.6
### Mobile devices & Mobile OS version
iPhone 7 Plus 32gb on iOS 10.2
### Computer OS version
Windows 10
### Network Type (home/corporate)
Home
### Is your network using a proxy?
No
### Computer / Network security (firewall / anti-virus / disk encryption)
Avast Anti-Virus.
### Are you using VMs on your computer?
No
### Do you have multiple network adapters (or virtual network adapters)?
No
### Are you using VPN?
No
### Expected Behaviour
Application Continues to display as per norm
### Actual Behaviour
White Screen is seen. Stopping everything from working (even connecting through app)
### Steps to Reproduce 
Launch the Desktop app on any version >0.3.5
#### Error messages
None

Further information/Photo

[EDIT] I have noticed that the error occurs when saving a file that is within the app documents. It appears the live update doesn't work.

![capture](https://cloud.githubusercontent.com/assets/23149108/21119669/84915fc6-c0bb-11e6-8fd1-53c4897dbcb6.PNG)

Other attempts to fix.
Changed graphics card (AMD Radeon R9 290 -> Nvidia 1060)
Reinstalled windows 10
Removed phonegap desktop from PC (uninstall)
Deleted folder: %appdata%/phonegap
Deleted folder: C:\Users\<USERNAME>\.cordova
Deleted folder: C:\Program Files(x86)\Phonegap Desktop
Deleted folder: C:\Users\<USERNAME>\.Settings

All have not worked.

Other issuses (rather than opening new post):
Error Code 1 when creating new project (Reproduce by creating new project) 
Chrome Developer tools launches when opening phonegap desktop (Reproduce by opening phonegap desktop)

**Comment by surajpindoria** [comment]
Hi @Devleaf-IT,

Which version of the Desktop App did you install that displays the Chrome Dev tools, the .exe or .zip?

**Comment by Devleaf-IT** [comment]
@surajpindoria I was using the 0.4.2 exe file. Although the dev tools were only persistent on 0.4.2, not < 0.4.1

**Comment by surajpindoria** [comment]
Thanks! I can confirm the dev tools on 0.4.2 using both exe and zip, this is a separate issue to yours but still something that needs to be fixed.

Can you try launching the app with your anti-virus disabled?

**Comment by Devleaf-IT** [comment]
@surajpindoria Thanks for checking, it's nice to know it's not just my PC.

I currently don't have access to my windows PC at the moment, but will test and feedback results when I get home later with anti-virus disabled. 

Thanks.

**Comment by Devleaf-IT** [comment]
@surajpindoria Hi Suraj,
Just got home now and disabled anti-virus then tried again. Same problem however, it seems like it's not anti-virus that is the problem.

Thanks for your support.

**Comment by windsurfer** [comment]
Any work arounds? Any extra information that could help fix this?

**Comment by surajpindoria** [comment]
Unfortunately we haven't been able to make any progress on this. We still can't reproduce this issue on our systems so it has made debugging very difficult. We will continue investigating though.

**Comment by brian-codes-stuff** [comment]
Any traction on this. I am having the same issue.  Everything was working as it should and today I am now having the issue described above.

**Comment by surajpindoria** [comment]
Sorry @brian-codes-stuff,

We have not been able to resolve this issue yet. At this time we are just trying to get as much info as we can so that we can hopefully understand what is going on. If you could answer the following questions it would definitely help us out.

1. PhoneGap Desktop version / PhoneGap CLI version
1. PhoneGap Mobile App version
1. Mobile devices & Mobile OS version
1. Computer OS version
1. network type (home/corporate)
1. is your network using a proxy?
1. computer / network security (firewall / anti-virus / disk encryption)
1. are you using VMs on your computer?
1. do you have multiple network adapters (or virtual network adapters)
1. are you using VPN?

**Comment by rafleo** [comment]
I have the same problem. The PhoneGap Desktop app just becomes blank when I change & save any project file.

1) PhoneGap Desktop v0.4.5
2) 1.7.10
3) Sony Xperia M2 (D2303), Android 5.1.1
4) Windows 10 Pro 64bit (Version 1703)
5) home
6) no
7) none
8) no
9) no
10) no

In the developer console for PhoneGap Desktop I get the error `Failed to load resource: net::ERR_CONNECTION_REFUSED` for the **livereload.js** upon startup.

When I edit and save the index.html, for example, I get the white screen, and the developer console reads:
![errors](https://user-images.githubusercontent.com/3229505/29065633-0099a5f6-7c2d-11e7-927d-8faf2fc5e4dd.png)

**Comment by surajpindoria** [comment]
Hi @rafleo,

You can ignore the log about `livereload.js`, we just use that for our own testing purposes and it does not effect the app. But from the other logs it seems like there is a problem inside the browser platform folder. Can you manually delete this folder, `<project>/platforms/browser`, and then restart the desktop app.

**Comment by brian-codes-stuff** [comment]
I just tried deleting the browser folder, restarted the desktop app and still getting the blank screen on any file save.

**Comment by rafleo** [comment]
Hi @surajpindoria,
Unfortunately, it doesn't help me either - same problem, same log.

Interesting fact: I can work on the project just fine using the CLI, with no errors coming up.

**Comment by surajpindoria** [comment]
Dang, I was hoping that would do the trick. If you are ok using the CLI I would recommend doing so. We had to use some workarounds in order to get it work with the desktop app and that is the reason for some of these issues people are seeing.

**Comment by surajpindoria** [comment]
When you run the application, could you try right-clicking and then "Run as Administrator". Maybe there are some weird permissions issues going on in the background.

**Comment by rafleo** [comment]
Just tried: running the program with administrator rights doesn't help either.

I'm fine using the CLI, but am happy to assist in any way to the bottom of this issue. Maybe it would help you guys to fiddle around with it in a Remote Desktop session?
