### ISSUE TITLE
Roll back CLI version 

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/phonegap-app-desktop#752]
Found some issues with the latest CLI 6.4.2 that are effecting the desktop app. Specifically around `cordova-fetch` and the `dependency-ls` module. Plan is to roll back for now and take a look at the issue in the new year.

https://github.com/stevengill/dependency-ls/blob/master/index.js#L28

**Comment by hermwong** [comment]
Tested this on OSX (Sierra) and Win 10. I was able to create projects successfully with instances of the PG-Desktop that were launched via double clicking on the PG-Desktop icon.

**Comment by hermwong** [comment]
Also verified that the CLI rollback works on OSX when using the DMG installer. Will verify Win EXE installer next.

**Comment by hermwong** [comment]
Verified that the PG-Desktop installed from the Win EXE installer is able to create projects without any error.
