### ISSUE TITLE
stuck on loading :(

### ISSUE THREAD

**Issue by hasanreza** [phonegap/phonegap-app-desktop#756]

**Comment by c006** [comment]
PhoneGap Desktop Beta 0.4.2 

Windows 8 x64 (24GB RAM)
System updates, current

Home (Verizon Fiber 75MB/75MB)

No Proxy

Windows Firewall, exception added

No VM

Single Network Adapter

No VPN

Application shows loading spinner
Application is unresponsive

Double click PhoneGap.exe icon to reproduce
