### ISSUE TITLE
Can't create project in PhoneGap, servers are offline, nothing connects.

### ISSUE THREAD

**Issue by HaginCodes** [phonegap/phonegap-app-desktop#757]

**Comment by hermwong** [comment]
We're having issues with 0.4.2 of the PhoneGap Desktop. Can you try using [0.4.1](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.4.1) for the time being.

**Comment by hermwong** [comment]
We've released [0.4.3](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.4.3) which should resolve the issue of not being able to create a project.

**Comment by HaginCodes** [comment]
thanks  I will try it out :)
