### ISSUE TITLE
Cannot download via DAP

### ISSUE THREAD

**Issue by codegreenie** [phonegap/phonegap-app-desktop#762]
## _System Configuration_
Whenever i try downloading the phonegap desktop app via Download Accelerator Plus, it starts asking me for Amazon's Username and Password

**Comment by surajpindoria** [comment]
Hi @codegreenie,

Can you try installing the app directly from the GitHub download link. I am not sure what DAP is doing behind the scenes but it may be messing things up.

https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.4.3

**Comment by hermwong** [comment]
Have you tried downloading the PhoneGap Desktop App without using Download Accelerator Plus?

**Comment by codegreenie** [comment]
I have used Internet Download Manager. Thanks a lot!

-----Original Message-----

**Comment by surajpindoria** [comment]
Ok great, glad you got it to work!
