### ISSUE TITLE
Build Desktop on Windows

### ISSUE THREAD

**Issue by subediramji** [phonegap/phonegap-app-desktop#764]
Is this possible to build for windows os 64bit
if yes how to build this any body know help me

**Comment by surajpindoria** [comment]
Hi @subediramji,

Currently we only support 32 bit builds of the desktop app on Windows. While there are 64 bit versions of both Electron and Node, this would require some adjustments in multiple locations throughout the build process. We have also not tested this so while I don't foresee any issues, I cannot be certain.

**Comment by ramjisubedi** [comment]
ok can you teach me how to do for 32bit or any guide for this @surajpindoria

**Comment by surajpindoria** [comment]
Hi @subediramji,

I have just updated the README in a new release branch for now. Once we publish the release, it will make it's way to the main GitHub page. But in the meantime, here is the link to the instructions.

https://github.com/phonegap/phonegap-app-desktop/tree/v0.4.4#build-setup-for-windows

**Comment by surajpindoria** [comment]
Going to close this as it seems to be resolved.
