### ISSUE TITLE
how to resolve --> project failed code 1 error please?

### ISSUE THREAD

**Issue by ajith555** [phonegap/phonegap-app-desktop#765]

**Comment by ajith555** [comment]
? anyone pls

**Comment by hermwong** [comment]
Could you provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?

**Comment by acidjazz** [comment]
i get this error no matter what character i put in any field, i am unable to create a project in phonegap

1. latest, 0.4.3
2. only installed the desktop version
3. havent gotten that far
5. internet, no proxy, no firewall/etc, no VM's, 1 adapter, no VPN

macOS Sierra 10.12.3
node v7.1.0
phonegap v0.4.3

![image](https://cloud.githubusercontent.com/assets/967369/23869369/f6c7ad50-07df-11e7-8da2-8989113d6d27.png)

![image](https://cloud.githubusercontent.com/assets/967369/23869381/fd80ec6a-07df-11e7-9452-413f0c0b0519.png)

**Comment by surajpindoria** [comment]
@acidjazz We have just released version 0.4.4 that should provide you with a more helpful error message. If you are still seeing this please try that version.
