### ISSUE TITLE
Can't preview app on Phonegap Developer App

### ISSUE THREAD

**Issue by renanzaum** [phonegap/phonegap-app-desktop#771]
So I'm developing an hybrid app using Phonegap and Ionic framework (and AngularJS). For some reason It works fine on the browser but when I test using Phonegap Developer App it just simply shows the header and a blank white screen. I am confused, if that would work or i just have to rewrite te code using a different framework.

Thanks a lot guys!

**Comment by surajpindoria** [comment]
Hi @renanzaum,

I currently don't know of any issues with Ionic/Angular and the developer app. If you could provide us with the following information from the issue template, we can better assist you with this.

https://github.com/phonegap/phonegap-app-desktop/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by chrisgriffith** [comment]
By the header, you mean the status bar? How are you generating the Ionic build that is being passed to the PG Developer App? 

Since you are working with Ionic, why not use Ionic View instead?

**Comment by renanzaum** [comment]
Hi @surajpindoria 

## _System Configuration_

### PhoneGap Desktop version
(v0.4.3)

### PhoneGap Mobile App version
1.7.6

### Mobile devices & Mobile OS version
iPad 2 16GB

### Computer OS version
Windows 8.1 64 bits

### Network Type (home/corporate)
Corporate

### Is your network using a proxy?
No

### Computer / Network security (firewall / anti-virus / disk encryption)
BitDefender EndPoint

### Are you using VMs on your computer?
No

### Do you have multiple network adapters (or virtual network adapters)?
No

### Are you using VPN?
Yes

### Expected Behaviour

### Actual Behaviour

### Steps to Reproduce 

#### Error messages

**Comment by renanzaum** [comment]
@chrisgriffith I'm using ionic view, the only thing displayed by the Developer app is whats inside 
`<div class="bar bar-header bar-positive" > </div>`

**Comment by chrisgriffith** [comment]
Nothing in the console log? Again how are you building the ionic app? What command are you using? Also what version of Ionic?

A code exception is being thrown, hence why the app is failing. You need to capture that exception and resolve it. If the remote debugging is not catching it, then after you have attached to the app, you can reload the app in the developer console and should see the issue.

**Comment by renanzaum** [comment]
Hi @chrisgriffith  sorry for the delay,

So I've been trying to follow the best as i can the tutorial on https://ionicframework.com/docs/guide/building.html. I'm using the version 1.4.3 of ionic, should I move to Ionic 2? I'm not very good at Javascript though.

What the console log says about any error is relate to the following: 

`Persistent fs quota granted
 Error: exec proxy not found for :: StatusBar :: _ready
 Error: exec proxy not found for :: LocalNotification :: `

I'm not really sure how to fix it. I've tried to test the app on the mobile version of the browser which works fine and makes me more confused.

**Comment by BHunter2889** [comment]
I'm getting the same above error `Error: exec proxy not found for :: StatusBar :: _ready` 
However, the rest of my app displays appropriately. Has anyone figured this out yet?

**Comment by surajpindoria** [comment]
This error only displays on the desktop browser because there is no implementation for the statusbar plugin. It can be safely ignored.

**Comment by BHunter2889** [comment]
I should add that StatusBar doesn't work appropriately on the developer app. It doesn't overlay the actual content, and if I use framework7 statusbar div class, it renders a separate statusbar immediatley below the actual status bar... which is why I thought the error I was seeing may mean something.
