### ISSUE TITLE
Unable to connect with ios device through mobile app (iphone 5 - ios 10.2.1)

### ISSUE THREAD

**Issue by Kaysernayem** [phonegap/phonegap-app-desktop#773]

**Comment by surajpindoria** [comment]
Hi @Kaysernayem,

Here are some things I would try based on the information your provided.

1. Check that your corporate network allows peer-to-peer connections. If it doesn't, then you won't be able to connect to the mobile app.
1. Try disabling your computers firewall, sometimes this blocks the mobile app.
1. If you are seeing multiple IP addresses in the desktop app, try using one of the others and see if that works.

**Comment by Berdic** [comment]
I've got the same problem.

I've created the "HelloWorld" template and then tried to start it on iPhone6 16GB and on my iPad4. It did not work. It starts, downloading and after a while "Error" message pops up saying it could not download it from server.

I've followed steps described under section "PhoneGap Developer App is unable to download from the server" on this [link ](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/) and it did not help me solve the problem.:

**Comment by surajpindoria** [comment]
@Berdic Could you provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
1. PhoneGap Mobile App version
1. Mobile devices & Mobile OS version
1. Computer OS version
1. network type (home/corporate)
1. is your network using a proxy?
1. computer / network security (firewall / anti-virus / disk encryption)
1. are you using VMs on your computer?
1. do you have multiple network adapters (or virtual network adapters)
1. are you using VPN?
