### ISSUE TITLE
Desktop app won't open

### ISSUE THREAD

**Issue by refo** [phonegap/phonegap-app-desktop#774]
### PhoneGap Desktop version
VERSION 0.4.3 (BETA)

### PhoneGap Mobile App version
1.7.6

### Mobile devices & Mobile OS version
iPhone 6 - iOS 10.2 (14C92)

### Computer OS version
OS X 10.11.6

### Network Type (home/corporate)
corporate

### Is your network using a proxy?
no

### Computer / Network security (firewall / anti-virus / disk encryption)
no

### Are you using VMs on your computer?
yes

### Do you have multiple network adapters (or virtual network adapters)?
yes

### Are you using VPN?
no

### Expected Behaviour
Desktop app to open

### Actual Behaviour
Desktop app won't open

### Steps to Reproduce 
Double-click on app icon

#### Error messages
"PhoneGap" is damaged and can't be opened. You should move it to the Trash.

![screen shot 2017-02-17 at 11 24 58](https://cloud.githubusercontent.com/assets/1114116/23058195/e153f89a-f504-11e6-8bc7-5cf9606ce46e.png)

**Comment by hermwong** [comment]
See [here](https://support.apple.com/en-us/HT202491) for more details. Basically you need to update your OSX security settings to allow apps to be installed from anywhere.

**Comment by refo** [comment]
Well, i did right-click open the app to intentionally pass unidentified developer warning. I don't think i want to disable gatekeeper altogether. Maybe try again after the app released. Thanks.
