### ISSUE TITLE
cant not download https://github.com/phonegap/phonegap-app-desktop/releases/download/0.4.3/PhoneGapDesktop.dmg from china

### ISSUE THREAD

**Issue by leeboo** [phonegap/phonegap-app-desktop#775]
hello guys, i can not download from https://github-cloud.s3.amazonaws.com/releases/14698686/b5227b4a-d671-11e6-9e54-2c7d15870ba9.dmg,
in china, have a another way?

**Comment by surajpindoria** [comment]
Hi @leeboo,

Unfortunately we don't have any other places to download the desktop app from. You could try either using a VPN to download from another location or pulling down the source code and building from there.

**Comment by surajpindoria** [comment]
Unfortunately there isn't much we can do here. I am going to close this issue off.
