### ISSUE TITLE
Error when closing activeWidget watcher with multiple projects in app

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/phonegap-app-desktop#781]
In `project-widget.js`, when we set a new active widget we first attempt to close the open watcher for the current active project. With multiple projects in the app, this will try to close the watcher before it has been set causing a runtime error.

**Comment by hermwong** [comment]
The sequence of method calls that drill down to the `setWatcher` method which tries to `global.activeWidget.watcher.close()` is as follows:

In `local-storage.js`

- `getProjects` has loop that calls `getProjectConfig`
- `getProjectConfig` -> `parseConfigForRendering` -> `removeMissingProjects`
- `removeMissingProjects` then calls `setActiveWidget` (found in `project-widget.js`)

In `project-widget.js`

- `setActiveWidget` -> `setConfigWatcher` -> `setWatcher`
