### ISSUE TITLE
can existing phonegap mobile application can be converted into windows desktop application?

### ISSUE THREAD

**Issue by sunil1293** [phonegap/phonegap-app-desktop#783]
## _Can existing PhoneGap mobile application can be converted into windows Desktop Application?_

The Application is running successfully on iOS. The same application should be executed on Windows desktops especially on Windows 7 and 8 OS.

Please provide the suggestions and solutions.

**Comment by surajpindoria** [comment]
Hi @sunil1293,

If you want to target Windows desktop platform then we recommend that you aim for Windows 10, as that supports [Microsofts UWP](https://docs.microsoft.com/en-us/windows/uwp/get-started/whats-a-uwp). For earlier versions of Windows it won't really work, 8 has some support for this, 8.1 is better but still not great.

**Comment by sunil1293** [comment]
Hi @surajpindoria,

There is a requirement to support the application on Windows 7 Desktop platform which was running on Win 10.
Is there anyway or monkey patch to achieve this?

Thanks for your support.

**Comment by surajpindoria** [comment]
Unfortunately there is no way around this. You could attempt using electron, but then you will lose access to all of the cordova APIs and would essentially be rebuilding the app.
