### ISSUE TITLE
PhoneGap Developer can't connect to PhoneGap Desktop

### ISSUE THREAD

**Issue by GitWiter** [phonegap/phonegap-app-desktop#785]
PhoneGap Desktop version	=  v04.3
PhoneGap Mobile App version	=	1.7.6 
Mobile devices & Mobile OS version	= SamSung GT-18190N & Andriod version 4.1.2
Computer OS version	=	Windows 7			
Network Type (home/corporate)	= 	home
Is your network using a proxy?	= 	no
Computer / Network security (firewall / anti-virus / disk encryption) = Windows Firewall / AVG 
Are you using VMs on your computer?  = no
Do you have multiple network adapters (or virtual network adapters)? 	= no
Are you using VPN?	= 	no	
Expected Behaviour	=  PhoneGap Developer App should pair with PhoneGap Desktop to immediately preview my app on the device 
Actual Behaviour = Unable to download archive from the server because Unable to properly connect to server

Steps to Reproduce

I created a “Hello World” project on PhoneGap Desktop and it tells me that
“Server is running on http://192.168.11111:3000”
and the server log says 
“starting app server...
listening on 192.168.1.111:3000”

I put that address into my Android  PhoneGap Developer and launched it
It replied
“CONNECTING
TAP TO CANCEL
DOWNLOADING …”
then it alternates between the last two messages for almost 3 minutes before saying
“Alert
Unable to download archive from the server.
Unable to properly connect to server”

Turned off my Firewall and AV but still have this problem.

Using the command-line, and “netstat -aon “ I see that, indeed
“TCP	[::]:3000		[::]:0			LISTENING		
and it has a PID =4500
Using Task Master, I see that PID 4500 has Image Name “PhoneGap.exe *32" and Description “Electron” but its priority is set and Low, so I changed it to “High”. But that didn't help.

Meanwhile, using Task Master, I discovered PID 2532 also has Image Name “PhoneGap.exe *32" and Description “Electron” but its priority is Normal so I left it alone.
Using the command-line, and “netstat -aon “ I get 
TCP	192.168.1.111:55053	151.101.16.133:433	ESTABLISHED 	2532
I don't know what that's all about (do you)?

I have tired different ports but still get one LISTENING (identified by PhoneGap Desktop) and another ESTABLISHED (not mentioned by PhoneGap Desktop) 

BTW, even if I turn off PhoneGap Desktop, PhoneGap Developer still tells me 
“CONNECTING
TAP TO CANCEL
DOWNLOADING …”
and takes about as long as when  PhoneGap Desktop is running, to tell me 
“Alert
Unable to download archive from the server.
Unable to properly connect to server”

Regardless, after many tries, I can't get this to work.
Any suggestions?

Cheers,

Jamie

**Comment by surajpindoria** [comment]
Hi @GitWiter,

Can you take a look at this [FAQ](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/), there are a bunch of suggestions there that may help you.

**Comment by GitWiter** [comment]
Well I feel stupid. My wifi was misbehaving. Working fined now.

**Comment by surajpindoria** [comment]
Glad you were able to get it working!

**Comment by GitWiter** [comment]
I'm glad too! And embarrased.  But I'm glad I've discovered GitHub. It's 
the kind of suppot I can use.
Best
Jamie

**Comment by shazinfosys** [comment]
maintain same internet connection
