### ISSUE TITLE
use configstore instead of localstorage for persisting desktop app data

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#786]
Phase out usage of `localStorage` and use `configstore` as the method of storing the Desktop App's data.

The main benefit of making this change is so that the Desktop App will have access to all of the data from both of Electron's processes (`renderer` and `main`).

Currently the following pieces of data are stored in `localStorage`:

- userId
- portNumber
- projects

As part of the metrics / analytics work in task #607, we have already moved `userId` and `portNumber` out of `localStorage` into `configstore`.

However we still need to look at the various use cases around adding (through create new or add existing), loading projects on app load and deleting of projects when we make the change to store project info in `configstore`.

**Comment by surajpindoria** [comment]
Did we finish this with 0.4.4 release @hermwong?

**Comment by hermwong** [comment]
We moved `userId` and `portNumber` over to the `configstore` however, we have not moved the projects over to `configstore` they're still stored in 'localStorage`.
