### ISSUE TITLE
unable to view app on android device phonegap on windows10

### ISSUE THREAD

**Issue by upendrawatwe** [phonegap/phonegap-app-desktop#790]

**Comment by upendrawatwe** [comment]
I have windows10 machine running PhoneGap for windows desktop and a Android Mobile device running the PhoneGap Mobile App.
The App that can be viewed via the emulator under Chrome on desktop cannot be viewed via the PhoneGap Mobile App .
I am not using any VPN , but I have McAfee.

**Comment by surajpindoria** [comment]
Are you seeing any error messages on the mobile app? Take a look at this [FAQ](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/), there are a bunch of suggestions that may help you.

**Comment by surajpindoria** [comment]
@upendrawatwe did you manage to get this working?=

**Comment by sanchamp** [comment]
@surajpindoria I'm facing the same problem and getting error as unable  to download server.
I followed FAQ and change the firewall setting change port and my wifi connection is also same on device and PC

**Comment by hermwong** [comment]
Are you using a network proxy?
