### ISSUE TITLE
Mysql database connection

### ISSUE THREAD

**Issue by cvaraj** [phonegap/phonegap-app-desktop#791]
Hello all,
    i'm new on Phonegap development tool, i have used Mysql  for database connect, it will work fine in desktop phonegap, but mobile phonegap not working front end works fine but database connection not working any idea to solve this

Thank you

**Comment by surajpindoria** [comment]
How are you using your MySQL database? In the mobile app we compile the app with preselected plugins, it could be the case that it doesn't exist in our app, but if you build the full app it could be fine.

**Comment by surajpindoria** [comment]
@cvaraj any update on this?
