### ISSUE TITLE
Server is Offline issue

### ISSUE THREAD

**Issue by Swapgdkr** [phonegap/phonegap-app-desktop#792]
## _System Configuration_  
Processor: Intel(R) Core(TM) i5-3210M CPU @2.50GHz 2.50GHz
RAM : 6 GB
System Type : 64 bit Operating System, x64-based processor

### PhoneGap Desktop version
PhoneGap-Desktop-Beta-0.4.3-win

### PhoneGap Mobile App version
Version 1.7.6

### Mobile devices & Mobile OS version
Asus Zenfone 2
OS Android 5.0

### Computer OS version
Windows 8.1 Single Language

### Network Type (home/corporate)
Home

### Is your network using a proxy?
No

### Computer / Network security (firewall / anti-virus / disk encryption)
Firewall

### Are you using VMs on your computer?
No

### Do you have multiple network adapters (or virtual network adapters)?
No

### Are you using VPN?
No

### Expected Behaviour
Desktop App:
Server Connected

Mobile App:
Server Connected

### Actual Behaviour
Desktop App:
Server is Offline Issue
and
'Project create failed with code 1' issue occurs when tried creating new project

Mobile App:
'Unable to download archive from the server
unable to properly connect to the server'
issue occurs when tried connecting on mobile app

### Steps to Reproduce 
Desktop App:
Step 1: Open desktop App, 'Server is Offline' message is displayed at the bottom.
Step 2: Try creating new project using existing template of ' Hello World', 'Project create failed with code 1' issue occurs

Mobile App:
Open the App and then click on 'Connect' button,'Unable to download archive from the server
unable to properly connect to the server'
issue occurs 

#### Error messages
Desktop App: 
1. 'Server is Offline' 
2. 'Project create failed with code 1'

Mobile App:
'Unable to download archive from the server
unable to properly connect to the server'
![phonegap desktop issue 1](https://cloud.githubusercontent.com/assets/28013997/25397022/71177720-2a04-11e7-98fd-704d034a588b.png)
![phonegap desktop issue 2](https://cloud.githubusercontent.com/assets/28013997/25397020/710739c8-2a04-11e7-8477-bb928694716a.png)
![phonegap mobile app issue](https://cloud.githubusercontent.com/assets/28013997/25397021/7109706c-2a04-11e7-8093-85bd69f41e87.jpg)

**Comment by surajpindoria** [comment]
Take a look at this [FAQ](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/), there are a bunch of suggestions that may help you.

We are also aiming to release a new version of the app hopefully this week that should give you more information on the 'Project create failed with code 1' error.

**Comment by edukondalu123** [comment]
TQ @surajpindoria . We will see, whether it will work or not in this upcoming new update.

**Comment by surajpindoria** [comment]
We have just released version 0.4.4 which should provide more details than just exit code 1, please try it out and let me know if gives you any useful info.

@Swapgdkr @edukondalu123

**Comment by QuasarX** [comment]
Same problem: "Server is offline"
![image](https://user-images.githubusercontent.com/13033837/41252488-f24da46c-6dc5-11e8-9293-efd427036e4b.png)
