### ISSUE TITLE
Cannot create application (hello world, blank, whatever)

### ISSUE THREAD

**Issue by Allixria** [phonegap/phonegap-app-desktop#793]
## _System Configuration_
Windows 8
### PhoneGap Desktop version
v0.0.4
### PhoneGap Mobile App version
v1.7.6
### Mobile devices & Mobile OS version
?!
### Computer OS version
?!
### Network Type (home/corporate)
home
### Is your network using a proxy?
no
### Computer / Network security (firewall / anti-virus / disk encryption)
no, yes, added phonegap to exceptions (tried them all)
### Are you using VMs on your computer?
no
### Do you have multiple network adapters (or virtual network adapters)?
yes the other is unplugged (TAP-Windows Adapter V9)
### Are you using VPN?
no
### Expected Behaviour
I would love to be able to "create" an app, even just the Hello World one.
### Actual Behaviour
I click the green create button, but nothing happens, no message, nothing.
### Steps to Reproduce 
Create new project, enter path, enter name and click the create button.
#### Error messages
none

**Comment by wgathright** [comment]
I'm having the same exact issue.

**Comment by Apareo** [comment]
Same Issue - Uninstalled and reinstalled, but no difference.
Tried Run as Administrator as well. Did not work.

**Comment by Allixria** [comment]
Tried the same too as Apareo, I obviously tried to uninstall, and reinstall...  I'll try to download a previous version of the app (if I can find), to see if it could be the current distributed version itself...

**Comment by baccarg** [comment]
Same problem here.. any solution?

**Comment by baccarg** [comment]
v0.4.4

**Comment by surajpindoria** [comment]
Just to clarify @Allixria this is with version 0.4.4? You put version 0.0.4 above. Are you using the installer or the zip file? The zip has some additional steps that need to be completed before that will work.

In the meantime I'd suggest you use 0.4.3 until we can figure out what is going on here.

**Comment by baccarg** [comment]
Im just download the installer (PhoneGapSetup-win32.exe).

**Comment by surajpindoria** [comment]
@baccarg Thanks for the info, hopefully version 0.4.3 works for you while we fix 0.4.4.

**Comment by baccarg** [comment]
@surajpindoria ok, im downloading and installing v0.4.3. Notice: Im using windows 10.
In few minutes report if work in v0.4.3...

**Comment by Allixria** [comment]
@surajpindoria Yes sorry it was late : 0.4.4 :)

Where can I find the 0.4.3 package ? Thanks !

**Comment by baccarg** [comment]
@Allixria https://github.com/phonegap/phonegap-app-desktop/releases

**Comment by Allixria** [comment]
Awesome baccarg, thanks! I'll try the previous version

**Comment by baccarg** [comment]
@surajpindoria @Allixria @Apareo @wgathright  Ok confirm, v0.4.3 works fine.

**Comment by Allixria** [comment]
@surajpindoria and others : 0.4.3 works fine for me too... 
I think the 0.4.4 is bugged somewhere.. :)
If you download the 0.4.3, make sure to uninstall the 0.4.4 version first tho! ^_~

**Comment by Apareo** [comment]
Using v0.4.3 resolved the issue.  Thanks.

**Comment by surajpindoria** [comment]
I managed to find the issue with the previous installer and have updated the releases page. Could you please try installing version 0.4.4 and let me know if that works now?

@Allixria @baccarg @Apareo @wgathright

**Comment by pascuale** [comment]
Verified.  Spent all morning trying different versions of windows.  Can you share the details of the issue you corrected.

**Comment by surajpindoria** [comment]
Well for 0.4.4 I forgot to include a new dependency that we added for this release, Mac was unaffected due to the differences in how we bundle the packaged app. But this was only affecting version 0.4.4 for Windows. Not sure about the other issues you were seeing @pascuale. As far as I know there are no other issues with previous installers.

**Comment by Apareo** [comment]
Uninstalled v0.4.3 and installed v0.4.4.
Tested and all seems good noe.
Thanks.

**Comment by baccarg** [comment]
v0.4.4 works now. Great!

**Comment by Allixria** [comment]
@baccarg Thanks for letting me know !

**Comment by surajpindoria** [comment]
This seems to be fixed now, I am going to close this off. Thanks for testing everyone!
