### ISSUE TITLE
Track analytics opt in rate

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/phonegap-app-desktop#794]
Currently we do not have a way to know if a user has opted in for analytics or not. This is helpful for us to know what percentage of our users have allowed us to receive analytics.

**Comment by hermwong** [comment]
By default when users install the Desktop App the analytics are enabled.

We should determine how we want this event to trigger.

1. when a user manually opts out
1. when a user manually opts in
1. should we also perform a 1 time tracking event when a user installs Desktop app to track the default opt in?

**Comment by surajpindoria** [comment]
Ahh ok, my understanding was that the default is analytics off. But we should fire an event when people opt in/out just so we can maintain an accurate number. That way we can get a better sense of what the analytics data actually represents.

**Comment by filmaj** [comment]
For reference, the [phonegap-cli prompts the user on first-run, and tracks the result of the prompt via analytics](https://github.com/phonegap/phonegap-cli/blob/master/lib/cli/analytics.js#L167). So on first-run, presumably the user sends _at least_ one analytics event: either `analytics-prompt accepted` or `analytics-prompt declined`.

**Comment by hermwong** [comment]
Here is the [code](https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/settings-handlers.js#L37-L45) where the Desktop App sets the analytics flag to `true` unless the user has manually opted out.

**Comment by hermwong** [comment]
I'll look at adding & testing this enhancement today.
