### ISSUE TITLE
Add menu item to open developer console

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/phonegap-app-desktop#795]
As I have begun issue gardening I am noticing a frustrating trend where more often then not we are unable to reproduce the issues being reported or we don't have enough information to dig further. If the user had the option to display the developer console this could potentially provide us with the information needed to debug and hopefully fix the issue.

What are your thoughts?
@hermwong @mwbrooks @jahoni

**Comment by jahoni** [comment]
I think if it is helpful, it certainly makes sense to do.

**Comment by surajpindoria** [comment]
Ok cool, going to add this onto the next bug fix release.

**Comment by hermwong** [comment]
We need to audit all of our `console.log` statements within the app before we enable this feature in the release.

Decide which of the current ones we want to keep and which ones to remove. We may also need to clean up the messaging on the debug messages that we decide to keep.

**Comment by surajpindoria** [comment]
Agreed, we have a lot of log statements that we do not need if we go ahead with this.

**Comment by hermwong** [comment]
We need to make sure this doesn't impact the `debugMode` flag that we use within the Desktop App.

The potential risk is that our analytics could be impacted with the wrong `_env` value.

**Comment by surajpindoria** [comment]
We need to find a way to differentiate between the "developer console", which will help to debug issues with the desktop app, and the "server log" which shows the output from the served application. Leaving this open for now.

**Comment by hermwong** [comment]
Do you think we could just label the "developer console" as the "PhoneGap Desktop Debug Info"?

**Comment by surajpindoria** [comment]
I think that will help, but most likely there will still be a little confusion. We will just need to add a note on the docs for this and be ready for some incoming questions.

**Comment by surajpindoria** [comment]
Went ahead and added a little section in the docs for the developer console. @hermwong if you can review that would be great.

https://github.com/phonegap/phonegap-docs/tree/desktop-dev-console
