### ISSUE TITLE
Cannot Create New Project after updating to 0.4.4

### ISSUE THREAD

**Issue by judson75** [phonegap/phonegap-app-desktop#799]
#### Error messages
You have been opted out of telemetry. To change this, run: cordova telemetry on.
Creating a new cordova project.
Using cordova-fetch for phonegap-template-blank@1.1.0
Error: Uncaught, unspecified "error" event. (�[1m �[31m Error from Cordova Fetch: Error: npm: Command failed with exit code 243 Error output:
npm ERR! Darwin 15.6.0
npm ERR! argv "/Applications/PhoneGap.app/Contents/Resources/app/bin/node" "/Applications/PhoneGap.app/Contents/Resources/app/node_modules/npm/bin/npm-cli.js" "install" "phonegap-template-blank@1.1.0"
npm ERR! node v6.3.1
npm ERR! npm v3.10.3
npm ERR! path /Users/jcooper/.npm/phonegap-template-blank
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/Users/jcooper/.npm/phonegap-template-blank'
npm ERR! at Error (native)
npm ERR! { Error: EACCES: permission denied, mkdir '/Users/jcooper/.npm/phonegap-template-blank'
npm ERR! at Error (native)
npm ERR! errno: -13,
npm ERR! code: 'EACCES',
npm ERR! syscall: 'mkdir',
npm ERR! path: '/Users/jcooper/.npm/phonegap-template-blank' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR! /Users/jcooper/.cordova/node_modules/npm-debug.log)

**Comment by judson75** [comment]
After updating to the latest version 5.0, I am now getting an error:

You have been opted out of telemetry. To change this, run: cordova telemetry on.
Creating a new cordova project.
Using cordova-fetch for phonegap-template-blank@1.1.0
Error: Uncaught, unspecified "error" event. ([1m [31m Error from Cordova Fetch: Error: npm: Command failed with exit code 243 Error output:
npm ERR! Darwin 15.6.0
npm ERR! argv "/Applications/PhoneGap.app/Contents/Resources/app/bin/node" "/Applications/PhoneGap.app/Contents/Resources/app/node_modules/npm/bin/npm-cli.js" "install" "phonegap-template-blank@1.1.0"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! path /Users/jcooper/.npm/phonegap-template-blank
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/Users/jcooper/.npm/phonegap-template-blank'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, mkdir '/Users/jcooper/.npm/phonegap-template-blank'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/Users/jcooper/.npm/phonegap-template-blank' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jcooper/.cordova/node_modules/npm-debug.log)

**Comment by surajpindoria** [comment]
Looks like you are running into permissions issues with your npm directory. Can you try running the command using `sudo`. To prevent these issues in the future check out this [article](https://docs.npmjs.com/getting-started/fixing-npm-permissions) that tells you how to fix the permissions.

**Comment by judson75** [comment]
I run the commands on the article, and it works running the commands from terminal, but I still cannot add a new project from the desktop application. I still have to run the line in terminal as sudo. So the question is how can I get the desktop application to work? Do I need to reinstall the Phonegapp desktop application?

**Comment by surajpindoria** [comment]
Hmm, reinstalling may help. I have never seen a report where someone needed to use sudo for the desktop app before. Does the desktop app display any errors? Or just the same one above?

**Comment by judson75** [comment]
The ones posted are from Desktop. It started after I updated the desktop app

**Comment by hermwong** [comment]
A couple of other things you could try:

1. Run the desktop app as administrator
1. Make sure you have permissions to write to `/Users/jcooper/.npm/` directory and any child directories. You can even manually set read & write permissions on the folder using finder by right clicking on the folder, selecting `Get Info` and the updating the permissions under the `Sharing & Permissions` section. You will need to enable viewing of hidden folders & files in Finder to see the `.npm` folder.

The error message seem to indicate that you don't have permissions to write in the `/Users/jcooper/.npm/`
