### ISSUE TITLE
Server is Offline & Cannot add existing project

### ISSUE THREAD

**Issue by bit-trip** [phonegap/phonegap-app-desktop#800]
## _System Configuration_

       Windows 7 64-bit
       8 GB Ram 
       AMD FX-8320E Eight-Core Processor 3.20 Ghz
       Nvidia GTX 970
    
### PhoneGap Desktop version

       Beta v0.4.4

### Computer OS version
       Windows 7 64 Bit

### Network Type (home/corporate)
        Home

### Is your network using a proxy?
        No

### Computer / Network security (firewall / anti-virus / disk encryption)

        Firewall

### Are you using VMs on your computer?
        No

### Do you have multiple network adapters (or virtual network adapters)?
        No

### Are you using VPN?
        No

### Expected Behaviour
        Desktop App:
        Server Connected
        Existing projects show up on client

### Actual Behaviour
        Desktop App:
        Server is Offline
        Existing projects do not show up on client, nor can I add it back to client.

### Steps to Reproduce 
        Steps to Reproduce

Desktop App:
        Step 1: Open desktop App, 'Server is Offline' message is displayed at the bottom. Previously displayed projects are not listed in phonegap project list.
        Step 2: Try adding your existing project, it will proceed without any error messages and the project will not be added.

#### Error messages
         No error messages were displayed throughout the process or in the client log.

![35c48134c97a0c5d40b32647d42be5bf](https://cloud.githubusercontent.com/assets/27754760/25934074/9d798966-35d0-11e7-9ab3-a080a9367cc7.png)

Error only began occuring after version update to 0.4.4 Beta if that helps.

**Comment by surajpindoria** [comment]
Hi @bit-trip,

Thanks for reporting this, I will continue to look into this.

**Comment by bit-trip** [comment]
Issue has been solved for me personally. I just loaded up the phonegap desktop client today and it's working. Thank you @surajpindoria for your hard work!

**Comment by surajpindoria** [comment]
The server is actually all local to your machine, so not sure what has changed since you filed this but glad to hear it is working!

Going to close this off.

**Comment by Rithika9** [comment]
I'm having VM and Cisco VPN in my system. Does this caus e this issue?

**Comment by bit-trip** [comment]
@Rithika9 I did not have a VPN when this issue occured and it occured again over time. To worl around this issue I began controlling my project through command prompt and mac terminal.

cordova build android
cordova run android --device

Make sure your device is plugged into computer that your building app on and enable USB debugging on your phone. Its a lot easier imo
