### ISSUE TITLE
Refused to execute inline script because it violates the following Content Security Policy directive

### ISSUE THREAD

**Issue by mulyoved** [phonegap/phonegap-app-desktop#801]
### PhoneGap Desktop version
v0.4.4

### PhoneGap Mobile App version
N/A

### Mobile devices & Mobile OS version
N/A

### Computer OS version
Windows 7

### Network Type (home/corporate)
Home

### Is your network using a proxy?
No

### Computer / Network security (firewall / anti-virus / disk encryption)
Windows default

### Are you using VMs on your computer?
Yes, Turned off

### Do you have multiple network adapters (or virtual network adapters)?
No

### Are you using VPN?
No

### Expected Behaviour
Using Desktop app to create new react hot loader app should be able to run locally

### Actual Behaviour
Browser show empty page and give errors in console

### Steps to Reproduce 
Install fresh PG desktop 
Start
Create react app
Start app
Open browser dev console to see the errors

#### Error messages
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' data: https://ssl.gstatic.com 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-v0d22+aHqfBMiCT7ynbzP6xj0P+9//Kfwt8iZGGUt1Q='), or a nonce ('nonce-...') is required to enable inline execution.
```

this is www/index.html that was generated
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no" />
    <meta name="msapplication-tap-highlight" content="no" />
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height" />
    <meta http-equiv="Content-Security-Policy" content="default-src 'self' gap:; script-src 'self' data: https://ssl.gstatic.com 'unsafe-eval'; object-src *; style-src 'self' data: 'unsafe-inline'; img-src 'self' data:; media-src 'self' data:; font-src 'self' data:; connect-src *">
    <title>React hot-loading Hello World</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript" src="./bundle.js"></script>
  </body>
</html>
```

**Comment by surajpindoria** [comment]
Hi @mulyoved,

Thanks for reporting this. I am able to reproduce the issue and will continue to look into it.

**Comment by devgeeks** [comment]
I will look into this...

**Comment by paragw09ckp** [comment]
Any break-through on this? Thanks.

**Comment by Chandrakala14** [comment]
Hi , I am also facing same issue.
Is there any solution for this ?

**Comment by satya-somayajulu** [comment]
Im Running with this issue and it is affecting my scripts plz tell me the fix!

**Comment by taltmann42** [comment]
Had the same problem and I think I found a fix for it. As the warning message suggests, inline-scripts are blocked because they violate the Content Security Policy (CSP). 

The CSP is defined in `www/index.html`: `<meta http-equiv="Content-Security-Policy" ...`.

Changing

```html
script-src * data: https://ssl.gstatic.com 'unsafe-eval';
```

in the content-string to

```html
script-src * data: https://ssl.gstatic.com 'unsafe-inline' 'unsafe-eval';
```

fixed it for me.

More info here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_inline_script

**Comment by uglycoyote** [comment]
I was also getting this on a phonegap application nearly fresh out of the box (from creating it using the CLI and the Framework7 template)

Chrome was giving 

```   
 <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *">
```

unlike @taltmann42's situation, mine already had ```unsafe-inline``` in there.

I found that just commenting out the entire ```<meta>``` line got rid of the errors.

DISCLAIMER:  I have no idea what the purpose of this line is or what the implications of removing it are.  All I know is it's a line I would not have added to ```index.html``` myself, and getting rid of it makes the error go away.

**Comment by deysayantan** [comment]
thank you taltmann42,for the solution

**Comment by hinalpithadia** [comment]
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *"> if i write this than my amchart not display.

**Comment by Ahmed-Ammar** [comment]
just remove this default-src 'self';

**Comment by pcaly626** [comment]
My problem was that my  html document was not named "index.html" that fixed my issue

**Comment by VladRud** [comment]
In .env file you can define INLINE_RUNTIME_CHUNK=false
It's works for me.
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#advanced-configuration

**Comment by abhijit-padhy** [comment]
Adding CSP in manifest.json file removes the error. It worked for my react app.
I guess missing ' , ' is the issue for your code, otherwise add the below line and then try.

    "csp": "script-src 'self' 'unsafe-inline'; object-src 'self'"

Refer below link for more details :[https://crosswalk-project.org/documentation/manifest/content_security_policy.html](url)

**Comment by qroft** [comment]
Hi everyone, i had the same problem and changed from safe to unsafe-inline.
**Now my only question is**: how unsafe is this?

I mean, what we are doing with 'safe' is that no inline scripts should be launched, what is great for security issues. But now that i have removed it, what could possibly happen?

For me at the moment this solutions sound a bit like 'just deactivate your firewall and anti-vir software to be able to visit our website" - what i feel not that good about :)

**Comment by carlosdiazchavez** [comment]
For me the solution was change this "<meta http-equiv="Content-Security-Policy" content="default-src * data: gap://ready; style-src 'self' 'unsafe-inline' *; script-src * 'unsafe-inline' 'unsafe-eval'; media-src *; connect-src *">"

**Comment by carlosdiazchavez** [comment]
for me the solution was change this <meta http-equiv="Content-Security-Policy" content="default-src * data: gap://ready; style-src 'self' 'unsafe-inline' *; script-src * 'unsafe-inline' 'unsafe-eval'; media-src *; connect-src *">

**Comment by carlosdiazchavez** [comment]
for me the solution was change `this `<meta http-equiv="Content-Security-Policy" content="default-src * data: gap://ready; style-src 'self' 'unsafe-inline' *; script-src * 'unsafe-inline' 'unsafe-eval'; media-src *; connect-src *">`

**Comment by RNMR** [comment]
it's happenning to me, and I don't get these changes y'all r suggesting

**Comment by shauryaverma4296** [comment]
It's happening the same for me, Please suggest a solution

**Comment by CheerfulCherry** [comment]
I just add directory to not existing js file and it works for me:

``<script src="main.js"></script>``

**Comment by Ahmed-Sbai** [comment]
it can be caused because of an wrong extension or name(index) of the html or other files

**Comment by hugoderre** [comment]
I had the same issue, I have a solution but it's because i was tired 
Are you ready ? My "index.html" file was not at the root directory (yea it's dumb). 1 hour lost for that lol. That's it. 
Maybe it will help you, maybe not, but good luck mates

**Comment by anzarmalik** [comment]
I am facing same issue , i tried to write different  meta tags etc , but i got stuck on the problem ... please help ...
i am using hjs templating engine and node js ...

**Comment by thomasmso** [comment]
For me, I was missing `'unsafe-inline'` from the CSP meta tag in the `default-src` directive. So I just had to update this

```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">
```

to

```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">
```

**Comment by iamtheef** [comment]
> In .env file you can define INLINE_RUNTIME_CHUNK=false
My gosh, can't thank you enough!
Any ideas what was the problem?

**Comment by iamtheef** [comment]
> In .env file you can define INLINE_RUNTIME_CHUNK=false


Can't thank you enough!
Any ideas as of what was the problem?

**Comment by DanielGoldfine** [comment]
For me, adding sha256 as the error suggests worked the best.

`<meta http-equiv="Content-Security-Policy" content="script-src 'self' https://example.com 'sha256-s0m3r@nd0msh**';">`

`<script sha256="s0m3r@nd0msh**" src="https://example.com"></script>`

**Comment by DanielGoldfine** [comment]
For me, adding sha256 as the error suggested worked the best. Just note you must provide the exact sha256 value suggested in the error, didn't seem to work otherwise.

`<meta http-equiv="Content-Security-Policy" content="script-src 'self' https://example.com 'sha256-somesha';">`

`<script sha256="somesha" src="https://example.com"></script>`
