### ISSUE TITLE
Connection problem with PhoneGap Developer App 

### ISSUE THREAD

**Issue by Gerriko** [phonegap/phonegap-app-desktop#802]
I did a search online about this issue, as I too am experiencing this very same problem (issue number #566). Namely when trying to run the developer app on my mobile phone it gets stuck trying to download files and times out saying it cannot find server etc. despite entering correct IP address / port number.

So I am opening the issue again, as after 2 years of other people raising similar issues (which have been closed), I note that there is very little provided in terms of clear answers and documentation of what to do / how to resolve. If there are answers as to what to do, please could you tell me. 

I have a Windows 10 desktop and an Android phone.

To help me troubleshoot, please can you explain where the "server" actually resides and what is the process when trying to upload files from server to my phone. There is very little on the website that explains this process. If it is my desktop that is being treated as the server, then in my case this is most likely a Windows local networking issue and I then I have to find a way to open up my PC to the LAN so that other devices can "see" it, which is not ideal as creates a security risk (IMO).

Thanks

**Comment by surajpindoria** [comment]
Hi @Gerriko,

When the app launches a project it starts up a local server on your computer. Therefore your computer and network need to be set up properly to allow peer-to-peer connections.

If you do not not want to go down this route, you can always use the PhoneGap CLI to build the apk for your project and then install it onto your mobile device for testing. But using this method, you will lose some of the features of the developer app such as live reloading

**Comment by Gerriko** [comment]
Hi @surajpindoria 

Thank you for the very quick response. Yes that indeed works. 

To fix I went to my Windows 10 Control Panel: Network & Internet and clicked on Network & Sharing Centre (Advanced Sharing Settings link on the left) and changed my settings to a Private Network to allow other devices on my network to see my PC.

Thank you for the tip about using PhoneGap CLI as an option if I want to keep my PC hidden on the network. Very useful, but as you say it has limitations when developing (No live reloading etc.).

Very happy now :-)

**Comment by surajpindoria** [comment]
Glad you were able to get this working!

**Comment by DoneDevelop** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/4d428482-1dad-4da8-ad6a-94f32f611f5d-e5f5d06a-bb40-4f30-9271-d78c678361dc-v1.png?transparent=1&palette=1&width=246) Did it work?
