### ISSUE TITLE
Mac PhoneGap Desktop App stuck on loading screen

### ISSUE THREAD

**Issue by playgraph** [phonegap/phonegap-app-desktop#804]
### PhoneGap Desktop version
 0.4.4 (Beta)

### PhoneGap Mobile App version
1.7.9

### Mobile devices & Mobile OS version
iPhone 7 iOs 10.3.2

### Computer OS version
Mac OS Sierra 10.12.4

### Network Type (home/corporate)
Home - Google Fiber

### Is your network using a proxy?
No Proxy 

### Computer / Network security (firewall / anti-virus / disk encryption)
Tried with Mac firewall on and off - no change to app behavior

### Are you using VMs on your computer?
No VM

### Do you have multiple network adapters (or virtual network adapters)?
No adapters or virtual network adapters

### Are you using VPN?
no VPN

### Expected Behaviour
Desktop app should open

### Actual Behaviour
Desktop app remains stuck on loading screen with spinning loading icon after initial instal and all subsequent app starts

### Steps to Reproduce 
download app for Mac and install following prompts.

#### Error messages
No error message - just blank loading screen

**Comment by surajpindoria** [comment]
Hi @playgraph,

Are you able to load the application if you use an older version?

**Comment by playgraph** [comment]
Hi @surajpindoria, I have not tried that. I did not see a link to legacy versions on the adobe phonegap site. Could you provide a link? Thanks!

**Comment by surajpindoria** [comment]
https://github.com/phonegap/phonegap-app-desktop/releases

**Comment by playgraph** [comment]
@surajpindoria - loading 0.4.3 loads but when creating a Hello World project I get the following error:

> Project create failed with code 1

**Comment by surajpindoria** [comment]
Ok thanks for trying. Unfortunately without being able to reproduce the issue ourselves this has been a difficult one to solve. In the meantime the only thing I can really recommend would be to use the PhoneGap CLI.
