### ISSUE TITLE
Need to move crash reporter server from Heroku to our PG AWS

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/phonegap-app-desktop#805]

**Comment by filmaj** [comment]
May i suggest we get a new repo set up under the phonegap org to house this code? If we want to automate the set up and maintenance tasks for this server, may want to follow the blueprint I put together for metrics.phonegap.com tracked under the private phonegap-infrastructure repo

**Comment by hermwong** [comment]
It's already under the PhoneGap Org: https://github.com/phonegap/phonegap-desktop-crash-report-server

**Comment by filmaj** [comment]
Perfect

**Comment by hermwong** [comment]
Found some initial [docs](https://github.com/phonegap/phonegap-service-push-config/blob/master/readme-push-server-admin.md)

**Comment by filmaj** [comment]
@hermwong Are you looking for docs on how to set up a new server instance? I set up metrics based on my prior AWS experience. If you are looking for help in creating a new server, we could go through that together and then write up docs for 'AWS Instance Setup 101' as we do it.

**Comment by hermwong** [comment]
@filmaj Yeah, I've looking into setting up a new server instance so that we can migrate our Crash Reporter server over to AWS.

**Comment by hermwong** [comment]
updated to use https://crashreporter.phonegap.com here: 3d1588028cf1382289b1b353aa110986eef8cfdf
