### ISSUE TITLE
PhoneGap Desktop 0.4.4 Fails to startup. Console log included.

### ISSUE THREAD

**Issue by MisterFister666** [phonegap/phonegap-app-desktop#806]
## _System Configuration_
os x
### PhoneGap Desktop version
0.4.4
### Computer OS version
osx 10.11.6
### Network Type (home/corporate)
home
### Is your network using a proxy?
no
### Computer / Network security (firewall / anti-virus / disk encryption)
none
### Are you using VMs on your computer?
no
### Do you have multiple network adapters (or virtual network adapters)?
no
### Are you using VPN?
no
### Expected Behaviour
application would start
### Actual Behaviour
application fails to start. displays system error dialog "The application PhoneGap can't be opened"
### Steps to Reproduce 
Install PhoneGap desktop 0.4.4 from EITHER the .dmg or the .zip. They BOTH fail the same way.
#### Error messages
Here is the appropriate section from the console log. It appears that something called "electron" is not installed. Or there is a permission problem on a .plist. Or something.

5/30/17 6:40:18.483 PM lsd[468]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
5/30/17 6:40:18.492 PM lsd[468]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
5/30/17 6:40:18.498 PM com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000018.Electron[37039]) Could not find and/or execute program specified by service: 2: No such file or directory: /Applications/PhoneGap.app/Contents/MacOS/Electron
5/30/17 6:40:18.497 PM Finder[498]: spawn_via_launchd() failed, errno=111 label=[0x0-0x145145].com.electron.phonegap path=/Applications/PhoneGap.app/Contents/MacOS/Electron flags=1 : LaunchApplicationClient.cp #963 LaunchApplicationWithSpawnViaLaunchD() q=com.apple.root.default-qos
5/30/17 6:40:18.497 PM Finder[498]: spawn_via_launchd() failed, errno=111 label=[0x0-0x145145].com.electron.phonegap path=/Applications/PhoneGap.app/Contents/MacOS/Electron flags=1
5/30/17 6:40:18.502 PM lsd[468]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
5/30/17 6:40:18.510 PM lsd[468]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist

**Comment by MisterFister666** [comment]
The almost opposite problem was reported here and closed without resolution. In that case, the app was looking for nwjs and the only thing in the directory was electron. Now it's looking for electron and it's not there.

https://github.com/phonegap/phonegap-app-desktop/issues/634

**Comment by surajpindoria** [comment]
Hi @MisterFister666,

My first thought with this is maybe something going on with your Gatekeeper settings. If you try right clicking the app icon and then selecting "Open" does that help?

**Comment by MisterFister666** [comment]
Thanks! It is not Gatekeeper. But it does appear to be related to permissions. Your comment prompted me to try opening it from Terminal. If I am logged in as myself, it fails in this way:

$ open ./PhoneGap.app
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/PhoneGap.app.
$

But if I open it as root, it succeeds!
root# open PhoneGap.app
root# 


A quick google search on that function name and error number turns up a lot of other situations where it also happens. Presumably there is something in the app which requires admin privileges to execute?

**Comment by surajpindoria** [comment]
That is really strange, I don't know of any permissions that would require admin privileges. Although when searching the web I did notice this article that mentioned sometimes the files in `*.app/Contents/MacOS/` may not be executable. Which could also cause this error.

https://superuser.com/questions/898124/the-application-someapp-app-can-t-be-opened

**Comment by MisterFister666** [comment]
Does the installer copy any existing files from elsewhere in the system which may already have the wrong permissions? I installed the command line version sometime ago and may have done this as root.

**Comment by kerrishotts** [comment]
Discussed on the PG forums (thread: https://forums.adobe.com/thread/2340175)

Another app that has the issue (and a workaround): https://forums.adobe.com/external-link.jspa?url=https%3A%2F%2Fgithub.com%2Fyhat%2Frodeo%2Fissues%2F301%23issuecomment-225998791

And @MisterFister666's fix: https://forums.adobe.com/message/9623953#9623953

I don't know if there's any way to include the fix in the packager or not, but in case there is, I thought I'd drop the info here.

**Comment by mmufaad** [comment]
Please use phonegap 0.3 , that will work well ...

Thank you....

**Comment by hermwong** [comment]
Related to permissions on OSX - see @kerrishotts comments for links to solutions.
