### ISSUE TITLE
Can't create a new project

### ISSUE THREAD

**Issue by Filavision** [phonegap/phonegap-app-desktop#808]
## _System Configuration_
Processor: Intel i5-2400 3.10GHz
RAM: 8GB
### PhoneGap Desktop version
0.4.4
### Computer OS version
Win10 Pro 64bit
### Network Type (home/corporate)
home
### Is your network using a proxy?
no
### Computer / Network security (firewall / anti-virus / disk encryption)
avast antivirus
### Are you using VMs on your computer?
no
### Do you have multiple network adapters (or virtual network adapters)?
yes
### Are you using VPN?
no
### Steps to Reproduce 
- i just click on + create new PG project
- choose Push Notifications example and click next
- chosse path c:\test and name "test"
- i can't click on create project, it just happens nothing... no loading status or anything
- i tried it also with an id but doesn't change
#### Error messages
none

**Comment by surajpindoria** [comment]
Hi @Filavision,

There was an issue with the original release of 0.4.4 for Windows that was causing this issue. Can you try reinstalling using the new installer files and let me know if you are still seeing this issue?

https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.4.4

**Comment by Filavision** [comment]
This solves the problem, thanks!
