### ISSUE TITLE
Analytics reporting errors to wrong object property

### ISSUE THREAD

**Issue by timkim** [phonegap/phonegap-app-desktop#810]
### PhoneGap Desktop version
0.4.4

### Expected Behaviour
The analytics format expects that `_error_msg` contains the actual error message: https://github.com/phonegap/phonegap-metrics#analytics-format

### Actual Behaviour
The desktop app instead puts the error message in `full_message`: https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/analytics.js#L58

**Comment by surajpindoria** [comment]
Thanks @timkim, I'll take care of this and add it to our next bug fix release
