### ISSUE TITLE
If user app proxies URLs (does CORS), certain proxied-URL behaviours can trigger error flows in the Desktop App

### ISSUE THREAD

**Issue by filmaj** [phonegap/phonegap-app-desktop#811]
This error is over 50% of all errors being logged in our analytics for the desktop app at this point. I think that makes it high priority!

The error logged in analytics is as follows:

```
RangeError: Invalid status code: 0
 at ServerResponse.writeHead %28_http_server.js:195:11%29
 at error %28C:\Program Files %28x86%29\Adobe\PhoneGap\PhoneGap Desktop\resources\app.asar.unpacked\node_modules\connect-phonegap\lib\middleware\proxy.js:37:25%29
 at ClientRequest.proxyError %28C:\Program Files %28x86%29\Adobe\PhoneGap\PhoneGap Desktop\resources\app.asar.unpacked\node_modules\http-proxy\lib\http-proxy\passes\web-incoming.js:146:9%29
 at emitOne %28events.js:101:20%29 at ClientRequest.emit %28events.js:188:7%29
 at Socket.socketCloseListener %28_http_client.js:285:9%29
 at emitOne %28events.js:101:20%29
 at Socket.emit %28events.js:188:7%29
 at TCP._handle.close [as _onclose] %28net.js:501:12%29
```

There are two problems in this issue.

# Problem 1

We are using a version of connect-phonegap that has some issues with proxying. The issues in particular are logged here:
 - https://github.com/phonegap/connect-phonegap/issues/197
 - https://github.com/phonegap/connect-phonegap/issues/191

Note that the latest master of connect-phonegap has solved these issues. One path forward is:
a) do a new connect-phonegap release
b) do a new phonegap-cli release with the latest connect-phonegap release
c) update the version of phonegap-cli in the desktop app and do a new release

# Problem 2

There are still some problems even when I update my local copies to the latest versions. In particular, if one tries to proxy a bogus URL, that seems to trigger another exception in the desktop app:

```
server-status.js:61 Proxy error for url: http://sdkjhfsadsd.com/blah
server-status.js:75 undefined
server-status.js:99 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at parsePortNumber (server-status.js:99)
    at checkMessageType (server-status.js:85)
    at formatServerErrorMessages (server-status.js:76)
    at PhoneGap.<anonymous> (server-status.js:63)
    at emitOne (events.js:101)
    at PhoneGap.emit (events.js:188)
    at Server._errorHandler (/Users/maj/src/phonegap-app-desktop/www/node_modules/phonegap/lib/phonegap/serve.js:102)
    at emitTwo (events.js:111)
    at Server.emit (events.js:191)
    at EventEmitter.<anonymous> (/Users/maj/src/phonegap-app-desktop/www/node_modules/connect-phonegap/lib/serve.js:170)
```

Looks to be caused by `server-status.js` trying to parse port numbers for error message formatting. However, the error handler for `global.phonegap.serve` is passed an undefined error object. Thus, the port formatting code has no error message to parse, and blows up.

# Recommended Next Steps

 - update connect-phonegap version inside desktop app as per steps laid out above
 - understand why the phonegap-serve error handler is passed an empty error object for the proxy-bogus-url case and fix it.

**Comment by surajpindoria** [comment]
@filmaj I will start taking a look at this today. As for "Problem 2", is this the same as https://github.com/phonegap/connect-phonegap/issues/191? If so, curious why this is an issue in the desktop only and not through the CLI as well.

**Comment by filmaj** [comment]
As I mentioned:

> Looks to be caused by server-status.js trying to parse port numbers for error message formatting. However, the error handler for global.phonegap.serve is passed an undefined error object. Thus, the port formatting code has no error message to parse, and blows up.

**Comment by surajpindoria** [comment]
Oops, looks like I need to do a better job of reading 😃. Thanks!
