### ISSUE TITLE
PhoneGapDesktop.dmg will not mount.

### ISSUE THREAD

**Issue by spencerthayer** [phonegap/phonegap-app-desktop#812]
Your DMG is broken.

```
hdiutil attach PhoneGapDesktop.dmg
hdiutil: attach failed - Resource temporarily unavailable
```

**Comment by surajpindoria** [comment]
Hi @spencerthayer,

Where did you download the DMG from? I just tried the one from GitHub and the PhoneGap website and they both work for me.

**Comment by spencerthayer** [comment]
Same. It must be an issue on my end. I just tried it on another computer. Thanks.
