### ISSUE TITLE
not able to create new project in phonegap desktop.

### ISSUE THREAD

**Issue by raja-shanmugam1901** [phonegap/phonegap-app-desktop#813]
### PhoneGap Desktop version

I have installed phone gap desktop app but when I am creating a new hello world project.i am getting a error like" command line failed with exit code enoent".I have installed Cordova also in CLI by given npm install -g Cordova but still not able to create.so please help me to fix this issue..  Thanks in advance.

**Comment by surajpindoria** [comment]
Hi @rohitraja95,

Can you please provide the full error message? Also can you fill in the the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
1. PhoneGap Mobile App version
1. Mobile devices & Mobile OS version
1. Computer OS version
1. network type (home/corporate)
1. is your network using a proxy?
1. computer / network security (firewall / anti-virus / disk encryption)
1. are you using VMs on your computer?
1. do you have multiple network adapters (or virtual network adapters)
1. are you using VPN?

**Comment by xAegir** [comment]
same but i cannot add existing projects anymore, it just leaves me blank app screen :(

PhoneGap Desktop Version (v0.4.4)
Windows 7 Ultimate
Home Network

**Comment by surajpindoria** [comment]
Hi @xAegir,

Does the desktop app display any error messages when you try to add an existing project?

**Comment by TheJaymoe** [comment]
I have the same problem.

Just installed everything and when trying to create "Hello World" project i get error.

![image](https://user-images.githubusercontent.com/1438204/33952948-a93ece2e-e033-11e7-832b-6f70d928a019.png)

**Comment by danish1023** [comment]
Same here

**Comment by Jslx7** [comment]
And same here.....

**Comment by qesterx** [comment]
Same here

**Comment by andreyduarte** [comment]
I had the same issue.
Fixed it by adding **"C:\Windows\System32"** to the **PATH** variable.
On Windows 10 ou can add it at 
System Properties> Advanced > Evironmental Variables > System Variables

**Comment by MohanRam1996** [comment]
thank you andreyduarte,

i had the same issue , i was able to resolve it by adding the path variable "C:\Windows\System32"

**Comment by islamemam** [comment]
the same issue and here's the error msg
error from cordova Fetch:Error: cmd: command failed with exit code ENOENT 

any help

**Comment by AFayad0** [comment]
> 
> 
> the same issue and here's the error msg
> error from cordova Fetch:Error: cmd: command failed with exit code ENOENT
> 
> any help



> 
> 
> I had the same issue.
> Fixed it by adding **"C:\Windows\System32"** to the **PATH** variable.
> On Windows 10 ou can add it at
> System Properties> Advanced > Evironmental Variables > System Variables

From andreyduarte, Thank you

**Comment by Htewech7** [comment]
Good job, the problem was resolved

**Comment by Djekswon** [comment]
> I had the same issue.
> Fixed it by adding **"C:\Windows\System32"** to the **PATH** variable.
> On Windows 10 ou can add it at
> System Properties> Advanced > Evironmental Variables > System Variables

Thank you very much

**Comment by anascann** [comment]
> I had the same issue.
> Fixed it by adding **"C:\Windows\System32"** to the **PATH** variable.
> On Windows 10 ou can add it at
> System Properties> Advanced > Evironmental Variables > System Variables

love you man <3

**Comment by rajeshmondal46** [comment]
> > the same issue and here's the error msg
> > error from cordova Fetch:Error: cmd: command failed with exit code ENOENT
> > any help
> 
> > I had the same issue.
> > Fixed it by adding **"C:\Windows\System32"** to the **PATH** variable.
> > On Windows 10 ou can add it at
> > System Properties> Advanced > Evironmental Variables > System Variables
> 
> From andreyduarte, Thank you

But which variable name?
