### ISSUE TITLE
Mobile App Stuck On Success

### ISSUE THREAD

**Issue by ahanraina** [phonegap/phonegap-app-desktop#816]
Hi! My desktop app is v0.4.4 and my phone app is v1.7.10. I have a 2015 Macbook Pro. When I try to connect to my app from my phone, it goes through everything, reaches Success, but then doesn't do anything. Thanks in advance for your help!

**Comment by surajpindoria** [comment]
Hi @addyraina,

Take a look at this [FAQ](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/), there are some suggestions that may help you.
