### ISSUE TITLE
about "React Hot Loader" template

### ISSUE THREAD

**Issue by carly1987** [phonegap/phonegap-app-desktop#817]
how to use phonegap with react?

i choose "React Hot Loader", and start. and have error. because no "./bundle.js".

how to build?
i know build ios .... but about "browser" platform, how to build?

**Comment by devgeeks** [comment]
You will have to build the app from the command line first to use that particular template.
The Desktop app has no concept of running npm build scripts. 

https://github.com/phonegap/phonegap-template-react-hot-loader#build-the-app-for-production

**Comment by surajpindoria** [comment]
Hmmm, if that is the case maybe we should consider removing the react-hot-loader template from the app. No point in having it there if it doesn't work correctly. Thoughts @devgeeks?

**Comment by devgeeks** [comment]
I would agree, at least till we work out a solution for the problem. We will need to for the new Vue templates as well.

**Comment by surajpindoria** [comment]
Cool, I'll add removing this to the next release. We can add it back in later once we have a solution.
