### ISSUE TITLE
PhoneGap  Requesting Registration ID problem - first use

### ISSUE THREAD

**Issue by mzn** [phonegap/phonegap-app-desktop#818]
I got this problem when try to open first time http://192.168.42.118:3000/

Uncaught TypeError: undefined is not a function 192.168.42.118:3000/:98
Error: exec proxy not found for :: StatusBar :: _ready cordova.js:989
Received Device Ready Event index.js:36
calling setup push index.js:37
calling push init index.js:41
Uncaught Error: Service Workers are not supported on your browser. push.js:83

**Comment by surajpindoria** [comment]
Hi @mzn,

What browser are you using to test this? The first few errors don't seem to be related to your issue. But the final 'Uncaught Error' shows that service workers are not support. This is why you are unable to get a registration ID.
