### ISSUE TITLE
No "README" or "INSTALL" files in ZIP

### ISSUE THREAD

**Issue by Y-Less** [phonegap/phonegap-app-desktop#821]
### PhoneGap Desktop version

Latest

### PhoneGap Mobile App version

None

### Mobile devices & Mobile OS version

N/A

### Computer OS version

Windows 8.1

### Network Type (home/corporate)

Home

### Is your network using a proxy?

No

### Computer / Network security (firewall / anti-virus / disk encryption)

Avast

### Are you using VMs on your computer?

No

### Do you have multiple network adapters (or virtual network adapters)?

Yes

### Are you using VPN?

Yes

### Expected Behaviour

On this page:

http://docs.phonegap.com/getting-started/1-install-phonegap/desktop/#win

It says:

> If you're unable to run the Windows Installer for some reason, there's also a zip file available that can be used to install PhoneGap Desktop manually. Download the zip file for the latest release and follow the instructions in the README and INSTALL files within the downloaded zip.

I can't run it because I can't download it (see #820 ), so I got the ZIP instead.

### Actual Behaviour

There are no INSTALL or README files in the zip file (or rather, there is one, but for a dependency and not the main program).

### Steps to Reproduce 

Download this:

https://github.com/phonegap/phonegap-app-desktop/releases/download/0.4.4/PhoneGap-Desktop-Beta-0.4.4-win.zip

Extract it.

Look for the promised files.

**Comment by surajpindoria** [comment]
Hi @Y-Less,

You are correct that the README and INSTALL files are not present in the downloaded zip. This is definitely an oversight on our part and I will get this fixed for the next releases. In the meantime, you can find these files in the root of the project on GitHub.

Thanks for bring this up!

**Comment by hermwong** [comment]
This change seems to be causing issues with the OSX code signing. The code signing returns an error stating `unsealed contents present in the bundle root`.

**Comment by hermwong** [comment]
Seems like we may only need to copy the files over for Windows. OSX users aren't required to follow additional install instructions provided within the INSTALL file or the README file.

We should only copy these files for the Windows build.
