### ISSUE TITLE
Can't use my own domain for an identifier

### ISSUE THREAD

**Issue by Y-Less** [phonegap/phonegap-app-desktop#822]
### PhoneGap Desktop version

0.4.4

### PhoneGap Mobile App version

1.7.10

### Mobile devices & Mobile OS version

Android

### Computer OS version

Windows 8.1

### Network Type (home/corporate)

Home

### Is your network using a proxy?

No

### Computer / Network security (firewall / anti-virus / disk encryption)

Avast

### Are you using VMs on your computer?

No

### Do you have multiple network adapters (or virtual network adapters)?

Yes

### Are you using VPN?

Yes

### Expected Behaviour

Use my domain name in a reverse format for a unique ID.  The docs I read say to base uniqueness on domain ownership, so should accept valid domains.

### Actual Behaviour

Claims it is invalid, despite the fact that it isn't.

### Steps to Reproduce 

Type an ID of `com.y-less.appname`.

I tried my other two domains as well - `six-by-nine.com` and `y-l.es`, neither worked.

#### Error messages

App ID contains a reserved word, or is not a valid identifier.

**Comment by devgeeks** [comment]
Android limits the characters available in App IDs.

Dashes are not allowed.

See: https://developer.android.com/studio/build/application-id.html

> - It must have at least two segments (one or more dots).
> - Each segment must start with a letter.
> - All characters must be alphanumeric or an underscore [a-zA-Z0-9_]
