### ISSUE TITLE
Phonegap Desktop App does not show projects when creating new OR adding existing (OSX Sierra)

### ISSUE THREAD

**Issue by Sth0nian** [phonegap/phonegap-app-desktop#823]
## _System Configuration_
Model Identifier:	MacBookPro12,1
Processor Name:	Intel Core i5
Processor Speed:	2,9 GHz
### PhoneGap Desktop version
v0.4.4
### PhoneGap Mobile App version
1.7.10
### Mobile devices & Mobile OS version
iPhone 6s (10.3.2)
### Computer OS version
10.12.5
### Network Type (home/corporate)
corporate
### Is your network using a proxy?
no
### Computer / Network security (firewall / anti-virus / disk encryption)
none
### Are you using VMs on your computer?
no
### Do you have multiple network adapters (or virtual network adapters)?
yes
### Are you using VPN?
no
### Expected Behaviour
The Phonegap application should list the different projects I added / created.
### Actual Behaviour
 after a restart, the list is empty showing the "Drop PhoneGap project folders here" background instead.
### Steps to Reproduce 
Restart Phonegap
#### Error messages
None

**Comment by surajpindoria** [comment]
Hi @Sth0nian,

Could you try to create/add a project on a non-corporate network. From the information you have provided, the only thing I can think of is that something is getting messed up when the app is attempting to download necessary files.
