### ISSUE TITLE
After saving the project file the compiling application is keep refreshing in the browser inifinity

### ISSUE THREAD

**Issue by mmufaad** [phonegap/phonegap-app-desktop#826]
0.4.4 phonegap in windows 10..
after i save my project files, in runtime my application is keep refreshing the same page in my web browser , its really irritating , need solution for  this . or else if there is any option to stop auto compiling with browser that will be help full .

Thank you..

**Comment by surajpindoria** [comment]
Hi @mmufaad,

I have just tried this on my Windows machine and was not able to reproduce it.
Could you provide the following information so we can help to debug this:

1. PhoneGap Desktop version / PhoneGap CLI version
1. PhoneGap Mobile App version
1. Mobile devices & Mobile OS version
1. Computer OS version
1. network type (home/corporate)
1. is your network using a proxy?
1. computer / network security (firewall / anti-virus / disk encryption)
1. are you using VMs on your computer?
1. do you have multiple network adapters (or virtual network adapters)
1. are you using VPN?

**Comment by Valkhan** [comment]
Having the same issue:

1. PhoneGap Desktop version (v0.4.4)
2. PhoneGap Mobile App version (1.7.10)
3. Mobile devices & Mobile OS version (iOS 10.3.2  iPhone 6 OSx or Android
4. Computer OS version (Windows 10)
5. network type (home/corporate) (Home)
6. is your network using a proxy? (No)
7. computer / network security (firewall / anti-virus / disk encryption) (Localhost, no firewall blocks, no antivirus no disk encryption)
8. are you using VMs on your computer? (have VMPlayer installed but was not running any vms at the moment)
9. do you have multiple network adapters (or virtual network adapters) (yes)
10. are you using VPN? (no)

**Comment by mjy12** [comment]
i think u have error in you project debug for any mistake in project

**Comment by Valkhan** [comment]
@mjy12 Error where exactly? 

HTML+JS+CSS is working, i did a global error catcher, if anything happens in JS it pops up an alert where the code has crashed, so far... no erros in this area.

Perhaps some plugin or something else? in this case, i've deleted all (hooks, platforms, plugins) saved just the "www" folder so phonegap would recreate its plugins to no avail... issue still occurs.

config.xml - never changed that, can't be this file.

I really don't think is something in the project, it has never happened again until i've installed VMware Player.

I'm also considering at this point to create a virtual environment for developing mobile apps with cordova 'cause right now is unnusable in my main machine, i've just oppened my phonegap app and an update was found (0.45) will try this as it said to fix this kind of behavior.

**Comment by Valkhan** [comment]
Just tested version 0.4.5 of phonegap App in Windows 10 desktop:

When I Say: "Modify a file" I mean: Add a space or remove a space and save.

Chrome 60 - OK

Firefox 54 - Infinite loop (No extensions enabled), console errors:

> adding proxy for BarcodeScanner  127.0.0.1:3000:170:13
adding proxy for Camera  127.0.0.1:3000:170:13
adding proxy for Device  127.0.0.1:3000:170:13
adding proxy for File  127.0.0.1:3000:170:13
adding proxy for NetworkStatus  127.0.0.1:3000:170:13
Error: exec proxy not found for :: StatusBar :: _ready  127.0.0.1:3000:170:13

All those console errors above were present before the issue starts (before installing vmware) and i think it's browser related and do not relate to the problem.

IOs iPhone 10.3.3 - OK

Android - 4.2.2 - intermittent, sometimes the app crashes (Error network something...)  and sometimes it runs just fine
