### ISSUE TITLE
BAST - OSX Code Signing Setup

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#834]
Setup Adobe's signing server to code sign the OSX binaries.

**Comment by hermwong** [comment]
We currently have a CI server that triggers whenever commits are made to the master branch or any branches defined in the [.travis.yml](https://github.com/phonegap/phonegap-app-desktop/blob/master/.travis.yml).

It may be possible to automate the server to upload the OSX build to Adobe's code signing server after a successful build from the CI server.

**Comment by hermwong** [comment]
After further investigation, it looks like our Mac Mini CI server is using BuildKite - however the BuildKite scripts were removed way back in Desktop 0.2.0 when we moved over to Travis-CI.

I'll work on restoring the CI from the Mac Mini so that we will have an internal build machine that can be whitelisted to post builds up to Codex.

**Comment by surajpindoria** [comment]
We should hold off on this for now. The signing team is in the process of enabling OSX signing using their new tools by mid/late September. This new tool is much more streamlined and will remove a lot of the headaches I was facing when figuring this out for Windows.
