### ISSUE TITLE
The new Adobe Build ceates app that does not work when using desktop 0.4.5 

### ISSUE THREAD

**Issue by AlainGauthier** [phonegap/phonegap-app-desktop#835]

**Comment by AlainGauthier** [comment]
build is complete successfully but the app is has nothing in and run infinitely. Was working yesterday.

**Comment by hermwong** [comment]
Hi @AlainGauthier,

Could you please fill out the details in the form above so that we have more information to help debug the issue.

**Comment by AlainGauthier** [comment]
I fixed the issue, please disregards this post.

**Comment by hermwong** [comment]
Awesome thanks. Would you be able to share your solution in the comments so that others that run into the same issue can use your solution?

**Comment by AlainGauthier** [comment]
Sorry nothing interesting, I was simply uploading the wrong files (was doing to many things in parallel)... thanks for asking
