### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by 1stNaNo** [phonegap/phonegap-app-desktop#838]
#### Error messages

white screen and freeze

**Comment by 1stNaNo** [comment]
I have problem with desktop app on mac os x its crashed when app start. Maybe reason is installed plugin with cordova or i used build ios command. please check it

**Comment by surajpindoria** [comment]
Hi @1stNaNo,

Can you please provide the info that is listed above so we can help to debug your issue.

**Comment by 1stNaNo** [comment]
I can give u my project source
