### ISSUE TITLE
No support android 2.X?

### ISSUE THREAD

**Issue by DrMinh** [phonegap/phonegap-app-desktop#839]
Why apk create by phonegap v0.4.5 can not run on android 2.x? I try to replace android-minSdkVersion value to 1. My app can intall but can not run, it stop when i try to open.

**Comment by hermwong** [comment]
PhoneGap Desktop 0.4.5 uses the PhoneGap-CLI 6.5.2 which does not support Android 2.X. Please refer to the following platform support [chart](https://build.phonegap.com/current-support) for the PhoneGap-CLI versions.
