### ISSUE TITLE
No icon or splash screen showing using phonegap desktop

### ISSUE THREAD

**Issue by Annuther** [phonegap/phonegap-app-desktop#844]
Im confused as to where we are supposed to place the default icon.png and splash.png files. New projects place config.xml outside of the www folder yet all documentation advised to place resources in the root of www folder. All references to the splash sceen and icons resources in config.xml reference the www folder as if this file were INSIDE the www folder??? Right now i have no splash nor icon showing. I havent yet built the apk file but i thought the splash and default icon  would show while developieng in phonegap desktop. when i place the resources outside the www folder and remove the reference in config.xml the app wont run. Where do these resources reside now AND when we come to build the apk????

Here a (fragment) of my config.xml file in the default location when a new app is created: 

```
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="android-minSdkVersion" value="14"/>
  <preference name="orientation" value="portrait" />
  <preference name="SplashScreen" value="screen"/>  
  <preference name="show-splash-screen-spinner" value="true" />
  <preference name="splash-screen-duration" value="10000" />
  <preference name="auto-hide-splash-screen" value="true" />
  <preference name="disable-cursor" value="false" />

  <icon src="www/icon.png" />
  <splash src="www/splash.png" />
  
  <platform name="android">
    <icon src="www/res/icon/android/ldpi-icon.png" qualifier="ldpi"/>
    <icon src="www/res/icon/android/mdpi-icon.png" qualifier="mdpi"/>
    <icon src="www/res/icon/android/hdpi-icon.png" qualifier="hdpi"/>
    <icon src="www/res/icon/android/xhdpi-icon.png" qualifier="xhdpi"/>
    <icon src="www/res/icon/android/xxhdpi-icon.png" qualifier="xxhdpi"/>
    <icon src="www/res/icon/android/xxxhdpi-icon.png" qualifier="xxxhdpi"/>
    <splash src="www/res/screen/android/ldpi.png" qualifier="ldpi"/>
    <splash src="www/res/screen/android/mdpi.png" qualifier="mdpi"/>
    <splash src="www/res/screen/android/hdpi.png" qualifier="hdpi"/>
    <splash src="www/res/screen/android/xhdpi.png" qualifier="xhdpi"/>
    <splash src="www/res/screen/android/xxhdpi.png" qualifier="xxhdpi"/>
    <splash src="www/res/screen/android/xxxhdpi.png" qualifier="xxxhdpi"/>
  </platform>
```

Note: im only developing for Android - all the paths are correct and have been checked multiple times to ensure all images are in the right place. I don't even see the app icon in Phonegap desktop while running - instead i see a white icon with the first letter of the apps name - this has been the case since the last two PG Desktop updates. the projects app use to show no problem in older versions of phonegap desktop.

thanks in advance ...

**Comment by surajpindoria** [comment]
Hi @Annuther,

You can have your config.xml in either the project root or www directory, but all icon/splash screen paths should be relative to the project root. When working with the PhoneGap Desktop App it will not display your apps icon or splash screen when you preview the app on the PhoneGap Developer App. If you want to test these out you will need to do a full build and then install it to a device.

Regarding your apps icon not showing up in the Desktop app, we updated the icon logic awhile back in the hopes of displaying a higher quality image. In order to do this, we are checking that the image meets certain dimension requirements. And since you do not specify the height/width for your icons in config.xml, it is failing to meet these requirements and therefore we display the default (white icon with first letter).

**Comment by hermwong** [comment]
If you want the icons to show up in the desktop app like this:

<img width="360" alt="screen shot 2017-08-21 at 1 34 39 pm" src="https://user-images.githubusercontent.com/107754/29537184-a923d38e-8675-11e7-97b0-b2ac58119154.png">

The Desktop app checks checks that the dimensions of your icon have the same width & height which must be greater than 64.

**Comment by Annuther** [comment]
@surajpindoria & hermwong,
Thanks for clearing that up i'll leave the config.xml file on the project root since thats were PGDesktop puts it. I got the icon to show up now in PGDesktop list using your recommendation (70x70). Not sure where this info is on the main PG/Cordova docs but couldnt find it anywhere. I'd been using a default icon with dimensions 48x48px and i believe that this used to be recommended. 

While trying to get the splash working and reading other users config files dumps on Stackoveflow and such it becomes confusing where exactly your config.xml file needs to be? I'm presuming that the www directory is disregarded and only the contents are referenced when you come to build your project.

Any how thanks again for your help guys - keep up the excellent work your doing with phonegap - it rocks!
