### ISSUE TITLE
hi, i'm using phonegap desktop v0.4.5 on windows 7. seems to work fine, but when i launch it the window is small, maximize button greyed out, can't drag edges to expand. as a result, when i bring up developer console everything is unreadable. i can't make the window any bigger.

### ISSUE THREAD

**Issue by johnd2323** [phonegap/phonegap-app-desktop#846]

**Comment by surajpindoria** [comment]
Hi @johnd2323,

You can remove the developer console from the main application window. If you press the button on the console with the 3 dots, the first option will remove it from the main window. Also just to clarify, this developer console is only for debugging the desktop application. It cannot be used on a PhoneGap project that you load into it.

![console](https://user-images.githubusercontent.com/6467569/29530283-c95cc75a-8657-11e7-951f-8c31ce850b32.png)
