### ISSUE TITLE
PhoneGap mobile conection error

### ISSUE THREAD

**Issue by HappaQ** [phonegap/phonegap-app-desktop#851]
The mobile PhoneGap can not connect to the IP showed in the desctop version.
Even thogh PC and Phone are connected to the same WiFi.
I'm also receiving an download error when tryíng to get the error.

**Comment by surajpindoria** [comment]
Hi @HappaQ,

Take a look at this [FAQ](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/), there are a bunch of suggestions that may help you.
