### ISSUE TITLE
Phonegap Desktop 0.4.3 Project create failed with code 1

### ISSUE THREAD

**Issue by Bruplanet** [phonegap/phonegap-app-desktop#852]
Hi there

I'd love to get the Phonegap Desktop app working on my Mac! I am using version 0.4.3 because 0.4.4 and 0.4.5 will not progress past the loading screen (endlessly spinning circle).

However when I try to create a project using any variation of project type and the simplest possible project settings (no funny characters in names, etc) I receive the error "Project create failed with code 1".

## _System Configuration_
Mac OS Sierra 10.12.6
Phonegap CLI 7.0.1
I also have the Cordova CLI installed

### PhoneGap Desktop version
0.4.3

### PhoneGap Mobile App version
Not installed 

### Mobile devices & Mobile OS version
Not relevant yet

### Computer OS version
Mac OS Sierra 10.12.6

### Network Type (home/corporate)
Have tried both work and home networks - same on both

### Is your network using a proxy?
No

### Computer / Network security (firewall / anti-virus / disk encryption)
EndPoint Security for Mac anti-virus
No firewall

### Are you using VMs on your computer?
No

### Do you have multiple network adapters (or virtual network adapters)?
No

### Are you using VPN?
Yes but the problem persists whether or not I am connected to the VPN

### Expected Behaviour
A project creates successfully

### Actual Behaviour
Project creation fails with code 1

### Steps to Reproduce 
- Install 0.4.3 on Mac
- Do not accept update to later versions
- Click + for new Phonegap project
- Choose Hello World
- Set a local path to which my user has write permissions, Name = hello, ID = com.bruplanet.hello
- Click "Create Project"

#### Error messages
Project create failed with code 1
![screen shot 2017-09-22 at 15 32 36](https://user-images.githubusercontent.com/32200274/30749434-51985640-9fab-11e7-93d5-0a9d9d9fb5b4.png)
![screen shot 2017-09-22 at 15 32 29](https://user-images.githubusercontent.com/32200274/30749435-519b708c-9fab-11e7-86c3-237565cf9312.png)

**Comment by Bruplanet** [comment]
Update: I've tried going around the problem by creating the project with the CLI then opening it within the Desktop App. This seems to work, so I'm able to progress, but it would obviously be neat if the bug wasn't present.

**Comment by surajpindoria** [comment]
Hi @Bruplanet,

I believe there was a problem with project creation in 0.4.3 which would explain why you are seeing this issue. As to the constant spinner issue in the later versions, in 0.4.5 we have the option to display the developer console for the desktop app. If you could try that version again and paste any errors from the console that could help us to resolve this for you.
