### ISSUE TITLE
Not able to maximize the window in windows 10

### ISSUE THREAD

**Issue by skcsknathan001** [phonegap/phonegap-app-desktop#853]
### I simply installed the PhoneGap Desktop software on my Windows 10 computer and the screen size of the application is really small compared to my screen and other apps.
![phonegap-not-able-to-maximize](https://user-images.githubusercontent.com/2206397/31674544-0c74054e-b330-11e7-92b4-3d505423539e.PNG)

**Comment by surajpindoria** [comment]
Hi @skcsknathan001,

The desktop app is not supposed to be able to use full screen, we have chosen that specific size for various design reasons. It looks like you are trying to use the developer console, a few things regarding that:

- That developer console is **only** for debugging issues with the desktop app, not your projects that you have loaded.
- If you do indeed want to debug an issue with the desktop app, you can move the console to a separate window that does resize, [here](https://github.com/phonegap/phonegap-app-desktop/issues/846#issuecomment-323799786) is how you can do that.

**Comment by skcsknathan001** [comment]
So, what is a IDE to actually work on the project? Do you have an IDE or do
I use Visual Studio?

_______________
http://adadaa.net/
All Tamil news in one place

**Comment by purplecabbage** [comment]
VS-Code is the editor of choice
