### ISSUE TITLE
PhoneGap desktop app  & Wikitude Demo - AR web view failed 

### ISSUE THREAD

**Issue by alexd100** [phonegap/phonegap-app-desktop#854]
### PhoneGap Desktop version
0.4.5
### PhoneGap Mobile App version
1.8.1
### Mobile devices & Mobile OS version
iphone 6  - ios 10
### Computer OS version
Windows 7
### Network Type (home/corporate)
home
### Is your network using a proxy?
no
### Computer / Network security (firewall / anti-virus / disk encryption)
360 total security / My other PC is using Windows Essentials ( both have the same phonegap error )
### Are you using VMs on your computer?
no
### Do you have multiple network adapters (or virtual network adapters)?
no
### Are you using VPN?
no
### Expected Behaviour
Demo app from Wikitude to work ( which it was doing about 3-4 weeks ago )
### Actual Behaviour
Augmented reality page from the demo app doesn't work and gives error message
### Steps to Reproduce 
open desktop app - create Wkitude demo - View on mobile using the PhoneGap mobile app
#### Error messages
index.html
Loading AR view failed: Frame load inerrupted

I've spoken to Wikitude about this, and they have confirmed that the AR view is not loading from the side of PhoneGap.

**Comment by timkim** [comment]
Hi @alexd100 

I've confirmed this error and a fix for the developer app (1.8.2) should out shortly (about 3 days depending on review time). Thanks for reporting.
