### ISSUE TITLE
Unable to maximize developer console Mac

### ISSUE THREAD

**Issue by janj1234** [phonegap/phonegap-app-desktop#855]
<img width="484" alt="screen shot 2017-11-13 at 5 49 23 pm" src="https://user-images.githubusercontent.com/33641939/32755495-3353d8ee-c89b-11e7-8a1e-b9b09320889b.png">

<img width="576" alt="screen shot 2017-11-13 at 5 50 16 pm" src="https://user-images.githubusercontent.com/33641939/32755498-3a3e2736-c89b-11e7-886d-5b3151ca4e5f.png">

### PhoneGap Desktop version
downloaded today

### Computer OS version
please see screen shots

### Network Type (home/corporate)
Home

### Is your network using a proxy?
no

### Computer / Network security (firewall / anti-virus / disk encryption)
ESET security

### Are you using VMs on your computer?
no

### Do you have multiple network adapters (or virtual network adapters)?
no

### Are you using VPN?
no

### Expected Behaviour
the developer console to be large enough to use
### Steps to Reproduce 
please see screen shots

#### Error messages
please see screen shots

**Comment by surajpindoria** [comment]
Please take a look at my response to another issue: https://github.com/phonegap/phonegap-app-desktop/issues/846#issuecomment-323799786
