### ISSUE TITLE
PhoneGap Requesting Registration ID problem

### ISSUE THREAD

**Issue by nikitaaZ** [phonegap/phonegap-app-desktop#856]
Hello, I start work with phonegap and try to test notification simple app. When I start it on my phone it start requesting registration id all time, when I open app on chrome - same problem.
console log(android):
undefined Content Security Policy has been modified to be: <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' gap: ws: https://ssl.gstatic.com;style-src 'self' 'unsafe-inline' data: blob:;media-src *;img-src * 'self' data: content:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">
undefined Content Security Policy has been added: <meta http-equiv="Content-Security-Policy" content="default-src * gap: ws: https://ssl.gstatic.com;img-src * 'self' data: content:;style-src 'self' 'unsafe-inline' data: blob:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">
200 /__api__/appzip
200 /socket.io/socket.io.js
200 /socket.io/?EIO=3&transport=polling&t=L_PL06Q
200 /socket.io/?EIO=3&transport=polling&t=L_PL07f&sid=0QptSRm1ZJ8GQf_EAAAI
 Received Device Ready Event
200 /socket.io/?EIO=3&transport=polling&t=L_PL08z&sid=0QptSRm1ZJ8GQf_EAAAI
 calling setup push
 calling push init
200 /socket.io/?EIO=3&transport=polling&t=L_PL0PB&sid=0QptSRm1ZJ8GQf_EAAAI
200 /socket.io/?EIO=3&transport=polling&t=L_PL091&sid=0QptSRm1ZJ8GQf_EAAAI

console log(chrome):
undefined Content Security Policy has been modified to be: <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' gap: ws: https://ssl.gstatic.com;style-src 'self' 'unsafe-inline' data: blob:;media-src *;img-src * 'self' data: content:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">
undefined Content Security Policy has been added: <meta http-equiv="Content-Security-Policy" content="default-src * gap: ws: https://ssl.gstatic.com;img-src * 'self' data: content:;style-src 'self' 'unsafe-inline' data: blob:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">
200 /__api__/appzip
200 /socket.io/socket.io.js
200 /socket.io/?EIO=3&transport=polling&t=L_PL06Q
200 /socket.io/?EIO=3&transport=polling&t=L_PL07f&sid=0QptSRm1ZJ8GQf_EAAAI
 Received Device Ready Event
200 /socket.io/?EIO=3&transport=polling&t=L_PL08z&sid=0QptSRm1ZJ8GQf_EAAAI
 calling setup push
 calling push init
200 /socket.io/?EIO=3&transport=polling&t=L_PL0PB&sid=0QptSRm1ZJ8GQf_EAAAI
200 /socket.io/?EIO=3&transport=polling&t=L_PL091&sid=0QptSRm1ZJ8GQf_EAAAI
200 /
304 /socket.io/socket.io.js
200 /css/index.css
200 /js/index.js
200 /cordova.js
200 /cordova_plugins.js
200 /socket.io/?EIO=3&transport=polling&t=L_PLCBh
200 /img/logo.png
200 /socket.io/?EIO=3&transport=polling&t=L_PLCJt&sid=it39C-vW5FioGmEVAAAJ
200 /plugins/cordova-plugin-statusbar/www/statusbar.js
200 /plugins/cordova-plugin-statusbar/src/browser/statusbar.js
200 /plugins/phonegap-plugin-push/www/push.js
200 /plugins/phonegap-plugin-push/www/browser/push.js
200 /plugins/cordova-plugin-dialogs/www/notification.js
200 /plugins/cordova-plugin-dialogs/www/browser/notification.js
200 /socket.io/?EIO=3&transport=polling&t=L_PLCN0&sid=it39C-vW5FioGmEVAAAJ
 Error: exec proxy not found for :: StatusBar :: _ready
 Received Device Ready Event
 calling setup push
 calling push init
 after init
 SecurityError: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
204 https://cr-input.mxpnl.net/data?_channel_id=&_partner_id=39571&_sub_id=0000&_app_version=1.0.23&_app=cs-dca

**Comment by nikitaaZ** [comment]
and no requesting permission on screen

**Comment by surajpindoria** [comment]
I can see the issue in the browser, but on my phone it works just fine. Are you using the PhoneGap Developer App to load your project?

**Comment by nikitaaZ** [comment]
yes, I use official app, and Hello world example works good

**Comment by surajpindoria** [comment]
What version of the developer app are you using?

**Comment by ewashburn** [comment]
I'm having a similar issue using *PhoneGap Desktop (v0.4.5)*.
I built the Push Notifications App from the template.
No issues for iPhone, the app registers for and receives notifications.
But the Android (Pixel 2) is failing (halts) after push init:
```
undefined Content Security Policy has been modified to be: <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' gap: ws: https://ssl.gstatic.com;style-src 'self' 'unsafe-inline' data: blob:;media-src *;img-src * 'self' data: content:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">
undefined Content Security Policy has been added: <meta http-equiv="Content-Security-Policy" content="default-src * gap: ws: https://ssl.gstatic.com;img-src * 'self' data: content:;style-src 'self' 'unsafe-inline' data: blob:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">
200 /__api__/appzip
200 /socket.io/socket.io.js
200 /socket.io/?EIO=3&transport=polling&t=L_WfDiD
200 /socket.io/?EIO=3&transport=polling&t=L_WfDkG&sid=ffZD2NkhpawW5ZXAAAAU
 Received Device Ready Event
200 /socket.io/?EIO=3&transport=polling&t=L_WfDkZ&sid=ffZD2NkhpawW5ZXAAAAU
 calling setup push
 calling push init
200 /socket.io/?EIO=3&transport=polling&t=L_WfDki&sid=ffZD2NkhpawW5ZXAAAAU
200 /socket.io/?EIO=3&transport=polling&t=L_WfDka&sid=ffZD2NkhpawW5ZXAAAAU 
```
I have also tried using Chrome on my desktop with some success. 
I get a registration event, but no registration id, so I can't test the notification.

Any thoughts or suggestions?

**Comment by shoutweb** [comment]
Same issue as aly9 - says push.js not found

**Comment by thandonguocmo2020** [comment]
Same issue push.js not found.  help !
