### ISSUE TITLE
href links do not open

### ISSUE THREAD

**Issue by jayfagin** [phonegap/phonegap-app-desktop#857]

**Comment by surajpindoria** [comment]
Could you provide answers to the information stated above.

**Comment by jayfagin** [comment]
PhoneGap Desktop version - 0.4.5
PhoneGap Mobile App version - not sure how 
Mobile devices & Mobile OS version - iphone 5se IOS 10
Computer OS version Windows 8
Network Type (home/corporate) Home
Is your network using a proxy? No
Computer / Network security (firewall / anti-virus / disk encryption) None, disabled.
Are you using VMs on your computer? No
Do you have multiple network adapters (or virtual network adapters)? No
Are you using VPN? No.
Expected Behaviour - Click on Submit and go to page. Works in a Desktop browser though.
Actual Behaviour - Nothing happens in IOS.  Work in any Desktop browser.
Steps to Reproduce - Load index.html in phonegap and open on iphone.

**Comment by jayfagin** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>


<allow-navigation href="http://*/*" />
<access origin="content:///*" />
<access origin="http://*.google.com" />
<access origin='*' allows-arbitrary-loads-for-media='true' allows-arbitrary-loads-in-web-content='true' allows-local-networking='true' />
<meta name="format-detection" content="telephone=yes,date=yes,address=yes,email=yes,url=yes" />
<meta charset="utf-8" />
<meta name="msapplication-tap-highlight" content="no" />
<meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />

<meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline'; style-src 'self' 'unsafe-inline'; media-src *" />

<link rel="stylesheet" type="text/css" href="css/index.css" />
    
<title>A Smart Ask Expert Login</title>

</head>

<body>

<div style="position: absolute; width: 320px; height: 100px; z-index: 1; background-color: #666666" id="layer2">
	<p style="font-family:arial; font-size:200%; text-align:center; color:#EFEFEF"><br>A Smart Ask</p>
</div>

<div style="position: relative; width: 320px; height: 100px; z-index: 2; top: 120px" id="layer3">
<br><br>

 <form action="http://www.foxrunsolutions.com/exams/www/passwd_exec.asp" method="Post" name="ExpertForm">
	<p style="color:white; font-size:15px;">&nbsp;&nbsp;&nbsp;&nbsp;Email Address:<br>
	&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="emailaddress" style="font-size:25px" required ><br><br><br>
	&nbsp;&nbsp;&nbsp;&nbsp;Password:<br>
	&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="password" style="font-size:25px" required > <br><br>
	</p>
	<center><a href="javascript: submitform('test.html')"><button style="font-size:25px">Login</button></a></center>
 </form>
<br><br>

<a href="https://maps.google.com" target="_blank"> Address new </a>

<center><a style="font-size:20px" href="#" onclick="window.open('http://www.foxrunsolutions.com/exams/www/expert_signup.html','_system'); return false;">Expert Sign Up</a></center>
<center><a style="font-size:20px" href="#" onclick="window.open('http://www.foxrunsolutions.com/exams/www/user_login.html','_system'); return false;">User Login</a></center>
<br><br>

	<center><a href="#" onclick="window.open('tel:18598781060', '_system'); return false;">Call Support 859-878-1060</a>
	<p><a href="#" onclick="window.open('http://www.foxrunsolutions.com/exams/index.html', '_system'); return false;">www.asmartask.com</a> </p>
	</center>
	
	</div>
</div>

<script type="text/javascript" src="cordova.js"></script>
<script type="text/javascript" src="js/index.js"></script>

</body>

</html>

**Comment by jayfagin** [comment]
Here is the simple html.

 

 

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

 

<head>

 

 

<allow-navigation href="http://*/*" />

<access origin="content:///*" />

<access origin="http://*.google.com" />

<access origin='*' allows-arbitrary-loads-for-media='true' allows-arbitrary-loads-in-web-content='true' allows-local-networking='true' />

<meta name="format-detection" content="telephone=yes,date=yes,address=yes,email=yes,url=yes" />

<meta charset="utf-8" />

<meta name="msapplication-tap-highlight" content="no" />

<meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />



<meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline'; style-src 'self' 'unsafe-inline'; media-src *" />



<link rel="stylesheet" type="text/css" href="css/index.css" />

    

<title> </title>

 

</head>

 

<body>

 

<div style="position: absolute; width: 320px; height: 100px; z-index: 1; background-color: #666666" id="layer2">

                <p style="font-family:arial; font-size:200%; text-align:center; color:#EFEFEF"><br>A Smart Ask</p>

</div>

 

<div style="position: relative; width: 320px; height: 100px; z-index: 2; top: 120px" id="layer3">

<br><br>

 

<form action="http://www.foxrunsolutions.com/exams/www/passwd_exec.asp" method="Post" name="ExpertForm">

                <p style="color:white; font-size:15px;">&nbsp;&nbsp;&nbsp;&nbsp;Email Address:<br>

                &nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="emailaddress" style="font-size:25px" required ><br><br><br>

                &nbsp;&nbsp;&nbsp;&nbsp;Password:<br>

                &nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="password" style="font-size:25px" required > <br><br>

                </p>

                <center><a href="javascript: submitform('test.html')"><button style="font-size:25px">Login</button></a></center>

</form>

<br><br>

 

<a href="https://maps.google.com" target="_blank"> Address new </a>

 

<center><a style="font-size:20px" href="#" onclick="window.open('http://www.foxrunsolutions.com/exams/www/expert_signup.html','_system'); return false;">Expert Sign Up</a></center>

<center><a style="font-size:20px" href="#" onclick="window.open('http://www.foxrunsolutions.com/exams/www/user_login.html','_system'); return false;">User Login</a></center>

<br><br>

 

                <center><a href="#" onclick="window.open('tel:18598781060', '_system'); return false;">Call Support 859-878-1060</a>

                <p><a href="#" onclick="window.open('http://www.foxrunsolutions.com/exams/index.html', '_system'); return false;">www.asmartask.com</a> </p>

                </center>

                

                </div>

</div>

 

<script type="text/javascript" src="cordova.js"></script>

<script type="text/javascript" src="js/index.js"></script>

 

</body>

 

</html>

 

Thanks,

 

Jay Fagin

President
FOX RUN Systems & Solutions
513.238.0083   |    <http://www.foxrunsolutions.com/> foxrunsolutions.com

 



 

 

 

Confidentiality Notice: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by surajpindoria** [comment]
I have just tested this on iOS and I am able to get the call number prompt to come up. Can you try updating to the latest version of the developer app if you aren't already using it. Also are you seeing the same thing when you install the app to the device?

**Comment by jayfagin** [comment]
I do not have a problem getting the phone number to come up.

 

I can not get the Submit button to work. Or any other link that goes to another page.  Unless I use target _System.  Then it opens a new Safari window.  This is running on my Iphone 5 se IOS 10.

 

Thanks,

 

Jay Fagin

President
FOX RUN Systems & Solutions
513.238.0083   |    <http://www.foxrunsolutions.com/> foxrunsolutions.com

 



 

 

 

Confidentiality Notice: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by surajpindoria** [comment]
Try using the inappbrowser plugin. I just tried this with '_blank' instead of '_system' and it loads the page within the app.

**Comment by jayfagin** [comment]
I don’t know how to user a plugin.

 

The _blank sort of worked.  Which is good. It does open another page inside the phonegap app window.  But at the bottom the word Done appears and it shows the link to the page.  When I click on Done it takes me back to the index.html page.

 

Thanks,

 

Jay Fagin

President
FOX RUN Systems & Solutions
513.238.0083   |    <http://www.foxrunsolutions.com/> foxrunsolutions.com

 



 

 

 

Confidentiality Notice: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by jayfagin** [comment]
cordova.InAppBrowser.open('http://192.168.1.111:3000/user_signup.html', '_blank', 'location=yes');

 

Like this?

 

Thanks,

 

Jay Fagin

President
FOX RUN Systems & Solutions
513.238.0083   |    <http://www.foxrunsolutions.com/> foxrunsolutions.com

 



 

 

 

Confidentiality Notice: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by surajpindoria** [comment]
You will need to add the plugin first before you are able to make a call to it.

`phonegap plugin add cordova-plugin-inappbrowser`

**Comment by jayfagin** [comment]
window.open("http://192.168.1.111:3000/user_signup.html","_blank");

 

this no longer works either.  Same cannot GET message.  Something broke.

 

Thanks,

 

Jay Fagin

President
FOX RUN Systems & Solutions
513.238.0083   |    <http://www.foxrunsolutions.com/> foxrunsolutions.com

 



 

 

 

Confidentiality Notice: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by jayfagin** [comment]
I ran that code at a dos prompt.  Phonegap opened up. When I run this code I get “Cannot GET /user_signup.html” 

 

<script>

function loginCheck ()

{

window.alert ("Open a Window");

cordova.InAppBrowser.open('http://192.168.1.111:3000/user_signup.html', '_blank', 'location=yes');

}

</script>

 

Thanks,

 

Jay Fagin

President
FOX RUN Systems & Solutions
513.238.0083   |    <http://www.foxrunsolutions.com/> foxrunsolutions.com

 



 

 

 

Confidentiality Notice: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by surajpindoria** [comment]
Try without the url in front of the filename, `cordova.InAppBrowser.open('user_signup.html', '_blank', 'location=yes');`

**Comment by jayfagin** [comment]
I restarted phonegap and it can find my html file now.  still have the weird “Done” and hyper link at the bottom of the browser window.

 

Thanks,

 

Jay Fagin

President
FOX RUN Systems & Solutions
513.238.0083   |    <http://www.foxrunsolutions.com/> foxrunsolutions.com

 



 

 

 

Confidentiality Notice: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by jayfagin** [comment]
cordova.InAppBrowser.open('user_signup.html', '_top', 'location=yes');

 

This does not find the html file.  When I add the http address back it found it.

 

Still have the Done at the bottom.

 

Thanks,

 

Jay Fagin

President
FOX RUN Systems & Solutions
513.238.0083   |    <http://www.foxrunsolutions.com/> foxrunsolutions.com

 



 

 

 

Confidentiality Notice: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by purplecabbage** [comment]
This is all covered by the plugin docs and not a phonegap-desktop issue.
https://github.com/apache/cordova-plugin-inappbrowser
