### ISSUE TITLE
dataDirectory works on PhoneGap but not later on deployed android app

### ISSUE THREAD

**Issue by nicktsek** [phonegap/phonegap-app-desktop#858]
### PhoneGap Desktop version
v.0.4.5
### PhoneGap Mobile App version
v.1.8.2
### Mobile devices & Mobile OS version
Huawei P10 - Android 7.0
### Computer OS version
Win 7
### Network Type (home/corporate)
Home
### Is your network using a proxy?
No
### Computer / Network security (firewall / anti-virus / disk encryption)
No
### Are you using VMs on your computer?
No
### Do you have multiple network adapters (or virtual network adapters)?
No
### Are you using VPN?
No
### Expected Behaviour
The deployed app should recognize Wikitude as PhoneGap does.
### Actual Behaviour
The camera starts, but an error is raised: Failed to load Architect World. net::ERR_FILE_NOT_FOUND.
Url: file:///data/user/0/finesse.store.codingweb/files/www/wiki/wiki.html
### Steps to Reproduce 
I created a new app (adding Wikitude and other plugins using the command line).
I use the same structure as Wikitude demo (wiki folder in www folder that includes the code)
and in index.js of my main file, I use "cordova.file.dataDirectory + 'www/wiki/wiki.html'".
#### Error messages
Failed to load Architect World. net::ERR_FILE_NOT_FOUND.
Url: file:///data/user/0/finesse.store.codingweb/files/www/wiki/wiki.html

Please notice that when I simulate this app using PhoneGap application, it is working.
Am I missing something here?
Thank you in advance.

Kind Regards,
Nicholas.

**Comment by nicktsek** [comment]
Hi,

Can anyone assist on this issue?
I still did not find a proper solution

Regards,
Nicholas

**Comment by nicktsek** [comment]
Here is my config.xml file:

<?xml version='1.0' encoding='utf-8'?>
<widget id="Finesse.Source.CodingWeb" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>test</name>
    <description>test</description>
    <author>Nicholas Tsekouras</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <preference name="android-minSdkVersion" value="19" />
        <icon density="ldpi" src="www/assets/icon/android/ApplicationIcon.png" />
        <icon density="mdpi" src="www/assets/icon/android/ApplicationIcon.png" />
        <icon density="hdpi" src="www/assets/icon/android/ApplicationIcon.png" />
        <icon density="xhdpi" src="www/assets/icon/android/ApplicationIcon.png" />
        <icon density="xxhdpi" src="www/assets/icon/android/ApplicationIcon.png" />
        <icon density="xxxhdpi" src="www/assets/icon/android/ApplicationIcon.png" />
        <allow-intent href="market:*" />
    </platform>
    <preference name="iosPersistentFileLocation" value="Library" />
    <preference name="iosExtraFilesystems" value="library,library-nosync,documents,documents-nosync,cache,bundle,root" />
    <preference name="AndroidExtraFilesystems" value="files,files-external,documents,sdcard,cache,cache-external,assets,root" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="AndroidPersistentFileLocation" value="Compatibility" />
    <engine name="android" spec="^6.3.0" />
    <engine name="browser" spec="^5.0.1" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="com.wikitude.phonegap.WikitudePlugin" spec="https://github.com/Wikitude/wikitude-cordova-plugin.git" />
    <plugin name="cordova-plugin-file" spec="git+https://github.com/apache/cordova-plugin-file.git" />
    <plugin name="cordova-plugin-device" spec="*" />
    <plugin name="cordova-plugin-dialogs" spec="*" />
    <plugin name="cordova-custom-config" spec="*" />
    <plugin name="cordova.plugins.diagnostic" spec="2" />
</widget>

**Comment by timkim** [comment]
Hi @nicktsek 

I'm not _quite_ sure why it's failing to load for you. It seems like you have the path listed correctly. 

Can you make sure you can load the wikitude ar experience by going to: speeder.phonegap.com in the PhoneGap Developer App on your phone and see if that actually launches ok for you?

Otherwise, I would re-check the paths of your files and folders.

If it helps, here's the git repo of that speeder demo to see how I set it up: https://github.com/timkim/phonegap-wikitude-speeder-template/tree/master/www

**Comment by nicktsek** [comment]
Hi timkim,

Thanks for your response.

I downloaded your app and using my config.xml file I executed the below:
> cordova platform add android
> npm install cordova-custom-config
> cordova plugin add https://github.com/Wikitude/wikitude-cordova-plugin.git
> cordova build android
I uploaded android-debug.apk on my phone, installed it and in this case it does not even do anything.
Through the PhoneGap Mobile App it is working.

Kind Regards,
Nicholas.

**Comment by timkim** [comment]
Hi @nicktsek 

If you are doing your own build of the app and trying to get the Wikitude experience working, the path should just be: `www/wiki/wiki.html`. Don't worry about the `cordova.file.dataDirectory` part.
For more info: http://www.wikitude.com/external/doc/documentation/latest/phonegap/setupguidecordovacli.html#setup-guide-cordova-cli

If you are trying to load the experience from the PhoneGap Developer App, then the path will be: `cordova.file.dataDirectory + 'www/wiki/wiki.html`.

**Comment by nicktsek** [comment]
Hi timkim,

That's all folks =)
Just a simple mistake that was messing everything up..

Thanks a lot,
Nicholas.
