### ISSUE TITLE
iPhone won't connect

### ISSUE THREAD

**Issue by ckameron99** [phonegap/phonegap-app-desktop#860]

**Comment by ckameron99** [comment]
I just downloaded phonegap developer onto my pc and iphone, both of which are running the latest OS, I set up a server on my PC and ran it, however, when I tried to connect from my iphone it waited about 30 seconds before giving an alert stating that the archives could not be downloaded and that I should enter a valid URL to continue. I am connected to the same wi-fi network and have tried to visit the server from a web browser from both machines, I can visit it from my PC but not my phone. I have an antivirus with a firewall, however configured it to open port 3000, and when that didn't work disabled both the firewall and antivirus. I also downloaded phonegap onto my friend's iphone 6 to see if it was just my iphone 5 but had the same result. I am not using a VPN and phonegap has the default config. I have checked the IP many times now and it is definitely correct. Thanks for any help that you can give, I am new to this sort of thing so I may have made a silly error...

**Comment by surajpindoria** [comment]
Hi @ckameron99,

Take a look at this [FAQ](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/), there are a bunch of suggestions that may help you.

**Comment by ckameron99** [comment]
@surajpindoria I've checked the FAQ and done everything that it suggests, it still doesn't work
