### ISSUE TITLE
PhoneGap App Stuck on Launching

### ISSUE THREAD

**Issue by bfleishman** [phonegap/phonegap-app-desktop#861]
### Computer OS version
Windows 10 Pro

### Network Type (home/corporate)
Corporate

### Is your network using a proxy?
No

### Computer / Network security (firewall / anti-virus / disk encryption)
Disabled

### Are you using VMs on your computer?
No

### Do you have multiple network adapters (or virtual network adapters)?
No

### Are you using VPN?
No

### Expected Behaviour
Program launches

### Actual Behaviour
Stuck with Blue spinning circle

### Steps to Reproduce 
Install latest version on Windows 10

![phonegap](https://user-images.githubusercontent.com/360187/34364026-9b431c96-ea4f-11e7-9d98-c47733f6f1ec.PNG)

#### Error messages

When I launch the PhoneGap desktop app, I jsut get a blue spinning wheel. I have recreated this on several Windows 10 computer. I attached a screen shot. Please help!

**Comment by bfleishman** [comment]
UPDATE
------------------------------------------------
This version runs on my PC if I download and run the exe that is located in the "PhoneGap-0.3.0-loading-fix-2-win32.zip" ZIP file.

[https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.3.0](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.3.0)

**Comment by zerox1212** [comment]
Uninstall Phonegap. Install Node.js. Install Phonegap again and see if it works.

**Comment by shaunleo** [comment]
Same issue. Tried the Node.js but still dosen't work. The PhoneGap-0.3.0-loading-fix-2-win32.zip works, but once I update to the current version the issues comes back.
