### ISSUE TITLE
Proxy Error on Ajax GET request

### ISSUE THREAD

**Issue by chrisutpg** [phonegap/phonegap-app-desktop#862]
## _System Configuration_
Windows
Flask development server on 127.0.0.1:5000

### PhoneGap Desktop version
0.4.5

### PhoneGap Mobile App version
N/A

### Mobile devices & Mobile OS version
N/A

### Computer OS version
Win10

### Network Type (home/corporate)
Home

### Is your network using a proxy?
No

### Computer / Network security (firewall / anti-virus / disk encryption)
Firewall disabled

### Are you using VMs on your computer?
No

### Do you have multiple network adapters (or virtual network adapters)?
No

### Are you using VPN?
No

### Expected Behaviour
My API is residing on 127.0.0.1:5000/some/api/stuff when I make an Ajax call from any regular HTML file, the call works as anticipated. This is what I would expect from HTML running on the PhoneGap server on 10.0.0.113:3000 but this results in the Ajax call getting the wrong url.

### Actual Behaviour
My API is residing on 127.0.0.1:5000/some/api/stuff when I make an Ajax call from any regular HTML file, the call works as anticipated. However making the same call from a HTML file hosted on the PhoneGap server on 10.0.0.113:3000 results in the GET request like so; 10.0.0.113:3000%3127.0.0.1:5000%2some%2api%2stuff looking at the log it shows there is a proxy error.

### Steps to Reproduce 
Would need a Flask development server to serve the API

#### Error messages
Proxy error

Although I think if I moved the API to a live site it would probably work this makes developing a nightmare. I want to be able to debug and develop both the API and PhoneGap app locally first. Any thoughts would be helpful.

**Comment by surajpindoria** [comment]
I don't have too much experience with this kind of testing but my guess is that something is getting messed up with the way that we run the local server for the desktop app and how your API needs to be accessed. Can you try making a full a build of your app and installing it to your device to test this?

**Comment by chrisutpg** [comment]
Thanks for the reply. I actually did figure this out. I downloaded the CLI and just ran the server from there and it seemed to start working. Not sure what the desktop app does that's different.. But thanks for the help!

**Comment by surajpindoria** [comment]
The desktop app is doing the same thing under the hood as the CLI but we have noticed some issues because it is running under an Electron app. But glad you got this working!
