### ISSUE TITLE
Conection error:Time Out

### ISSUE THREAD

**Issue by lfqwx** [phonegap/phonegap-app-desktop#863]

**Comment by surajpindoria** [comment]
Could you provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
1. PhoneGap Mobile App version
1. Mobile devices & Mobile OS version
1. Computer OS version
1. network type (home/corporate)
1. is your network using a proxy?
1. computer / network security (firewall / anti-virus / disk encryption)
1. are you using VMs on your computer?
1. do you have multiple network adapters (or virtual network adapters)
1. are you using VPN?

**Comment by purplecabbage** [comment]
assuming this is abandoned ... reopen if you still have this issue.
