### ISSUE TITLE
PhoneGapDesktop sqlite

### ISSUE THREAD

**Issue by Parthos90** [phonegap/phonegap-app-desktop#870]
Hello,

one of my mates and me have to use PhoneGapDesktop to develop a app (during a course by the university of kiel). We are now at the point where and how to store data like questions of a quiz the user of the app has to answer. When the user closes the app and starts it again, the answered questions should not be unanswered again. 
We found a lot of ways to store the data.
For example: WebSQL (deprecated), IndexedDB (what we try to use now), localStorage and other versions of localStorage, We decided to use IndexedDB, but we may get a problem becuse of its limitations (space for saving data). We then considered to use the cordova sqlite plugin but saw, that it only works with the cordova CLI version and not PhoneGapDesktop.

Does anyone know, if there is a way to use the sqlite plugin with the PhoneGapDesktop, or if there exists another solution to use sql, sqlite or something quite similar to stora unlimited data.

The bad thing is, that we have to use PhoneGapDesktop and must not use the Cordova CLI (we did not get an answer why).

We willl be happy about every answer and of course about a solution for our problem. We say sorry for our bad english, we have to practise it again.

**Comment by surajpindoria** [comment]
Hi @Parthos90,

The Desktop app works along with the PhoneGap Developer app and they only support the core Cordova plugins and a few others. This is why you aren't able to use the sqlite plugin. But if you want you can create a custom build of the Developer App that includes it, [here](https://github.com/phonegap/phonegap-app-developer/#adding-custom-plugins) is the link for how to do this.
