### ISSUE TITLE
Why the working environment does not open PhoneGap?

### ISSUE THREAD

**Issue by ArslanaliDag** [phonegap/phonegap-app-desktop#873]
### Installation was without problems
![default](https://user-images.githubusercontent.com/11228826/35904445-3487dbd8-0bf4-11e8-9da9-42b972957426.JPG)

**Comment by surajpindoria** [comment]
Could you provide the following information to help us debug this:

1. PhoneGap Desktop version / PhoneGap CLI version
1. PhoneGap Mobile App version
1. Mobile devices & Mobile OS version
1. Computer OS version
1. network type (home/corporate)
1. is your network using a proxy?
1. computer / network security (firewall / anti-virus / disk encryption)
1. are you using VMs on your computer?
1. do you have multiple network adapters (or virtual network adapters)
1. are you using VPN?
