### ISSUE TITLE
location.href not working even if white list is set up correctly

### ISSUE THREAD

**Issue by cszasz** [phonegap/phonegap-app-desktop#876]

**Comment by cszasz** [comment]
It seems that the <allow-navigation href="*" /> directive in config.xml does not have an effect when I test the app through the ios PhoneGap. However, if I build the ios app and install it, then it works.

Any idea if I did something wrong or it is a bug in the PhoneGap app?

**Comment by surajpindoria** [comment]
Hi @cszasz,

I have just tested this on both on the browser and by installing this to my iOS device and am getting to work. Do you have an example for how you are trying to use this?

**Comment by cszasz** [comment]
My initial goal was to implement the facebook login. Which worked all right
with FB api until I used it in the browser.
When I switched to the Phonegap it didn't do anything, the FB API did not
even initialize.
Then I tried other alternatives to solve the problem, one of which was
involving locaction.href="https://connect.facebook.net..." which again
didn't do anything.
Then I changed to other simple addresses like "www.google.com" and it
didn't work either.
As said I added the access to "*" the config.xml still got the same result.

2018-02-15 20:34 GMT+01:00 Suraj Pindoria <notifications@github.com>:

**Comment by surajpindoria** [comment]
You may have to use a combination of the CSP tag in `index.html` and the whitelist plugin.

https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/

**Comment by cszasz** [comment]
I set everything up and tested in the browser and it works:
<meta http-equiv="Content-Security-Policy" content="default-src 'self' ws:
https://scontent.xx.fbcdn.net https://connect.facebook.net https://*.
facebook.com http://*.facebook.com facebook.com 'unsafe-inline'
'unsafe-eval' ">


Still in Phonegap the FB does not initialize.


2018-02-16 20:30 GMT+01:00 Suraj Pindoria <notifications@github.com>:

**Comment by cszasz** [comment]
Hi,

To avoid cofusion, here I attach a very simple project where the starting
page should load the FB api and test it, right after loading, no need to do
anything. If works well it should display the status of facebook session.

It works well in the browser but not in the Phonegap.

Best regards,
Csaba


2018-02-16 20:30 GMT+01:00 Suraj Pindoria <notifications@github.com>:

**Comment by cszasz** [comment]
[test.zip](https://github.com/phonegap/phonegap-app-desktop/files/1735776/test.zip)

**Comment by cszasz** [comment]
Hi, any chance that you could have a look?

I am completely stuck with this. I am trying all alternatives and none of them work.

**Comment by cszasz** [comment]
I think I found the root cause although I couldn't find a solution.

The issue is that when running in Phonegap the location.hostname is empty.
When testing in the browser this is not empty and is the one I registered in Facebook.

What should I do to make it work even when locaction.hostname is empty?
Can this be configured somewhere?

**Comment by surajpindoria** [comment]
I would always be careful when testing a phonegap app in the browser since it is not a perfect representation of how your app will function when on a device. And the reason that `location.hostname` is empty on the device is we use the file protocol to launch your apps `index.html`, so there is no host.

I have not worked with the facebook API in phonegap apps before but there are plugins that help you to do login using facebook. If you don't want to use this option you may have to hardcode this value somewhere if it is required.

https://github.com/jeduan/cordova-plugin-facebook4

**Comment by cszasz** [comment]
Hi already tried  cordova-plugin-facebook4
<https://github.com/jeduan/cordova-plugin-facebook4> already and coundn't
make it work that either.

It is very strange that these apps are up since months, nobody raising any
issue even though it doesn't work.
I tested multiple times building up from scratch everything and it doesn't
work.
BTW, it doesn't work on Android either so it is not an IOS problem, rather
execute in "native" problem.



2018-02-20 19:43 GMT+01:00 Suraj Pindoria <notifications@github.com>:

**Comment by purplecabbage** [comment]
Running this in the browser and ios both have the same result for me.
![screen shot 2018-09-07 at 3 56 59 pm](https://user-images.githubusercontent.com/46134/45246768-effe9b80-b2b7-11e8-9bbd-b1893cc75d95.png)
The app-id is invalid, but everything else appears to work.
Regardless, this does not appear to be an issue with the phonegap-desktop application.  If you still have issues, please post it in phonegap/phonegap-cli if it is still an issue.
Ultimately, I would recommend that you reconsider your design and not use a redirect to authenticate.  I have a blog post that outlines how to use the InAppBrowser plugin to do OAuth2
https://medium.com/@purplecabbage/oauth2-in-apache-cordova-3a3ba059b184

**Comment by northyorkdev** [comment]
Set both <access origin/> and <allow-navigation/> in config.xml.
