### ISSUE TITLE
Can't connect PhoneGap Desktop project in to PhoneGap Developer app

### ISSUE THREAD

**Issue by BrunaoW** [phonegap/phonegap-app-desktop#882]
### Network Type: Home

I'm a beginner in app development, and I chose Adobe PhoneGap to create multiplataform apps.
So, I created a new project in PhoneGap Desktop, and then opened the PhoneGap App. I wrote the server address in the app and tapped to connect. But instead of instantly showing the succesful message, it's just showing the "Downloading" and "Tap to cancel" message continuously. What's probably going on? I've tried to look at the "Advanced Sharing Settings" in the Control Panel, but I didnt messed with something.

**Comment by surajpindoria** [comment]
Hi @BrunaoW,

Take a look at this [FAQ](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/), there are a bunch of suggestions that may help you.

**Comment by BrunaoW** [comment]
@Aboalmaali, wasup! So I solved this problem using the CLI Phonegap, which is basically controlling your project through the terminal, instead of the desktop app. Doing this, you'll be able to connect your phone through the port link.

**Comment by Aboalmaali** [comment]
I solved the issue, in fact in some scenarios phonegap desktop app gives you more than one server address , we should use the server of the IP of our desktop machine (local IP)
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kdahlhaus** [comment]
Thanks, that worked for me.   

> I solved the issue, in fact in some scenarios phonegap desktop app gives you more than one server address , we should use the server of the IP of our desktop machine (local IP) Thanks Get Outlook for iOS<https://aka.ms/o0ukef>
