### ISSUE TITLE
Try to make the background image will scroll with the page

### ISSUE THREAD

**Issue by rom529** [phonegap/phonegap-app-desktop#885]
### PhoneGap Desktop version
0.4.5
### Mobile devices & Mobile OS version
android oneplus 5t
### Computer OS version
windows 10
### Network Type (home/corporate)
home
### Expected Behaviour
the background image will scroll with the page
### Actual Behaviour
This happens in the Chrome browser on my computer but not in the phonegap on my phone

**Comment by purplecabbage** [comment]
I suspect you are not using proper cross-browser css, but I cannot know without seeing more.
If you are still having this issue please reopen and post some sample code that demonstrates the issue.
This does not appear to be a phonegap-desktop issue.
