### ISSUE TITLE
PhoneGap IOS showing reservation.html 404 not found---------- Framework7.js(line-12720)

### ISSUE THREAD

**Issue by viawebonline** [phonegap/phonegap-app-desktop#888]

**Comment by viawebonline** [comment]
![image](https://user-images.githubusercontent.com/41105508/42555822-23706c48-8507-11e8-8df6-ef03594d8535.png)

**Comment by purplecabbage** [comment]
Are you using a template?  I would need to see more to know what is happening here.
What are you doing to trigger the error? or does it just happen?

**Comment by purplecabbage** [comment]
calling this stale and closing ... please reopen if you have answers to the above questions.
