### ISSUE TITLE
Error: Unhandled "error" event. (+[1m +[31m Error from Cordova Fetch: Error: cmd: Command failed with exit code ENOENT)

### ISSUE THREAD

**Issue by pilbug** [phonegap/phonegap-app-desktop#889]
### PhoneGap Desktop version
0.4.5 (Latest at post)
### PhoneGap Mobile App version
1.8.4 (Latest at post - not relevant)
### Mobile devices & Mobile OS version
Not relevant
### Computer OS version
Windows 7
### Network Type (home/corporate)
home
### Is your network using a proxy?
No
### Computer / Network security (firewall / anti-virus / disk encryption)
None
### Are you using VMs on your computer?
No
### Do you have multiple network adapters (or virtual network adapters)?
No
### Are you using VPN?
No
### Expected Behaviour
Creating a new Phone Gap project via the desktop app
### Actual Behaviour
Throws an error when attempting to clicking the "Create Project" button in the desktop app
### Steps to Reproduce 
Go to https://phonegap.com/getstarted/
Follow the steps
Get stuck on step 3, will not create a new project.
#### Error messages
Error: Unhandled "error" event. (+[1m +[31m Error from Cordova Fetch: Error: cmd: Command failed with exit code ENOENT)
![phonegap-error](https://user-images.githubusercontent.com/41352206/42856154-dfd9bfa6-8a11-11e8-8111-a09d9bf770c3.jpg)

**Comment by purplecabbage** [comment]
This seems to be the same issue as #891
Please reopen if this is still an issue.
