### ISSUE TITLE
Update Framework 7 Template to use latest version

### ISSUE THREAD

**Issue by rachaelkavit** [phonegap/phonegap-app-desktop#896]
Could you look into updating the old Framework 7 Template to use a more up to date version as the current one is using Version 1 which is hugely out of date.

**Comment by chrisgriffith** [comment]
Feel free to update it yourself and submit a PR. :)

**Comment by rachaelkavit** [comment]
Oh it looks like it might be much simpler than I originally thought. I think I've submitted a PR ( I'm quite new to using Git though so if I've done something wrong let me know so I can learn )

It looked like it was referencing this project https://www.npmjs.com/package/phonegap-template-framework7?activeTab=versions all I've done is update the version number in the template-list.js file to the version that was updated a month ago. 

I can create a new template but I figured it didn't make sense to reinvent the wheel if there was one already there.

**Comment by purplecabbage** [comment]
thanks, merged
