### ISSUE TITLE
linking Mac book app (phone gap) to andriod developer app

### ISSUE THREAD

**Issue by jasdalucl2018** [phonegap/phonegap-app-desktop#899]

**Comment by purplecabbage** [comment]
need some info to know what this is ...

**Comment by jasdalucl2018** [comment]
Nothing to worry about .. I was just looking around GitHub and testing its functionality -aka- the "watch" button ..

On 13 Feb 2019, at 07:20, Jesse MacFadyen <notifications@github.com<mailto:notifications@github.com>> wrote:


need some info to know what this is ...
