### ISSUE TITLE
Cannot Open Existing Project

### ISSUE THREAD

**Issue by KenpoJ** [phonegap/phonegap-app-desktop#905]
## _System Configuration_
MacOS 10.14.5

### PhoneGap Desktop version
0.4.5

### PhoneGap Mobile App version
N/A (since it's not available for iOS at the moment)

### Mobile devices & Mobile OS version
iPhone 8 iOS 12.3.1 (I only use the phone to browse to the local server)

### Computer OS version
MacOS 10.14.5

### Network Type (home/corporate)
Corporate (I believe)

### Is your network using a proxy?
No

### Computer / Network security (firewall / anti-virus / disk encryption)
None I am aware of

### Are you using VMs on your computer?
No

### Do you have multiple network adapters (or virtual network adapters)?
No

### Are you using VPN?
No

### Expected Behaviour
By using Command+O, dragging and dropping a folder or using the "+" in the app I am trying to open a project I created just a few days ago. My expectation is that it will be added to the list, the server will start and I can go to work.

### Actual Behaviour
Nothing happens. I can add a new project or existing projects that I didn't modify, but this project that I did modify (from the base Hello World project) does not load. I am guessing that something I did with the config file may have messed something up, but I can't be sure as I have replaced the config file with the one from the Hello World.

I have also run across this interesting error:
As you can see from the screenshot there are no projects showing in the window. When I try to add an existing project I get the error that "I'm trying to add a project that already exists." I'm not sure what that means.

### Steps to Reproduce 
See my description above.

#### Error messages
See above

![Screen Shot 2019-06-26 at 2 50 13 PM](https://user-images.githubusercontent.com/14362807/60218437-3bbd0a00-9824-11e9-8dc8-4e585e131e66.png)
![Screen Shot 2019-06-26 at 2 51 15 PM](https://user-images.githubusercontent.com/14362807/60218442-411a5480-9824-11e9-8ddc-73a9948b308e.png)

**Comment by EdePC** [comment]
Greetings,
- On Windows, on run Phonegap Desktop the same thing happens, then close the Phonegap Desktop and relaunch to solve.
