### ISSUE TITLE
Unable to  verify the first certificate - Ajax request

### ISSUE THREAD

**Issue by kalaiprakash93** [phonegap/phonegap-app-desktop#908]
While using phonegap build API request (Angular JS 1.7.5) is always returns unable to verify the first certificate error .
am using 8.0.0 phonegap cli version
API is working except phonegap build
Please give me the best solution
Thanks in advance .. !

**Comment by pastoolio** [comment]
I am having the same issue. My App works perfectly to standard HTTP API but as soon as I change the API calls over to SSL I get the error: Unable to verify the first certificate in my AJAX call.

The API is accessible via SSL using any browser and is not using a self signed certificate. 

My using:
Microsoft Windows [Version 10.0.17134.885]
PhoneGap 0.4.5

I have tried installing the certificate on the Windows PC but it didn't work.
