### ISSUE TITLE
Link is not opening in phonegap desktop

### ISSUE THREAD

**Issue by rakeshbaral92** [phonegap/phonegap-app-desktop#921]
Link is not opening and also the image is not showing in phonegap desktop.

**Comment by nelliejellie** [comment]
im having the same issue also. pleas whats the fix

**Comment by rakeshbaral92** [comment]
Phonegap Desktop is not working in some systems. Please run your project using command line.
cordova run browser --live-reload
It will automatically refresh like phonegap desktop.
