### ISSUE TITLE
Aplication Crashes in Loading Projects

### ISSUE THREAD

**Issue by WillFontana** [phonegap/phonegap-app-desktop#925]
## _System Configuration_
CPU - IntelCore 13-4170 Dual Core 3.70GHz
16GB Ram
### Computer OS version
Windows 10 Pro/1909 64bit
### Network Type (home/corporate)
Corporate
### Is your network using a proxy?
No
### Are you using VMs on your computer?
No
### Do you have multiple network adapters (or virtual network adapters)?
Yes
### Are you using VPN?
No
### Expected Behaviour
The application should open the project folders
### Actual Behaviour
The aplication keeps in an infinite loading state after opened.
### Steps to Reproduce 
Click the app icon
#### Error messages
None

**Comment by chrisgriffith** [comment]
If you look in the previous issues, you will see this issue has already been reported. Adobe is no longer maintaining the project and there will not be a fix. You should switch to using the Cordova CLI directly instead.

**Comment by WillFontana** [comment]
I understand, thanks for the reply, I will check the other issue and see how to proceed.
